### ISSUE TITLE
VS 4 Mac beta - Socket error on UITest tests

### ISSUE THREAD

**Issue by owenniblock** [xamarin/xamarin-android#1817] opened 2018-06-13 19:30 UTC
### Steps to Reproduce

1. Download code sample: https://github.com/King-of-Spades/AppCenter-Test-Samples/tree/master/Xamarin.UITest/UITestDemo
2. Switch VS 4 Mac to beta channel
3. Open Android emulator & select in VS 4 Mac
4. Run Android tests

### Expected Behavior
Tests run successfully (they run correctly on VS 4 Mac stable).

### Actual Behavior
Tests fail to run either with error:
```
SetUp : System.Net.Http.HttpRequestException : An error occurred while sending the request
  ----> System.Net.WebException : Unable to read data from the transport connection: Connection reset by peer.
  ----> System.IO.IOException : Unable to read data from the transport connection: Connection reset by peer.
  ----> System.Net.Sockets.SocketException : Connection reset by peer
```

or error:
```
SetUp : System.Net.Http.HttpRequestException : An error occurred while sending the request
  ----> System.IO.IOException : Unable to write data to the transport connection: The socket is not connected.
  ----> System.Net.Sockets.SocketException : The socket is not connected
```

### Version Information

=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.6 Preview (7.6 build 947)
Installation UUID: 088a769e-be74-4fd9-b64b-065d830c7305
Runtime:
	Mono 5.12.0.260 (2018-02/58637d0ee7c) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 512000260

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.2
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.5.0.331 (Visual Studio Community)
Hash: 238eb94c
Branch: master
Build date: 2018-05-25 07:47:00-0400

=== Xamarin.iOS ===

Version: 11.11.0.331 (Visual Studio Community)
Hash: 238eb94c
Branch: master
Build date: 2018-05-25 07:47:00-0400

=== Xamarin.Android ===

Version: 8.3.99.12 (Visual Studio Community)
Android SDK: /Users/owenniblock/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706000947
Git revision: f7b338b596748ffa52b2f86a292bb52a1ce2a4fd
Build date: 2018-05-25 12:47:39-04
Xamarin extensions: 179dd16370b3fd3f3e71ef70ba136fea5e66c60c
Build lane: monodevelop-lion-master

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Internet of Things (IoT) development (Preview) 7.5

### Log File

--------- NOTE: Had to truncate log as it was huge - let me know if you want an upload of the whole thing.
06-13 19:07:56.090  5277  5277 I InstrumentationBackend: Added:'DumpHtml', with key:'dump_html'
06-13 19:07:56.090  5277  5277 I InstrumentationBackend: Added:'EnterTextByCssSelector', with key:'enter_text_by_selector'
06-13 19:07:56.090  5277  5277 I InstrumentationBackend: Added:'GetLoadProgress', with key:'get_load_progress'
06-13 19:07:56.090  5277  5277 I InstrumentationBackend: Added:'GetUrl', with key:'get_url'
06-13 19:07:56.090  5277  5277 I InstrumentationBackend: Added:'ScrollTo', with key:'scroll_to'
06-13 19:07:56.090  5277  5277 I InstrumentationBackend: Added:'SetPropertyByCssSelector', with key:'set_property_by_css_selector'
06-13 19:07:56.090  5277  5277 I calabash: Instantiating http server at 54604
06-13 19:07:56.091  5277  5277 I System.out: HTTP Daemon listening on: 54604
06-13 19:07:56.837  2233  2727 D EGL_emulation: eglMakeCurrent: 0xae594c00: ver 2 0 (tinfo 0xae5926f0)
06-13 19:08:00.063  1262  1321 D hwcomposer: hw_composer sent 599 syncs in 60s
06-13 19:09:00.055  1262  1321 D hwcomposer: hw_composer sent 12 syncs in 60s
06-13 19:10:00.038  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:11:00.065  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:11:34.233  1948  2100 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
06-13 19:11:34.316  5303  5303 W dex2oat : Unexpected CPU variant for X86 using defaults: x86
06-13 19:11:34.316  5303  5303 W dex2oat : Mismatch between dex2oat instruction set features (ISA: X86 Feature string: smp,-ssse3,-sse4.1,-sse4.2,-avx,-avx2) and those of dex2oat executable (ISA: X86 Feature string: smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2) for the command line:
06-13 19:11:34.316  5303  5303 W dex2oat : /system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/user/0/com.google.android.gms/app_fb/f.apk --oat-file=/data/user/0/com.google.android.gms/app_fb/f.dex
06-13 19:11:34.316  5303  5303 I dex2oat : /system/bin/dex2oat --dex-file=/data/user/0/com.google.android.gms/app_fb/f.apk --oat-file=/data/user/0/com.google.android.gms/app_fb/f.dex
06-13 19:11:34.340  5303  5303 I dex2oat : dex2oat took 24.014ms (threads: 4) arena alloc=121KB java alloc=63KB native alloc=1605KB free=1722KB
06-13 19:11:34.341  3722  3802 E linker  : readlink('/proc/self/fd/28') failed: Permission denied [fd=28]
06-13 19:11:34.341  3722  3802 E linker  : warning: unable to get realpath for the library "/data/data/com.google.android.gms/app_fb/f.dex". Will use given name.
06-13 19:11:34.341  3722  3802 W System  : ClassLoader referenced unknown path: 
06-13 19:11:34.346  3722  3802 D EGL_emulation: eglCreateContext: 0xae5954a0: maj 2 min 0 rcv 2
06-13 19:11:34.346  3722  3802 D EGL_emulation: eglMakeCurrent: 0xae5954a0: ver 2 0 (tinfo 0x9bd75050)
06-13 19:11:34.685  2769  3296 W Conscrypt: Could not set socket write timeout:
06-13 19:11:34.686  2769  3296 W Conscrypt:    java.lang.reflect.Method.invoke(Native Method)
06-13 19:11:34.686  2769  3296 W Conscrypt:    com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@11743470:13)
06-13 19:11:34.816  2769  3296 W Conscrypt: Could not set socket write timeout:
06-13 19:11:34.816  2769  3296 W Conscrypt:    java.lang.reflect.Method.invoke(Native Method)
06-13 19:11:34.816  2769  3296 W Conscrypt:    com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@11743470:13)
06-13 19:11:35.082  2769  3296 W GLSUser : [AppCertManager] IOException while requesting key: 
06-13 19:11:35.082  2769  3296 W GLSUser : java.io.IOException: Invalid device key response.
06-13 19:11:35.082  2769  3296 W GLSUser : 	at eyw.a(:com.google.android.gms@11743470:14)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at eyw.a(:com.google.android.gms@11743470:65)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at eyu.a(:com.google.android.gms@11743470:8)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at eyq.a(:com.google.android.gms@11743470:1)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at eyp.a(:com.google.android.gms@11743470:10)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at com.google.android.gms.auth.account.be.legacy.AuthCronChimeraService.b(:com.google.android.gms@11743470:7)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at edr.call(:com.google.android.gms@11743470:3)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at mmu.run(:com.google.android.gms@11743470:26)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at mse.run(:com.google.android.gms@11743470)
06-13 19:11:35.082  2769  3296 W GLSUser : 	at java.lang.Thread.run(Thread.java:818)
06-13 19:12:00.065  1262  1321 D hwcomposer: hw_composer sent 7 syncs in 60s
06-13 19:13:00.062  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:14:00.058  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:15:00.060  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:16:00.050  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:17:00.045  1262  1321 D hwcomposer: hw_composer sent 8 syncs in 60s
06-13 19:18:00.055  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:19:00.047  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:19:44.119  1948  3853 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
06-13 19:19:44.560  3722  3733 D EGL_emulation: eglCreateContext: 0xae594a80: maj 2 min 0 rcv 2
06-13 19:19:44.560  3722  3733 D EGL_emulation: eglMakeCurrent: 0xae594a80: ver 2 0 (tinfo 0x9bd75140)
06-13 19:19:44.580  3722  3733 D EGL_emulation: eglCreateContext: 0xae594f00: maj 2 min 0 rcv 2
06-13 19:19:44.581  3722  3733 D EGL_emulation: eglMakeCurrent: 0xae594f00: ver 2 0 (tinfo 0x9bd75140)
06-13 19:19:44.592  3733  3733 W Binder_1: type=1400 audit(0.0:46): avc: denied { read } for name="/" dev="tmpfs" ino=5121 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:device:s0 tclass=dir permissive=0
06-13 19:19:44.622  3733  3733 W Binder_1: type=1400 audit(0.0:47): avc: denied { search } for name="1680" dev="proc" ino=7219 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:zygote:s0 tclass=dir permissive=0
06-13 19:19:44.762  2769  3296 W Conscrypt: Could not set socket write timeout:
06-13 19:19:44.762  2769  3296 W Conscrypt:    java.lang.reflect.Method.invoke(Native Method)
06-13 19:19:44.762  2769  3296 W Conscrypt:    com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@11743470:13)
06-13 19:19:44.874  2769  3296 W Conscrypt: Could not set socket write timeout:
06-13 19:19:44.874  2769  3296 W Conscrypt:    java.lang.reflect.Method.invoke(Native Method)
06-13 19:19:44.874  2769  3296 W Conscrypt:    com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@11743470:13)
06-13 19:19:45.135  2769  3296 W GLSUser : [AppCertManager] IOException while requesting key: 
06-13 19:19:45.135  2769  3296 W GLSUser : java.io.IOException: Invalid device key response.
06-13 19:19:45.135  2769  3296 W GLSUser : 	at eyw.a(:com.google.android.gms@11743470:14)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at eyw.a(:com.google.android.gms@11743470:65)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at eyu.a(:com.google.android.gms@11743470:8)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at eyq.a(:com.google.android.gms@11743470:1)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at eyp.a(:com.google.android.gms@11743470:10)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at com.google.android.gms.auth.account.be.legacy.AuthCronChimeraService.b(:com.google.android.gms@11743470:7)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at edr.call(:com.google.android.gms@11743470:3)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at mmu.run(:com.google.android.gms@11743470:26)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at mse.run(:com.google.android.gms@11743470)
06-13 19:19:45.135  2769  3296 W GLSUser : 	at java.lang.Thread.run(Thread.java:818)
06-13 19:20:00.055  1262  1321 D hwcomposer: hw_composer sent 8 syncs in 60s
06-13 19:21:00.054  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:22:00.058  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:22:32.982  1948  1961 I UsageStatsService: User[0] Flushing usage stats to disk
06-13 19:23:00.044  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:24:00.050  1262  1321 D hwcomposer: hw_composer sent 5 syncs in 60s
06-13 19:25:00.070  1262  1321 D hwcomposer: hw_composer sent 9 syncs in 60s

NOTE 2: I can't seem to set a Label :)

**Comment by King-of-Spades** [comment] 2018-06-13 20:16
@owenniblock Since you referenced the project I maintain as part of the reproduction, I issued a release snapshot of that version so it's a fixed reference point. I don't anticipate any changes in the code that would alter the reproducibility of this bug, but here's that release reference point just in case: https://github.com/King-of-Spades/AppCenter-Test-Samples/releases/tag/0.1-pre2

**Comment by jonathanpeppers** [comment] 2018-06-15 14:50
@owenniblock am I right in thinking this is an issue with UITest and not Xamarin.Android itself?

**Comment by owenniblock** [comment] 2018-06-15 15:14
@jonathanpeppers - we don't think it's an issue with UITest. Nothing is changing other than the VS 4 Mac versioning - we _suspect_ that it's a bug in HTTP connection between the client and the server running on the Android device.

It's hard to identify exactly where the issue is so I wasn't sure where to log it - so if there's anything we can do to better identify the issue - please let us know.

@King-of-Spades - do you know if we also logged this with VS 4 Mac team yet?

**Comment by jonathanpeppers** [comment] 2018-06-15 15:22
So it is only a VS for Mac change, no upgrade to Xamarin.Android occurred?

**Comment by King-of-Spades** [comment] 2018-06-15 17:28
@owenniblock Should I just file my original data for the issue using the https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem process?

**Comment by owenniblock** [comment] 2018-06-18 06:41
@jonathanpeppers - thanks for helping me with this - I've been digging and I believe that you are correct - this is not a Xamarin.Android issue (the issue lies elsewhere). I'm going to write down my findings here and then hopefully we can work out the best place for this 🙂 

### The code on our side causing this issue
We have a call to a webservice on the device:
```
response = _HttpClient.SendAsync(request, cts.Token).Result;
```

Which receives an expected error and we retry until the service is ready:
```
bool ShouldRetryOnWebExceptionStatus(Exception ex, IList<WebExceptionStatus> status)
        {
            var webException = ex is WebException ?
                ex as WebException : //Mono
                ex.InnerException as WebException; //.NET

            if (webException == null)
            {
                Log.Info("Exception is not a WebException: " + ex);
                return false;
            }

            Log.Info("Checking for retry against WebException Status: " + webException.Status.ToString());

            if (webException != null && status.Contains(webException.Status))
            {
                return true;
            }

            return false;
        }
```

This is our list of acceptable exception Statuses:
```
                    var retryExceptions = new[]
                    {
                        WebExceptionStatus.ReceiveFailure,
                        WebExceptionStatus.ConnectionClosed,
                        WebExceptionStatus.ConnectFailure,
                        WebExceptionStatus.KeepAliveFailure,
                    };
```

I have added some logging to the above method to we can see what's happening more easily.

### Behaviour on current stable branch of VS 4 Mac
When we run this on the current stable branch - the call to System.Net.HttpClient returns an expected error:
```
{System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error getting response stream (ReadDone1): ReceiveFailure ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
  at System.Net.Sockets.Socket.EndReceive (System.IAsyncResult asyncResult) [0x0000c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/net/System/Net/Sockets/Socket.cs:4522 
  at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x00057] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/net/System/Net/Sockets/NetworkStream.cs:858 
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x0007c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/net/System/Net/Sockets/NetworkStream.cs:870 
  at System.Net.WebConnection.ReadDone (System.IAsyncResult result) [0x0001b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net/WebConnection.cs:467 
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00052] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net/HttpWebRequest.cs:1031 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/FutureFactory.cs:550 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x003d3] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs:402 
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0046c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs:406 
--- End of stack trace from previous location where exception was thrown ---
  at Xamarin.UITest.Shared.Http.HttpClient.SendData (System.String endpoint, System.String method, System.Net.Http.HttpContent content, Xamarin.UITest.Shared.Http.ExceptionPolicy exceptionPolicy, System.Nullable`1[T] timeOut) [0x000e0] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest.Shared/Http/HttpClient.cs:220 
  at Xamarin.UITest.Shared.Http.HttpClient.Post (System.String endpoint, System.String arguments, Xamarin.UITest.Shared.Http.ExceptionPolicy exceptionPolicy, System.Nullable`1[T] timeOut) [0x0001b] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest.Shared/Http/HttpClient.cs:159 
  at Xamarin.UITest.Shared.Http.HttpClient.PostUntilExpectedResultReceived (System.String endpoint, System.String arguments, System.String expectedContent, System.Int32 retries) [0x0001c] in /Users/owenniblock/Xamarin.UITest/src/Xamarin.UITest.Shared/Http/HttpClient.cs:121 }
	base: {System.Exception}
```

We retry because we're getting a Status of `WebExceptionStatus.ReceiveFailure`

### Behaviour on current beta branch of VS 4 Mac
When running on the beta branch - we see 2 different behaviours - in the first - the exception looks almost identical but we're getting the Status as: `WebExceptionStatus.UnknownError`

Other times - the exception we receive does not have an InnerException of Type `WebException` (we we can't get the Status):
```
Exception is not a WebException: System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.IO.IOException: Unable to write data to the transport connection: The socket is not connected. ---> System.Net.Sockets.SocketException: The socket is not connected
  at System.Net.Sockets.Socket.BeginSend (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags, System.AsyncCallback callback, System.Object state) [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/net/System/Net/Sockets/Socket.cs:3490 
  at System.Net.Sockets.NetworkStream.BeginWrite (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.AsyncCallback callback, System.Object state) [0x0009b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/net/System/Net/Sockets/NetworkStream.cs:934 
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.BeginWrite (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.AsyncCallback callback, System.Object state) [0x000c7] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/net/System/Net/Sockets/NetworkStream.cs:954 
  at System.IO.Stream+<>c.<BeginEndWriteAsync>b__53_0 (System.IO.Stream stream, System.IO.Stream+ReadWriteParameters args, System.AsyncCallback callback, System.Object state) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/stream.cs:729 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncTrim[TInstance,TArgs] (TInstance thisRef, TArgs args, System.Func`5[T1,T2,T3,T4,TResult] beginMethod, System.Func`3[T1,T2,TResult] endMethod) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/FutureFactory.cs:1349 
  at System.IO.Stream.BeginEndWriteAsync (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/stream.cs:727 
  at System.IO.Stream.WriteAsync (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.Threading.CancellationToken cancellationToken) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/stream.cs:719 
  at System.Net.WebRequestStream+<ProcessWrite>d__33.MoveNext () [0x001f5] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net/WebRequestStream.cs:246 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at System.Net.WebRequestStream+<WriteAsyncInner>d__32.MoveNext () [0x001aa] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net/WebRequestStream.cs:195 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00324] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs:393 
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0047d] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs:408 
--- End of stack trace from previous location where exception was thrown ---
  at Xamarin.UITest.Shared.Http.HttpClient.SendData (System.String endpoint, System.String method, System.Net.Http.HttpContent content, Xamarin.UITest.Shared.Http.ExceptionPolicy exceptionPolicy, System.Nullable`1[T] timeOut) [0x000c7] in <26c8ed4595584c60887b32e26a2f88cc>:0 
  at Xamarin.UITest.Shared.Http.HttpClient.Post (System.String endpoint, System.String arguments, Xamarin.UITest.Shared.Http.ExceptionPolicy exceptionPolicy, System.Nullable`1[T] timeOut) [0x00014] in <26c8ed4595584c60887b32e26a2f88cc>:0 
  at Xamarin.UITest.Shared.Http.HttpClient.PostUntilExpectedResultReceived (System.String endpoint, System.String arguments, System.String expectedContent, System.Int32 retries) [0x0001a] in <26c8ed4595584c60887b32e26a2f88cc>:0
```

**Comment by jonathanpeppers** [comment] 2018-06-18 13:02
Overall I'm guessing changes to mono and the HTTP stack have caused your issue.

It seems like `HttpRequestException` is a valid exception that should be caught and retried. It also supports HTTP status codes, I thought.

Is this code running on the device? or on the desktop inside an NUnit test? If running on the desktop, it's likely nothing to do with Xamarin.Android at all.

#### Side note
```
response = _HttpClient.SendAsync(request, cts.Token).Result;
```
Oh dear... Can this be refactored to use `async/await`?

#### I'm closing this for now, feel free to reopen if you find something that might be an issue in Xamarin.Android.

**Closed by jonathanpeppers** 2018-06-18 13:02 UTC
Labels: need-info, s/needs-info

**Comment by felipeslongo** [comment] 2018-08-24 19:52
I had the exact same problem in my Xamarin.Android UI Tests.
[To solve it we had to downgrade our mono version.](https://stackoverflow.com/questions/52009889/xamarin-ui-test-sometimes-fails-to-start/52009890#52009890)

**Comment by rohsin02** [comment] 2018-08-28 11:14
@felipeslongo I am also facing the same issue. How can I downgrade the mono version?

**Comment by rohsin02** [comment] 2018-08-28 19:00
Solution: [To solve it we had to downgrade our mono version.](https://stackoverflow.com/questions/52009889/xamarin-ui-test-sometimes-fails-to-start)

**Comment by King-of-Spades** [comment] 2018-08-30 16:25
@rohsin02 & @felipeslongo I worked with @owenniblock on the original reproduction of this issue. I'm no longer able to reproduce it when using the latest stable version of Xamarin.UITest 2.2.5, so please try updating to see if that helps.

**Comment by King-of-Spades** [comment] 2018-08-30 16:26
I confirmed based on the linked reproduction that updating to UITest 2.2.5 resolves the scenario we reported here: https://github.com/xamarin/xamarin-android/issues/1817#issuecomment-397071186
