### ISSUE TITLE
DesignMode.IsDesignModeEnabled not working as expected.

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#7765] opened 2023-02-04 02:11 UTC
---
**Issue moved from dotnet/maui#7773**
- Please respond to @beto-rodriguez.

---

_From @beto-rodriguez on Sunday, June 5, 2022 6:07:45 PM_

### Description

The `DesignMode.IsDesignModeEnabled` is not working as it should.
The property value is true even when it is running inside the Android emulator:

> true if the applications is being run in a previewer, false is the applications is being run on a device or emulator.

### Steps to Reproduce

1. Clone https://github.com/beto-rodriguez/MauiDesignModeBug
2. Run the application and see the output console.

If ran on WinUI:

![image](https://user-images.githubusercontent.com/10853349/172064111-ad769393-a46c-4ce8-ac87-42137f3b4a68.png)

If ran on Android emulator:

![image](https://user-images.githubusercontent.com/10853349/172064149-31516b89-68fc-4ed3-9658-b979c5543b84.png)

You can find additional information about this issue at https://github.com/dotnet/maui/issues/7350

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 (at least)

### Did you find any workaround?

No

**Comment by mattleibow** [comment] 2023-02-04 02:11
---
**Issue moved from dotnet/maui#7773**
- Please respond to @kristinx0211.

---

_From @kristinx0211 on Monday, June 6, 2022 5:03:09 AM_

verified repro on android 12 with vs 17.3.0 Preview 3.0 [32605.41.main].
![image](https://user-images.githubusercontent.com/99457000/172097986-89864c38-8287-4b9b-b60e-f302384f601e.png)

**Comment by jpobst** [comment] 2023-02-06 18:26
@mattleibow `DesignMode.IsDesignModeEnabled` seems to be an API provided by MAUI and does not seem to call into any XA function.  Can you clarify where in XA the issue potentially is?

**Comment by mattleibow** [comment] 2023-02-14 07:13
I was just moving an issue from @beto-rodriguez

**Comment by beto-rodriguez** [comment] 2023-02-14 07:27
I do know know if this issue belongs to Xamarin or MAUI but you can reproduce the issue in the provided repo.

**Comment by mattleibow** [comment] 2023-02-14 10:02
Maybe we need to go back to the OG issue. You are saying that the property says it is not in design mode when on the emulator? I think that behavior is correct as the emulator is not design mode. It is a running app in a valid environment.

Are you looking for a way to determine a device vs emulator? This is sometimes had as emulators try their best to pretend. But you can maybe try the essentials api DeviceInfo and is the type physical vs emulator.

**Comment by beto-rodriguez** [comment] 2023-02-14 14:40
The problem I see is that the property does not behave as the documentation says, the docs say: 

> true if the applications is being run in a previewer, false is the applications is being run on a device or emulator.

So according to the docs, it seems like a bug.

In my case this issue causes that a SkiaSharp-based control is not drawn in the emulator, you can find more info about the case at https://github.com/dotnet/maui/issues/7350.

**Comment by beto-rodriguez** [comment] 2023-02-14 15:58
In the case of LiveCharts, the issue is that I cannot load SkiaSharp in the designer (not sure if possible), So when the chart is in the designer, I just do not draw the control. That seems to work fine, but only in MAUI the library has this issue.

**Comment by jpobst** [comment] 2023-08-14 15:15
This is a MAUI API, so I don't think there's anything for XA to do here.
https://github.com/dotnet/maui/blob/ff02f57419b5337e430cc9d9fc4d6c28577876a4/src/Controls/src/Core/DesignMode.cs#L6

Closing. If this is still an issue it needs to go back to the original MAUI issue or a new MAUI issue.

**Closed by jpobst** 2023-08-14 15:15 UTC
Labels: needs-triage, need-attention
