### ISSUE TITLE
Generic RecyclerView.Adapter crashes

### ISSUE THREAD

**Issue by ctrl-shift** [xamarin/xamarin-android#1189] opened 2018-01-12 11:34 UTC
Xamarin android version included in latest VS Preview does not handle generic RecyclerView Adapters.
Check attached test project. Everything runs fine from current stable version of VS.

### Steps to Reproduce

1. Create generic RecyclerView.Adapter
2. Set it as adapter to RecyclerView
3. Observe crash on runtime without stacktrace

[TestApp.zip](https://github.com/xamarin/xamarin-android/files/1625843/TestApp.zip)

### Expected Behavior
Everything runs fine
### Actual Behavior
App crashes without output or catching exception in debug
### Version Information

Microsoft Visual Studio Community 2017 Preview (2)
Version 15.6.0 Preview 2.0
VisualStudio.15.Preview/15.6.0-pre.2.0+27309.0
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

**Comment by jonpryor** [comment] 2018-01-12 22:07
I am unable to reproduce a crash on a Pixel 2 running Android 8.0.

*However*, I do observe the following message in `adb logcat`:

```
E RecyclerView: No layout manager attached; skipping layout
```

If I [try to search for the above](https://www.google.com/search?q=RecyclerView:+No+layout+manager+attached;+skipping+layout), a [stackoverflow response comes up](https://stackoverflow.com/questions/29141729/recyclerview-no-adapter-attached-skipping-layout), and from a quick reading of the answer I think your repro project is incomplete. For example, you don't have a `<android.support.v7.widget.RecyclerView/>` element within `Resources\layout\Main.axml`.

I also don't understand how the repro is supposed to work: `Resource.Layout.Main` is just a `<LinearLayout/>` which doesn't do anything with the `RecyclerView` instance created in the constructor.

I don't understand how this is supposed to work in the first place.

**Comment by erikpowa** [comment] 2018-01-13 02:07
I had similar issues or the same with the xamarin.android that came with the  15.6 pewview 2.0, maybe it was 8.1.3.0?
[App9.csproj.zip](https://github.com/xamarin/xamarin-android/files/1627956/App9.csproj.zip)
As I remember, from 8.2.0.6? it's not reproducible anymore since this version.

**Comment by ctrl-shift** [comment] 2018-01-15 08:16
@jonpryor This is just a simplest repro project that crashes for me on latest VS preview but not on stable.
I've got the same issue in multiple places in a rather large app.
Looked a bit more into the logs of the app, found:  
`F/art     ( 3928): art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: can't make objects of type android.support.v7.widget.RecyclerView$Adapter: 0x12c2cc80
F/art     ( 3928): art/runtime/java_vm_ext.cc:470]     in call to AllocObject
...`

Checked Xamarin.Android version on VS preview - it's 8.2.0.1 (HEAD/1e47e7ed5), so it might be the version with the issue @erikpowa mentioned. Is there any way to update Xamarin.Android in VS preview without waiting for whole VS update, so I can check if issue is resolved at 8.2.0.6?

**Comment by erikpowa** [comment] 2018-01-15 10:05
@ctrl-shift [jenkins](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-d15-6/) . But prepare for other bugs. You can roll back whenever you want from VS Extensions.

**Comment by ctrl-shift** [comment] 2018-01-15 12:09
Updated to 8.2.0.6 and I can no longer reproduce this anywhere.
I suppose issue can be closed.

**Comment by jonpryor** [comment] 2018-01-16 00:59
Closing.

**Closed by jonpryor** 2018-01-16 00:59 UTC
Labels: need-info
