### ISSUE TITLE
VS2019 16.7.0 Prev 3.1 Not preserving data cache on device between deploys

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#4913] opened 2020-07-12 01:15 UTC
Prev 3.0 and 3.1 were/are wiping out my default preference settings on about every third/fourth deploy. It is very difficult to determine exactly how much code you can edit/add between debug deploys before you find that the latest deploy has wiped out your settings. Obviously really frustrating and tedious to have to repeatedly set all the default settings (such as Google Sign In, get a license etc from the server etc) before you can even test the latest changes.

Does anyone have suggestions as to why this is happening or workarounds? The property is checked in the IDE under Xamarin/Android settings

**Comment by dellis1972** [comment] 2020-07-14 10:52
This can happen, while we tell `adb` to preserve the data sometimes the apk is just incompatible and has to be fully uninstalled. This will result in the loss of data. There does not seem to be any specific list of things that might cause this. But things like, changing the AndroidManifest.xml, changing signing keys or even resources (layouts) might well cause the apk to be incompatible. 

What would be helpful is the diagnostic deployment log. This should contain warnings or output which will say that the application was fully uninstalled.

**Comment by gmck** [comment] 2020-07-14 20:44
@dellis1972. Items like you have suggested have not been changed recently. The androidmanifest.xml, resource.designer.cs, layout files etc, for instance, have not been modified since late in June. All the changes I've made since moving to Prev 3.1 have been made in three fragments plus the MainActivity. So they are all code changes, which shouldn't normally result in the apk being removed between builds.

I can send the buildlogs, but I would probably have to send several because as I've said this doesn't happen on every change and it is problematic knowing when the next build is going to totally replace the apk. 

I'm trying to use the new NavigationComponent to control what I used to do with FragmentTransactions. Typically I used OnResume/OnPause of the fragment to subscribe/unsubscribe to a bunch of event handlers to handle configuration changes. But the behaviour of the fragment lifecycle has changed using the Navigation component. For instanced OnPause of an existing fragment can be called after OnResume of the fragment you are about to enter, which totally screws up my event handlers. OnDestinationChanged can result in a change to the TopLevelFragment when you are not even trying to navigate to it.  I can only assume that this behaviour is related to the new exaggerated way they animate the transition from one fragment to another. I don't want to trash NavigationComponent just yet because I'm very close to getting the behaviour that I want. However, this VS build behaviour is not making it any easier.

If you could point me to the area of the diagnostic build log where I'm likely to find the reason for the removal of the apk, then I can probably narrow it down and then send you those logs.

**Comment by gmck** [comment] 2020-07-15 01:30
@dellis1972 . I'm attaching a build log that produced an apk which wiped out my previous settings.  The only changes to the project since the previous build was the editing of the code of a single fragment. Most of the editing was cleaning up redundant code and adding comments re the changes made. A number of empty lifecycle events e.g. OnStop, OnDestroy and OnDestroyView were also removed, as the experimental code within them was no longer required and in a number of cases had already been commented out. Basically there were far more comments added than code removed. Please note I upgraded earlier this morning to VS 17.7.0 Prev 4.0.

[OBDNowProBuild.txt](https://github.com/xamarin/xamarin-android/files/4922306/OBDNowProBuild.txt)

**Comment by dellis1972** [comment] 2020-07-15 10:43
Looking at the log we see

```
DEBUG RunShellCommand 94FAY0NMDH pm uninstall -k "com.glmsoftware.OBDNowPro"
```

We are passing the `-k` option which is the option that you use to tell `pm` to preserve data.

```
pm uninstall [-k] [--user USER_ID] [--versionCode VERSION_CODE] PACKAGE [SPLIT]
    Remove the given package name from the system.  May remove an entire app
    if no SPLIT name is specified, otherwise will remove only the split of the
    given app.  Options are:
      -k: keep the data and cache directories around after package removal.
      --user: remove the app from the given user.
      --versionCode: only uninstall if the app has the given version code.
```

So it looks like we are doing everything right. So my guess would be that something in adb/pm is causing the data to be erased :(.

**Comment by gmck** [comment] 2020-07-15 21:22
@dellis1972 Thanks for checking that. Interesting result! I checked Android's ADB docs and I have to agree with your comments, it does look like you doing everything right. 

However, that still leaves the question how is it going to be corrected? If it doesn't work for me, with 3.0 and 3.1 then I would assume that it doesn't work for anyone else either,  but that doesn't appear to be the case as no one else has joined this thread. Either that or I'm the only guy trying to use Preview 3.1!!!

**Comment by minno726** [comment] 2020-07-22 19:53
I'm having this issue too. I'm using Visual Studio for Mac version 8.6.6 (build 11), Xamarin.Forms 4.7.0.1142, and a Google Pixel with Android 10. I don't have an exact date, but I think it started happening in the past week. I have confirmed that Preferences > Android > Preserve data/cache is checked.

**Comment by dellis1972** [comment] 2021-02-04 10:57
Closing this issue as we are tracking it on #5331 5331

**Closed by dellis1972** 2021-02-04 10:57 UTC
Labels: Area: App+Library Build
