### ISSUE TITLE
visual studio hangs during android build

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#5211] opened 2020-10-08 16:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1204029/visual-studio-hangs-during-android-build.html)._

---
[severity:It's more difficult to complete my work]
When I try to either debug or build my android xamarion forms project it starts building then just sits there forever with no progress in the output just the starting line.
1>------ Build started: Project: FMWorksApps.Android, Configuration: Debug Any CPU ------

---
#### Feedback Bot on 9/30/2020, 10:39 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by brendanzagaeski** [comment] 2020-10-26 19:21
To add a couple details to dellis1972's comment, the new Preview version of Xamarin.Android that includes the fixes from https://github.com/xamarin/xamarin-android/pull/5134 and https://github.com/xamarin/xamarin-android/pull/5071 has been published. The fixes are not yet included in a Release version. I will update this item again when a Release version is available that includes the fixes.

I will tentatively plan to close this issue when the Release version that includes the fixes is published, but I will also plan to reopen the issue after that if the reporter of this issue replies that the problem is not yet fixed in that new version.

_Release status update_

Fixes included in Xamarin.Android SDK version 11.1.0.15.

Fixes included on Windows in Visual Studio 2019 version 16.8 Preview 4 and higher. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fixes included on macOS in Visual Studio 2019 for Mac version 8.8 Preview 4 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

### Additional background info

The trace information attached to the original [Visual Studio Developer Community item](https://developercommunity.visualstudio.com/content/problem/1204029/visual-studio-hangs-during-android-build.html) shows that `Xamarin.Android.Tasks.Aapt2Daemon.Aapt2DaemonStart()` was getting stuck on a [call to `File.Exists()`](https://github.com/xamarin/xamarin-android/blob/025fde9547ff5de62b426caa46af474ceb593ba3/src/Xamarin.Android.Build.Tasks/Utilities/Aapt2Daemon.cs#L247).

This matches the analysis of the problem in <https://github.com/xamarin/xamarin-android/pull/5071>, so the chances are very good that the fixes included in Xamarin.Android 11.1 will also resolve this issue.

**Comment by brendanzagaeski** [comment] 2020-11-10 20:28
Because the candidate fix for this issue is now available in a Release version, I will close this issue based on my previous analysis. If the reporter of this issue discovers that the problem is not yet fixed in the new version, please do reply back so I can reopen the issue. Thanks!

_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android SDK version 11.1.0.17.

Fix included on Windows in Visual Studio 2019 version 16.8. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.8. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Closed by brendanzagaeski** 2020-11-10 20:28 UTC
Labels: Area: App+Library Build
