### ISSUE TITLE
[Xamarin.Android] Assertion `tramp-arm64.c:52, condition '((ins >> 24) & 0x1f) == 0x10' not met`

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-android#7352] opened 2022-09-07 11:52 UTC
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 of Azure Devops agents 20220828.1

### Description

Using Profiled AOT, the following crash happens when running on device (A surface Duo 2 here). Note that the issue does not happen when using "normal" AOT without a profile. I'm not able to reproduce on net6.0 because there are no easy steps to create a profile.

```
09-06 22:33:33.042  8303  8303 I crash_dump64: performing dump of process 8271 (target tid = 8271)
09-06 22:33:33.045  8303  8303 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-06 22:33:33.045  8303  8303 F DEBUG   : Build fingerprint: 'surface/duo2/duo2:11/2022.519.47/202205190047:user/release-keys'
09-06 22:33:33.045  8303  8303 F DEBUG   : Revision: '0'
09-06 22:33:33.045  8303  8303 F DEBUG   : ABI: 'arm64'
09-06 22:33:33.045  8303  8303 F DEBUG   : Timestamp: 2022-09-06 22:33:33-0400
09-06 22:33:33.045  8303  8303 F DEBUG   : pid: 8271, tid: 8271, name: ive.uno.ui.demo  >>> com.nventive.uno.ui.demo <<<
09-06 22:33:33.045  8303  8303 F DEBUG   : uid: 10308
09-06 22:33:33.045  8303  8303 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
09-06 22:33:33.046  8303  8303 F DEBUG   : Abort message: '* Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/mini/tramp-arm64.c:52, condition `((ins >> 24) & 0x1f) == 0x10' not met
09-06 22:33:33.046  8303  8303 F DEBUG   : '
09-06 22:33:33.046  8303  8303 F DEBUG   :     x0  0000000000000000  x1  000000000000204f  x2  0000000000000006  x3  0000007fccd03f00
09-06 22:33:33.046  8303  8303 F DEBUG   :     x4  fefefefefefefeff  x5  fefefefefefefeff  x6  fefefefefefefeff  x7  7f7f7f7f7f7f7f7f
09-06 22:33:33.046  8303  8303 F DEBUG   :     x8  00000000000000f0  x9  2e64e12967d126ae  x10 0000000000000000  x11 ffffffc0fffffbdf
09-06 22:33:33.046  8303  8303 F DEBUG   :     x12 0000000000000001  x13 00000000000000a3  x14 0000c8057b4e42db  x15 0000000034155555
09-06 22:33:33.046  8303  8303 F DEBUG   :     x16 0000007c8968dc80  x17 0000007c8966f870  x18 0000000000000008  x19 000000000000204f
09-06 22:33:33.046  8303  8303 F DEBUG   :     x20 000000000000204f  x21 00000000ffffffff  x22 000000798a6a0320  x23 000000798a7de480
09-06 22:33:33.046  8303  8303 F DEBUG   :     x24 b400007ae68b9bd0  x25 0000007990511000  x26 000000798a6a02e8  x27 0000000000000000
09-06 22:33:33.046  8303  8303 F DEBUG   :     x28 0000007c8be69000  x29 0000007fccd03f80
09-06 22:33:33.046  8303  8303 F DEBUG   :     lr  0000007c896232a0  sp  0000007fccd03ee0  pc  0000007c896232cc  pst 0000000000001000
09-06 22:33:33.046  8303  8303 F DEBUG   : backtrace:
09-06 22:33:33.046  8303  8303 F DEBUG   :       #00 pc 000000000004e2cc  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 49090ae59e6ae37f8beae53c551820ad)
09-06 22:33:33.046  8303  8303 F DEBUG   :       #01 pc 000000000028e850  /data/app/~~6hfhmZOL2T6K4N24pAS5VQ==/com.nventive.uno.ui.demo-ErE4OrB5kZmmdiQVwrImHw==/lib/arm64/libmonosgen-2.0.so (monoeg_assert_abort+24)
09-06 22:33:33.126   854   854 E tombstoned: Tombstone written to: /data/tombstones/tombstone_28
```

### Steps to Reproduce

1. checkout https://github.com/unoplatform/Uno.Gallery/commit/bca93dd536af22a40f07321fe063160b98829c15
2. Build `Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj` in Release
3. Run on device.

### Did you find any workaround?

- Using non-profiled AOT
- Disabling LLVM (https://github.com/xamarin/xamarin-android/issues/7352#issuecomment-1239864201)

**Comment by dellis1972** [comment] 2022-09-07 12:23
@grendello do we need any additional info to investigate this?

**Comment by grendello** [comment] 2022-09-07 13:57
@dellis1972 someone from the Runtime team needs to look at it, however a full log would be a good thing to have.

@jeromelaban would you mind recording and attaching the crash log using instructions below?

```shell
$ adb shell setprop debug.mono.log default,assembly,mono_log_mask=all,mono_log_level=debug
$ adb logcat -G 16M
$ adb logcat -c
# Run the app here and after it crashes, do
$ adb logcat -d > log.txt
```

**Comment by jeromelaban** [comment] 2022-09-07 14:07
Here's the log: 
[log.txt](https://github.com/xamarin/xamarin-android/files/9506873/log.txt)

**Comment by grendello** [comment] 2022-09-07 14:57
@jeromelaban hm, I spotted something interesting in your log above:

```
09-07 10:03:33.957  2929  2929 V Mono    : AOT: FOUND method System.OutOfMemoryException:.ctor (string) [0x79886bd360 - 0x79886bd3c4 0x798864fa07]
09-07 10:03:33.957  2929  2929 V Mono    : AOT NOT FOUND: (wrapper runtime-invoke) <Module>:runtime_invoke_void__this___object (object,intptr,intptr,intptr).
09-07 10:03:33.957  6947 23406 D PaneManager: IDLListener#LayoutChanged() check for valid layout for: com.microsoft.launcher
09-07 10:03:33.957 21038 21038 D PaneManager: Current configuration for: com.touchtype.swiftkey should be in sync with the latest VLM pane states!.
09-07 10:03:33.957 21038 21038 D PaneManager: onPaneStateChange for: com.touchtype.swiftkey
09-07 10:03:33.957  2929  2929 V Mono    : AOT: FOUND method System.Exception:.cctor () [0x79886c4b60 - 0x79886c4bc4 0x798864fbef]
09-07 10:03:33.957  2929  2929 V Mono    : AOT NOT FOUND: (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr).
09-07 10:03:33.957  2929  2929 F .ui.demo.canar: * Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/mini/tramp-arm64.c:52, condition `((ins >> 24) & 0x1f) == 0x10' not met
--------- beginning of crash
09-07 10:03:33.957  2929  2929 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 2929 (.ui.demo.canary), pid 2929 (.ui.demo.canary)
```

It looks like the runtime asserts when `OutOfMemoryException` is being constructed?

**Comment by jeromelaban** [comment] 2022-09-07 15:04
Definitely looks that way, though I don't believe we're doing anything with `OutOfMemoryException`.

**Comment by grendello** [comment] 2022-09-07 15:07
It seems it happens when the Mono runtime creates a default `OutOfMemoryException` instance very early in the startup sequence, to stash it for potential further use.

@lambdageek thinks it might have to do with an old issue when the compiler or assembler output Thumb instructions instead of non-Thumb and the runtime didn't know how to process them.

**Comment by grendello** [comment] 2022-09-07 15:08
@jeromelaban would you be able to test the app without AOT enabled? Just to see if it crashes then.

**Comment by jeromelaban** [comment] 2022-09-07 15:25
@grendello the application works properly without AOT.

**Comment by grendello** [comment] 2022-09-07 15:26
@jeromelaban thanks, it most likely confirms @lambdageek's theory

**Comment by grendello** [comment] 2022-09-07 20:11
@jeromelaban so, we already fixed the issue in https://github.com/xamarin/xamarin-android/commit/e1f2198e8a84f3e1fb17c8ee7332ee3ce475274e, you would have to update to XA 17.3 to get the fix though.

**Comment by jeromelaban** [comment] 2022-09-07 20:12
@grendello Thanks for the update. Would you know when (or for which VS release) is it slated to be released?

**Comment by grendello** [comment] 2022-09-07 20:15
@jeromelaban I think it's released for VS 2022 right now, you can also download the package here https://github.com/xamarin/xamarin-android#current

**Comment by jeromelaban** [comment] 2022-09-07 20:19
Ok, so if it's released (Hosted Agents are using [17.3.32825.248](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022)) it would mean that it's a different issue?

**Comment by grendello** [comment] 2022-09-07 20:27
@jeromelaban to be honest, I don't know what version of XA shipped with that version of VS - it **should** be XA 13 which contains the fix, but I can't tell from the manifest you linked to if this is the case

**Comment by grendello** [comment] 2022-09-07 20:31
According to the list of tags under the commit, [v13.0.99.36](https://github.com/xamarin/xamarin-android/releases/tag/v13.0.99.36) [v13.0.99.18](https://github.com/xamarin/xamarin-android/releases/tag/v13.0.99.18) [v13.0.0.0](https://github.com/xamarin/xamarin-android/releases/tag/v13.0.0.0) [v12.3.99.95](https://github.com/xamarin/xamarin-android/releases/tag/v12.3.99.95) [v12.3.99.58](https://github.com/xamarin/xamarin-android/releases/tag/v12.3.99.58) should have the fix

**Comment by grendello** [comment] 2022-09-07 20:33
I checked in VS 2022 17.3.0 Preview 5.0, and it contains XA 13.0.0.0

**Comment by grendello** [comment] 2022-09-07 20:34
@jeromelaban would you be able to obtain a binlog of the CI build? We would be able to check what arguments are passed to the native linker when AOT-ing

**Comment by jeromelaban** [comment] 2022-09-07 20:43
Of course, here's one: [7352-build.zip](https://github.com/xamarin/xamarin-android/files/9510431/7352-build.zip)

**Comment by grendello** [comment] 2022-09-07 20:52
@jeromelaban I see your build enables LLVM - this will cause the AOT task to **not** pass the `--no-relax` flag to the linker, which will eventually cause the issue. Can you try disabling LLVM to see if this is really the case?

**Comment by jeromelaban** [comment] 2022-09-07 20:53
Sure! It'll take me a few hours, I'll let you know.

**Comment by jeromelaban** [comment] 2022-09-08 00:33
@grendello Indeed, without LLVM yet with Profiled AOT enabled, the build is working properly.

**Comment by grendello** [comment] 2022-09-08 08:51
@jeromelaban until https://github.com/xamarin/xamarin-android/pull/6901 is merged and released, you'll need to keep LLVM disabled. Glad that it works though :)

**Comment by grendello** [comment] 2022-09-08 08:53
@jeromelaban since we addressed the original problem, I will close the issue and we can revisit enabling LLVM once #6901 is merged and you can test with it.

**Closed by grendello** 2022-09-08 08:53 UTC
Labels: Area: Mono Runtime, need-attention

**Comment by salgiza** [comment] 2022-09-08 10:18
FWIW, I discovered this thread after having the same problem on an existing pipeline, and I can confirm that disabling LLVM solved the issue.

**Comment by jeromelaban** [comment] 2022-09-08 11:45
It's also worth noting that disabling LLVM slightly increases the package size.

**Comment by SamMonoRT** [comment] 2022-09-09 19:24
Android LLVM crashes might be fixed with https://github.com/dotnet/runtime/pull/74991, https://github.com/dotnet/runtime/pull/75261 and https://github.com/dotnet/runtime/pull/74674 backported to release\7.0 -- these should be included in RC2

**Comment by Alex-Dobrynin** [comment] 2022-09-15 22:49
I have the same error, but there is no mention about AOT or LLVM.
this is my device log
[device log.txt](https://github.com/xamarin/xamarin-android/files/9579440/device.log.txt)

This only happens when I build using appcenter. when I build using VS 2022 my app works fine

**Comment by salgiza** [comment] 2022-09-16 07:55
@Alex-Dobrynin Two things that you should check, just in case:

- Does AppCenter use a different build configuration (e.g. you build using Debug and AppCenter using Release)? The EnableLLVM option is usually enabled for Release, but not for Debug.
- Does AppCenter set the EnableLLVM param when compiling? (You can pass the parameter to msbuild to ignore what's in the csproj file). If it wasn't for this bug, EnableLLVM should be enabled for Release builds, so it wouldn't surprise me if AppCenter added some default params. to msbuild, and this was one of them.

**Comment by Alex-Dobrynin** [comment] 2022-09-16 09:13
@salgiza this is my proj settings
![image](https://user-images.githubusercontent.com/23138430/190601917-f66b30ca-dfb9-49a4-92b6-2c608ba5a0d5.png)
VS 2022 17.3.4

appcenter uses the same config but it uses this version of XA
![image](https://user-images.githubusercontent.com/23138430/190602431-92d13ea4-e0cf-4e2c-a4ba-29738b0d44d8.png)

**Comment by salgiza** [comment] 2022-09-16 09:50
@Alex-Dobrynin under "AOT Compilation", uncheck the "Use LLVM Optimizing Compiler" option. If it's the same bug that we've talked about in this thread, that's the option that caused the issue to appear.

**Comment by Alex-Dobrynin** [comment] 2022-09-16 19:50
@salgiza then why built by VS it is working? LLVM is on

**Comment by salgiza** [comment] 2022-09-19 07:15
@Alex-Dobrynin no idea, but it's worth giving it a shot. If it stills fails compiling after you disable that option, though, that would mean that, even though the resulting error is the same, you might have found a different bug.
