### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object 

### ISSUE THREAD

**Issue by BalasubramaniSundaram** [xamarin/xamarin-android#3905] opened 2019-11-12 18:29 UTC
Hi Team,

Current we have encountered the random issue we are facing in Xamarin.Android from the Android.Widget.TextView, Android.Widget.ProgressBar, Android.Views.GestureDetector when navigating to the page or rotator view to showcase our custom control view but the issue didn't consistently produce in our side and also in the simple sample.

In our production code, on deep and hard analysis, we found that when we are going to access the Derived view of Base view (Android.Widget.ProgressBar) but in that base property "Progress" gets automatically disposed of from the framework so at a time "ObjectDisposedException" gets throwing. 

We have tried to sort out in a simple sample but it didn't get reproduced so we get blocked here to move a further step to resolve this issue in our end.  We have shared the details of the exception call stack in different scenarios based on that whether any step to resolve this issue. please help to resolve the issue

![image](https://user-images.githubusercontent.com/45868997/68698725-8f4bac80-05a7-11ea-9674-89321c98f24b.png)

![image](https://user-images.githubusercontent.com/45868997/68698685-7b07af80-05a7-11ea-89de-b80a834e5a91.png)

![image](https://user-images.githubusercontent.com/45868997/68698711-86f37180-05a7-11ea-8945-5e9d62c7911c.png)

We have tried some sample with a custom view that sample also we have attached in the incident please refer the sample to known the flow of action.

Sample 
[GridFragmentSample.zip](https://github.com/xamarin/xamarin-android/files/3837615/GridFragmentSample.zip)

[DataGridDemo.zip](https://github.com/xamarin/xamarin-android/files/3837618/DataGridDemo.zip)

**Comment by pjcollins** [comment] 2019-11-13 19:43
This is possibly a duplicate of an older bug, which has been moved to  https://github.com/mono/mono/issues/14282.

To help confirm if this is a duplicate, are you still able to reproduce the issue if you set the  `MONO_GC_PARAMS=bridge-implementation=old` environment variable in your application project?

You can do this by adding a new text file which contains the line above, and then setting the build action of the file to `AndroidEnvironment`.

**Comment by BalasubramaniSundaram** [comment] 2019-11-14 05:46
Hi @pjcollins, 

Thanks for the help. We will check and update the status.

Regards, 
Balasubramani Sundaram

**Comment by BalasubramaniSundaram** [comment] 2019-11-18 09:48
Hi @pjcollins, 

If we change the bridge implementation from Tarjan to old or new it will affect the other things in our application. 

Regards,
Balasubramani Sundaram

**Comment by BalasubramaniSundaram** [comment] 2019-11-20 06:33
Hi @pjcollins , 

Thanks for the help, The provided solution is working fine after we changed to "Old" but we need some details on this after changed to old it will affect any other cause in application-level when we upgrading the mono android level. 

Regards, 
Balasubramani Sundaram.

**Comment by BalasubramaniSundaram** [comment] 2019-11-20 06:34
Hi @pjcollins, 

Could you please update on this? 

Regards,
Balasubramani Sundaram.

**Comment by pjcollins** [comment] 2019-11-20 14:59
It's possible that changing GC options will result in some sort of impact on the performance of your application, though you may not notice any differences. Here's some documentation that may be of use if you do experience any extra or longer GC pauses after switching - https://docs.microsoft.com/en-us/xamarin/android/internals/garbage-collection#helping-the-gc

**Comment by BrzVlad** [comment] 2020-01-07 15:02
Should be fixed by https://github.com/mono/mono/pull/18239

**Closed by BrzVlad** 2020-01-07 15:02 UTC

**Comment by brendanzagaeski** [comment] 2020-04-08 21:14
Duplicate of #2049
