### ISSUE TITLE
Visual Studio 15.6.1 regression Android.Util.AndroidRuntimeException Activity did not call through to super.onCreate()

### ISSUE THREAD

**Issue by jalbertSyncroTech** [xamarin/xamarin-android#1399] opened 2018-03-12 17:11 UTC
Cross posted to mono and Xamarin.Forms
https://github.com/mono/mono/issues/7577
https://github.com/xamarin/Xamarin.Forms/issues/2081

We have a Xamarin.Forms Android app that was previously working with VS 15.5.7 and is no longer working with VS 15.6.1.  It crashes during startup with the unhandled exception AndroidRuntimeException: Activity did not call through to super.onCreate().

Our activity does override OnCreate(), and we've verified via the debugger that the base.OnCreate() is being called.  However, the Xamarin.Forms FormsAppCompatActivity that Android applications are supposed to sub-class also overrides OnCreate(), so if it's just overriding that causes the issue everyone using Xamarin.Forms should be seeing this.

This is currently a show-stopper for our development team.

### Steps to Reproduce

1. Upgrade from VS 15.5.7 or earlier to 15.6.1
2. Android Application crashes at startup with the unhandled exception AndroidRuntimeException: Activity did not call through to super.onCreate()

### Expected Behavior

App should not crash, it was previously working with 15.5.7.

### Actual Behavior

App crashes, this is a regression.

### Version Information

Visual Studio 15.6.1
Xamarin.Android SDK   8.2.0.15 (HEAD/22d97e153)
Xamarin.Forms 2.5.0.280555 (also w/Xamarin.Forms 2.4.0.280)

### Log File

Call Stack
```
0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
0x1 in System.Diagnostics.Debugger.Mono_UnhandledException	C#
0x6 in Android.Runtime.UncaughtExceptionHandler.UncaughtException	C#
0x1A in Java.Lang.Thread.IUncaughtExceptionHandlerInvoker.n_UncaughtException_Ljava_lang_Thread_Ljava_lang_Throwable_	C#
0x1D in object.9a1fd30c-e995-4621-8122-35964d969409	C#
```

**Comment by jalbertSyncroTech** [comment] 2018-03-16 15:28
Another instance of this issue
#1414 android.util.SuperNotCalledException

**Comment by atsushieno** [comment] 2018-03-23 07:02
> Steps to Reproduce
>
>    Upgrade from VS 15.5.7 or earlier to 15.6.1
>    Android Application crashes at startup with the unhandled exception AndroidRuntimeException: Activity did not call through to super.onCreate()

This is not a description for repro steps, in that we cannot do the same. An example repro steps would be:

1. Open the app.sln in http://foobarbaz.microsoft.com/blahbleh.zip 
2. Build and run.

Could you point to any public repro solution/project or upload your projects?

**Comment by jalbertSyncroTech** [comment] 2018-03-23 13:40
@atsushieno I understand that this isn't a *good* set of reproducible steps, but none the less my entire team is unable to develop on Android with 15.6, where as they could with 15.5.

I'm happy to do further investigation with the code base we have - maybe there's some higher level of logging you know how to enable? - but I can't provide that code as is for numerous reasons.
* I *did* try to reproduce this using a new Xamarin.Forms project and referencing the same set of 3rd party packages that our project is using, but it didn't have any impact.
* We've also used MultiDex at various time because of the size of our project, but enabling/disabling that didn't have any impact.
* Sometimes, instead of this exception we will instead get "Failed resolution of: Lcom/google/android/gms/R$string".  Sometime, it will also just work.

The most frustrating aspect of all of this is that two developers with the same setup can checkout the same code base, and one have it run fine and the other get this error.  Even doing a "rebuild all" it will sometimes work and sometimes fail.  There appears to be something in the Xamarin.Android build process that is completely non-deterministic, and it's thwarting all of our efforts to further investigate this show-stopper issue.

**Comment by atsushieno** [comment] 2018-03-23 13:56
This is an open source repository. If you cannot discuss with open code, you'd rather like to ask Microsoft support. support@xamarin.com would redirect to somewhere appropriate (sorry but I don't know how the latest support logistics dispatches things internally, it's not visible to me).

**Comment by jalbertSyncroTech** [comment] 2018-04-06 17:11
Minor update:
This happens consistently on a clean checkout, but using "Rebuild Solution" specifically (without cleaning first, and not just "Build Solution") seems to work-around the issue.

**Comment by patook** [comment] 2018-04-06 22:05
@jalbertSyncroTech unfortunately we ended up pushing such a build to the app store. It was working fine on all local devices but now we are getting crashes. Do you happen to know what the latest version of Visual Studio/Xamarin Android/Mono that was working for you was?

To add to the conversation, we do NOT use Xamarin Forms, and this is a new regression. 

We have very high frequency repros on Android 8.0 in the play store so this might be a good starting point (in fact it looks like it crashes most of the time). I do not have a 8.0 capable device though. This started happening only in the latest version of Mono/Xamarin Android

android.util.SuperNotCalledException: Activity {com.xxx.yyy/md5772a35d98782517b430c7cfa7d5634a5.MainActivity} did not call through to super.onCreate()

and here is MainActivity

```
public class MainActivity : AppCompatActivity
    { 
       protected override async void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
```

Has there been any progress on this since it was opened?

**Comment by jalbertSyncroTech** [comment] 2018-04-06 22:50
Another update:
This seems to be related to the generated Resource.Designer.cs file.  We have multiple library projects that provide shared resources to our main application.  There are duplicate id's in these files such that different projects have the same id for different resources.  Occasionally when we see a crash on startup, it's referring to a resource with one of these duplicate id's.

**Comment by jalbertSyncroTech** [comment] 2018-04-06 22:53
@patook We've been seeing this since we upgraded from VS 15.5.x to 15.6.x.  No progress on our end other than discovering that "Rebuild solution" seems to work, and no response from either Xamarin.Android or Xamarin.Forms in over two weeks.

**Comment by patook** [comment] 2018-04-06 23:07
We've received a bunch of e-mails from our Android 8.0 users and they are telling us the app just never launches. It says "Unfortunately, app has stopped". 

MainActivity is the one where it's crashing - @atsushieno if you have an 8.0 device you might be able to get a repro just with the code below:
```

 [Activity(Label = "@string/app_name",
        LaunchMode = LaunchMode.SingleTask, 
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation,
        ScreenOrientation = ScreenOrientation.Portrait ,
        Theme = "@style/SplashTheme",   
        MainLauncher = true)]
    public class MainActivity : AppCompatActivity
    {    
protected override async void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

}
}

```

**Comment by jalbertSyncroTech** [comment] 2018-04-16 14:34
@atsushieno, @patook, @PureWeen I've discovered a related bug and have a temporary work around, see #1544 Android.Runtime.ResourceIdManager.UpdateIdValues() called multiple times, adds 23 seconds to application startup

**Comment by JonDouglas** [comment] 2018-05-02 16:35
I am marking this issue as a duplicate of #1414 although this was reported first, the report in #1414 has a bit more information such as device versions and models to the issue at hand. I appreciate you being diligent and filing this issue more times than you really should have to. Further discussion will take place in #1414 regarding the `android.util.SuperNotCalledException` issue.

**Closed by JonDouglas** 2018-05-02 16:35 UTC
Labels: bug, duplicate, need-info
