### ISSUE TITLE
keystore was tampered with or password was incorrect

### ISSUE THREAD

**Issue by mrklintscher** [xamarin/xamarin-android#2166] opened 2018-09-09 14:04 UTC
### Steps to Reproduce

1. Build and archive app
2. Sign the app
3. 

### Expected Behavior

Signing app with keystore certificate.

### Actual Behavior

keystore was tampered with or password was incorrect

The entered password is 100 % correct.

### Version Information

VS 2107 Build 15

**Comment by JonDouglas** [comment] 2018-09-09 22:57
Do you have a sample keystore and password that demonstrates this issue? Please note that keystore prompts are case-sensitive when inputting your existing passwords. If you suspect there is a problem with signing in the IDE, try to manually sign your package and let us know if that worked:

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/signing/manually-signing-the-apk

**Comment by mrklintscher** [comment] 2018-09-10 04:46
[Royal Flush Entertainment.zip](https://github.com/xamarin/xamarin-android/files/2365158/Royal.Flush.Entertainment.zip)

Password: Pwd123

**Comment by mrklintscher** [comment] 2018-09-10 07:10
I dont know how to manually sign an apk. Where is the apk stored? Keystore was created with IDE. Maybe something went wrong with storing password in the keystore?

**Comment by mrklintscher** [comment] 2018-09-10 07:27
And the password is 100 % correct. Thats sure.

**Comment by mrklintscher** [comment] 2018-09-10 09:13
I tried to manually sign the apk using jarsigner. Same output. There must be a bug in creating the keystore using VS.

How can this critical bug be fixed? I need to reuse the keystore, because i had to do an update of my app.

**Comment by JonDouglas** [comment] 2018-09-10 14:46
@mrklintscher There are typically two passwords for a keystore, the key password and the keystore password. To test your keystore, I would need both of those.

Just to give context here, the keystore that you signed your application with will have to be used for any future updates of your application. If you do not use [Google Play App Signing](https://medium.com/mindorks/securing-and-optimizing-your-app-with-google-play-app-signing-24a3658fd319), then you are responsible for safely storing the keystore to be used in a future app update.

Do you have reproduction steps for what you did in Visual Studio so I can understand the context here(Please be as detailed as possible)? Please also include your Visual Studio version information using `Help -> About Visual Studio`.

This is the first report of this issue to my knowledge. Our keystore creation tooling uses `keytool` behind the scenes. I tried creating a keystore and then using `apksigner sign --ks <keystore path> <apk path>` which worked fine from a quick test.

**Comment by mrklintscher** [comment] 2018-09-10 15:03
It was done with an erlier version of Visual Studio. There was no need of a second password. Yes i have written down it. I only have this one.

Von meinem iPhone gesendet

**Comment by mrklintscher** [comment] 2018-09-14 08:44
Any news? I need to update my app ...

**Comment by JonDouglas** [comment] 2018-09-14 15:33
@mrklintscher Without reproduction steps or an isolated case, it will be very difficult for us to fix anything. Specifically with this case where the `keytool` is telling you that your keystore is tampered with or the password is incorrect.

Without opt-ing into [Google Play App Signing](https://medium.com/mindorks/securing-and-optimizing-your-app-with-google-play-app-signing-24a3658fd319), you are responsible for ensuring you have a backup of the keystore on disk and the password is valid.

https://stackoverflow.com/questions/6089813/how-to-handle-a-lost-keystore-password-in-android

https://stackoverflow.com/questions/4459719/android-i-lost-my-android-key-store-what-should-i-do

You could potentially use a [brute force technique](https://github.com/tonytlwu/android-keystore-password-recover) with a few known passwords to try and crack your existing keystore. Otherwise you'll have to create a new keystore and re-upload to the Google Play Store.

**Comment by jonathanpeppers** [comment] 2018-10-08 13:46
Hi @mrklintscher,

I agree with @JonDouglas' suggestions.

But I would also suggest running [apksigner](https://developer.android.com/studio/command-line/apksigner) manually against your apk file, and see what happens there?

If `apksigner` fails, unfortunately there isn't a whole lot Xamarin.Android can do here...

It's been a while since we heard back on this. Closing this for now, but feel free to reopen if you get more info, thanks!

**Closed by jonathanpeppers** 2018-10-08 13:46 UTC
Labels: need-info

**Comment by mrklintscher** [comment] 2018-10-08 13:53
Yes you can close. I've lost my app since this horrible bug.
