### ISSUE TITLE
AndroidUseLatestPlatformSdk = true leads to build errors

### ISSUE THREAD

**Issue by cobey** [xamarin/xamarin-android#1512] opened 2018-04-04 21:28 UTC
### Details

Android Forms App created in VS Stable does not work in VS Preview or on VS for Mac Stable. The error is similar in both situations. This error can be "fixed" by setting AndroidUseLatestPlatformSdk to false on both Windows and Mac

### Steps to Reproduce

1. Download sample from [App.zip](https://github.com/xamarin/xamarin-android/files/1877687/App.zip)
2. Open App1 in VS Preview or VS Mac Stable
3. Attempt to build
4. Once build fails, edit App1.Android.csproj
5. Change `AndroidUseLatestPlatformSdk` to `false`
6. Open and build again

### Expected Behavior

App should build at step 3

### Actual Behavior

App fails to build at step 3 and succeeds at step 6

#### Mac Error

/Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/xbuild/Microsoft/NuGet/Microsoft.NuGet.targets(5,5): Error: Your project is not referencing the "MonoAndroid,Version=v7.1" framework. Add a reference to "MonoAndroid,Version=v7.1" in the "frameworks" section of your project.json, and then re-run NuGet restore. (App1.Android)

<img width="1784" alt="screen shot 2018-04-04 at 2 27 09 pm" src="https://user-images.githubusercontent.com/8754258/38335751-470f64aa-3814-11e8-9124-e5ed7a3faf4b.png">

#### Windows Error

2>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(186,5): error : Your project is not referencing the "MonoAndroid,Version=v8.1" framework. Add a reference to "MonoAndroid,Version=v8.1" in the "frameworks" section of your project.json, and then re-run NuGet restore.

#### VS Mac

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.4.2 (build 12)
Installation UUID: e1f78869-2e8c-4b18-b0ba-52c72492257c
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Enterprise)
Android SDK: /Users/codybeyer/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Enterprise)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704020012
Git revision: 0d8e3f0a4d683771f17959739956fa09c7ba21e3
Build date: 2018-03-30 10:45:17-04
Xamarin addins: 958839ea56ab1e331caf7c92b6ad50fb9e6ee9d2
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

### Log File

> VS bug [#595460](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/595460), VS bug [#603506](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/603506)

**Comment by dellis1972** [comment] 2018-04-06 09:40
This problem looks like the Nuget targets is just taking the `$(TargetFrameworkVersion)` directly. What they don't realise is it gets changed when `AndroidUseLatestPlatformSdk` is true.. I guess that is what is causing the `project.assets.json` file to not have the correct values.

**Comment by dellis1972** [comment] 2018-04-06 09:46
can you post the diagnostic output for `msbuild /t:Restore /v:diag` in the case where it fails to build. 
We need to check that `_SetLatestTargetFrameworkVersion` is running as part of that Restore process

**Comment by pjcollins** [comment] 2018-04-13 19:49
@dellis1972 here's diagnostic restore output - https://gist.githubusercontent.com/pjcollins/f72de2abd08cd9f6d6f6dbf162b72ea2/raw/be5d02996327d525f5ca3baabc9e396eb47a02f9/gistfile1.txt

**Comment by dellis1972** [comment] 2018-04-17 09:32
The only way I can repo this is by the following

1. Open App1
2. Change TargetFrameworkVersion to v7.1 in the IDE
3. Right click on App1->Packages and click Restore.
4. Open project.assets.json and see that "MonoAndroid,Version=v7.1" is present.
5. Build (it should work)
6. Change TargetFrameworkVersion to UseLatestSdk (v8.1)  in the IDE
7. Build it will fail with the error.
8. Right click on App1->Packages and click Restore.
9. Build it will fail with the error.


step 8 should have fixed the issue since the csproj changed. I feel this is a bug in the Nuget.targets or how it works in VSForMac maybe.

**Comment by dellis1972** [comment] 2018-04-17 09:33
Note #1562 has no relation to this issue.

**Comment by mrward** [comment] 2018-04-19 20:49
Both Visual Studio for Mac problems should now be fixed in version 7.5.0.1212 and later (d15-7). VS Mac will now set the correct project target framework when use latest is set so the project.assets.json is created. VS Mac will also now run a restore if the target framework is changed so the project.assets.json is updated with the correct target framework so the build will not fail due the project and the project.assets.json file being out of sync.

The problem with Visual Studio on Windows I suspect is due to a bug affecting the target framework for Android - https://github.com/xamarin/XamarinVS/pull/9011 This affects VS 15.7 (preview) and not 15.6.6 so presumably this should be fixed in a later preview.

**Comment by pjcollins** [comment] 2018-04-23 18:12
Using the steps Dean mentions I am no longer able to reproduce this in VSMac using d15-7 / 7.5.0.1222. I'm going to resolve this based on the fix in VS Mac that Matt is referring to, and have opened an issue against XVS in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/605102.

**Closed by pjcollins** 2018-04-23 18:12 UTC
Labels: bug, vs-sync
