### ISSUE TITLE
Starting debug shared runtime Got a SEGV while executing native code.

### ISSUE THREAD

**Issue by nbelley** [xamarin/xamarin-android#4994] opened 2020-08-10 12:02 UTC
### Steps to Reproduce

1.  Updated VS to 16.7
2.  Updated some nuget packages (local packages to our company)
3.  Trying to debug, crashes on start

### Version Information
Android 10 Pixel phone, crashes also on the emulator

Crash logfile attached
[adblogcat.txt](https://github.com/xamarin/xamarin-android/files/5050681/adblogcat.txt)

**Comment by grendello** [comment] 2020-08-10 13:09
Duplicate of https://github.com/xamarin/xamarin-android/issues/4983

**Closed by grendello** 2020-08-10 13:09 UTC
Labels: Area: App Runtime
