### ISSUE TITLE
Java invocation failure with master/15.6

### ISSUE THREAD

**Issue by alanmcgovern** [xamarin/xamarin-android#1187] opened 2018-01-12 10:55 UTC
With the latest master/15.6 builds of X.A i am triggering this issue inside the forms previewer:
```
Java.Lang.InstantiationException: android.view.ViewGroup
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <808e27c157614d6b865c43847235b62d>:0 
  at Java.Interop.JniEnvironment+Object.AllocObject (Java.Interop.JniObjectReference type) [0x0003c] in <8e80eb3ca41f4c3eb745bd7c73458796>:0 
  at Java.Interop.JniType.AllocObject () [0x0000c] in <8e80eb3ca41f4c3eb745bd7c73458796>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters) [0x0003e] in <8e80eb3ca41f4c3eb745bd7c73458796>:0 
  at Android.Views.ViewGroup..ctor (Android.Content.Context context) [0x0005b] in <9ca7528089f0437883d939fbe90c65ab>:0 
  at Xamarin.Forms.Platform.Android.PlatformRenderer..ctor (Android.Content.Context context, Xamarin.Forms.Platform.Android.IPlatformLayout canvas) [0x00000] in C:\Users\hartez\Documents\Xamarin\Xamarin.Forms\Xamarin.Forms.Platform.Android\PlatformRenderer.cs:16
```

The code in question is the chaining to the base constructor here https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/PlatformRenderer.cs#L16

The latest stable release of X.A works fine, so this looks like a regression between then and now.

**Comment by jonpryor** [comment] 2018-01-12 15:14
@alanmcgovern: Could you provide more output? That's an exception being thrown from Java.

**Comment by alanmcgovern** [comment] 2018-01-12 17:25
There is no more output unfortunately

**Comment by jonpryor** [comment] 2018-01-12 18:47
@alanmcgovern: *normally* a Java-side exception will contain the [Java-side stack trace](https://github.com/xamarin/xamarin-android/blob/c4e81655ac22b06806e732e9dd0bc729e8d2c1d7/src/Mono.Android/Java.Lang/Throwable.cs#L136-L169), but there isn't one being shown here.

There also aren't any repro instructions, I don't know how to recreate this behavior.

Without the Java-side exception, it's hard to reason about what could be going wrong. :-(

**Comment by jonpryor** [comment] 2018-01-22 16:49
@alanmcgovern: Please try the following code in a codepath "somewhere before" `PlatformRenderer` is created:

```csharp
var g = Type.GetType("Xamarin.Forms.Platform.Android.PlatformRenderer, Xamarin.Forms.Platform.Android")
var m = (JniPeerMembers) g.GetField("_members", BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.FlattenHierarchy).GetValue (null);
var ctors = (JniPeerMembers.JniInstanceMethods) m.InstanceMethods.GetType().GetMethod ("GetConstructorsForType", BindingFlags.NonPublic | BindingFlags.Instance).Invoke (m.InstanceMethods, new[]{g});
var dt = (Type) ctors.GetType().GetField("DeclaringType", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(ctors);
Console.WriteLine($"# jonp: ctors.DeclaringType={dt.FullName}"); 
var pt = (JniType) ctors.GetType().GetProperty("JniPeerType", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(ctors);
Console.WriteLine($"# jonp: ctors.JniPeerType={pt.Name}");
```

**Comment by jonpryor** [comment] 2018-01-25 19:01
We believe that this is a duplicate of Issue #1149. Please try with d15-6 Preview 4 installers, Xamarin.Android 8.2.0.9 or later.

**Closed by jonpryor** 2018-01-25 19:01 UTC
Labels: Area: App Runtime, regression
