### ISSUE TITLE
HTTPCLient Panifully slow on local host and via ip address

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/xamarin-android#3090] opened 2019-05-02 07:55 UTC
When I run http client in a standard console app or through the browser to my api i get very fast results however in the http client consumed in xmairan forms its very very slow

I am using the HttpClient but my results are taking up to 6-8 seconds coming back from the same machine on the same subnet and ip range of 192.168. When I call the api directly from the ip address the results are more or less instant so why is it so slow with httpclient on the same computer.

I have seen other so's that suggest set to use proxy as false is the best way to go.

I have also tested this on a stock phone and it takes around 8 seconds for the login to be successful on the phone. When i browse to the api the results as returned in second?.
```

private HttpClient _client;
public async Task<String> Getusers()
{
        var content = "";
        HttpClientHandler hch = new HttpClientHandler();
        hch.Proxy = null;
        hch.UseProxy = false;
        _client = new HttpClient(hch);
        var uri = new Uri(Constants.ApiEndPoint + "/Users"); // Your url is here

        try
        {
            var response = await _client.GetAsync(uri);
            if (response.IsSuccessStatusCode)
            {
                content = await response.Content.ReadAsStringAsync();
            }
        }
        catch (Exception ex)
        {
            throw ex;
        }

        return content;
}
```

```
private async void BtnLogin_Clicked(object sender, EventArgs e)
{
    string content = await Getusers(); //Sends a GET request to the specified Uri and returns the response body as a string in an asynchronous operation
    List<Users> _users = JsonConvert.DeserializeObject<List<Users>>(content); //Deserializes or converts JSON String into a collection of Post
    var userName = txtUserName.Text;
    var password = txtPassword.Text;
    var isValidUser = _users.Where(w => w.UserName == userName && w.password == password).FirstOrDefault();
    var driverId = _users.Where(w => w.UserName == userName && w.password == password).FirstOrDefault().ID;         


    if (isValidUser != null)
    {

            Application.Current.Properties["driverId"] = driverId;
            Application.Current.MainPage = new MainPage();
    }
    else
    {
            lblError.Text = "Error your credentials are invalid, please try again";
    }         

  }
```

**Comment by brendanzagaeski** [comment] 2019-05-22 01:21
/cc @grendello for a quick first look when you get a chance. Perhaps it will need to be forwarded once more to Mono for further investigation?

In case it's helpful, I was able to see files for the test case mentioned a few comments ago if I left out the username from the URL: <https://dev.azure.com/davidbuckleyweb/DeliveryGo/_git/DeliveryGo>. The Android application project has `$(AndroidHttpClientHandlerType)` set to `Xamarin.Android.Net.AndroidClientHandler`. I did not yet test locally to check if I could reproduce the reported behavior. One similar behavior I remember from the past was when the first HTTP request took some extra time to prepare `HttpClient` and JIT the code path, but it sounds like this new reported behavior might happen consistently across repeated requests.

**Comment by grendello** [comment] 2019-05-22 07:06
It's very unlikely this is a Xamarin.Android issue as we do not have any specific code that  deals with creation and setting up of network connections (except for `AndroidClientHandler`, but it is also merely forking out to Java for all the networking needs) and it *might* not be a Mono issue either. From reading the comments and a quick look at the code, my guess is that it's a matter of DNS lookups. What speaks in favor of it is the fact that using a plain IP address is quick, but using `localhost` makes the request slow. In theory, looking up `localhost` should be quick because it's listed in `/etc/hosts` but in practice there might be a few steps before `/etc/hosts` is consulted - name service switch may consult several databases before it reaches the plain text file on host. I would suggest using plain IP whenever possible, especially that some modern Android devices will have the secure DNS enabled and may favor those DNS servers over the locally configured ones, so the name lookup will first ask the secure/external servers, wait for it to time out, then ask the local DNS servers, time out, only then read `/etc/hosts`. @brendanzagaeski you may consider forwarding it to Mono for further investigation, should the problem lives in HttpClient and/or DNS lookup code, but I'm not certain this can be considered our stack bug at all.

**Comment by fntc** [comment] 2020-06-19 06:39
I recognized that DNS resolution is painfully slow from android in LAN.
I get a hostname on my local network after 20s, a public DNS name is resolved in a few ms.
Maythe the issue is not the HTTP at all but the android DNS?

`  Stopwatch w = new Stopwatch();
            w.Start();
            var hostEntry = Dns.GetHostEntry("developer-machine-name");
            w.Stop();
            var time = w.Elapsed.ToString();

            Stopwatch w2= new Stopwatch();
            w2.Start();
            var hostEntry2 = Dns.GetHostEntry("github.com");
            w2.Stop();
            var time2 = w2.Elapsed.ToString();
`

**Closed** 2024-05-03 21:10 UTC
Labels: Area: HTTP
