### ISSUE TITLE
VS Studio 16.6.0 Prev 3.0 App crashes immediately on startup

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#4571] opened 2020-04-17 01:35 UTC
Upgraded to Prev 3, cleaned/built/deployed and the app immediately crashed.
Ran adb uninstall Mono.Android.DebugRuntime as suggested by @brendanzagaeski  in issue 4471 and it immediately fixed the problem. Made some changes and cleaned/built and deployed a number of times and the problem hasn't reappeared.

**Comment by brendanzagaeski** [comment] 2020-04-17 07:15
Thanks for the heads-up! Now that I've had a chance to look into #4471 a bit more today, I can confirm that this behavior in Visual Studio 2019 version 16.6 Preview 3 is a recurrence of the same underlying problem from #4471 that surfaced in Preview 2.

I'll close this as a duplicate for further tracking.

**Comment by brendanzagaeski** [comment] 2020-04-17 07:15
Duplicate of #4471

**Closed by brendanzagaeski** 2020-04-17 07:15 UTC
Labels: Area: App Runtime
