### ISSUE TITLE
Process has died error

### ISSUE THREAD

**Issue by jrahma** [xamarin/xamarin-android#3413] opened 2019-07-30 17:57 UTC
Hi,

I am testing my app on Debug mode and it's working perfectly and then when I install the apk (from Release mode) to my device then the app crashes immediately.

I am getting [no crash log in AppCenter](https://github.com/microsoft/appcenter/issues/789) which is also another problem

How can I know where is the problem here? and how can I fix it?

This is the log I get from Android Device Monitor

Thanks,
[Jassim](https://www.jassimrahma.net)

[log.txt](https://github.com/xamarin/xamarin-android/files/3448229/log.txt)

**Comment by jpobst** [comment] 2019-07-31 14:06
Duplicate of https://github.com/xamarin/xamarin-android/issues/3391.

**Closed by jpobst** 2019-07-31 14:06 UTC
