### ISSUE TITLE
Error deploying Android App : Command Too Long

### ISSUE THREAD

**Issue by ptabatt** [xamarin/xamarin-android#5710] opened 2021-03-08 17:06 UTC
### Steps to Reproduce

1. Clean Solution
2. Make sure "Use Fast Deployment" is checked under "Android Options" in the project properties
3. Run Solution against a device or emulator in debug mode

### Expected Behavior
Device either A) builds and runs successfully or B) fails and shows a meaningful error message indicating some sort of issue on the developer's part

### Actual Behavior
Device builds android project and dependencies successfully and fails upon deployment with the following error message:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Command too long
   at Mono.AndroidTools.Adb.AdbClient.GetCommandBuffer(String command) in C:\A\1\36\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 258
   at Mono.AndroidTools.Adb.AdbClient.BeginWriteCommand(String command, AsyncCallback callback, Object state) in C:\A\1\36\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 227
   at Mono.AndroidTools.Adb.AdbClient.BeginWriteCommandWithStatus(String command, AsyncCallback callback, Object state) in C:\A\1\36\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 274
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at Mono.AndroidTools.Internal.AdbClientTaskExtensions.WriteCommandWithStatusAsync(AdbClient client, String command, TaskCreationOptions options) in C:\A\1\36\s\External\androidtools\Mono.AndroidTools\Internal\AdbClientTaskExtensions.cs:line 62
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass62_0.<RunShellCommand>b__0(Task t) in C:\A\1\36\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 403
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()		 	0	

```

### Version Information

Microsoft Visual Studio Enterprise 2019
Version 16.9.0
VisualStudio.16.Release/16.9.0+31025.194
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA407
Microsoft Visual C++ 2019

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ASP.NET and Web Tools 2019   16.9.687.37626
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2107702+c4adaa061f13292143de82a96c71341e50bc4032
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.687.37626
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.687.37626
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.9.687.37626
Azure Functions and Web Jobs Tools

C# Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   16.0.30502.00
Microsoft Office Developer Tools for Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TFS Auto Shelve   6.2
Create a shelveset for the latest version of all pending changes, automatically.  Pending changes from the local TFS workspaces will be shelved to the TFS Server every "x" number of minutes when solutions are opened.

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   16.9.000.271 (d16-9@863670b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.316 (remotes/origin/d16-9@fdbf64026)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.68 (8e9b569)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.0.21 (d16-9/93eab59)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@d6d86b2
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@9d8924d

Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File
[androidlogfile.txt](https://github.com/xamarin/xamarin-android/files/6102981/androidlogfile.txt)

**Comment by dellis1972** [comment] 2021-03-08 19:21
Some background on this. For d16-9 we had to completely re-write the fast deployment system, This is because API 30 no loner supports things the old fast deployment system was relying on. You can see the release notes at [1].
The key feature is the run-as shell command. Somehow we are generating an `adb` command which is longer that 1024 characters. 

It wold be helpful to have the diagnostic output for the error though if you can provide it. Its possible we might be able to work around any restrictions on the device. If you run the following command from a Developer Command Prompt

```
msbuild <your android csproj>  /restore /t:Install /bl /p: _FastDeploymentDiagnosticLogging=true
```

the post the msbuild.binlog ( you might have to zip it first). That will help us diagnose the problem your particular device is having.

To work around this issue you can disable fast deployment in the IDE or by setting `EmbedAssembliesIntoApk` to false in the csproj.

[1] https://docs.microsoft.com/en-us/xamarin/android/release-notes/11/11.2#rewritten-fast-deployment-system

**Comment by dellis1972** [comment] 2021-03-09 11:12
@ptabatt do you have a build log I could take a look at as mentioned in https://github.com/xamarin/xamarin-android/issues/5710#issuecomment-793008449. 
I think I have found the issue, but I'd like to add a unit test which will replicate the problem.

**Comment by ptabatt** [comment] 2021-03-09 16:21
[msbuillog.zip](https://github.com/xamarin/xamarin-android/files/6109893/msbuillog.zip)

**Comment by dellis1972** [comment] 2021-03-09 16:42
@ptabatt can you do that log again please, that one had not changes so it skipped all the targets. So uninstall the app from the device and run the command again, it should reproduce the error.

**Comment by ptabatt** [comment] 2021-03-09 16:50
Two things: 
1) Does this command write to any log file anywhere I can find in my solution? I can't find it; I'm copying and pasting from the dev console and it's too long.
2) The command only builds the project and you're having me send you the build log, but the error is on deployment. Is this intentional?

**Comment by dellis1972** [comment] 2021-03-09 16:52
@ptabatt the `/t:Install` target does the installation/deployment. So it should do the deployment

**Comment by dellis1972** [comment] 2021-03-09 18:54
@ptabatt the command

```
msbuild <your android csproj>  /restore /t:Install /bl /p: _FastDeploymentDiagnosticLogging=true
```

will produce a `msbuild.binlog` file in the same directory that you run it from. It will build the app and send it to the attached device/emulator so it should contain all the data we need.

**Comment by ptabatt** [comment] 2021-03-09 19:02
I see, thanks. Sorry for the delay.

[msbuild.zip](https://github.com/xamarin/xamarin-android/files/6110845/msbuild.zip)

**Comment by dellis1972** [comment] 2021-03-09 19:08
@ptabatt 

That was great thanks, but it didn't have the error you reported? Does that error only show up in the IDE or have you seen it on the command line as well?

**Comment by ptabatt** [comment] 2021-03-09 19:12
Only saw it on the IDE. I never build/deploy my app this way

**Comment by mportune-bw** [comment] 2021-03-10 16:11
Here's the `msbuild` output.  Let me know if this has what you need or if I need to try something else.

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-android/files/6117252/msbuild.binlog.zip)

**Comment by ptabatt** [comment] 2021-03-10 16:27
These are the bin logs from the tool @jonathanpeppers mentioned

[BinLogs.zip](https://github.com/xamarin/xamarin-android/files/6117379/BinLogs.zip)

**Comment by MarcosCobena** [comment] 2021-03-15 09:31
Hi, I am facing the same issue with latest stable Visual Studio for Mac and its dependencies: is there any feasible workaround in the meantime? I have Fast Assembly Deployment disabled, although the Deploying to Device panel shows the following:
```
Install FastDeployment Tools
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(590,5): error : Command too long
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(590,5): error :   at Mono.AndroidTools.Adb.AdbClient.GetCommandBuffer (System.String command) [0x0006d] in /Users/builder/azdo/_work/278/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Adb/AdbClient.cs:265 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(590,5): error :   at Mono.AndroidTools.Adb.AdbClient.BeginWriteCommand (System.String command, System.AsyncCallback callback, System.Object state) [0x00006] in /Users/builder/azdo/_work/278/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Adb/AdbClient.cs:227 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(590,5): error :   at Mono.AndroidTools.Adb.AdbClient.BeginWriteCommandWithStatus (System.String command, System.AsyncCallback callback, System.Object state) [0x0000a] in /Users/builder/azdo/_work/278/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Adb/AdbClient.cs:275 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(590,5): error :   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncImpl[TArg1] (System.Func`4[T1,T2,T3,TResult] beginMethod, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, TArg1 arg1, System.Object state, System.Threading.Tasks.TaskCreationOptions creationOptions) [0x000f9] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:919 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(590,5): error :   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1] (System.Func`4[T1,T2,T3,TResult] beginMethod, System.Action`1[T] endMethod, TArg1 arg1, System.Object state, System.Threading.Tasks.TaskCreationOptions creationOptions) [0x00000] in <36514b14425c4337b446653c547aa9c3>:0 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(590,5): error :   at Mono.AndroidTools.Internal.AdbClientTaskExtensions.WriteCommandWithStatusAsync (Mono.AndroidTools.Adb.AdbClient client, System.String command, System.Threading.Tasks.TaskCreationOptions options) [0x00000] in /Users/builder/azdo/_work/278/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Internal/AdbClientTaskExtensions.cs:62 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(590,5): error :   at Mono.AndroidTools.AndroidDevice+<>c__DisplayClass62_0.<RunShellCommand>b__0 (System.Threading.Tasks.Task t) [0x0000f] in /Users/builder/azdo/_work/278/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/AndroidDevice.cs:403 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(590,5): error :   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00024] in <36514b14425c4337b446653c547aa9c3>:0 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(590,5): error :   at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 
Done building target "_Upload" in project "Poseidon.Android.csproj" -- FAILED.

Done building project "***.Android.csproj" -- FAILED.

Build FAILED.
```

Thank you in advance :-)

**Comment by dellis1972** [comment] 2021-03-15 09:54
@MarcosCobena apparently there is a Bug in VSForMac which does not update the `EmbedAssembliesIntoApk` element when you click it via the IDE https://developercommunity.visualstudio.com/t/Cant-Disable-Fast-Assembly-Deployment-O/1362042
I Suggest you manually disable it in the csproj by adding the following to your Debug configuration ProeprtyGroup section.


```
<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
```

That should allow you to at least deploy until d16-3 SR 2 is  released which contains a fix.

**Comment by MarcosCobena** [comment] 2021-03-15 10:20
@dellis1972 it worked! Thank you so much :-)

**Comment by mportune-bw** [comment] 2021-03-16 19:18
Just updated to v11.2.2.1 stable and this appears to be fixed.  Thank you!

**Comment by ataparia** [comment] 2021-03-17 20:19
Hello Community,
I still continue to get this error even after upgrading VS for Windows to 16.9.2 & Xamarin.Android.SDK is 11.2.2.1.
I upgraded VS after reading the release notes where this issue is marked as fixed but doesnt seem like it unless I am doing something wrong. 

I even deleted my bin/obj folders but that didnt help either.

**Comment by jonathanpeppers** [comment] 2021-03-17 20:23
@ataparia can you attach a log as mentioned above? The fix in VS 16.9.2 increased the limit to 4096, but we will be able to have a proper fix in a future 16.10 release.

**Comment by ataparia** [comment] 2021-03-17 20:39
@jonathanpeppers  The solution builds fine and thus the command msbuild <your android csproj>  /restore /t:Install /bl /p: _FastDeploymentDiagnosticLogging=true results in success. Its just when I try to deploy to a physical device that I get "Command too long..." error. Anyways I attached "AndroidBuildLog.txt" for that command as well.
[AndroidBuildLog.txt](https://github.com/xamarin/xamarin-android/files/6159574/AndroidBuildLog.txt)


I enabled "Diagnostics"logging on VS and attached the build/deploy output. 
[AndroidDeployLog.txt](https://github.com/xamarin/xamarin-android/files/6159557/AndroidDeployLog.txt)

**Comment by mportune-bw** [comment] 2021-03-17 21:21
For the sake of completeness I should mention I'm using Jetbrains Rider for development/deployment, but use the VS Installer for updating Xamarin components.  Hopefully this helps focus the troubleshooting since 11.2.2.1 fixed the issue for me.

**Comment by jonathanpeppers** [comment] 2021-03-18 13:47
@ataparia I have an idea why the fix might be working for you command-line, but not when inside Visual Studio.

Check if your VS is installed in `Enterprise`, `Professional`, or `Community`. Mine is installed in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise`

Make a backup of this file somewhere (just in case):

    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Xamarin.VisualStudio\Mono.AndroidTools.dll"

Then open an administrator command-prompt and run:

    > copy "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Mono.AndroidTools.dll" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Xamarin.VisualStudio\Mono.AndroidTools.dll"

Next, restart Visual Studio and see if that solves the problem or not. Thanks!

**Comment by ataparia** [comment] 2021-03-18 14:25
@jonathanpeppers  Thank you so very much. Yes copying that dll did fix the issue. Cheers!

**Comment by jonathanpeppers** [comment] 2021-03-18 20:43
@ataparia they are looking to get this file updated in a future service release, thanks.

**Closed** 2021-03-23 17:01 UTC
Labels: Area: App+Library Build, need-info
