### ISSUE TITLE
JDK 11 Error when trying to build Xamarin Project on App Center

### ISSUE THREAD

**Issue by JustinJWyatt** [xamarin/xamarin-android#7244] opened 2022-08-09 18:24 UTC
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022

### Description

I find an error when trying to build my Xamarin Forms app (which includes 3 projects, Android, iOS and UWP).

My intent here is to build my UWP project, but the other projects get built as well.

When I do build this only in App Center, I get the following error:

`##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(265,5): Error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0.  Note: the Android Designer is incompatible with Java SDK 11.0: https://aka.ms/vs2019-and-jdk-11`

You will see in the error log that the JDK it's trying to target is specified in the path above .

This is a strange error since I have VS 2022 and not VS 2019. So this must be something in the cloud with some build tool that doesn't have the necessary JDK?

### Steps to Reproduce

1. Create new Xamarin Forms project. Include iOS, Android and UWP.
2. Connect your Azure repo to App Center and build your project

You will see the above error.

**Comment by jonathanpeppers** [comment] 2022-08-09 18:32
Can you get a verbose build log from App Center? I think we need that to understand what Java it's trying to use.

**Comment by JustinJWyatt** [comment] 2022-08-09 19:19
> Can you get a verbose build log from App Center? I think we need that to understand what Java it's trying to use.

Task         : Visual Studio build
Description  : Build with MSBuild and set the Visual Studio version property
Version      : 1.199.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/visual-studio-build
==============================================================================
##[command]"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.199.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [15.0,16.0) -latest -format json
##[command]"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.199.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [15.0,16.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
##[command]"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.199.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [17.0,18.0) -latest -format json
##[command]"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.199.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [17.0,18.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
##[command]"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.199.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [16.0,17.0) -latest -format json
##[warning]Visual Studio version '15.0' not found. Falling back to version '16.0'.
##[command]"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" "D:\a\1\s\EFCloud.sln" /nologo /nr:false /dl:CentralLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.199.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=5d8fec2a-1006-4c60-9f0a-ac5e14ee2ca5|SolutionDir=D:\a\1\s|enableOrphanedProjectsLogs=true"*ForwardingLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.199.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundlePlatforms="ARM|x86|x64" /p:AppxPackageDir=".\AppPackages" /p:platform="ARM" /p:configuration="Debug UWP" /p:VisualStudioVersion="16.0" /p:_MSDeployUserAgent="VSTS_7ead0839-472a-4e36-a8d4-3c34398ecf06_build_2_0"
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 8/9/2022 6:09:28 PM.
Project "D:\a\1\s\EFCloud.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug UWP|ARM".
ValidateProjects:
  The project "EFCloud.iOS" is not selected for building in solution configuration "Debug UWP|ARM".
  The project "EFCloud.UWP" is not selected for building in solution configuration "Debug UWP|ARM".
##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(429,3): Warning XA0119: Using fast deployment and the linker at the same time is not recommended. Use fast deployment for Debug configurations and the linker for Release configurations.
Project "D:\a\1\s\EFCloud.sln" (1) is building "D:\a\1\s\EFCloud\EFCloud.Android\EFCloud.Android.csproj" (2) on node 1 (default targets).
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(429,3): warning XA0119: Using fast deployment and the linker at the same time is not recommended. Use fast deployment for Debug configurations and the linker for Release configurations. [D:\a\1\s\EFCloud\EFCloud.Android\EFCloud.Android.csproj]
_CreateStampDirectory:
  Creating directory "obj\Debug UWP\120\stamp\".
_ResolveAndroidTooling:
  Found Java SDK version 1.8.0.
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(265,5): Error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0.  Note: the Android Designer is incompatible with Java SDK 11.0: https://aka.ms/vs2019-and-jdk-11
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(265,5): error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0.  Note: the Android Designer is incompatible with Java SDK 11.0: https://aka.ms/vs2019-and-jdk-11 [D:\a\1\s\EFCloud\EFCloud.Android\EFCloud.Android.csproj]
Done Building Project "D:\a\1\s\EFCloud\EFCloud.Android\EFCloud.Android.csproj" (default targets) -- FAILED.
Project "D:\a\1\s\EFCloud.sln" (1) is building "D:\a\1\s\EFCloud.UITest\EFCloud.UITest.csproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "bin\Debug\".
  Creating directory "obj\Debug\".
CoreCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /fullpaths /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\mscorlib.dll" /reference:D:\a\1\s\packages\NUnit.3.12.0\lib\net45\nunit.framework.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.dll" /reference:D:\a\1\s\packages\Xamarin.UITest.3.2.4\lib\net45\Xamarin.UITest.dll /debug+ /debug:full /optimize- /out:obj\Debug\EFCloud.UITest.dll /subsystemversion:6.00 /target:library /utf8output /langversion:7.3 BaseTestFixture.cs AppManager.cs PlatformQuery.cs BasePage.cs Tests\StartupTest.cs Page\StartupPage.cs Page\EnterpriseConfigPage.cs "obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs"
  CompilerServer: server - server processed compilation - f75245c2-2edd-424d-9f80-1b66c8e77431
_CopyFilesMarkedCopyLocal:
  Copying file from "D:\a\1\s\packages\NUnit.3.12.0\lib\net45\nunit.framework.pdb" to "D:\a\1\s\EFCloud.UITest\bin\Debug\nunit.framework.pdb".
  Copying file from "D:\a\1\s\packages\Xamarin.UITest.3.2.4\lib\net45\Xamarin.UITest.dll" to "D:\a\1\s\EFCloud.UITest\bin\Debug\Xamarin.UITest.dll".
  Copying file from "D:\a\1\s\packages\NUnit.3.12.0\lib\net45\nunit.framework.xml" to "D:\a\1\s\EFCloud.UITest\bin\Debug\nunit.framework.xml".
  Copying file from "D:\a\1\s\packages\NUnit.3.12.0\lib\net45\nunit.framework.dll" to "D:\a\1\s\EFCloud.UITest\bin\Debug\nunit.framework.dll".
  Copying file from "D:\a\1\s\packages\Xamarin.UITest.3.2.4\lib\net45\Xamarin.UITest.xml" to "D:\a\1\s\EFCloud.UITest\bin\Debug\Xamarin.UITest.xml".
  Creating "D:\a\1\s\EFCloud.UITest\obj\Debug\EFCloud.UITest.csproj.CopyComplete" because "AlwaysCreate" was specified.
_CopyOutOfDateSourceItemsToOutputDirectory:
  Copying file from "D:\a\1\s\packages\Xamarin.UITest.3.2.4\tools\test-cloud.exe" to "D:\a\1\s\EFCloud.UITest\bin\Debug\test-cloud.exe".
CopyFilesToOutputDirectory:
  Copying file from "D:\a\1\s\EFCloud.UITest\obj\Debug\EFCloud.UITest.dll" to "D:\a\1\s\EFCloud.UITest\bin\Debug\EFCloud.UITest.dll".
  EFCloud.UITest -> D:\a\1\s\EFCloud.UITest\bin\Debug\EFCloud.UITest.dll
  Copying file from "D:\a\1\s\EFCloud.UITest\obj\Debug\EFCloud.UITest.pdb" to "D:\a\1\s\EFCloud.UITest\bin\Debug\EFCloud.UITest.pdb".
Done Building Project "D:\a\1\s\EFCloud.UITest\EFCloud.UITest.csproj" (default targets).
Project "D:\a\1\s\EFCloud.sln" (1) is building "D:\a\1\s\EFCloud\EFCloud\EFCloud.csproj" (4) on node 1 (default targets).
PrepareForBuild:
  Creating directory "bin\Debug\netstandard2.0\".
  Creating directory "obj\Debug\netstandard2.0\".
XamlG:
  Generating code behind for XAML files
CssG:
Skipping target "CssG" because it has no outputs.
CssG:
Skipping target "CssG" because it has no outputs.

**Comment by jonathanpeppers** [comment] 2022-08-09 19:26
What do you have set for this setting? This is what my App Center shows as latest right now:

![image](https://user-images.githubusercontent.com/840039/183744360-7e0897b9-07f5-4e41-ba0e-65a1c39b547e.png)

It seems like you have an old image, as it's showing VS 2019 in your log:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe"
```

**Comment by jonathanpeppers** [comment] 2022-08-09 19:51
We had a lot of Azure DevOps image issues come in recently, I think this could be duplicate of: https://github.com/actions/runner-images/issues/6038

The `macos-latest` image is broken, and I think you need to reinstall Xamarin.Android over top:
```
dotnet tool install --global boots 
boots --stable Xamarin.Android
```

But to do this on App Center you have to use a "pre build" script like this example:

https://github.com/jonathanpeppers/boots/blob/main/samples/HelloForms.Android/appcenter-pre-build.sh

**Comment by JustinJWyatt** [comment] 2022-08-09 21:13
> What do you have set for this setting? This is what my App Center shows as latest right now:
> 
> ![image](https://user-images.githubusercontent.com/840039/183744360-7e0897b9-07f5-4e41-ba0e-65a1c39b547e.png)
> 
> It seems like you have an old image, as it's showing VS 2019 in your log:
> 
> ```
> "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe"
> ```

I'm not using an Android Project. I'm building a UWP Project. So I don't have that SDK version option

**Comment by jonathanpeppers** [comment] 2022-08-09 21:32
@JustinJWyatt can you remove the Android project from your `.sln`?

It seems like you might need to file an issue with App Center instead of here. To update their image?

Here is their support link: https://docs.microsoft.com/appcenter/help

I don't think there is anything we can offer except recommend updating Xamarin.Android to latest? Thanks!

**Closed by jonathanpeppers** 2022-08-09 21:32 UTC
Labels: Area: App+Library Build, need-attention
