### ISSUE TITLE
error ADB1000: Xamarin.AndroidTools.AndroidDeploymentException: FailedToSynchronizeFastDevAssemblies ---> Mono.AndroidTools.AdbException: secure_mkdirs failed: Permission denied

### ISSUE THREAD

**Issue by pmahend1** [xamarin/xamarin-android#5147] opened 2020-09-23 20:11 UTC
### Steps to Reproduce

1. Download Visual Studio 2019 Preview 8.3 or Visual Studio for Mac Preview 8.3
2. Create Xamarin forms solution
3. Target android project to API level 30 (Android 11) in both manifest and compilation levels
4. Turn on Shared Debug runtime and Fast Debug options
5. Build and try to deploy android project to Android 11 emulator

Could be related to #4996 

### Expected Behavior
Fast debug should work with new Xamarin android 11 changes

### Actual Behavior

Not deploying app.

### Log File

adb log and msbuild.log shared over email to  @dellis1972

**Comment by brendanzagaeski** [comment] 2020-09-23 20:27
I just thought of one idea for a first quick check that might be interesting to test if you get a chance. If you replace the _Mono.Android.DebugRuntime-*.apk_ in the Visual Studio Preview installation with the versions from https://github.com/xamarin/xamarin-android/issues/4996#issuecomment-679957732 similar to how you tested [before](https://github.com/xamarin/xamarin-android/issues/4996#issuecomment-682189468), does that chance resolve the problem again?

The default installation location for the _Mono.Android.DebugRuntime-*.apk_ files to replace in the Preview version is:

_C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android_

Thanks again!

**Comment by pmahend1** [comment] 2020-09-23 22:47
@brendanzagaeski Oh,Yeah. I was thinking the same, then thought they must be same. Will check and update here.

**Comment by pmahend1** [comment] 2020-09-24 01:52
@brendanzagaeski I did the same test by replacing APKs of Preview version. Same error is thrown while deploying. 
What is the PR #4690 about ? @dellis1972 mentioned about it in the last issue. I see it being open.

**Comment by dellis1972** [comment] 2020-09-24 07:47
@pmahend1 I don't think we can work around this. We are using the new api's on API 29+ devices, and if they are still throwing the error then running without the shared runtime will probably be the only option. 

PR #4690 is the new Fast deployment system. It does not have a shared runtime and does not use the external storage. So we won't hit these permissions problems. Its still a work in progress though.

**Comment by brendanzagaeski** [comment] 2020-09-25 15:45
Because it turned out that the candidate fix for #4996 did not consistently resolve the issue for the original reporter of that issue (@pmahend1, also the reporter of this issue), the issue has now been reopened. I will accordingly close this item as a duplicate to help consolidate further updates about the problem.

Thanks again for reporting these issues and helping check the candidate fix, @pmahend1!

**Comment by brendanzagaeski** [comment] 2020-09-25 15:45
Duplicate of #4996

**Closed by brendanzagaeski** 2020-09-25 15:45 UTC
Labels: Area: App+Library Build
