### ISSUE TITLE
16.3.0 Preview 2.0 Apk size increased from 28,454KB to 32,964KB. Compared to Preview 1.0

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#3499] opened 2019-08-14 11:16 UTC
### Steps to Reproduce

1. 
2. 
3.

**Comment by gmck** [comment] 2019-08-14 11:26
This is the first time I've reported anything here and I'm not sure exactly what is required. The app is compiled with BundleAssemblies true. Looking at the apk and the previous version apk, just about all the increases are in the lib folder. Is this a known issue in Xamarin.Android 10.0.0.4. The app is running fine.
Could someone please advise what is required?

**Comment by brendanzagaeski** [comment] 2019-08-14 18:24
Thanks for trying the preview version, and thanks for the report! This is indeed a known issue in Xamarin.Android 10.0.0.4. It can be found in the known issues section in the Xamarin.Android SDK release notes on [docs.microsoft.com](https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.0) and [GitHub](https://github.com/xamarin/xamarin-android/releases/tag/v10.0.0.4#known-issues-in-xamarinandroid-10004).

Apologies that it's not easier to find these items from the Visual Studio release notes. I have some ideas for things to try to make the list of known issues for the Xamarin.Android SDK easier to find and browse in the future.

**Comment by brendanzagaeski** [comment] 2019-08-14 18:25
Duplicate of https://github.com/xamarin/xamarin-android/issues/3454

**Closed by brendanzagaeski** 2019-08-14 18:25 UTC
