### ISSUE TITLE
After updating to VS 17.1, deploying often fails

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-android#6815] opened 2022-03-06 15:54 UTC
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 v17.1.0

### Description

When initially building and deploying a Xamarin.Android app, everything works just fine.
Also editing C# code and rebuilding + deploying the app works fine.
The problems start when I make changes to the .xml files (layouts, menus, styles etc). When editing those and then trying to deploy again, the app builds successfully, but it fails to deploy (not always, but in >50% of the cases). It doesn't seem to make a difference if I use a physical device or emulator. Also the API level of the device that I try to deploy to, doesn't seem to make a difference.
Sometimes, deploying works after waiting a few seconds and then trying to build + deploy again. Sometimes I need to have to clear the obj+bin folders and rebuild the app from scratch. Of course, this has been slowing me down a lot

### Steps to Reproduce

- Build + deploy app
- Make change to .xml file
- Try to deploy app again (F5)

### Relevant log output

```shell
1>  ...\obj\Debug\120\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-31\optional\androidx.window.extensions.jar
1>  ...\obj\Debug\120\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-31\optional\androidx.window.sidecar.jar
1>
1>    3 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:00:03.37
2>Starting deployment to Pixel_3a_API_30 ...
2>Deploying to Pixel_3a_API_30 ...
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by E75** [comment] 2022-03-07 07:51
I have also the same problem. 
For now there is no other option than to use an older version, because this is no longer really workable.

**Comment by davidtolleback** [comment] 2022-03-07 09:25
Im facing the same issue, also 17.1.

**Comment by dellis1972** [comment] 2022-03-07 10:28
This is a duplicate of https://github.com/xamarin/xamarin-android/issues/6652.
The IDE team have been informed and are investigating the issue.

**Closed by dellis1972** 2022-03-07 10:28 UTC
Labels: Area: App+Library Build
