### ISSUE TITLE
Add Property attribute that matches "property" element in "service" element in AndroidManifest.xml

### ISSUE THREAD

**Issue by entdark** [xamarin/xamarin-android#8770] opened 2024-02-27 19:57 UTC
### Android application type

Classic Xamarin.Android (MonoAndroid13.0, etc.), .NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VS for Mac 17.6.9

### Description

In Android 14 SDK (API 34) they added `property` element for `service` element in case of Service special usage in AndroidManifest.xml: https://developer.android.com/about/versions/14/changes/fgs-types-required#special-use
I'd like to have `PropertyAttribute` with `Name` and `Value` properties for `Service` + `ServiceAttribute` similar `IntentFilterAtribute` so I can define it in the code instead of AndroidManifest.xml

### Steps to Reproduce

-

### Did you find any workaround?

Instead of defining `ServiceAttrbute` with `PropertyAttribute` in the code it's possible to define Service with `property` element in AndroidManifest.xml directly.

**Comment by jpobst** [comment] 2024-02-27 20:00
This is one of the things I am looking at tackling shortly, which should help resolve this:
https://github.com/xamarin/xamarin-android/issues/8272

**Comment by jpobst** [comment] 2024-02-29 20:20
Duplicate of https://github.com/xamarin/xamarin-android/issues/8729.

Closing in favor of existing issue.

**Closed by jpobst** 2024-02-29 20:20 UTC
Labels: enhancement, Area: Mono.Android
