### ISSUE TITLE
VSMac 17.0: Error "Index was outside the bounds of the array" will occur when creating an Android project

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6794] opened 2022-02-24 20:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VSMac-170:-Error-Index-was-outside-the/1665776)._

---
[severity:It's more difficult to complete my work]
VS Mac 17.0

1. Launch VSfM
2. Create an Android project
3. observe error:

Error "Index was outside the bounds of the array" will occur when creating an Android project
Error: /Users/grace/Projects/AndApp56/AndApp56/Resources/values/ic_launcher_background.xml(2,2): Error: Index was outside the bounds of the array.
  at Xamarin.Android.Tasks.GenerateLibraryResources.RunTaskAsync () [0x0007f] in <27202c2eac7644b5b7b219a7e58a179a>:0

---
#### Feedback Bot on 2/15/2022, 09:34 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 2/15/2022, 02:52 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jonathanpeppers** [comment] 2022-03-23 02:32
I think this is duplicate of: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1419296

Which (might?) be caused by: https://github.com/xamarin/vsmac-xamarin-extensions/pull/1074

It is reported fixed in VS Mac 17.0 Preview (17.0.0.7922) or newer.

**Closed by jonathanpeppers** 2022-03-23 02:32 UTC
Labels: need-info, Area: App+Library Build
