### ISSUE TITLE
Debugging hangs on "Starting Android application"

### ISSUE THREAD

**Issue by kjeremy** [xamarin/xamarin-android#1547] opened 2018-04-12 14:01 UTC
### Steps to Reproduce

1. Select run from VS2017

### Expected Behavior
App should build and then run, immediately going into the debugger.

### Actual Behavior
Output says "Starting Android application" and then the Run button becomes enabled again.  Some amount of time (30 seconds or so) goes by and all of a sudden the Run button becomes disabled again and the debugger starts.

### Version Information

Microsoft Visual Studio Professional 2017 
Version 15.6.6
VisualStudio.15.Release/15.6.6+27428.2037
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA214
Microsoft Visual C++ 2017

.NET Portability Analyzer   1.1.10808.0
Evaluates portability of assemblies across .NET platforms.

Application Insights Tools for Visual Studio Package   8.11.10402.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2017.3.5    Build 111.0.20180323.160610
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.753 (f0f46392f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.96 (a702a9ceb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.9.1.24 (f62de47)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File

[xamarin-logs.zip](https://github.com/xamarin/xamarin-android/files/1903448/xamarin-logs.zip)

**Comment by kjeremy** [comment] 2018-04-13 15:42
Xamarin Diagnostics: 
[xamarin-diagnostics.txt](https://github.com/xamarin/xamarin-android/files/1908017/xamarin-diagnostics.txt)

Build Log: 
[xamarin-build.txt](https://github.com/xamarin/xamarin-android/files/1908019/xamarin-build.txt)

**Comment by mhallmark** [comment] 2018-04-16 23:58
@kjeremy Do you by chance have a `google-services.json` file in your project (for FCM)?

I do, and my visual studio hangs exactly as you describe, but it never releases. It hangs permanently.

I removed the `google-services.json` file and it builds normal. I'm not sure what the issue is with that file.

**Comment by kjeremy** [comment] 2018-04-17 00:02
Hm. I do have one.  I'll check tomorrow and see if that helps.

**Comment by mhallmark** [comment] 2018-04-17 17:18
[This here](https://bugzilla.xamarin.com/show_bug.cgi?id=52906) may be what we're seeing.

**Comment by kjeremy** [comment] 2018-04-18 20:44
@mhallmark it's definitely not the same issue as it still occurs with Xamarin.Build.Download 0.4.10.

I can also reproduce this on VS2017 15.7.0 Preview 4.0

**Comment by tlemmons** [comment] 2018-04-28 14:54
I am seeing this also.  I do not have google-services.json in my app.  I am running VS 2017 ver 15.6.6, Xamarin.Build.Download 0.4.10.

**Comment by jpc0001** [comment] 2018-05-01 16:01
I am seeing this as well

**Comment by kjeremy** [comment] 2018-05-08 15:33
So I think this is a debugger issue.  In VS 15.7.0 I now see `Extension 'Mono Debugging for Visual Studio 4.10.5' likely caused 195 seconds of unresponsiveness.`.  Disabling the Shared Runtime has no effect.

**Comment by dlpopescumtk** [comment] 2018-05-09 16:19
Still happening with Xamarin.Build 0.4.11, same message as above. 

Microsoft Visual Studio Professional 2017 
Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40501.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

C# Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

Multilingual App Toolkit   4.0
Multilingual App Toolkit helps you localize your Windows Store app by providing file management, pseudo and machine translation, translation editor, and build integration. http://aka.ms/matinstall

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 16ecf5a30ad868d183c58e4a71a71c23d4ed3ba9.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Unity   3.7.0.1
Visual Studio Tools for Unity

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput   2.5.1
Color output for build and debug windows - http://mike-ward.net/vscoloroutput

WiX Toolset Visual Studio Extension   0.9.21.62588
WiX Toolset Visual Studio Extension version 0.9.21.62588
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamaridea.VisualStudioPlugin   1.0
VS + Xamarin + IDEA = Love

Xamarin   4.10.0.442 (396b18cef)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.264 (fc37cd02e)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.177 (7e782c1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by nwestfall** [comment] 2018-05-10 13:09
This is happening to a co-worker and I as well in VS 2017 15.7 and 15.8 Preview.  It will eventually work and attach, but it's 15 minutes or more before it will finally work (not just once either, each time we go to debug).

We both have switched to VS for mac and the same project works fine when we go to debug there.  It's just VS on windows.

**Comment by dlpopescumtk** [comment] 2018-05-10 13:30
@nwestfall : I know. For now, I've disabled the Mono Debugging Visual Studio extension on the Windows machine, and, so far, so good. I can still debug my Android project.

**Comment by jvinis** [comment] 2018-05-10 15:56
Big mistake to update Visual studio during Build 2018 conference!!!
Disabled the Mono Debugging has no effect, lost time for each run 30 sec minimum.
I hope the Update button on visual studio will bink soon ;)

**Comment by kjeremy** [comment] 2018-05-10 20:50
FYI I filed this for it a while ago: https://developercommunity.visualstudio.com/content/problem/232244/xamarin-takes-forever-to-deploy-to-android-device.html

**Comment by dlpopescumtk** [comment] 2018-05-10 21:04
Yes, I saw.
I've added a solution, but I hardly think this is the way to go.

**Comment by cjlotz** [comment] 2018-05-11 06:48
Getting the same issue and warning about the Mono Debugger causing 199 seconds of delay.

**Comment by dlpopescumtk** [comment] 2018-05-11 06:53
@cjlotz: try disabling the extension, see if it works. It will still hang for a couple of sec, at least on my machine it does, but I'm not sure what this extension does in the first place and whether it should be disabled. I'm also curious about why it happens on some windows machines only.

**Comment by TB-SWG** [comment] 2018-05-11 11:28
I am seeing this too on Xamarin.Forms project. I tried rolling back to VS 15.5.7 - no effect.
What solves the problem for me is re-cloning my GIT repo. This allows the debugger to start on iOS and Driod normally. Then after a while the problem starts again. I haven't pinned down what causes the problem but most likely a file on disk somewhere. Would be interested if re-cloning GIT  repo helps anyone else.

**Comment by ornolisvt** [comment] 2018-05-15 16:26
In my case, I disabled the Mono Debugging for Visual Studio extension. When trying to debug the app, an error occurred and in the logs it showed that there was a null reference in Xamarin Inspector. I disabled this option and then activate Mono Debugging. That solved the problem, it no longer hangs when you start the debug session

**Comment by JPLarouche** [comment] 2018-06-07 22:31
In my case, I believe the issue was that the Target API for Android was set to 7.1 while my testing device was on Android 8.0

I simply set the Target API for Android to 8.1 (current release Android version), closed Visual Studio, deleted the bin and obj folders from the Android project, waited maybe 2-3min (time for any other Visual Process to end) and restarted Visual Studio. Works like a charm since then ! 

Hope this helps.

**Comment by KevM** [comment] 2018-08-15 17:55
> In my case, I disabled the Mono Debugging for Visual Studio extension. When trying to debug the app, an error occurred and in the logs it showed that there was a null reference in Xamarin Inspector. I disabled this option and then activate Mono Debugging. That solved the problem, it no longer hangs when you start the debug session

I keep seeing this solution for this flavor of problem but with VS 15.8 I do not see how to disable `Mono Debugging for Visual Studio` as it seems to now be a system component.

**Comment by AndrueCope** [comment] 2018-10-04 12:55
Still plaguing me. Makes using vs for mobile apps very disheartening.

**Comment by Idsert** [comment] 2018-10-25 13:16
Having almost the same issue here. The moment I'm expecting the debugger to start the Run button gets enabled again and noting happens (not even after an hour or more). The app seems to be build and deployed just fine as I can find it and start it on the emulator manually.

The only thing the VS output gives me is:

`Start debugging Android application ...
Starting Android application ...`

What I tried so far is:

 - Start new project (works fine)
 - Tried reverting the project to point where I was sure it worked before (is does not work anymore)
 - Created a new android 9 simulator (Same problem)
 - Updated the emulator (Did not help)
 - Updated VS a couple of times (Now on 15.8.8 and still not working)

**Comment by barisonur** [comment] 2018-10-29 11:46
Repairing Visual Studio from Visual Studio Installer fixed this issue for me.

**Comment by Idsert** [comment] 2018-10-31 12:31
I repaired it but still the same problem.

**Comment by rahuldotline** [comment] 2020-07-05 12:37
VS2019 Xamarin forms not responding on opening android project.

![image](https://user-images.githubusercontent.com/50820332/86532811-4e175c80-beea-11ea-87f5-7a711494d611.png)

**Comment by gsgou** [comment] 2021-03-02 14:01
I am seeing the same recently only with a Xiaomi Pocophone F1 but not with a Google Pixel 3a.
After factory resetting the phone worked for a while and broke again. Maybe relates to some Android tool.
I ll try roll back android tools in older versions.

**Comment by jpobst** [comment] 2022-03-01 20:06
This seems like it hasn't been seen in several years so I'm going to close it.  I suspect if this was still happening we would be hearing about it.

**Closed by jpobst** 2022-03-01 20:06 UTC
