### ISSUE TITLE
Managed Resource Parser is not aware of some Resource types, and fails to provide intellisense for them.

### ISSUE THREAD

**Issue by fullmetaltac** [xamarin/xamarin-android#1262] opened 2018-02-01 10:09 UTC
### Steps to Reproduce

1. Rebuild project.
2. Right click on project -> Unload project. 
3.  Right click on project -> Reload project.
4. Navigate to class that contain Resource.Plurals or Resource.String etc.

![image](https://user-images.githubusercontent.com/5435980/35672745-23b7c40e-0748-11e8-9a70-c508c90b13e4.png)

### Expected Behavior
Resource object should be available via Intellisense.

### Actual Behavior
Resource object is not availabe via Intellisense.

### Version Information
15.6.0 Preview 3.0
[VS_info.txt](https://github.com/xamarin/xamarin-android/files/1685028/VS_info.txt)

### Comment
During sample porting all resources where available except Plurals. After that I decided to Rebuild -> Unload -> Reload project.
I think it's related to Design Time builds. Strange that another resources like String and Id where available. They all lying on the same level.
![image](https://user-images.githubusercontent.com/5435980/35672917-a49b313c-0748-11e8-92a9-5d99ef0027ef.png)

**Comment by dellis1972** [comment] 2018-02-05 10:43
Our initial version of the ManagedResourceParser [1] which is used for design time builds does not contain any code to handle `Plurals` resources. So that is one problem. 

The other one, are you able to get us the design time build logs via [2] ?

[1] https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs#L32
[2] https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#visual-studio-2017-version-153-or-earlier

**Comment by fullmetaltac** [comment] 2018-02-08 15:09
@dellis1972 Hi. I created build logs.

**Comment by pjcollins** [comment] 2018-02-16 17:32
Considering that the first step here is:
> 1. Rebuild project.

I'm thinking that this will be resolved by the fix mentioned in #1286

**Comment by pjcollins** [comment] 2018-02-16 19:06
While part of the issue discussed here appears to be a duplicate of #1268, there is still a consideration for Plurals resources as Dean mentions in his previous comment. I will leave this issue open to track that discrepancy. We should also do a thorough review of everything mentioned in the Android resource documentation below to make sure that this new parser handles all expected types and any relevant children (e.g. Plurals):

https://developer.android.com/guide/topics/resources/available-resources.html

**Comment by pjcollins** [comment] 2018-02-16 19:34
At a first glance it looks like we may need to add `Animator`, `Font`, `Menu`, and `Plurals` to the managed resource parser.

**Comment by dellis1972** [comment] 2018-02-16 21:33
@pjcollins any chance you can post an example layout(s) which contain the missing items? it would help me update the unit tests.

**Comment by pjcollins** [comment] 2018-02-16 21:46
Animator:
https://github.com/xamarin/monodroid-samples/blob/master/android5.0/Topeka/Topeka/Resources/animator/slide_in_bottom.xml

Font:
I used a random .ttf file.

Menu:
https://github.com/xamarin/monodroid-samples/blob/master/AndroidBeamDemo/AndroidBeamDemo/Resources/menu/Options.xml

Plurals:
https://github.com/xamarin/monodroid-samples/blob/master/android-o/AndroidPlayLocation/LocUpdPendIntent/LocUpdPendIntent/Resources/values/strings.xml#L16-L20

There may be others I've missed, my review of the resource documentation above was somewhat brief.

**Closed** 2018-03-08 20:21 UTC

**Comment by pjcollins** [comment] 2018-04-03 18:12
Intellisense for the examples listed above for Animator, Font, Menu, and Plurals is working as expected for me with the new managed resource parser system enabled in d15-7 (XA 8.3.0.11).
