### ISSUE TITLE
dlopen fails on FireOS 7.3 (fire hd 10 9th gen)

### ISSUE THREAD

**Issue by shimfish** [xamarin/xamarin-android#4008] opened 2019-12-09 13:31 UTC
### Steps to Reproduce

1.  Create Android Xamarin project with correct libs directory
2. Use dlopen(libnname,RTLD_LAZY) to load lib

### Expected Behavior

Linked library loads correctly - same project appears to work on many, many android devices and versions.

### Actual Behavior

Fails with console message:

`[linker] library "/data/app/com.app-ZKMGKBJll0P0FdhrTdxKyQ==/lib/arm/libopenal32.so" ("/data/app/com.app-ZKMGKBJll0P0FdhrTdxKyQ==/lib/arm/libopenal32.so") needed or dlopened by "(unknown)" is not accessible for the namespace: [name="(anonymous)", ld_library_paths="", default_library_paths="/system/lib", permitted_paths=""]`

It appears using [DLLImport] works fine still. However, my project uses monogame which relies on dlopen.

### Version Information

Visual Studio Community 2019 for Mac
Version 8.3.10 (build 2)
Installation UUID: 6590125c-d565-4d7a-847a-ac3931c963b7
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

Mono Framework MDK
Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

NuGet
Version: 5.3.0.6192

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.1.1
	2.0.5

Xamarin.Profiler
Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 11.2.1 (15526.1)
Build 11B500

Xamarin Designer
Version: 16.3.0.256
Hash: 8a223bfd7
Branch: remotes/origin/d16-3
Build date: 2019-11-01 21:02:02 UTC

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 13.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:08-0400

Xamarin.Android
Version: 10.0.6.2 (Visual Studio Community)
Commit: xamarin-android/d16-3/c407838
Android SDK: /Users/shim/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 29.0.1

Build Information: 
Mono: mono/mono/2019-06@476d72b9e32
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Microsoft Mobile OpenJDK
Java SDK: /Users/shim/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:22 UTC

Android Device Manager
Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:42 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 803100002
Git revision: add3a4998a5cb5b081e0404e1fe13acfecb7801d
Build date: 2019-11-20 13:35:15+00
Build branch: release-8.3
Xamarin extensions: 79c69708816813b498283eeda7bcb4d464433a04

Operating System
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Sat Oct 12 00:02:19 PDT 2019
    root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64

**Comment by jonathanpeppers** [comment] 2020-01-07 16:34
@shimfish could you attach the full [adb logcat output](https://docs.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log)?

If you run `adb shell setprop debug.mono.log debug,dll` before capturing the log, it should print more info.

@grendello any other ideas on how they could get more info on this?

**Comment by grendello** [comment] 2020-01-07 16:46
@jonathanpeppers no, not really. The log is our only chance here. However, I suspect the error has to do with this [change in Android 7](https://developer.android.com/about/versions/nougat/android-7.0-changes#ndk). `/lib/arm/libopenal32.so` is not part of the "public" libraries, so both linking against it and `dlopen`-ing it would fail this way on Android 7+ (and FireOS 7 is based on Android 9). This is just a guess, but considering the error message I think it might be what's happening.

@shimfish if my guess above is correct, you might work around the issue by including OpenAL with your game - Android allows you to ship any DSOs your app needs and dlopen them from your app's lib directories.

**Comment by shimfish** [comment] 2020-01-07 20:02
Thanks both of you for getting back to me. I'll try to get the extended logs tomorrow.

The openAL libs *are* bundled with the APK. IIRC, when I ran dlopen from the debugger, it gave a slightly different error if I tried it with a non-existent file.

**Comment by grendello** [comment] 2020-01-08 15:58
@shimfish yes, they are bundled, but I wonder about their dependencies (if they reference any "private" libraries they will [fail to load](https://developer.android.com/about/versions/nougat/android-7.0-changes#ndk-errors))? I should have been more clear in my comment, sorry about that :) If you can, please enable detailed logging before running the app by adding an Android Environment File to your project:

```xml
<ItemGroup>
    <AndroidEnvironment Include="Environment.txt" />
  </ItemGroup>
```

Put the following lines in `Environment.txt`:

```
debug.mono.debug=1
debug.mono.log=default,assembly
MONO_LOG_LEVEL=debug
MONO_LOG_MASK=asm,dll
MONO_XDEBUG=1
```

This should give us the information we need, thanks!

**Comment by shimfish** [comment] 2020-01-08 17:09
[logcat.txt](https://github.com/xamarin/xamarin-android/files/4036418/logcat.txt)

**Comment by shimfish** [comment] 2020-01-08 17:23
[logcat.txt](https://github.com/xamarin/xamarin-android/files/4036481/logcat.txt)

**Comment by grendello** [comment] 2020-01-08 17:24
@shimfish can you extract the library from the apk as well as from the device, zip them up and attach here?

**Comment by shimfish** [comment] 2020-01-08 17:26
Forgive my ignorance but how do you extract the library from the device?

**Comment by shimfish** [comment] 2020-01-08 17:34
[lib.zip](https://github.com/xamarin/xamarin-android/files/4036516/lib.zip)

**Comment by grendello** [comment] 2020-01-08 17:40
@shimfish to retrieve a file from device, type in the terminal:

```
adb pull /data/app/com.app-ZKMGKBJll0P0FdhrTdxKyQ==/lib/arm/libopenal32.so
```

**Comment by shimfish** [comment] 2020-01-08 17:57
From device...
[libopenal32.so.zip](https://github.com/xamarin/xamarin-android/files/4036593/libopenal32.so.zip)

**Comment by grendello** [comment] 2020-01-08 18:15
@shimfish so, I verified that the library you attached doesn't reference any "private" libraries, so this is not the problem. However, it might still be related to symbols referenced by the library. To test this, can you please run your app in **debug** mode after issuing the following command from the terminal (assuming your app's package name is `com.playhome.lite`, if it isn't please use the correct one):

```
adb shell setprop debug.ld.com.playhome.lite dlerror,dlopen,dlsym
```

Please attach the resulting logcat output, thanks!

**Comment by shimfish** [comment] 2020-01-08 18:34
[extended-logcat.txt](https://github.com/xamarin/xamarin-android/files/4036727/extended-logcat.txt)

**Comment by grendello** [comment] 2020-01-08 18:55
@shimfish apologies, I made a typo in the command to set the property, can you try again after issuing this command:

```
adb shell setprop debug.ld.app.com.playhome.lite dlerror,dlopen,dlsym
```

Logcat should then contain entries similar to:

```
01-08 19:54:04.461  5985  5985 D linker  : find_libraries(ns=classloader-namespace): task=/data/user/0/org.grendel.httpconnectiontest/files/.__override__/links/libmonosgen-2.0.so, is_dt_needed=0
01-08 19:54:04.461  5985  5985 D linker  : load_library(ns=classloader-namespace, task=/data/user/0/org.grendel.httpconnectiontest/files/.__override__/links/libmonosgen-2.0.so, flags=0x3, realpath=/data/app/Mono.Android.DebugRuntime-sDgqXwDZjPSPqYyep92m-Q==/lib/x86/libmonosgen-32bit-2.0.so)
01-08 19:54:04.461  5985  5985 D linker  : load_library(ns=classloader-namespace, task=/data/user/0/org.grendel.httpconnectiontest/files/.__override__/links/libmonosgen-2.0.so): Adding DT_NEEDED task: libz.so
01-08 19:54:04.461  5985  5985 D linker  : load_library(ns=classloader-namespace, task=/data/user/0/org.grendel.httpconnectiontest/files/.__override__/links/libmonosgen-2.0.so): Adding DT_NEEDED task: libdl.so
01-08 19:54:04.461  5985  5985 D linker  : load_library(ns=classloader-namespace, task=/data/user/0/org.grendel.httpconnectiontest/files/.__override__/links/libmonosgen-2.0.so): Adding DT_NEEDED task: libc.so
01-08 19:54:04.461  5985  5985 D linker  : load_library(ns=classloader-namespace, task=/data/user/0/org.grendel.httpconnectiontest/files/.__override__/links/libmonosgen-2.0.so): Adding DT_NEEDED task: libm.so
01-08 19:54:04.461  5985  5985 D linker  : load_library(ns=classloader-namespace, task=/data/user/0/org.grendel.httpconnectiontest/files/.__override__/links/libmonosgen-2.0.so): Adding DT_NEEDED task: liblog.so
```

**Comment by shimfish** [comment] 2020-01-08 19:15
Tried the new command but don't see any entries like that.

**Comment by shimfish** [comment] 2020-01-08 19:23
[extended-logcat.txt](https://github.com/xamarin/xamarin-android/files/4036889/extended-logcat.txt)

**Comment by grendello** [comment] 2020-01-08 19:44
@shimfish the extended information is there:

```
01-08 21:13:53.609  6061  6061 D linker  : dlopen(name="libopenal32.so", flags=0x1, extinfo=(null), caller="(null)", caller_ns=(anonymous)@0xf07cf0d0) ...
01-08 21:13:53.609  6061  6061 D linker  : ... dlopen failed: library "libopenal32.so" not found
01-08 21:13:53.609  6061  6061 D linker  : dlerror set to "dlopen failed: library "libopenal32.so" not found"
01-08 21:13:53.614  6061  6061 D linker  : dlopen(name="/data/app/com.playhome.lite-wqKcdvQ7SN7H1JbfakDM4A==/lib/arm/libopenal32.so", flags=0x1, extinfo=(null), caller="(null)", caller_ns=(anonymous)@0xf07cf0d0) ...
01-08 21:13:53.614  6061  6061 E linker  : library "/data/app/com.playhome.lite-wqKcdvQ7SN7H1JbfakDM4A==/lib/arm/libopenal32.so" ("/data/app/com.playhome.lite-wqKcdvQ7SN7H1JbfakDM4A==/lib/arm/libopenal32.so") needed or dlopened by "(unknown)" is not accessible for the namespace: [name="(anonymous)", ld_library_path
s="", default_library_paths="/system/lib", permitted_paths=""]
01-08 21:13:53.614  6061  6061 D linker  : ... dlopen failed: library "/data/app/com.playhome.lite-wqKcdvQ7SN7H1JbfakDM4A==/lib/arm/libopenal32.so" needed or dlopened by "(unknown)" is not accessible for the namespace "(anonymous)"
01-08 21:13:53.614  6061  6061 D linker  : dlerror set to "dlopen failed: library "/data/app/com.playhome.lite-wqKcdvQ7SN7H1JbfakDM4A==/lib/arm/libopenal32.so" needed or dlopened by "(unknown)" is not accessible for the namespace "(anonymous)""
01-08 21:13:53.630  6061  6061 I mono-stdout: FuncLoader.LoadLibrary libopenal32.so Not Found!
01-08 21:13:53.633  6061  6061 D linker  : dlopen(name="/data/user/0/com.playhome.lite/lib/libopenal32.so", flags=0x1, extinfo=(null), caller="(null)", caller_ns=(anonymous)@0xf07cf0d0) ...
01-08 21:13:53.634  6061  6061 E linker  : library "/data/user/0/com.playhome.lite/lib/libopenal32.so" ("/data/app/com.playhome.lite-wqKcdvQ7SN7H1JbfakDM4A==/lib/arm/libopenal32.so") needed or dlopened by "(unknown)" is not accessible for the namespace: [name="(anonymous)", ld_library_paths="", default_library_path
s="/system/lib", permitted_paths=""]
01-08 21:13:53.634  6061  6061 D linker  : ... dlopen failed: library "/data/user/0/com.playhome.lite/lib/libopenal32.so" needed or dlopened by "(unknown)" is not accessible for the namespace "(anonymous)"
01-08 21:13:53.634  6061  6061 D linker  : dlerror set to "dlopen failed: library "/data/user/0/com.playhome.lite/lib/libopenal32.so" needed or dlopened by "(unknown)" is not accessible for the namespace "(anonymous)""
01-08 21:13:53.635  6061  6061 D linker  : dlopen(name="/data/user/0/com.playhome.lite/lib/libopenal32.so", flags=0x1, extinfo=(null), caller="(null)", caller_ns=(anonymous)@0xf07cf0d0) ...
01-08 21:13:53.635  6061  6061 E linker  : library "/data/user/0/com.playhome.lite/lib/libopenal32.so" ("/data/app/com.playhome.lite-wqKcdvQ7SN7H1JbfakDM4A==/lib/arm/libopenal32.so") needed or dlopened by "(unknown)" is not accessible for the namespace: [name="(anonymous)", ld_library_paths="", default_library_path
s="/system/lib", permitted_paths=""]
01-08 21:13:53.635  6061  6061 D linker  : ... dlopen failed: library "/data/user/0/com.playhome.lite/lib/libopenal32.so" needed or dlopened by "(unknown)" is not accessible for the namespace "(anonymous)"
01-08 21:13:53.635  6061  6061 D linker  : dlerror set to "dlopen failed: library "/data/user/0/com.playhome.lite/lib/libopenal32.so" needed or dlopened by "(unknown)" is not accessible for the namespace "(anonymous)""
```

And all the symbols appear to be available. This is definitely SELinux enforcing that prevents the library from being loaded, however there's one suspictious thing: note that the `caller` field in the debug messages from the native linker is `(null)` while the entries that succeed have a value in that field:

```
01-08 21:13:53.607  6061  6061 D Mono    : Probing 'dlopen'.
01-08 21:13:53.607  6061  6061 D linker  : dlsym(handle=0x178007ef("/system/lib/libdl.so"), sym_name="dlopen", sym_ver="(null)", caller="/data/app/Mono.Android.DebugRuntime-jv8TyK_4R28fsNDv3-oPXQ==/lib/arm/libmonosgen-32bit-2.0.so", caller_ns=classloader-namespace@0xf07cf150) ...
01-08 21:13:53.607  6061  6061 D linker  : ... dlsym successful: sym_name="dlopen", sym_ver="(null)", found in="libdl.so", address=0xee115d15
01-08 21:13:53.607  6061  6061 D Mono    : Found as 'dlopen'.
```

Also note that the attempts to load OpenAL are **not** preceeded by the Mono's `Probing '...'` message, which makes me think that this call isn't caused by `[DLLImport]` but rather by some other code (MonoGame runtime?). @dellis1972, mind taking a look at this issue since you know MonoGame in and out? :)

@shimfish This is probably going to fail, but can you try disabling SELinux on your device? Use these commands from the terminal:

```
adb root
adb shell setenforce 0
adb shell stop
adb shell start
```

If they succeed, try starting the app again and let's see if it works.

**Comment by shimfish** [comment] 2020-01-08 19:47
The relevant monogame code is here, I believe
```

    internal class FuncLoader
    {
        [DllImport("dl")]
        public static extern IntPtr dlopen(string path, int flags);

        [DllImport("dl")]
        public static extern IntPtr dlsym(IntPtr handle, string symbol);

        private const int RTLD_LAZY = 0x0001;

        public static IntPtr LoadLibrary(string libname)
        {
            // Let the OS search for the library by default.
            IntPtr lib = dlopen(libname, RTLD_LAZY);
            if (lib != IntPtr.Zero)
            {
                Console.WriteLine("FuncLoader.LoadLibrary {0}", libname);
                return lib;
            }

            // Some Android devices won't search the native library path
            // for the library, so we have to do it manually here.
            var nlibpath = Application.Context.ApplicationInfo.NativeLibraryDir;
            var libpath = Path.Combine(nlibpath, libname);
            lib = dlopen(libpath, RTLD_LAZY);
            if (lib != IntPtr.Zero)
            {	
                Console.WriteLine("FuncLoader.LoadLibrary {0}", libpath);
                return lib;
            }

            Console.WriteLine("FuncLoader.LoadLibrary {0} Not Found!", libname);
            return IntPtr.Zero;
        }

```

**Comment by shimfish** [comment] 2020-01-08 19:51
```
shim$ adb root
adbd cannot run as root in production builds
```

**Comment by dellis1972** [comment] 2020-01-10 11:49
This thread https://stackoverflow.com/questions/46494487/android-native-library-runtime-error-when-trying-to-load-jni-native-library suggests there are operating restrictions in place. 

I am also wondering if using the `android:extractNativeLibs="false"` feature might help? See https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs

**Comment by dellis1972** [comment] 2020-01-10 14:44
also can you try adding 

```
[CLSCompliant (false)]
                [DllImport ("libopenal32.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "alEnable")]
                public static extern void Enable (int cap);
```

to you MainActivity.cs and calling `Enable(0);` at the start. That should force the DllImport to load the native library. Then dlopen should work as its already loaded. Not a great fix, but it would hack around the problem. 

I don't have a FireOS device so its difficult to try to figure this out.

**Comment by shimfish** [comment] 2020-01-12 08:48
Adding DllImport doesn't work. It successfully loads the library but It seems that Monogame only works if the lib is loaded using dlopen as it uses that to get the pointer to the library.

**Comment by Owlzy** [comment] 2020-02-06 16:16
> Adding DllImport doesn't work. It successfully loads the library but It seems that Monogame only works if the lib is loaded using dlopen as it uses that to get the pointer to the library.

Did you find a resolution for this?  We are currently facing the same issue with a clients game.  I've opened an issue on the MonoGame github as well.

https://github.com/MonoGame/MonoGame/issues/7011

**Comment by dellis1972** [comment] 2020-03-09 13:58
I think the only way for us to look at this is to get a device. Can someone post exactly which device has the problem. i.e which one of these? https://www.amazon.com/Fire-HD-10/dp/B07K1RZWMC

**Comment by Owlzy** [comment] 2020-03-09 14:47
Okay this is very strange.  We have the devices here (model number : m2v3r5 is the one we primarily had been using to test this issue) , but before giving you the model number I decided I'd try the issue just to be certain I was giving you the correct device, but for me at least, the issue has now magically fixed itself.. 

The only thing I can imagine here is that MonoGame devs tend to use Visual Studio 2017 as the MG templates work with this version of VS.  So I was on 2017.  But recently I upgraded to 2019, which I'm guessing also upgraded my Xamarin Android.  That's the only difference I can think off.  

Is someone who is still facing this issue able to confirm that the issue is resolved after installing VS 2019?

**Comment by shimfish** [comment] 2020-03-16 15:33
Just tried it also and it appears to work.

I see there was an update to FireOS on 17 Feb - 7.3.1.2 - so maybe that fixed it????

**Comment by dellis1972** [comment] 2020-03-17 09:52
to be honest this was more than likely an OS issue that we would have to try to work around. So its not surprising that a FireOS update might have fixed it. 

Can someone test with the new FireOS and VS2019 to see if that works?

**Comment by dellis1972** [comment] 2020-04-17 15:18
Is anyone else able to confirm that the new FireOS Fixes this issue? We will be closing this issue in the next week unless there is any new information.

**Comment by tomspilman** [comment] 2020-05-11 14:22
@dellis1972 - I can confirm Fire OS 7.3.1.2 fixed the issue for us.  

It seems right when we were all experiencing the problem and trying to figure out a fix Amazon pushed this OS update which fixed it.

I think it is safe to say this is the right fix for now.

**Comment by dellis1972** [comment] 2020-05-13 15:00
@tomspilman thanks for the update. I'll close this issue in that case :)

**Closed by dellis1972** 2020-05-13 15:00 UTC
Labels: Area: Mono Runtime, need-info
