### ISSUE TITLE
Unable to activate instance of type Android.Util.SparseArray

### ISSUE THREAD

**Issue by wuhuangjia** [xamarin/xamarin-android#4795] opened 2020-06-09 17:01 UTC
### Steps to Reproduce

1. Use Xamarin.Forms V4.6.0.847, Xamarin.Android V10.3.1.4, Xamarin.GooglePlayServices.Vision V71.1702.2
2. Build a QRCode Scan function, and scan
3. when invoking ReceiveDetections, the event argument Detector.Detections DetectedItems will show error message "System.NotSupportedException: 'Unable to activate instance of type Android.Util.SparseArray`"
4. Downgrade to Xamarin.Android to V10.2.xx, everything just works fine

>  VS bug [<span>#</span>1140617](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1140617)

**Comment by brendanzagaeski** [comment] 2020-06-10 08:15
*Cross-referencing note for the Xamarin team*

There is a matching Developer Community item reported against Xamarin.Android 10.3.99.259 (d16-7) in Visual Studio 2019 version 16.7 Preview 2: <https://developercommunity.visualstudio.com/content/problem/1071004/vs-1670-preview-2-sparcearray-notsupportedexceptio.html>

**Comment by grendello** [comment] 2020-06-10 08:48
@wuhuangjia can you attach a simple project which triggers the problem for you? Thanks!

**Comment by wuhuangjia** [comment] 2020-06-10 09:14
> @wuhuangjia can you attach a simple project which triggers the problem for you? Thanks!

ok, will try to make a sample, thanks a lot

**Comment by JimmyPun610** [comment] 2020-06-11 00:44
should be the same issue
[https://github.com/JimmyPun610/BarcodeScanner.XF/issues/37](url)

**Comment by brendanzagaeski** [comment] 2020-06-12 03:11
Thanks for the note about the BarcodeScanner.XF sample app! I was able to reproduce the problem with that sample using the following steps:

1. Fetch <https://github.com/JimmyPun610/BarcodeScanner.XF>, and checkout commit f9c7e12e94f9747ee9f6babdd215d8fdad385328.
2. ```cmd
   msbuild -restore -t:Install SampleApp\SampleApp.Android\SampleApp.Android.csproj
   ```
3. Ensure the device is connected to Wi-Fi so the necessary module can be downloaded from Google.
4. Tap the icon on the device to launch it.
5. Tap **START SCANNING ON CLICK** in the app.
6. Allow camera permissions when prompted.

_Result:_

Shortly after the the new view opens and the screen starts showing an image from the camera, the app encounters the unhandled exception:

```
System.NotSupportedException: Unable to activate instance of type Android.Util.SparseArray`1[E] from native handle 0x19 (key_handle 0x547ad98). ---> System.MissingMethodException: No constructor found for Android.Util.SparseArray`1::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
    --- End of inner exception stack trace ---
   at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x000b5] in <43cddc76fe22432dbdbcea2397b6fcd7>:0
   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <43cddc76fe22432dbdbcea2397b6fcd7>:0
    --- End of inner exception stack trace ---
   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017e] in <43cddc76fe22432dbdbcea2397b6fcd7>:0
   at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x00023] in <43cddc76fe22432dbdbcea2397b6fcd7>:0
   at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <43cddc76fe22432dbdbcea2397b6fcd7>:0
   at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <43cddc76fe22432dbdbcea2397b6fcd7>:0
   at Android.Gms.Vision.Detector+Detections.get_DetectedItems () [0x0001f] in <ef7fc227a7e44020bc62e1ade21588fd>:0
   at GoogleVisionBarCodeScanner.Droid.CameraPreview+DetectorProcessor.ReceiveDetections (Android.Gms.Vision.Detector+Detections detections) [0x00001] in <41132494451344bebfd47921df020acc>:0
   at Android.Gms.Vision.Detector+IProcessorInvoker.n_ReceiveDetections_Lcom_google_android_gms_vision_Detector_Detections_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_detections) [0x0000f] in <ef7fc227a7e44020bc62e1ade21588fd>:0
   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.63(intptr,intptr,intptr)
```

_Notes:_

As JimmyPun610 found, this problem is fairly dependent on the particular set of assemblies and versions of assemblies used in an app, so in some cases, changing the target framework version of the app or updating NuGet packages might help avoid the issue, but it looks like this issue will need a fix in Xamarin.Android.

_Cross-referencing note for the Xamarin team:_

This issue might have same underlying cause as <https://github.com/xamarin/xamarin-android/issues/4809>.

_Version information:_

- Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
  - Mono: 165f4b0
  - Java.Interop: xamarin/java.interop/d16-6@2cab35c

The issue also occurs with Visual Studio 2019 version 16.7 Preview 2:

- Xamarin.Android SDK   10.3.99.259 (d16-7/feabf52)
  - Mono: 075c3f0
  - Java.Interop: xamarin/java.interop/d16-7@d6024f1

Testing device: arm64-v8a Android 9.0 Pie (API level 28) Google Pixel 3

**Comment by brendanzagaeski** [comment] 2020-06-12 04:10
One other result I should mention to be thorough is that like 
 in <https://github.com/xamarin/xamarin-android/issues/4809>, I was only able to reproduce the exception for ``Android.Util.SparseArray`1[E]`` in the Debug configuration, which uses the debug version of _libmonodroid.so_ and a different approach to typemaps than the Release configuration.

Although this additional result isn't especially helpful for the development scenario, it means there is a margin of safety for the final app publication scenario in the Release configuration.

**Comment by brendanzagaeski** [comment] 2020-06-27 01:57
_Status update_

A candidate fix for this issue has been added to the xamarin-android/d16-7 development branch in <https://github.com/xamarin/xamarin-android/commit/bb0f7ebeb12fd6abadafa6b4c9a3db318fb93183>. This change is not yet available in a published version. I will update this item again when a published version is available that includes the fix.

_Fix verification_

Fix verified. Using a development build that includes the fix, I retested the steps to reproduce [from before](https://github.com/xamarin/xamarin-android/issues/4795#issuecomment-643040411). I verified that I could no longer reproduce the problem with the development version and confirmed that the problem reappeared if I switched back the current published versions of Xamarin.Android.

Development build tested: Xamarin.Android SDK version 11.0.0.1 (d16-7@17cc49e)

**Comment by sunnyatticsoftware** [comment] 2020-07-14 10:59
This problem happens to me ONLY after using a splash screen and moving Xamarin initializations to Splash activity

**Comment by brendanzagaeski** [comment] 2020-07-14 23:37
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7 Preview 4. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 4. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment] 2020-08-05 22:14
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this issue.

Fix included in Xamarin.Android SDK version 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.7. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Closed by brendanzagaeski** 2020-08-05 22:14 UTC
Labels: Area: App Runtime, regression

**Comment by euandeas** [comment] 2021-04-04 13:32
I seem to be getting a very similar error to this but when trying to use one of my own classes through a viewmodel. "System.NotSupportedException: 'Unable to activate instance of type {my class} from native handle 0x65 (key_handle 0xf668c60).'"

In my app a fragment is opened and the view model is created and used it it, but once this fragment is closed and I go back to the previous fragment I dispose of the view model as it is scoped to the activity. Then if I try to re open the fragment this error is thrown.

One thing i did that seemed to fix it was by not adding the transaction to the fragment onto the back stack, and it seemed to dispose properly, however i need the back stack so i can allow the user to go back to the previous screen.

I am currently disposing of the viewmodel by overriding the OnStop() method of the fragment.

This is all on latest nuget packages.

Many Thanks

**Comment by euandeas** [comment] 2021-04-04 13:48
This is my stack trace:

"at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00154] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:299 \n  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x00023] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:304 \n  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:290 \n  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:281 \n  at AndroidX.Lifecycle.ViewModelProvider.Get (Java.Lang.Class modelClass) [0x0003e] in /Users/runner/work/1/s/generated/androidx.lifecycle.lifecycle-viewmodel/obj/Release/monoandroid9.0/generated/src/AndroidX.Lifecycle.ViewModelProvider.cs:371 \n  at ClubClays.Fragments.PreviousShootFragment.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState) [0x0000f] in D:\\Programming\\euandeas\\Club-Clays\\ClubClays\\Fragments\\PreviousShootFragment.cs:29 \n  at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState) [0x00021] in D:\\a\\1\\s\\generated\\androidx.fragment.fragment\\obj\\Release\\monoandroid9.0\\generated\\src\\AndroidX.Fragment.App.Fragment.cs:1962 \n  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.15(intptr,intptr,intptr,intptr,intptr)"
