### ISSUE TITLE
NetworkStream.ReadAsync can't cancel

### ISSUE THREAD

**Issue by sawachika-kenji** [xamarin/xamarin-android#7213] opened 2022-07-28 08:56 UTC
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS2022

### Description

var _conn_passive_detection = new CancellationTokenSource();
            var _remoteSock = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            Task.Run(async () =>
            {
               
                await _remoteSock.ConnectAsync("www.google.com", 443);
                var b = new byte[1];
                var _remoteStream = new NetworkStream(_remoteSock, false);
                try
                {
                    var bytesRead =  await _remoteStream.ReadAsync(b, 0, b.Length, _conn_passive_detection.Token);
                    Console.WriteLine();
                }
                catch(Exception ex)
                {
                    Console.WriteLine();
                }
            });
            Thread.Sleep(5000);
            _conn_passive_detection.Cancel();

Console.WriteLine() does not execute when canceled

Xamarin   17.2.0.175 (d17-2@e4ffdc0)
用于启用 Xamarin.iOS 和 Xamarin.Android 的开发的 Visual Studio 扩展。

Xamarin Designer   17.2.0.244 (remotes/origin/d17-2@197e1a0b7)
用于在 Visual Studio 中启用 Xamarin Designer 工具的 Visual Studio 扩展。

Xamarin Templates   17.2.15 (2e3b60e)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.3.0.3 (d17-2/bbba5a2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: adf1bc4
    Java.Interop: xamarin/java.interop/d17-2@9760f0a9
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.2@7b1e016
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-2@fc3c2ac

### Steps to Reproduce

Create a new app and run the code above

**Comment by grendello** [comment] 2022-07-28 09:37
The 5s delay between starting the async request start and the cancellation is a bit long, are you sure the async connection doesn't complete in that time?

**Comment by sawachika-kenji** [comment] 2022-07-28 09:43
> The 5s delay between starting the async request start and the cancellation is a bit long, are you sure the async connection doesn't complete in that time? Also, I'm not sure **which** `Console.WriteLine()` you have in mind?

Yes, the connection has been established
The two Console.WriteLine()s are not executed, that is, _remoteStream.ReadAsync does not return, and no exception is triggered. The result is that _remoteStream.ReadAsync is suspended and not cancelled.
The same code works fine on windows

**Comment by grendello** [comment] 2022-07-28 10:21
@sawachika-kenji would you mind attaching the full sample app, not just the code fragment? That will allow us to reproduce and trace the issue locally

**Comment by grendello** [comment] 2022-07-28 10:22
@simonrozsival it looks like it might be an issue with TPL and/or the network stack in the BCL, feel free to bounce it back to me if that's not the case, thanks!

**Comment by sawachika-kenji** [comment] 2022-07-28 10:36
> @sawachika-kenji would you mind attaching the full sample app, not just the code fragment? That will allow us to reproduce and trace the issue locally

Thanks for your reply, the above is the complete code, it is so simple, you can create a new android app, then copy and paste this code to OnCreate or anywhere else to run the test

**Comment by grendello** [comment] 2022-07-28 10:55
> > @sawachika-kenji would you mind attaching the full sample app, not just the code fragment? That will allow us to reproduce and trace the issue locally
> 
> Thanks for your reply, the above is the complete code, it is so simple, you can create a new android app, then copy and paste this code to OnCreate or anywhere else to run the test

The reason we ask for repro is that it's **never** so simple. There are often factors at play which are not in the pasted code. Hence we need something complete that reproduces the problem for you and, in effect, for us.

**Comment by sawachika-kenji** [comment] 2022-07-28 11:26
Trust me, it's that simple, create a new Android APP, then copy and paste this code into OnCreate, run it without any other changes, as shown in the screenshot, you can do the same

![1](https://user-images.githubusercontent.com/14105308/181493970-46539f6e-29e0-4081-a5a3-9ffb2d807fb0.png)

**Comment by simonrozsival** [comment] 2022-07-28 12:58
@sawachika-kenji I created a new Xamarin Android project (Mono.Android v12.0) and I copy&pasted the snipped you provided. The `ReadAsync` is cancelled and it returns `bytesRead == 0`:

![image](https://user-images.githubusercontent.com/374616/181509492-d2ab147b-bc22-468a-abb1-1afd2872ec13.png)

If I understand your report correctly, this isn't happening for you. Can you provide some additional information? What is the API level of your testing device? Can you please attach a full sample app, as @grendello suggested, so that we can run exactly the same code as you with exactly the same project configuration?

**Comment by sawachika-kenji** [comment] 2022-07-28 13:05
> @sawachika-kenji I created a new Xamarin Android project (Mono.Android v12.0) and I copy&pasted the snipped you provided. The `ReadAsync` is cancelled and it returns `bytesRead == 0`:
> 
> ![image](https://user-images.githubusercontent.com/374616/181509492-d2ab147b-bc22-468a-abb1-1afd2872ec13.png)
> 
> If I understand your report correctly, this isn't happening for you. Can you provide some additional information? What is the API level of your testing device? Can you please attach a full sample app, as @grendello suggested, so that we can run exactly the same code as you with exactly the same project configuration?

[App2.zip](https://github.com/xamarin/xamarin-android/files/9209852/App2.zip)
Thanks for your reply, I have uploaded the code, my phone is NOKIA X6, ANDROID 9

**Comment by simonrozsival** [comment] 2022-07-28 13:57
Thanks for the sample project. Even with this project and emulator with API 28, I'm not able to reproduce the problem. Can you reproduce the issue, @grendello?

**Comment by grendello** [comment] 2022-07-28 14:42
@simonrozsival works for me as well:

```
07-28 16:42:11.189 13244 13280 V mono-stdout: Bytes read: 0
```

Tested on Android 10, 11 and 12

**Comment by sawachika-kenji** [comment] 2022-07-28 15:15
I don't know why, but I really can't cancel here, what else can I do?

**Comment by grendello** [comment] 2022-07-28 15:30
@sawachika-kenji if you run the app on device, without VS debugging it - does it cancel? Try in both Release and Debug configurations.

**Comment by sawachika-kenji** [comment] 2022-07-29 03:25
without VS debugging/release still cannot be cancelled

**Comment by sawachika-kenji** [comment] 2022-07-29 03:38
I added some new logs, and also I found that in non-vs debug mode, in ADM, I can't see "start" and other output, only after 5 seconds, I see a "cancel" output, why is this


protected override void OnCreate(Bundle savedInstanceState)
        {
            var _conn_passive_detection = new CancellationTokenSource();
            var _remoteSock = new System.Net.Sockets.Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

            Console.WriteLine("start");
            Task.Run(async () =>
            {
                Console.WriteLine("start ConnectAsync");
                await _remoteSock.ConnectAsync("www.baidu.com", 443);
                Console.WriteLine("connected");
                var b = new byte[1];
                var _remoteStream = new NetworkStream(_remoteSock, false);
                try
                {
                    Console.WriteLine("start ReadAsync");
                    var bytesRead = await _remoteStream.ReadAsync(b, 0, b.Length, _conn_passive_detection.Token);
                    Console.WriteLine("ReadAsync:" + bytesRead);
                }
                catch (Exception ex)
                {
                    Console.WriteLine("ex:" + ex.Message);
                }
            });
            Thread.Sleep(5000);
            _conn_passive_detection.Cancel();
            Console.WriteLine("cancel");


            base.OnCreate(savedInstanceState);
            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            SetContentView(Resource.Layout.activity_main);

            Toolbar toolbar = FindViewById<Toolbar>(Resource.Id.toolbar);
            SetSupportActionBar(toolbar);

            FloatingActionButton fab = FindViewById<FloatingActionButton>(Resource.Id.fab);
            fab.Click += FabOnClick;
        }
![1](https://user-images.githubusercontent.com/14105308/181677813-ffdadc63-a5d6-4c42-bbee-383e8ad475d6.png)

**Comment by sawachika-kenji** [comment] 2022-07-29 03:46
When I add a line Thread.Sleep(1000); to the first line of Task.Run, I can see the log output "start ConnectAsync"
Is this problem related to ReadAsync not being able to cancel?

Task.Run(async () =>
            {
                Thread.Sleep(1000);//<------add this line
                Console.WriteLine("start ConnectAsync");
![1](https://user-images.githubusercontent.com/14105308/181678657-79e5e0e3-1f1d-4d81-8797-3a092a046c50.png)

**Comment by simonrozsival** [comment] 2022-07-29 14:41
I noticed that it takes a while for the read to be cancelled, that was something that I missed when I stepped through the code in debugger:

```
16:33:46.498 ... cancel
16:34:12.016 ... ReadAsync:0
```

the difference is 25 seconds. I'm not sure how it's implemented internally and if that's the correct behavior or not. I'll need to examine it in more detail on Monday.

@sawachika-kenji can you check if you eventually get the `ReadAsync:0`? BTW I didn't need to add the 1000ms delay and the `start` was logged just fine.

Full log from emulator:

```
07-29 16:33:41.459  8790  8790 V mono-stdout: start
07-29 16:33:41.509  8790  8825 V mono-stdout: start ConnectAsync
07-29 16:33:41.549  8790  8825 I monodroid-timing: Typemap.java_to_managed: end, total time; elapsed: 0s:0::228995
07-29 16:33:41.862  8790  8826 V mono-stdout: connected
07-29 16:33:41.864  8790  8826 V mono-stdout: start ReadAsync
07-29 16:33:46.498  8790  8790 V mono-stdout: cancel
07-29 16:33:46.529  8790  8790 I monodroid-timing: Typemap.java_to_managed: end, total time; elapsed: 0s:0::135381
07-29 16:33:46.535  8790  8790 I monodroid-timing: Typemap.managed_to_java: end, total time; elapsed: 0s:0::4698
07-29 16:33:46.537  8790  8790 I monodroid-timing: Typemap.managed_to_java: end, total time; elapsed: 0s:0::4086
07-29 16:33:46.541  8790  8790 I monodroid-timing: Runtime.register: registering type `Xamarin.Essentials.ActivityLifecycleContextListener, Xamarin.Essentials`
07-29 16:33:46.541  8790  8790 I monodroid-timing: Runtime.register: end time; elapsed: 0s:4::807433
07-29 16:33:46.562  8790  8790 W dissue7213repr: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
07-29 16:33:46.562  8790  8790 W dissue7213repr: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
07-29 16:33:46.587  8790  8790 I FloatingActionButton: Setting a custom background is not supported.
07-29 16:33:46.600  8790  8790 I monodroid-timing: Typemap.java_to_managed: end, total time; elapsed: 0s:0::96042
07-29 16:33:46.613  8790  8790 I monodroid-timing: Typemap.java_to_managed: end, total time; elapsed: 0s:0::94188
07-29 16:33:46.632  8790  8790 I monodroid-timing: Typemap.managed_to_java: end, total time; elapsed: 0s:0::141402
07-29 16:33:46.633  8790  8790 I monodroid-timing: Runtime.register: registering type `Android.Views.View+IOnClickListenerImplementor, Mono.Android`
07-29 16:33:46.634  8790  8790 I monodroid-timing: Runtime.register: end time; elapsed: 0s:2::69182
07-29 16:33:46.862  8790  8821 D HostConnection: HostConnection::get() New Host Connection established 0x7abfd4200d10, tid 8821
07-29 16:33:46.875  8790  8821 D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
07-29 16:33:46.953  8790  8821 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
07-29 16:33:47.006  8790  8821 D EGL_emulation: eglCreateContext: 0x7abfc42175d0: maj 3 min 0 rcv 3
07-29 16:33:47.012  8790  8821 D EGL_emulation: eglMakeCurrent: 0x7abfc42175d0: ver 3 0 (tinfo 0x7abf6441b710) (first time)
07-29 16:33:47.031  8790  8821 I Gralloc4: mapper 4.x is not supported
07-29 16:33:47.034  8790  8821 D HostConnection: createUnique: call
07-29 16:33:47.034  8790  8821 D HostConnection: HostConnection::get() New Host Connection established 0x7abfd4201490, tid 8821
07-29 16:33:47.037  8790  8821 D goldfish-address-space: allocate: Ask for block of size 0x100
07-29 16:33:47.038  8790  8821 D goldfish-address-space: allocate: ioctl allocate returned offset 0x3f7ffe000 size 0x2000
07-29 16:33:47.092  8790  8821 D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
07-29 16:33:48.167  8790  8821 I OpenGLRenderer: Davey! duration=1454ms; Flags=1, IntendedVsync=11256407026581, Vsync=11256407026581, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=11256410601476, AnimationStart=11256410606352, PerformTraversalsStart=11256410609324, DrawStart=11256843603683, SyncQueued=11256845373271, SyncStart=11256894830347, IssueDrawCommandsStart=11256940424721, SwapBuffers=11257886365146, FrameCompleted=11257910508917, DequeueBufferDuration=831490, QueueBufferDuration=5309311, GpuCompleted=0,
07-29 16:33:48.228  8790  8790 I monodroid-timing: Typemap.java_to_managed: end, total time; elapsed: 0s:0::214826
07-29 16:33:48.230  8790  8790 I monodroid-timing: Typemap.java_to_managed: end, total time; elapsed: 0s:0::29101
07-29 16:33:48.235  8790  8790 I Choreographer: Skipped 93 frames!  The application may be doing too much work on its main thread.
07-29 16:33:48.269  8790  8804 I dissue7213repr: Background concurrent copying GC freed 293(115KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2462KB/4925KB, paused 24us total 101.973ms
07-29 16:33:48.320  8790  8821 I OpenGLRenderer: Davey! duration=1639ms; Flags=0, IntendedVsync=11256423687216, Vsync=11257973687154, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=11257984140618, AnimationStart=11257984144318, PerformTraversalsStart=11257984332948, DrawStart=11257987093453, SyncQueued=11257989151631, SyncStart=11257995082613, IssueDrawCommandsStart=11257995222102, SwapBuffers=11258066649680, FrameCompleted=11258068650180, DequeueBufferDuration=382753, QueueBufferDuration=641178, GpuCompleted=8589934594,
07-29 16:34:12.016  8790  8832 V mono-stdout: ReadAsync:0
```

**Comment by sawachika-kenji** [comment] 2022-07-29 14:59
I waited for a few minutes and finally got "ReadAsync: 0", the same .NET CORE 3.1 code can cancel ReadAsync immediately on WINDOWS and LINUX, but has different behavior, which is that it throws a cancel exception instead of reading zero bytes

07-29 23:47:40.955: V/mono-stdout(3783): start
07-29 23:47:40.960: V/mono-stdout(3783): start ConnectAsync
07-29 23:47:41.038: V/mono-stdout(3783): connected
07-29 23:47:41.038: V/mono-stdout(3783): start ReadAsync
07-29 23:47:42.901: V/mono-stdout(3783): cancel
07-29 23:51:10.007: V/mono-stdout(3783): ex:Unable to read data from the transport connection: Network subsystem is down.
![1](https://user-images.githubusercontent.com/14105308/181787708-1f22f52f-35c1-411a-bcb4-1bc0142b8a43.png)

**Comment by sawachika-kenji** [comment] 2022-07-29 15:27
Or do I have any other way to know if a socket is closed? I am managing a connection pool, and I need to make sure that the socket that the user takes from the pool is not closed by the remote server. My current approach is to call ReadAsync on each socket in the pool. If it returns 0, it means that the socket has been close, and remove it from the pool, when the socket is taken out of the consumer pool, I need to cancel the ReadAsync and return the socket to the consumer, now the problem is that I can't cancel the ReadAsync

**Comment by simonrozsival** [comment] 2022-08-01 16:49
I re-ran the code and I'm still reaching the `ReadAsync:0` log. I'm getting the same behavior even when I remove the cancelation, so the read operation seems to time out independently.

In .NET 6/MAUI I'm getting an `OperationCanceledException`:
![image](https://user-images.githubusercontent.com/374616/182200495-d03b6bd8-c00b-4855-ab7d-edf01cfae5de.png)

My conclusion is that you're right, @sawachika-kenji, and there's some problem with canceling of the read operation. This is probably either a bug in legacy mono or a limitation of legacy mono's socket implementation. I'll do some more digging when I'm back from vacation.

**Comment by sawachika-kenji** [comment] 2022-08-06 04:17
Does upgrading to .net6 fix the problem? Does the Android version of .net6 use .net core or is it still mono? The various bugs of mono over the years have made me lose confidence in mono. I hope that xamarin.android can migrate from the underlying mono implementation to the .net core implementation.

**Comment by simonrozsival** [comment] 2022-08-11 13:04
> Does upgrading to .net6 fix the problem?

Yes, as I mentioned, it worked just fine for me.

> Does the Android version of .net6 use .net core or is it still mono?

Mono is now part of .NET 6. The Android version of .NET 6 uses the Mono virtual machine but the C# libraries are mostly shared with the rest of .NET (there are obviously some platform-specific parts of the codebase that cannot be shared).

@grendello I think that since the .NET 6 behaves as expected we should close this issue now.

**Closed** 2022-08-12 09:05 UTC
Labels: Area: Mono Runtime, need-attention
