### ISSUE TITLE
VS2019 Crashes Android when AOT and LLVM enabled

### ISSUE THREAD

**Issue by ianvink** [xamarin/xamarin-android#3140] opened 2019-04-02 18:51 UTC
In RELEASE mode for an Android app, if we set AOT and LLVM, then build the tool on our Build server (Mac VS2019) the app crashes with the crash log attached

When we disable LLVM, it works fine

 
### Steps to Reproduce

1.  Enable AOT and LLVM 
2.  Build to releasr
3.  Crash

### Expected Behavior
Not crash
### Actual Behavior
Crash
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - Android:   VS2019

### Reproduction Link

![2019-04-02 11_49_17-Window](https://user-images.githubusercontent.com/112916/55428160-60635780-553d-11e9-9488-d15e8316320a.png)

[log.txt](https://github.com/xamarin/Xamarin.Forms/files/3035510/log.txt)

**Comment by EmilAlipiev** [comment] 2019-05-31 21:30
Did you try without arm64-v8a? i figured out that my problem is with arm64-v8a.

**Comment by EmilAlipiev** [comment] 2019-05-31 23:17
my app is not crashing immediately but crashes on some certain pages and i dont see anything special about those pages. I try to debug in release mode but although i enabled "enable developer instrumentation", i am still not able to get any log. Crash log doesnt also appear in Appcenter. So how can i find the reason why it crashes? the same app with same settings works just fine using VS2017

**Comment by brendanzagaeski** [comment] 2019-06-06 15:37
Thanks again for the report! I will close this as a duplicate of <https://github.com/xamarin/xamarin-android/issues/2521> to tidy up the issue list. On Windows, the fix is currently available in Visual Studio 2019 version 16.1, but on Mac it's only in the Preview channel of Visual Studio for Mac at the moment. I will update the status of <https://github.com/xamarin/xamarin-android/issues/2521> to Closed when the fix has been published to the Stable channel of Visual Studio for Mac.

**Closed by brendanzagaeski** 2019-06-06 15:37 UTC

**Comment by beavis88** [comment] 2019-08-01 15:24
Still not working on VS2019 16.2.0.

**Comment by brendanzagaeski** [comment] 2019-08-01 15:40
@beavis88 , if you could report a [new issue](https://github.com/xamarin/xamarin-android/issues/new) with the full error message you are seeing (for example, including the output from [`adb logcat -d`](https://docs.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log?#accessing-from-the-command-line) after the app crashes if you are seeing an app crash), that would be perfect. Thanks in advance!

**Comment by beavis88** [comment] 2019-08-02 07:03
@brendanzagaeski , thank you for pointing out, issue created.
