### ISSUE TITLE
xamarin nuget with  symbols do not debug work unless source is in same location as original  build source path

### ISSUE THREAD

**Issue by generik0** [xamarin/xamarin-android#2460] opened 2018-11-27 15:20 UTC
Hi

When I create our own nuget packages I have GeneratePackageOnBuild and include symbols (portable) and include source for the .net stanadr projects creating the nugets.

The symbols and debugging works with "normal" .net apps., however, they are not debuggable in Xamavin project. With that said the symbols will work if I replicate the build path (on the service running the agent pool and MSBuild) to be on the same location on my local machine and add the source.

It does not matter what I enter in  VS2017 15.9.2 Options->Debugger->Symbols
The absolute path from where the package was built, is required locally and the source code should be in this location locally also.

Again. we need to have the source code in the same location/path as it is on the build server. (this is difficult as each build has its own id) and it will work.
It does not matter if i index and do a seperate pack on the build server. Or whatever i do. 

It just appears that the paths must be equal.

Any ideas?

**Comment by jonathanpeppers** [comment] 2018-12-04 03:09
@generik0 can you create a quick example project? or post a `*.nupkg`?

What value do you have set for `DebugType`? Options are `full`, `portable`, `pdbonly`, etc.

**Comment by generik0** [comment] 2018-12-04 08:35
@jonathanpeppers. I can but on holiday right now. Will get from college.
Used portable and full.
Both only work if the source code is in the same path as the build path.

I need a private email or something to send the nugets. I cannot send to an open forum.

**Comment by jonathanpeppers** [comment] 2018-12-04 18:00
> Both only work if the source code is in the same path as the build path.

Can you give a concrete example? XYZ is at path `C:\foo\etc` and ABC is at path `C:\bar\etc`.

I emailed you via the email listed on your Github account if you want to share nugets privately.

**Comment by generik0** [comment] 2018-12-05 03:02
Hi @jonathanpeppers.

Yes it is problaby best you replicate your self. Very easy.

1. Make a net standard solution with a c# library projekt
2. Open the csproj and change to net45
3. Enable “generate package on build”
4. Add some silly code in it.
5. Build

1. Create solution in a different root  path with a new droid project “. Bonus points if another drive.
2. In VS add a nuget to the path where you built the previous package and add to your new droid project. 
3. Add a inline where you call the silly code in the nuget.

1. Try to debug. It will work.
2. Change the root folder name where your nuget was built. Even move drive if you want to be sure. It won’t work...

**Comment by jonathanpeppers** [comment] 2018-12-05 21:52
To make sure I follow: You are trying to step into the source code of the compiled NuGet?

This sounds like an IDE problem, and not really anything to do with Xamarin.Android.

A couple of things to try:
1. [In this article](https://capgemini.github.io/development/debugging-into-a-nuget-package/), it mentions using `nuget pack -symbols` so symbols are included in the `nupkg`. Does your `nupkg` file have symbols in it?
1. [In this SO question](https://stackoverflow.com/a/21922429), they mention there is a setting in the IDE you have to point to a directory where your source code lives.

Hope that helps! Closing for now, as I think you would hit the same problem with a regular .NET console app. Feel free to comment if you find otherwise!

**Comment by generik0** [comment] 2018-12-05 22:17
@jonathanpeppers
No a regular console app does not have this issue. The IDE can open the src code from other locations than the exact build path.
This is an issue when specifically using the google Android emulator.

I am building the symbols package. I forgot to write for you to tick this in my steps. My mistake.

The settings pointing to the src code is filled out. But has no effect.

Once again this issue is isolated to the android emulator and VS nuget (with symbols) debugging.
The arrivals are all followed 100%. Did you at least try it yourself before closing?

**Comment by jonathanpeppers** [comment] 2018-12-05 22:22
Sorry, the steps seems a bit vague to me... Did you take a look at the two links? You're doing what they suggest already?

@generik0 I do think it's best if you could make a quick reproduction project, so we can look into this further.

What `$(DebugType)` is your project using in `Release` mode? `DebugType=portable` works better with Mono/Xamarin.Android. A quick sample would be best, so the problem is isolated.

**Comment by generik0** [comment] 2018-12-15 23:45
Hi @jonathanpeppers I need to pause this issue until Jan next year. I am on holidays until then.
My colleagues are 2 man down and need to focus on feature work. This core stuff is my responsibility. 
I will close the case, and reopen if it needs to be done so in Jan...
Sorry for the inconveinience happy holidays to you, when you get there :-)

**Comment by generik0** [comment] 2019-01-03 11:39
Hi @jonathanpeppers I am back. Lovely holiday. Happy new years to you,
The links you sent me, I was worried if my VS had this setting enabled:
![image](https://user-images.githubusercontent.com/2411563/50635856-2d1c2700-0f54-11e9-8e4a-04d87619c120.png)
But it doesn't, as you can see.

So I would like to start this up again.
As far as I can see, when using a droid in Xamarin, it appears that the source code path needs to match the build path before one can debug. Is this expected behaviour?

**Comment by jonathanpeppers** [comment] 2019-01-03 14:34
@generik0 at this point I think we can investigate further if you can attach a quick project/solution showing what's happening. It can literally be a "hello world" app using one library.

I'm not sure I'm following exactly what you are doing, sorry... I have another library I'm able to debug like you are trying to do.

**Comment by generik0** [comment] 2019-01-08 12:15
Hi @jonathanpeppers 
I have something for you now. here is a git demo.

You can see that the debugger will not step into:
![image](https://user-images.githubusercontent.com/2411563/50830095-fe80c080-1346-11e9-910f-6a7068b1f842.png)
1. Please open repo on AppOnly branch
2. Try to debug
3. Unless the source code (master branch )is in h:\Tmp\NugetDroidDebugger it will not debug into the logger
4. Or you rebuild the nugets from master and replace the nugets in the solution.

Hence Droid debug in VVS with google emulator (or tablet) only works when the source code for the nugets is located at the same path as the build was.
And this is impossible when using the vsts / azure deops hosted build server...

**Comment by generik0** [comment] 2019-01-15 17:50
@jonathanpeppers 
This does not help. And yes my setup is correct. I can step into and debug any nine droid app.

I will repeat the issue..

You cannot step into code when using xamarin and google emulator and a tablet UNLESS the source code is placed the same spot path as it was built in.
You can make portables, full, or any type of build / packaging you want.
Xamarin May even say that the modules are loaded...

But no matter what you do, and any VS setting you can think up, the source code must be located in the same path as it was at build time...

And this is not possible when tfs/vsts builds from many agents in a veriaty of possible locations...

Please take my issue seriously. And please look at my demo project I made specifically because you asked for it...
Just try to make xamarin and google Emulator step into the code... just try....

**Comment by jonathanpeppers** [comment] 2019-01-15 17:51
> I guess the source code for Shared.Core.1.0.1.nupkg and Shared.Interfaces.1.0.1.nupkg aren't in the zip?

@generik0 can you provide the source for the two NuGets so I can try it? thanks.

**Comment by generik0** [comment] 2019-01-15 17:53
@jonathanpeppers they are in the zip I sent. Please open the git repo, you will find them on the main branch

**Comment by jonathanpeppers** [comment] 2019-01-16 14:10
From @joj:
> We don't have support for finding source in a location different than what the source was compiled to in Mono. There is a related effort (supporting sourcelink) we have had some requests for and may help. At the moment, this is not something we support. If you can add a suggestion in developer community, it will be easier for us to track. This is not an android issue, though. It is an IDE issue. I'm going to close this for now (we can still comment on this after it's closed) so we can move the conversation to developer community, which is where we track IDE issues. Thanks!

I did run your project to make sure we didn't have an MSBuild issue. I was able to see the symbols copied to the right places in `$(IntermediateOutputPath)` and deployed to the device.

Closing for now @generik0, since this is an IDE problem. Can you file a [developer community feedback ticket](https://developercommunity.visualstudio.com/spaces/8/index.html)?

Feel free to ask @joj other questions, and link to the developer community ticket if you make one. Thanks!

**Closed by jonathanpeppers** 2019-01-16 14:10 UTC
Labels: Area: App+Library Build, need-info

**Comment by generik0** [comment] 2019-01-16 16:48
@jonathanpeppers so you are saying you can replicate the issue, but it is not a xamarin issue. It is an issue with VS?

**Comment by jonathanpeppers** [comment] 2019-01-16 16:52
Yes an issue with Visual Studio’s integration with Xamarin (more specifically Mono).

**Comment by generik0** [comment] 2019-01-17 12:10
@jonathanpeppers here is the ticket, if you are interested :-)
https://developercommunity.visualstudio.com/content/problem/429931/visual-studio-ide-mono-integration-does-not-allow.html
