### ISSUE TITLE
Possible IntelliSense integration error

### ISSUE THREAD

**Issue by WashingtonARamos** [xamarin/xamarin-android#4344] opened 2020-03-02 06:09 UTC
When I hover my mouse over `Android.Views.ViewGroup` an enormeous description appears with some code. I believe something went wrong with some XML somewhere. It happens when I hover over the type, not an object of the class.

![big](https://user-images.githubusercontent.com/14356419/75649793-eba80a00-5c32-11ea-9fa4-bcd1a7e2c470.png)

Visual Studio info:
```
Microsoft Visual Studio Community 2019
Version 16.4.4
VisualStudio.16.Release/16.4.4+29728.190
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA172
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.4.460.23317
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.4.460.23317
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.4.460.23317
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.4.460.23317
Azure Functions and Web Jobs Tools

C# Tools   3.4.1-beta4-19614-01+165046097562cfe65b09c2e9a9d8f7cd88526f2c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.21016.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.87+gbb515bf382
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.5.24 (1fafd7e)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61912.09160
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.11031.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.4.1-beta4-19614-01+165046097562cfe65b09c2e9a9d8f7cd88526f2c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.4.0-beta.19556.5+e7597deb7042710a7142bdccabd6f92b0840d354
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.4.000.309 (d16-4@1d551f9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.4.0.475 (remotes/origin/d16-4@ac250f5aa)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.3.7 (d16-4/d66aed0)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: fd9f379
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b


Xamarin.iOS and Xamarin.Mac SDK   13.10.0.17 (5f802ef)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by gugavaro** [comment] 2020-03-02 14:08
@brendanzagaeski is this a VS issue? or xml documentation?

**Comment by WashingtonARamos** [comment] 2020-03-02 15:04
> 
> 
> @brendanzagaeski is this a VS issue? or xml documentation?
I'm not sure. As I wrote this yesterday I was under the belief that the IntelliSense tooltip was integrated made XML files, that's why I wrote "I believe something went wrong with some XML somewhere", but now I remember it's "hardcoded" in the .cs files themselves (unless MonoDroid does it differently).

Anyway, it happens **in** Visual Studio, but I don't think it's caused **by** Visual Studio, rather by a documentation error.

**Comment by brendanzagaeski** [comment] 2020-03-03 06:39
The problem is caused by the content in *$ReferenceAssemblies/Microsoft/Framework/MonoAndroid/v10.0/Mono.Android.xml* in the installer.

It looks like this might be a build configuration issue. It appears that installers from master have had incorrect content for quite a while, whereas installers from release branches, except for d16-4, have had correct content. I checked a number of *.vsix* packages:

**master**

master@<https://github.com/xamarin/xamarin-android/commit/a20be392163df9aed72e9127368c9174ecdd4bdd> - *Incorrect*. (Latest master installer.)

**d16-6, built on Azure Pipelines**

d16-6@<https://github.com/xamarin/xamarin-android/commit/27ee3e3514cde77fcdca2d42aabc51e5bd4dbb38> (10.2.99.196) - Correct. (First installer built successfully after branching.)
master@<https://github.com/xamarin/xamarin-android/commit/2c2473155a29b4bd5dff76639baf8153b536db9c> (10.2.99.193) - *Incorrect*. (Last installer built successfully before branching.)

**d16-5, built on Azure Pipelines**

d16-5@<https://github.com/xamarin/xamarin-android/commit/0f79b506cec1840400bb34dc3c006a9d62d08a49> (10.1.99.55) - Correct. (First installer after branching.)
master@<https://github.com/xamarin/xamarin-android/commit/d229eed40d7aa796639da63a9e2f97ab9e64ff5c> (10.1.99.54) - *Incorrect*. (Last installer before branching.)

**d16-4, built on Azure Pipelines**

d16-4@<https://github.com/xamarin/xamarin-android/commit/8d041fe007db6e363307b8921c7ce6abe2549ffb> (10.0.99.75) - ***Incorrect***. (First installer after branching.)
master@<https://github.com/xamarin/xamarin-android/commit/e61a4ea35e7998f21206e17d25aae9c441472b60> (10.0.99.74) - *Incorrect*. (Last installer before branching.)

**d16-3, built on Jenkins**

d16-3@<https://github.com/xamarin/xamarin-android/commit/2eeec6bbd93b4c3bc746bbdcd17dd4d66de58670> (9.5.0.0) - Correct. (First installer built successfully after branching.)
master@<https://github.com/xamarin/xamarin-android/commit/063844c155bce5ce8661daa96efc483c9ee92ea2> (9.4.99.105) - *Incorrect*. (Last installer before branching.)

* * *

@pjcollins, does this difference between master and release branches look familiar by chance?

**Comment by pjcollins** [comment] 2020-03-03 16:23
@brendanzagaeski this is odd, I don't immediately see any differences that would be caused by branch naming. One thing I noticed is that we are maybe duplicating some work in docs generation? One potential oddity I noticed is that [the inverted build system appears to also be running](https://github.com/xamarin/monodroid/blob/master/docs.make#L31) `mdoc export-msxdoc` before our `create-installers.targets` do?

I'm not sure if this could cause the behavior seen above in our docs but if [this step is duplicated](https://github.com/xamarin/monodroid/blob/master/xa-integration.mk#L82) we should probably remove it either way, that may be a decent place to start.

**Comment by brendanzagaeski** [comment] 2020-03-04 02:34
It turns out the cause of the differences across the branches is that monodroid's android-api-docs submodule is out-of-date on master and d16-4.

  * master: https://github.com/xamarin/android-api-docs/commit/25aa18c2492ac91a2d286ef786ff891c128e6d17, March 2016

  * d16-6: https://github.com/xamarin/android-api-docs/commit/6012e04ae54cdc26174dbfe0ca32063193101b32, December 2019

    (Updated during branching: <https://github.com/xamarin/monodroid/commit/70d4ff405ad779a5b03a4137358c6911b8f521a5>)

  * d16-5: https://github.com/xamarin/android-api-docs/commit/cd414a93057b6f61afcdd3db6ff44391fb166246, June 2019

    (Updated during branching: <https://github.com/xamarin/monodroid/commit/2c9ce23d2288cc245729d32c2eabf6deebdf554b>)

  * d16-4: https://github.com/xamarin/android-api-docs/commit/25aa18c2492ac91a2d286ef786ff891c128e6d17, March 2016

    (*Not* updated during branching: <https://github.com/xamarin/monodroid/commit/60d4bd47cd90744535d7040a4726241a6b04a467>)

  * d16-3: https://github.com/xamarin/android-api-docs/commit/cc99763f7c7e7438d23ad9486cd80c7cdc269c86, April 2019

    (Updated during branching: <https://github.com/xamarin/monodroid/commit/7550edd7d8e86e8042ffec6e21d6f249fa50d49f>)

The problematically long docs for cases like `Android.Views.ViewGroup` were removed from android-api-docs in https://github.com/xamarin/android-api-docs/commit/c5412d5e05aaced74d70324398e21d3ec1e70bdf, April 2019.

**Comment by brendanzagaeski** [comment] 2020-03-27 04:46
This item should be all set now, so I'll close it. The latest Xamarin.Android 10.2 (d16-5) installer and the Xamarin.Android 10.3 (d16-6) Preview installer have the correct InelliSense docs.

A couple new changes have also been added thanks to this report (https://github.com/xamarin/xamarin-android/commit/d57ccfbbfeae30598c68407e345072204661da9d and https://github.com/xamarin/xamarin-android/commit/0eced74d189fbe9180875423f53864163aeb7185) to remove the redundant copy of the android-api-docs submodule from monodroid and help prevent any similar issues in the future.

Thanks again for submitting this issue!

**Closed by brendanzagaeski** 2020-03-27 04:46 UTC
Labels: regression
