### ISSUE TITLE
App crashes when collecting GC 

### ISSUE THREAD

**Issue by sheiksyedm** [xamarin/xamarin-android#2929] opened 2019-04-04 18:56 UTC
### Steps to Reproduce

1. Run the attached sample 
2. Perform freehand drawing over a screen
3. Application get crashed with ObjectDisposedException
. 
Sample : https://github.com/sheiksyedm/GC_Collect_Android

### Expected Behavior

I expect the app will not get crash when doing freehand drawing even GC collected. 

### Actual Behavior
In my project, when doing freehand drawing or some interaction like added shapes and resizing it, the app is getting crashed. It's happened when mono run time executing a GC.Collect(). 
So, i have prepared the demo app similar like my project and manually called the GC.Collect() for this demo purpose. As like my project, the exception thrown in the attached demo app. 

### Version Information
Microsoft Visual Studio Enterprise 2017 
Version 15.9.7
VisualStudio.15.Release/15.9.7+28307.423
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

### Log File

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Android.Graphics.Path'. occurred

04-05 00:22:58.769 D/Mono    (  376): DllImport searching in: '__Internal' ('(null)').
04-05 00:22:58.769 D/Mono    (  376): Searching for 'java_interop_jnienv_call_void_method_a'.
04-05 00:22:58.769 D/Mono    (  376): Probing 'java_interop_jnienv_call_void_method_a'.
04-05 00:22:58.769 D/Mono    (  376): Found as 'java_interop_jnienv_call_void_method_a'.
04-05 00:22:58.771 D/Mono    (  376): DllImport searching in: '__Internal' ('(null)').
04-05 00:22:58.771 D/Mono    (  376): Searching for 'java_interop_jnienv_get_static_field_id'.
04-05 00:22:58.771 D/Mono    (  376): Probing 'java_interop_jnienv_get_static_field_id'.
04-05 00:22:58.771 D/Mono    (  376): Found as 'java_interop_jnienv_get_static_field_id'.
04-05 00:22:58.772 D/Mono    (  376): DllImport searching in: '__Internal' ('(null)').
04-05 00:22:58.772 D/Mono    (  376): Searching for 'java_interop_jnienv_get_static_object_field'.
04-05 00:22:58.772 D/Mono    (  376): Probing 'java_interop_jnienv_get_static_object_field'.
04-05 00:22:58.772 D/Mono    (  376): Found as 'java_interop_jnienv_get_static_object_field'.
04-05 00:22:58.784 D/vndksupport(  376): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
04-05 00:22:58.804 D/InputMethodManager(  376): prepareNavigationBarInfo() DecorView@aa7cfb4[MainActivity]
04-05 00:22:58.805 D/InputMethodManager(  376): getNavigationBarColor() -855310
04-05 00:22:58.805 V/InputMethodManager(  376): Starting input: tba=GC_Collect_Android.GC_Collect_Android ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
04-05 00:22:58.805 D/InputMethodManager(  376): startInputInner - Id : 0
04-05 00:22:58.809 D/ViewRootImpl@e28124d[MainActivity](  376): MSG_RESIZED: frame=Rect(0, 0 - 1440, 2960) ci=Rect(0, 84 - 0, 168) vi=Rect(0, 84 - 0, 168) or=1
04-05 00:22:59.862 D/ViewRootImpl@e28124d[MainActivity](  376): ViewPostIme pointer 0
04-05 00:22:59.872 D/Mono    (  376): DllImport searching in: '__Internal' ('(null)').
04-05 00:22:59.872 D/Mono    (  376): Searching for 'java_interop_jnienv_call_nonvirtual_int_method_a'.
04-05 00:22:59.872 D/Mono    (  376): Probing 'java_interop_jnienv_call_nonvirtual_int_method_a'.
04-05 00:22:59.873 D/Mono    (  376): Found as 'java_interop_jnienv_call_nonvirtual_int_method_a'.
04-05 00:22:59.877 D/Mono    (  376): DllImport searching in: '__Internal' ('(null)').
04-05 00:22:59.877 D/Mono    (  376): Searching for 'java_interop_jnienv_call_nonvirtual_float_method_a'.
04-05 00:22:59.877 D/Mono    (  376): Probing 'java_interop_jnienv_call_nonvirtual_float_method_a'.
04-05 00:22:59.877 D/Mono    (  376): Found as 'java_interop_jnienv_call_nonvirtual_float_method_a'.
04-05 00:22:59.883 D/Mono    (  376): DllImport searching in: '__Internal' ('(null)').
04-05 00:22:59.883 D/Mono    (  376): Searching for 'java_interop_jnienv_call_nonvirtual_boolean_method_a'.
04-05 00:22:59.883 D/Mono    (  376): Probing 'java_interop_jnienv_call_nonvirtual_boolean_method_a'.
04-05 00:22:59.883 D/Mono    (  376): Found as 'java_interop_jnienv_call_nonvirtual_boolean_method_a'.
04-05 00:22:59.886 D/Mono    (  376): DllImport searching in: '__Internal' ('(null)').
04-05 00:22:59.886 D/Mono    (  376): Searching for 'java_interop_jnienv_call_boolean_method_a'.
04-05 00:22:59.886 D/Mono    (  376): Probing 'java_interop_jnienv_call_boolean_method_a'.
04-05 00:22:59.886 D/Mono    (  376): Found as 'java_interop_jnienv_call_boolean_method_a'.
04-05 00:23:03.581 D/Mono    (  376): GC_BRIDGE waiting for bridge processing to finish
04-05 00:23:03.592 I/Collect_Androi(  376): Explicit concurrent copying GC freed 9460(2MB) AllocSpace objects, 3(60KB) LOS objects, 83% free, 1217KB/7MB, paused 222us total 21.766ms
04-05 00:23:03.593 D/Mono    (  376): GC_TAR_BRIDGE bridges 17 objects 17 opaque 0 colors 15 colors-bridged 15 colors-visible 15 xref 4 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.05ms tarjan 0.05ms scc-setup 0.01ms gather-xref 0.00ms xref-setup 0.00ms cleanup 0.07ms
04-05 00:23:03.593 D/Mono    (  376): GC_BRIDGE: Complete, was running for 23.42ms
04-05 00:23:03.593 D/Mono    (  376): GC_MAJOR: (user request) time 1.61ms, stw 2.82ms los size: 1024K in use: 16K
04-05 00:23:03.593 D/Mono    (  376): GC_MAJOR_SWEEP: major size: 832K in use: 91K
Unhandled Exception:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Android.Graphics.Path'.

**Comment by Jkinley01** [comment] 2019-04-04 19:23
Well I'm seeing several GC related bugs recently. Hope this gets fixed because we cannot make any chances to our app now because of the latest VS update.

**Comment by radekdoulik** [comment] 2019-04-08 15:14
Looks like duplicate of https://github.com/xamarin/xamarin-android/issues/1368

Could you try to build and run your app with `MONO_GC_PARAMS=bridge-implementation=old`? (like this https://github.com/StephenClearyApps/PewBible/commit/652a5d7138e0e1f8e0015fe755fbeb7848c3822c)

This way we can check whether it is specific for the current GC bridge?

**Closed by radekdoulik** 2019-04-08 15:14 UTC
