### ISSUE TITLE
[Bug] Random Android Font resource issues after upgrading to VS 16.6.2

### ISSUE THREAD

**Issue by cmonto** [xamarin/xamarin-android#4894] opened 2020-06-30 15:02 UTC
### Description
After upgrade to VS 16.6.2 (Xamarin Android 10.3.1.4) facing weird issues with a Font resource on Android.
- After cleanup (bin/obj/etc.) first time builds and runs fine
- At random, subsequent build fails, with error MSB4006: There is a circular dependency in the target dependency graph involving target "UpdateAndroidResources"
- At random subsequent build succeeds and deploys to device and breaks with exception: Java.Lang.RuntimeException: 'Font asset not found fonts/<filename>.ttf' while calling Android.Graphics.Typeface.CreateFromAsset(..)
Cleanup only fixes the first build and issue comes back immediately after first build.

### Steps to Reproduce

1. Open the minimalist Project attached
2. Build and Debug Android head multiple times
3. As mentioned in the issue description, get build error or runtime exception (line 23, XFApp.Android\MainActivity.cs)

### Expected Behavior
- Building with Android Font Resource should succeed.
- No runtime Exception should be thrown on Android.Graphics.Typeface.CreateFromAsset().

### Actual Behavior
- At random, build fails, with error MSB4006: There is a circular dependency in the target dependency graph involving target "UpdateAndroidResources"
- At random build succeeds and deploys to device and breaks with exception: Java.Lang.RuntimeException: 'Font asset not found fonts/<filename>.ttf' while calling Android.Graphics.Typeface.CreateFromAsset(..)

### Basic Information

- Version with issue: VS 16.6.2
- Last known good version: VS 16.5.4
- IDE: VS 16.6.2
- Platform Target Frameworks: 
  - Android: 10.3.1.4 
- Android Support Library Version: Android X as included in Project
- Nuget Packages:
- Affected Devices: Tested in Pixel 2 running android 10

### Reproduction Link

[XFApp.zip](https://github.com/xamarin/Xamarin.Forms/files/4852669/XFApp.zip)

**Comment by cmonto** [comment] 2020-07-09 19:31
No action for past 10 days?

**Comment by brendanzagaeski** [comment] 2020-07-10 22:09
Thanks for the report and the test case.

1. For _Java.Lang.RuntimeException: 'Font asset not found fonts/.ttf'_, that problem matches the following Visual Developer Community item:

   https://developercommunity.visualstudio.com/content/problem/1045818/after-update-vs-2019-xamarin-app-debug-throws-exce.html

   There is a candidate workaround option mentioned there of moving the _.ttf_ asset out of the _fonts_ subdirectory to the root of the _Assets_ directory.
   
   I will update this GitHub issue when the fix for that problem is published in a Preview version and again when it is published in a Release version.

2. For _error MSB4006: There is a circular dependency in the target dependency graph involving target "UpdateAndroidResources"_, another user did see that about a year ago in <https://gitter.im/xamarin/xamarin-android?at=5d6ee2748a83ef34a3127b22>, but so far the steps to reproduce it have not been identified. I tried to reproduce the problem with the attached test case, but so far I have not been able to hit it. I tried about 50 repetitions of modifying and redeploying the project.

   If you can reproduce that behavior fairly consistently, then if you could gather and attach back the diagnostic MSBuild output for a build that fails with that error, that would be excellent:

   1. Set **Tools > Options > Project and Solutions [section] > Build and Run [subsection] > MSBuild project build output verbosity** to **Diagnostic**.
   2. Repeat the steps to reproduce the issue.
   3. Once you get the circular dependency build error, open the **View > Output** window, and set **Show output from** to **Build**.
   4. Make sure the **Output** window is selected, and then choose **File > Save Output As** to save the contents to a text file. Or copy and paste the build output into a text file.
   5. Attach back the text file in a new comment on this item. Note that by default that file will contain some details about your environment and project. If the build output contains information you need to keep private, you can remove the private information before attaching it or create a new Visual Studio Developer Community feedback item via **Help > Send Feedback > Report a Problem** in Visual Studio and attach the build output there instead (attachments on new Developer Community items are only visible to the Microsoft team).

   After you complete these steps, you can set **Tools > Options > Project and Solutions [section] > Build and Run [subsection] > MSBuild project build output verbosity** back to **Minimal** to avoid adding extra time to your future builds. Thanks in advance for the additional info!

**Comment by brendanzagaeski** [comment] 2020-07-16 02:54
1. For Java.Lang.RuntimeException: 'Font asset not found fonts/.ttf':

   _Release status update_
   
   A new Preview version of Xamarin.Android has now been published that includes the fix for that item ([tracked in Developer Community](https://developercommunity.visualstudio.com/content/problem/1045818/after-update-vs-2019-xamarin-app-debug-throws-exce.html)). The fix is not yet included in a Release version. I will update this again when a Release version is available that includes the fix.
   
   Fix included in Xamarin.Android 11.0.0.3.
   
   Fix included on Windows in Visual Studio 2019 version 16.7 Preview 4. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).
   
   Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 4. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by ederbond** [comment] 2020-07-16 22:40
To reproduce the Error on Visual Studio 2019 16.6.4 you'll need 2 devices.

1) Just run the attached sample project @cmonto has provided.
At first deploy It will run with successfuly.

2) Switch to the second device and hit F5;
As soon as the app starts you'll see the exception:


Java.Lang.RuntimeException
  Message=Font asset not found fonts/winjs-symbols.ttf

**Comment by grendello** [comment] 2020-08-17 07:17
Fixed in https://github.com/xamarin/xamarin-android/pull/4786

**Closed by grendello** 2020-08-17 07:17 UTC
Labels: need-info

**Comment by brendanzagaeski** [comment] 2020-08-17 18:52
1. For _Java.Lang.RuntimeException: 'Font asset not found fonts/.ttf'_:

   Apologies on forgetting to update this item after the Release version was published with the fix. I'll add that information now for completeness and add this issue to the milestone for that version.
   
   _Release status update_
   
   A new Release version of Xamarin.Android has now been published that includes the fix for this item.
   
   Fix included in Xamarin.Android SDK version 11.0.0.3.
   
   Fix included on Windows in Visual Studio 2019 version 16.7. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.
   
   Fix included on macOS in Visual Studio 2019 for Mac version 8.7. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

2. For _error MSB4006: There is a circular dependency in the target dependency graph involving target "UpdateAndroidResources"_, since that issue might be a separate problem, if any user sees that problem again in the future, please open a new GitHub issue and include the diagnostic MSBuild output as [described earlier](https://github.com/xamarin/xamarin-android/issues/4894#issuecomment-656915462). Thanks!
