### ISSUE TITLE
Xamarin.Android Linker is not working as expected. Animations can be deleted regardless of your ProGuard or excluding configuration

### ISSUE THREAD

**Issue by FANMixco** [xamarin/xamarin-android#6156] opened 2021-07-30 16:56 UTC
I have an app that is working fine but since I cannot link the libraries (because it causes an **abnormal behavior**) it becomes significantly bigger (20 MiB more). The main issue happens with one of my own libraries: 

https://www.nuget.org/packages/Xamarin-MaterialSearchBar
  
I "excluded" the package and its dependencies:  
>Xamarin.AndroidX.AppCompat;Xamarin.AndroidX.ConstraintLayout;Xamarin.AndroidX.RecyclerView;Xamarin.AndroidX.CardView  
  
But the "linking" options behave quite odd because they are not excluded neither in linking all or only linking SDK. The animations got somehow mad and they are working in a "particular" way, the hamburger menu transforms into an arrow when it shouldn't and vice-versa and if I do click on the X, it just removes the X forever and doesn't clean. The following image can give you an idea of its **abnormal behavior**. 

[![preview][1]][1]

This is the expected behavior and normal when I don't link anything:

[![preview][2]][2]

The app only works properly when I use **Don’t Link**. However, I want to understand what I must exclude (or how to do it properly) or change to avoid this issue. At this point, I tried excluding it in the ProGuard file, in the "exclusion" section, etc. but nothing works. This is a relatively old bug that I just "ignored" for a while because I prioritized other topics before.

My library is open-source so you can check it and tell me if I'm doing something wrong or I should add something else:

https://github.com/FANMixco/Xamarin-SearchBar

***It's important to highlight that I wrote this library in C# and Xamarin. This is not the binding of another one.***

### UPDATE 1:

I modified my library and added:

`[Preserve(AllMembers = true)]`

and:

`[assembly: LinkerSafe]`

And the bug persists.

### Update 2:

I excluded each of the libraries and the bug persisted in the ProGuard file and nothing worked. I think the linker is messing with the animations here:

- https://github.com/FANMixco/Xamarin-SearchBar/tree/master/tk.supernovaic.MaterialSearchBar/Resources/anim
- https://github.com/FANMixco/Xamarin-SearchBar/tree/master/tk.supernovaic.MaterialSearchBar/Resources/animator

Because I cannot find any other logic.

The code:

```
-keep class androidx.work.** { *; }
-keep class androidx.concurrent.** { *; }
-keep class androidx.tracing.** { *; }
-keep class androidx.paging.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class androidx.appcompat.widget.** { *; }
-keep class com.google.android.material.** { *; }
-keep class android.animation.ObjectAnimator.** { *; }
-keep class **.R
-keep class **.R$* { public static <fields>; }
-keepclassmembers class tk.supernovaic.MaterialSearchBar.* {
    <fields>;
    <init>();
    <methods>;
}
```

### Update 3:

Someone in a forum believes that the bug is here:

https://github.com/FANMixco/Xamarin-SearchBar/blob/master/tk.supernovaic.MaterialSearchBar/Resources/animator/menu_to_back_rotation.xml

But both linkers ignore these lines when I added them in the ProGuard file:

`-keep class android.animation.ObjectAnimator.** { *; }`
`-keep class android.animation.** { *; }`
`-keep class **.R$* { public static ; }`

Also, I added `--linkskip=android.animation --linkskip=tk.supernovaic.MaterialSearchBar` without any positive result.

I also tried to copy and paste the animations from my lib to my app, which didn't work. Plus, this would have been a terrible solution because my lib has considerable downloads (82 from the latest update a couple of days ago and over 3000 in total).

### Update 4:

I updated my library and app and added a new folder in the **Resources** called **raw** that contains a **keep.xml** with the following code:

    <?xml version="1.0" encoding="UTF-8" ?>
    <resources xmlns:tools="http://schemas.android.com/tools"
        tools:keep="@anim/fade_in_left,@anim/fade_in_right,@anim/fade_out,@anim/fade_out_left,@animator/back_to_menu_morph,@animator/back_to_menu_rotation,@animator/menu_to_back_morph,@animator/menu_to_back_rotation" />

And added to my ProGuard file:

    -keep class **.R
    -keepclassmembers class tk.supernovaic.MaterialSearchBar.* {
        ;
        ();
        ;
    }

All this without any positive result. The bug persists.

### Any idea why? Or what I am doing wrong?

Thanks for your support.

**P.S.:**

**I can create the package to be published, this is not my problem.**

Also, I have tested in both preview and stable versions of Visual Studio including the Windows one and it's not working. This is the one that I'm running right now:

>Visual Studio Community 2019 for Mac
>Version 8.10.6 (build 10)
>Installation UUID: 9295cc6a-682b-49ad-8980-ff4b3d4afc2c
>	GTK+ 2.24.23 (Raleigh theme)
>	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

>	Package version: 612000140

>Mono Framework MDK
>Runtime:
>	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
>	Package version: 612000140

>Roslyn (Language Service)
>3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

>NuGet
>Version: 5.9.0.7134

>.NET Core SDK
>SDK: /usr/local/share/dotnet/sdk/5.0.302/Sdks
>SDK Versions:
>	5.0.302
>	5.0.301
>	5.0.203
>	5.0.202
>	5.0.103
>	5.0.102
>	5.0.101
>	5.0.100
>	3.1.411
>	3.1.410
>	3.1.409
>	3.1.408
>	3.1.406
>	3.1.405
>	3.1.404
>	3.1.403
>	3.1.402
>	2.1.810
>	2.1.701
>MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

>.NET Core Runtime
>Runtime: /usr/local/share/dotnet/dotnet
>Runtime Versions:
>	5.0.8
>	5.0.7
>	5.0.6
>	5.0.5
>	5.0.3
>	5.0.2
>	5.0.1
>	5.0.0
>	3.1.17
>	3.1.16
>	3.1.15
>	3.1.14
>	3.1.12
>	3.1.11
>	3.1.10
>	3.1.9
>	3.1.8
>	3.1.2
>	2.1.22

>.NET Core 3.1 SDK
>SDK: 3.1.411

>Xamarin.Profiler
>Version: 1.6.12.29
>Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

>Updater
>Version: 11

>Apple Developer Tools
>Xcode 12.5.1 (18212)
>Build 12E507

>Xamarin.Mac
>Version: 7.14.0.24 (Visual Studio Community)
>Hash: c4b89cddb
>Branch: d16-10
>Build date: 2021-06-15 22:03:00-0400

>Xamarin Designer
>Version: 16.10.0.119
>Hash: 36a2d986f
>Branch: remotes/origin/d16-10
>Build date: 2021-06-02 19:41:34 UTC

>Xamarin.Android
>Version: 11.3.0.4 (Visual Studio Community)
>Commit: xamarin-android/d16-10/ae14caf
>Android SDK: /Users/fanmixco/Library/Developer/Xamarin/android-sdk-macosx
>	Supported Android versions:
>		None installed

>SDK Tools Version: 26.1.1
>SDK Platform Tools Version: 31.0.2
>SDK Build Tools Version: 30.0.2

>Build Information: 
>Mono: b4a3858
>Java.Interop: xamarin/java.interop/d16-10@f39db25
>ProGuard: Guardsquare/proguard/v7.0.1@912d149
>SQLite: xamarin/sqlite/3.35.4@85460d3
>Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

>Microsoft OpenJDK for Mobile
>Java SDK: /Users/fanmixco/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
>1.8.0-25
>Android Designer EPL code available here:
>https://github.com/xamarin/AndroidDesigner.EPL

>Android SDK Manager
>Version: 16.10.0.12
>Hash: e240b8c
>Branch: remotes/origin/d16-10
>Build date: 2021-06-01 18:26:34 UTC

>Android Device Manager
>Version: 16.10.0.14
>Hash: e340248
>Branch: remotes/origin/d16-10
>Build date: 2021-06-01 18:26:52 UTC

>Xamarin.iOS
>Version: 14.20.0.24 (Visual Studio Community)
>Hash: c4b89cddb
>Branch: d16-10
>Build date: 2021-06-15 22:03:01-0400

>Build Information
>Release ID: 810060010
>Git revision: 263d2fc9398e8092c231fa5d310cd72205cd627c
>Build date: 2021-07-08 14:37:29-04
>Build branch: release-8.10

>Operating System
>Mac OS X 10.16.0
>Darwin 20.6.0 Darwin Kernel Version 20.6.0
>    Wed Jun 23 00:26:31 PDT 2021
>    root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

  [1]: https://i.stack.imgur.com/z54BS.gif
  [2]: https://i.stack.imgur.com/CG0Ut.gif

**Comment by jonathanpeppers** [comment] 2021-07-30 16:59
Can you share a sample project that shows the issue? It seems like none of your screenshots worked.

If we could run a project where Debug has different behavior than Release, we can check what is going on.

**Comment by FANMixco** [comment] 2021-07-30 17:01
Hi @jonathanpeppers, I updated the bug and also, attached the project. The bug happens in both environments if you configure it as linking the libraries.

[B6327d7c14fbc46a597cebf8c7c8ba33a637628021245474207_LRM.zip](https://github.com/xamarin/xamarin-android/files/6909045/B6327d7c14fbc46a597cebf8c7c8ba33a637628021245474207_LRM.zip)

**Comment by FANMixco** [comment] 2021-07-30 17:05
[LRM_All.zip](https://github.com/xamarin/xamarin-android/files/6909061/LRM_All.zip)

This is another variation with everything I have said I have done :/. It just doesn't include the library because it's a binary but its Open Source:
https://github.com/FANMixco/Xamarin-SearchBar

**Comment by FANMixco** [comment] 2021-08-05 06:19
Hi @jonathanpeppers and @dellis1972, I'm wondering if the information that I provided is good enough, or am I missing something? I know that you might be busy and have other tasks and don't want to bother you.

Thanks.

**Comment by dellis1972** [comment] 2021-08-05 10:18
Would it be ok if you tried something?  Set the Linker mode in your Release config to a setting which causes the issue (SdkOnly I think). But then turn off Optimize, then see if you still have the issue? 

Looking at the behaviour of the incorrect animation you set it seems to be like its a state issue. Where the component gets into a state where it thinks it needs to show the hamburger menu when it actually should be showing the arrow. 
If this were me, I would start putting in a ton of `Android.Util.Log.Info` to see what is going on. 
I'm not familiar with the code but these seem like good places to start 

https://github.com/FANMixco/Xamarin-SearchBar/blob/master/tk.supernovaic.MaterialSearchBar/MaterialSearchBar.cs#L611
https://github.com/FANMixco/Xamarin-SearchBar/blob/master/tk.supernovaic.MaterialSearchBar/MaterialSearchBar.cs#L1081

Just so you can look at the log during a release run and see what order things are happening.

**Comment by FANMixco** [comment] 2021-08-05 10:48
Hi @dellis1972, but my question mark is the following, what should I exclude in the end? I have tried the following:

### UPDATE 1:

I modified my library and added:

`[Preserve(AllMembers = true)]`

and:

`[assembly: LinkerSafe]`

And the bug persists.

### Update 2:

I excluded each of the libraries and the bug persisted in the ProGuard file and nothing worked. I think the linker is messing with the animations here:

- https://github.com/FANMixco/Xamarin-SearchBar/tree/master/tk.supernovaic.MaterialSearchBar/Resources/anim
- https://github.com/FANMixco/Xamarin-SearchBar/tree/master/tk.supernovaic.MaterialSearchBar/Resources/animator

Because I cannot find any other logic.

### Update 3:

Someone in a forum believes that the bug is here:

https://github.com/FANMixco/Xamarin-SearchBar/blob/master/tk.supernovaic.MaterialSearchBar/Resources/animator/menu_to_back_rotation.xml

But both linkers ignore these lines when I added them in the ProGuard file:

`-keep class android.animation.ObjectAnimator.** { *; }`
`-keep class android.animation.** { *; }`
`-keep class **.R$* { public static ; }`

Also, I added `--linkskip=android.animation --linkskip=tk.supernovaic.MaterialSearchBar` without any positive result.

I also tried to copy and paste the animations from my lib to my app, which didn't work. Plus, this would have been a terrible solution because my lib has considerable downloads (82 from the latest update a couple of days ago and over 3000 in total).

### Update 4:

I updated my library and app and added a new folder in the **Resources** called **raw** that contains a **keep.xml** with the following code:

    <?xml version="1.0" encoding="UTF-8" ?>
    <resources xmlns:tools="http://schemas.android.com/tools"
        tools:keep="@anim/fade_in_left,@anim/fade_in_right,@anim/fade_out,@anim/fade_out_left,@animator/back_to_menu_morph,@animator/back_to_menu_rotation,@animator/menu_to_back_morph,@animator/menu_to_back_rotation" />

And added to my ProGuard file:

    -keep class **.R
    -keepclassmembers class tk.supernovaic.MaterialSearchBar.* {
        ;
        ();
        ;
    }

All this without any positive result. The bug persists.

And every single case when I use the linker fails, regardless if I use the full link or the SdkOnly. The situation never changed and the same happens in debug mode not only in release if I enable the linker. I agree it might confuse the linker, but how can I tell the linker that should exclude the entire library and even the animations one and still proceeds with "merging" or anything on the background ignoring the rules.

**Comment by dellis1972** [comment] 2021-08-05 11:20
Just to clarify there are two linkers in Xamarin.Android.
The Managed Linker which deals only with Managed Code only.
Then there is the android linking tool `r8` which deals with java code which is generated by our bindings as well as library imports, this is the tool which generates the final classes.dex file. 
We don't have anything which will link out the `Resources`. Our invocation of `aapt2` does not do any resource "linking" at all, so what ever you include should be in the final apk. 

The java class `android.animation.ObjectAnimator.` should not be linked out at all since it lives in the platform `android.jar` and will not be included in the final classes.dex file anyway. 

What I suggest is this. There is a tool called `dexdump` which is included in the Android SDK `build-tools/XX.X.X` folder (mine is 30.0.2).  

I would use the following command from your app directory for the working `Debug` config.

```
dexdump obj/Debug/android/bin/classes.dex | grep "Class descriptor" > debug.txt
```

Then do the same for the `Release` config which has the problem.

```
dexdump obj/Release/android/bin/classes.dex | grep "Class descriptor" > release.txt
```

Then do a diff and see what is missing between the two. Note that there will probably be ALLOT missing because the managed linker ran. Not all of which you need.  But you should see things like this

```
  Class descriptor  : 'Landroidx/core/view/ViewPropertyAnimatorCompat$ViewPropertyAnimatorListenerApi14;'
  Class descriptor  : 'Landroidx/core/view/ViewPropertyAnimatorListenerAdapter;'
  Class descriptor  : 'Landroidx/recyclerview/widget/RecyclerView$ItemAnimatorRestoreListener;'
  Class descriptor  : 'Landroidx/recyclerview/widget/SimpleItemAnimator;'
  Class descriptor  : 'Lcrc643f46942d9dd1fff9/GenericAnimatorListener;'
  Class descriptor  : 'Lmono/android/animation/AnimatorEventDispatcher;'
  Class descriptor  : 'Lmono/android/animation/Animator_AnimatorListenerImplementor;'
  Class descriptor  : 'Lmono/android/animation/Animator_AnimatorPauseListenerImplementor;'
  Class descriptor  : 'Lmono/android/animation/LayoutTransition_TransitionListenerImplementor;'
  Class descriptor  : 'Lmono/android/animation/TimeAnimator_TimeListenerImplementor;'
  Class descriptor  : 'Lmono/android/animation/ValueAnimator_AnimatorUpdateListenerImplementor;'
```

What you might be able to do is see what is missing and add those to the Proguard file bit by bit. For example if `Lmono/android/animation/AnimatorEventDispatcher;` is missing you might be able to add
`-keep class mono.android.animation.** { *; }` to see if that helps. 

If after adding everything in the `-keep` Progurd it is still not working, then the problem will be in the ManagedLinker side. But I think we should start with the `r8` linker to see if that helps first.

**Comment by FANMixco** [comment] 2021-08-05 13:43
Hi @dellis1972, I have here the 3 files:

- [debug.txt](https://github.com/xamarin/xamarin-android/files/6939016/debug.txt)
- [release.txt](https://github.com/xamarin/xamarin-android/files/6939018/release.txt)
- [differences.txt](https://github.com/xamarin/xamarin-android/files/6939017/difference3.txt)

My only guessing is when I excluded everything that didn't contain the word `anim` and I found this: `Lcrc64f9f7571c828bfc75/MaterialSearchBar_AnimatorUpdateListener`

[anim.txt](https://github.com/xamarin/xamarin-android/files/6939052/anim.txt)

How would you exclude that "library"? It gives me guessing that is related to my library because of the word **MaterialSearchBar** .

In my case, I even tried new crazy exclusions like:

```
- keep class androidx.** { *; }
```

And the bug persisted but that line gives me an idea but that's not like a common class or something I have some control over. Any idea?

**Comment by dellis1972** [comment] 2021-08-05 14:06
try this maybe?

```
-keep class crc64f9f7571c828bfc75.** {*;}
```

Proguard is not my area, so I'm not sure.

**Comment by FANMixco** [comment] 2021-08-05 14:38
I guess I'm quite wrong @dellis1972 because since both files are quite massive, I found line existed in both cases. I sorted both files and got the proper ones:

- [debug_sorted.txt](https://github.com/xamarin/xamarin-android/files/6939367/debug_sorted.txt)
- [release_sorted.txt](https://github.com/xamarin/xamarin-android/files/6939368/release_sorted.txt)
- [textcompare.pdf](https://github.com/xamarin/xamarin-android/files/6939376/textcompare.pdf)
- [unique lines in debug.txt](https://github.com/xamarin/xamarin-android/files/6939382/SeqtWm9b.txt)
- [file with the only anims from the previous file](https://github.com/xamarin/xamarin-android/files/6939449/anims.txt)


Now, the only lines that contain the word anim are the following ones:

>    Class descriptor  : 'Landroidx/appcompat/R$anim;'
>    Class descriptor  : 'Landroidx/appcompat/R$animator;'
>    Class descriptor  : 'Landroidx/constraintlayout/widget/R$anim;'
>    Class descriptor  : 'Landroidx/dynamicanimation/animation/Force;'
>    Class descriptor  : 'Landroidx/fragment/R$anim;'
>    Class descriptor  : 'Landroidx/preference/R$anim;'
>    Class descriptor  : 'Landroidx/transition/R$anim;'
>    Class descriptor  : 'Lcom/jsibbold/zoomage/R$anim;'
>    Class descriptor  : 'Lcom/miguelcatalan/materialsearchview/R$anim;'
>    Class descriptor  : 'Lcom/miguelcatalan/materialsearchview/R$animator;'
>    Class descriptor  : 'Lmono/androidx/dynamicanimation/animation/DynamicAnimation_OnAnimationEndListenerImplementor;'
>    Class descriptor  : 'Lmono/androidx/dynamicanimation/animation/DynamicAnimation_OnAnimationUpdateListenerImplementor;'
>    Class descriptor  : 'Ltk/supernovaic/themayanroute/R$anim;'
>    Class descriptor  : 'Ltk/supernovaic/themayanroute/R$animator;'

I already tried:

```
- keep class androidx.** {*;}
- keep class tk.supernovaic** {*;}
```

And both cases failed. As you could see, there is something odd that doesn't seem to be my code the wrong one.

**Comment by dellis1972** [comment] 2021-08-05 14:48
Did you try
```
- keep class mono.android.** {*;}
```

If nothing it working for the ProGuard file, then its probably the Managed Linker stripping something out that you need.

**Comment by FANMixco** [comment] 2021-08-05 14:55
Hi @dellis1972, I added it without any result and this new section looks like this:

```
-keep class androidx.** {*;}
-keep class tk.supernovaic** {*;}
-keep class mono.android.** {*;}
```

I have also added an exclusive section that is "completely ignored" (in my opinion):

<img width="729" alt="Screen Shot 2021-08-05 at 16 49 30" src="https://user-images.githubusercontent.com/1666156/128370923-99102f63-574d-40b6-a1d0-f2fa58a5f1b5.png">

That's why I believe it's a bug in the Managed Linker.

**Comment by dellis1972** [comment] 2021-08-05 17:16
Changing this line https://github.com/FANMixco/Xamarin-SearchBar/blob/master/tk.supernovaic.MaterialSearchBar/MaterialSearchBar.cs#L633 to be.

```
if (NavIcon.Drawable is AnimatedVectorDrawable a)
```

Fixes the issue. For some reason the `IAnimatable` interface is not supported after the linker is run.

**Comment by FANMixco** [comment] 2021-08-05 17:21
Hi @dellis1972, I'm going to add it, but is it still a bug to be reported, isn't it?

**Comment by dellis1972** [comment] 2021-08-05 18:40
It is still a bug, but you have a work around for now. 
We'll need to look at see why the interface is removed as part of the link step.

**Comment by dellis1972** [comment] 2021-08-05 19:15
ok. so its not a linker bug, but I understand what is happening in this case.

So the code in the MaterialSearchBar library is relying on the `AnimatedVectorDrawable` class deal with its animations. However these is no code in the library which actually uses it directly. So the type is linked out as part of the SdkOnly/Full linker step. 
The java side of the code will still exist , but all the glue on the C# side which will react to events being raised from the java side is all gone. So when you access the `NavIcon.Drawable` property you just get a `Android.Graphics.Drawable` type back which does not support `IAnimatable`, because the actual type which the java type is , doesn't exist on the C# side.

The reason why my workaround works is that is stops the type from being linked away.
So you can either use the work around I provided or add something like this to the MaterialSearchBar class

```
// Linker stuff
#pragma warning disable 0219, 0649
    static bool falseflag = false;
    static MaterialSearchBar ()
    {
        if (falseflag) {
            var ignore = new AnimatedVectorDrawable ();
        }
    }
#pragma warning restore 0219, 0649
```

as described in https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker#falseflag.

So its not a bug, its how the linker works. There isn't anything we can really fix on this side. If the code is not directly using a type, it will be removed. The code above fools the linker into thinking the type is used.

**Closed** 2021-08-06 10:01 UTC
Labels: need-info, Area: App+Library Build
