### ISSUE TITLE
Get SystemNullReferenceException after implementing ViewPager2 with Fragments

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#7201] opened 2022-07-25 17:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Get-SystemNullReferenceException-after-i/10102661)._

---
After ViewPager1 was deprecated I updated my code base to use ViewPager2 which is somewhat different than ViewPager1. I'm extending FragmentStateAdapter with ViewPager2 and can't seem to figure out why I am getting a NullReferenceException in my ViewPager2Adapter ctor when upon debug it shows that the fragment I'm passing is not null.
Any help would be appreciated. If you need to review the code I can grant access through GitHub.
There is not a lot of Visual Studio/ViewPager2/Fragments information out there. Plenty for Android Studio, but next to nothing for Visual Studio.
Please help.
![NullRefException.png](https://aka.ms/dc/image?name=Bce0c516c385d44c4ba1be88f349d8a89637943035076083238_NullRefException.png&tid=ce0c516c385d44c4ba1be88f349d8a89637943035076083238)

---
#### Feedback Bot on 7/24/2022, 10:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jonpryor** [comment] 2022-07-25 20:44
Please provide the contents of the **Copy Details** button within the Unhandled Exception dialog.  A link to a repro would also be handy.

**Comment by gmck** [comment] 2022-07-26 00:41
Steven,

With ViewPager2 you can't code your FragmentStateAdapter as you did with ViewPager. You must implement the abstract CreateFragment(int position).  Do not pass a fragment list of previously created fragments and just return fragmentList[position] as was typical with GetItem in ViewPager.

This means a new fragment will be created every time one is needed by the fragmentManager.
You also must implement ItemCount.

Something like the following

```
public YourFragmentAdapter(FragmentManager fragmentManager, Lifecycle lifecylce, int itemCount) : base(fragmentManager, lifecylce)
        {
            this.itemCount = itemCount;
        }
```
 
`public override int ItemCount => itemCount;`

```
public override Fragment CreateFragment(int position)
        {
            // Could just replace with new YourFragment1() rather than using GetInstance. Using GetInstance allows you to optionally attach a bundle and supply the parameter int position if required to the fragment.
            // All fragment constructors are required to be parameterless, as the adapter can call the constructor any time while paging during the cycle of creating and destroying the fragment.
            // Note we always create a new fragment. Do not pass a fragment list of previously created fragments and just return fragmentList[position] as was done with GetItem in ViewPager.
            // The fragmentManager is responsible for looking after the creating and destroying of the fragments as the user swipes through the pages.

            return position switch
            {
                0 => YourFragment1.NewInstance(),       
                1 => YourFragment2.NewInstance(),
                2 => YourFragment3.NewInstance(),
                _ => null,
            };
        }
```
In the fragment (in its OnViewCreated() where you create the adapter call it like the following

```
// FragmentStateAdapter
// Using the third ctor of the FragmentStateAdapter by passing this fragment's ChildFragmentManager.  Note we also pass the total number of pages/fragments that we require.

```
```
YourFragmentAdapter yourFragmentAdapter = new YourFragmentAdapter(ChildFragmentManager, ViewLifecycleOwner.Lifecycle, numberOfPages);
YourViewPager.OffscreenPageLimit = ViewPager2.OffscreenPageLimitDefault;
YourViewPager.Adapter = yourFragmentAdapter;
```

- really no different from the Android Studio examples.

**Comment by swsquire** [comment] 2022-07-26 16:17
> Please provide the contents of the **Copy Details** button within the Unhandled Exception dialog. A link to a repro would also be handy.
**Copied Details Below:**
System.NullReferenceException
  Message=Object reference not set to an instance of an object.

I also sent you an invitation.

**Comment by swsquire** [comment] 2022-07-26 16:21
> Steven,
> 
> With ViewPager2 you can't code your FragmentStateAdapter as you did with ViewPager. You must implement the abstract CreateFragment(int position). Do not pass a fragment list of previously created fragments and just return fragmentList[position] as was typical with GetItem in ViewPager.
> 
> This means a new fragment will be created every time one is needed by the fragmentManager. You also must implement ItemCount.
> 
> Something like the following
> 
> ```
> public YourFragmentAdapter(FragmentManager fragmentManager, Lifecycle lifecylce, int itemCount) : base(fragmentManager, lifecylce)
>         {
>             this.itemCount = itemCount;
>         }
> ```
> 
> `public override int ItemCount => itemCount;`
> 
> ```
> public override Fragment CreateFragment(int position)
>         {
>             // Could just replace with new YourFragment1() rather than using GetInstance. Using GetInstance allows you to optionally attach a bundle and supply the parameter int position if required to the fragment.
>             // All fragment constructors are required to be parameterless, as the adapter can call the constructor any time while paging during the cycle of creating and destroying the fragment.
>             // Note we always create a new fragment. Do not pass a fragment list of previously created fragments and just return fragmentList[position] as was done with GetItem in ViewPager.
>             // The fragmentManager is responsible for looking after the creating and destroying of the fragments as the user swipes through the pages.
> 
>             return position switch
>             {
>                 0 => YourFragment1.NewInstance(),       
>                 1 => YourFragment2.NewInstance(),
>                 2 => YourFragment3.NewInstance(),
>                 _ => null,
>             };
>         }
> ```
> 
> In the fragment (in its OnViewCreated() where you create the adapter call it like the following
> 
> ```
> // FragmentStateAdapter
> // Using the third ctor of the FragmentStateAdapter by passing this fragment's ChildFragmentManager.  Note we also pass the total number of pages/fragments that we require.
> ```
> 
> ```
> YourFragmentAdapter yourFragmentAdapter = new YourFragmentAdapter(ChildFragmentManager, ViewLifecycleOwner.Lifecycle, numberOfPages);
> YourViewPager.OffscreenPageLimit = ViewPager2.OffscreenPageLimitDefault;
> YourViewPager.Adapter = yourFragmentAdapter;
> ```
> 
> * really no different from the Android Studio examples.

Need some time to study your solution. Thanks for the input.

**Comment by jonpryor** [comment] 2022-07-26 18:05
@swsquire: thank you for the invitation.  When I built & ran your project, i did not get a `NullReferenceException`.  Instead, I get an `IllegalStateException`:

```
Java.Lang.IllegalStateException: Fragment HomeFragment{7f0e8f} (47df2894-29a0-49fe-9cbd-8a5351145035) has not been attached yet.
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00088] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12324
  at Java.Interop.JniPeerMembers+JniInstanceMethods.FinishCreateInstance (System.String constructorSignature, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0003e] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:174
  at AndroidX.ViewPager2.Adapter.FragmentStateAdapter..ctor (AndroidX.Fragment.App.Fragment fragment) [0x00071] in D:\a\1\s\generated\androidx.viewpager2.viewpager2\obj\Release\monoandroid9.0\generated\src\AndroidX.ViewPager2.Adapter.FragmentStateAdapter.cs:48
  at ExecuRideDriver.Adapter.ViewPager2Adapter..ctor (AndroidX.Fragment.App.Fragment fragment) [0x00000] in /Volumes/Xamarin-Work/src/swsquire/ExecuRideDriver/ExecuRideDriver/Adapter/ViewPager2Adapter.cs:30
  at ExecuRideDriver.MainActivity.SetupViewPager () [0x00001] in /Volumes/Xamarin-Work/src/swsquire/ExecuRideDriver/ExecuRideDriver/MainActivity.cs:72
  at ExecuRideDriver.MainActivity.ConnectViews () [0x00046] in /Volumes/Xamarin-Work/src/swsquire/ExecuRideDriver/ExecuRideDriver/MainActivity.cs:67
  at ExecuRideDriver.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0001d] in /Volumes/Xamarin-Work/src/swsquire/ExecuRideDriver/ExecuRideDriver/MainActivity.cs:48
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00010] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.App.Activity.cs:2781
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (_JniMarshal_PPL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0) [0x00005] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:121
  at at (wrapper native-to-managed) Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(intptr,intptr,intptr)
  at java.lang.IllegalStateException: Fragment HomeFragment{7f0e8f} (47df2894-29a0-49fe-9cbd-8a5351145035) has not been attached yet.
  at at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1094)
  at at androidx.viewpager2.adapter.FragmentStateAdapter.<init>(FragmentStateAdapter.java:112)
  at at crc64c6dd469e58156a88.ViewPager2Adapter.<init>(ViewPager2Adapter.java:22)
  at at crc64f97fe90df0bc04f8.MainActivity.n_onCreate(Native Method)
  at at crc64f97fe90df0bc04f8.MainActivity.onCreate(MainActivity.java:40)
  at at android.app.Activity.performCreate(Activity.java:8054)
  at at android.app.Activity.performCreate(Activity.java:8034)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loopOnce(Looper.java:201)
  at at android.os.Looper.loop(Looper.java:288)
  at at android.app.ActivityThread.main(ActivityThread.java:7870)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Presumably @gmck's [comment](https://github.com/xamarin/xamarin-android/issues/7201#issuecomment-1194827533) has a fix for the `IllegalStateException`.

---

Which brings us to the originally reported `NullReferenceException`.  My current *guess* is that this is a duplicate of issue #7085 -- a `NullReferenceException` coming from `Android.Runtime.JNINativeWrapper._unhandled_exception()` -- which was fixed in 3d5231ca3a094b85302b5dbd3cc074be37efa2c0.  *If* this is what you are experiencing, then the fix is to use [Xamarin.Android 13.0](https://docs.microsoft.com/en-us/xamarin/android/release-notes/13/13.0), currently included with Visual Studio 17.3 Previews, and will be stable "soon-ish".

**Comment by gmck** [comment] 2022-07-26 23:33
@swsquire 
I took a look at your app and I'm a little confused about what you are actually trying to do. I'm wondering if you even need a ViewPager2. Am I right in assuming that your BottomNavigationView's items are the equivalent of the 4 fragments you have in the project? If so then you don't need a ViewPager, as the BottomNavView could handle those fragments.

As I mentioned yesterday you can't do what your code is trying to do because you'll get that illegalStateException from OnGetLayoutInflater because your fragment is not attached at that point.

Can you please confirm what you are attempting?

**Comment by swsquire** [comment] 2022-07-28 16:33
> @swsquire I took a look at your app and I'm a little confused about what you are actually trying to do. I'm wondering if you even need a ViewPager2. Am I right in assuming that your BottomNavigationView's items are the equivalent of the 4 fragments you have in the project? If so then you don't need a ViewPager, as the BottomNavView could handle those fragments.
> 
> As I mentioned yesterday you can't do what your code is trying to do because you'll get that illegalStateException from OnGetLayoutInflater because your fragment is not attached at that point.
> 
> Can you please confirm what you are attempting?

You are correct @gmck. The reason I'm using ViewPager2 is because I want the Fragments associated with BottomNavigationView to be swipeable horizontally. Plus I wanted to learn how to incorporate ViewPager2 in my code since ViewPager1 was deprecated. Almost all information on Google and YouTube is based on Android Studio and not Visual Studio 2022. I figured if I got this done, I'd be able to help someone else in the long run.

**Comment by swsquire** [comment] 2022-07-28 16:46
> @swsquire: thank you for the invitation. When I built & ran your project, i did not get a `NullReferenceException`. Instead, I get an `IllegalStateException`:
> 
> ```
> Java.Lang.IllegalStateException: Fragment HomeFragment{7f0e8f} (47df2894-29a0-49fe-9cbd-8a5351145035) has not been attached yet.
>   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00088] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12324
>   at Java.Interop.JniPeerMembers+JniInstanceMethods.FinishCreateInstance (System.String constructorSignature, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0003e] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:174
>   at AndroidX.ViewPager2.Adapter.FragmentStateAdapter..ctor (AndroidX.Fragment.App.Fragment fragment) [0x00071] in D:\a\1\s\generated\androidx.viewpager2.viewpager2\obj\Release\monoandroid9.0\generated\src\AndroidX.ViewPager2.Adapter.FragmentStateAdapter.cs:48
>   at ExecuRideDriver.Adapter.ViewPager2Adapter..ctor (AndroidX.Fragment.App.Fragment fragment) [0x00000] in /Volumes/Xamarin-Work/src/swsquire/ExecuRideDriver/ExecuRideDriver/Adapter/ViewPager2Adapter.cs:30
>   at ExecuRideDriver.MainActivity.SetupViewPager () [0x00001] in /Volumes/Xamarin-Work/src/swsquire/ExecuRideDriver/ExecuRideDriver/MainActivity.cs:72
>   at ExecuRideDriver.MainActivity.ConnectViews () [0x00046] in /Volumes/Xamarin-Work/src/swsquire/ExecuRideDriver/ExecuRideDriver/MainActivity.cs:67
>   at ExecuRideDriver.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0001d] in /Volumes/Xamarin-Work/src/swsquire/ExecuRideDriver/ExecuRideDriver/MainActivity.cs:48
>   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00010] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.App.Activity.cs:2781
>   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (_JniMarshal_PPL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0) [0x00005] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:121
>   at at (wrapper native-to-managed) Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(intptr,intptr,intptr)
>   at java.lang.IllegalStateException: Fragment HomeFragment{7f0e8f} (47df2894-29a0-49fe-9cbd-8a5351145035) has not been attached yet.
>   at at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1094)
>   at at androidx.viewpager2.adapter.FragmentStateAdapter.<init>(FragmentStateAdapter.java:112)
>   at at crc64c6dd469e58156a88.ViewPager2Adapter.<init>(ViewPager2Adapter.java:22)
>   at at crc64f97fe90df0bc04f8.MainActivity.n_onCreate(Native Method)
>   at at crc64f97fe90df0bc04f8.MainActivity.onCreate(MainActivity.java:40)
>   at at android.app.Activity.performCreate(Activity.java:8054)
>   at at android.app.Activity.performCreate(Activity.java:8034)
>   at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
>   at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
>   at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
>   at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
>   at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>   at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>   at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
>   at at android.os.Handler.dispatchMessage(Handler.java:106)
>   at at android.os.Looper.loopOnce(Looper.java:201)
>   at at android.os.Looper.loop(Looper.java:288)
>   at at android.app.ActivityThread.main(ActivityThread.java:7870)
>   at at java.lang.reflect.Method.invoke(Native Method)
>   at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>   at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> ```
> 
> Presumably @gmck's [comment](https://github.com/xamarin/xamarin-android/issues/7201#issuecomment-1194827533) has a fix for the `IllegalStateException`.
> 
> Which brings us to the originally reported `NullReferenceException`. My current _guess_ is that this is a duplicate of issue #7085 -- a `NullReferenceException` coming from `Android.Runtime.JNINativeWrapper._unhandled_exception()` -- which was fixed in [3d5231c](https://github.com/xamarin/xamarin-android/commit/3d5231ca3a094b85302b5dbd3cc074be37efa2c0). _If_ this is what you are experiencing, then the fix is to use [Xamarin.Android 13.0](https://docs.microsoft.com/en-us/xamarin/android/release-notes/13/13.0), currently included with Visual Studio 17.3 Previews, and will be stable "soon-ish".

Thx @jonpryor - Will keep this in mind.

**Comment by gmck** [comment] 2022-07-29 00:19
@swsquire 

_I'm using ViewPager2 is because I want the Fragments associated with BottomNavigationView to be swipeable horizontally._ 

Ok, understand. Then what I said above applies.

When you click on one of your bottomNav items, you need to open another fragment - let's call it your HomePagerFragment being your first item in your bottomNav. The layout for that will contain the viewpager and potentially a tablayout if you want to display dots to indicate which page is active. It would look like the following, just a viewpager2 and the tablayout

```
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.viewpager2.widget.ViewPager2
        android:id="@+id/dashboard_viewpager"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toTopOf="@+id/tablayout"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <com.google.android.material.tabs.TabLayout
        android:id="@+id/tablayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:tabBackground="@drawable/tab_selector"
        app:tabGravity="center"
        app:tabIndicatorHeight="0dp"/>

</androidx.constraintlayout.widget.ConstraintLayout>
```

It is from this fragment that you setup your ViewPager2 and TabLayout after you have inflated it in OnCreateView. You then have access to the viewpager and the tablayout, and in the OnViewCreated you can then create your HomeFragmentAdapter

HomeFragmentAdapter homeFragmentAdapter = new HomeFragmentAdapter(ChildFragmentManager, ViewLifecycleOwner.Lifecycle, numberOfPages);
            
homeViewPager.OffscreenPageLimit = ViewPager2.OffscreenPageLimitDefault;
homeViewPager.Adapter = homeFragmentAdapter;
 
The HomeFragmentAdapter is the same as what I posted earlier. Since you have now provided a CreateFragment method Android will automatically create each fragment as required as you scroll through your fragments. What you decide to put in each fragment is up to you.

If your bottomNavView is contained in an Activity, then I think you need to use the second constructor of FragmentStateAdapter. I haven't done that so I can't confirm.

I've made a series of tutorials on the NavigationComponent (NavigationGraph 1,2,3 and 5) at https://github.com/gmck, so I try and add a new one that demonstrates using viewPager2.

In the meantime, there are examples at https://github.com/android/views-widgets-samples, that demonstrate ViewPager2. Ok, you need Android Studio, but they aren't hard to convert to C# and will work exactly the same.

**Comment by swsquire** [comment] 2022-07-29 22:47
> @swsquire
> 
> _I'm using ViewPager2 is because I want the Fragments associated with BottomNavigationView to be swipeable horizontally._
> 
> Ok, understand. Then what I said above applies.
> 
> When you click on one of your bottomNav items, you need to open another fragment - let's call it your HomePagerFragment being your first item in your bottomNav. The layout for that will contain the viewpager and potentially a tablayout if you want to display dots to indicate which page is active. It would look like the following, just a viewpager2 and the tablayout
> 
> ```
> <androidx.constraintlayout.widget.ConstraintLayout
>     xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:app="http://schemas.android.com/apk/res-auto"
>     xmlns:tools="http://schemas.android.com/tools"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent">
> 
>     <androidx.viewpager2.widget.ViewPager2
>         android:id="@+id/dashboard_viewpager"
>         android:layout_width="0dp"
>         android:layout_height="0dp"
>         app:layout_constraintBottom_toTopOf="@+id/tablayout"
>         app:layout_constraintEnd_toEndOf="parent"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintTop_toTopOf="parent" />
> 
>     <com.google.android.material.tabs.TabLayout
>         android:id="@+id/tablayout"
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:layout_gravity="bottom"
>         app:layout_constraintBottom_toBottomOf="parent"
>         app:layout_constraintEnd_toEndOf="parent"
>         app:layout_constraintStart_toStartOf="parent"
>         app:tabBackground="@drawable/tab_selector"
>         app:tabGravity="center"
>         app:tabIndicatorHeight="0dp"/>
> 
> </androidx.constraintlayout.widget.ConstraintLayout>
> ```
> 
> It is from this fragment that you setup your ViewPager2 and TabLayout after you have inflated it in OnCreateView. You then have access to the viewpager and the tablayout, and in the OnViewCreated you can then create your HomeFragmentAdapter
> 
> HomeFragmentAdapter homeFragmentAdapter = new HomeFragmentAdapter(ChildFragmentManager, ViewLifecycleOwner.Lifecycle, numberOfPages);
> 
> homeViewPager.OffscreenPageLimit = ViewPager2.OffscreenPageLimitDefault; homeViewPager.Adapter = homeFragmentAdapter;
> 
> The HomeFragmentAdapter is the same as what I posted earlier. Since you have now provided a CreateFragment method Android will automatically create each fragment as required as you scroll through your fragments. What you decide to put in each fragment is up to you.
> 
> If your bottomNavView is contained in an Activity, then I think you need to use the second constructor of FragmentStateAdapter. I haven't done that so I can't confirm.
> 
> I've made a series of tutorials on the NavigationComponent (NavigationGraph 1,2,3 and 5) at https://github.com/gmck, so I try and add a new one that demonstrates using viewPager2.
> 
> In the meantime, there are examples at https://github.com/android/views-widgets-samples, that demonstrate ViewPager2. Ok, you need Android Studio, but they aren't hard to convert to C# and will work exactly the same.

Thanks @gmck this is my project for the weekend! Greatly appreciated!

**Comment by swsquire** [comment] 2022-08-07 22:22
@gmck,
One last question - where does homeViewPager get initialized to point to the HomeFragment created using CreateFragment in the Adapter?

**Comment by gmck** [comment] 2022-08-08 07:55
I'm not sure about your question and whether I'm understanding it, so I'll attempt to answer it in another way that hopefully makes sense to you.

The fragment that contains the ViewPager2 doesn't really know anything about the fragments the ViewPager2's is going to show. It is just a holding or container fragment. In other words, if you look at its layout it only contains the ViewPager2. No info about any fragments. However, in its OnViewCreated, it creates the FragmentStateAdapter which will control the number of fragments. All the holding fragment needs to know is how many fragments the ViewPager2 (ItemCount) will contain. The viewPager2 created in the holding or container fragment then gets assigned it's FragmentStateAdapter via holdingFragment.Adapter =   homeFragmentAdapter. So it probably would make it less confusing if you changed the name of your adapter to something other than "home". Could just change it to HoldingPagerFragment and HolderPagerStateAdapter.  
 
I think I may have confused you in my original post when I referred to HomePagerFragment and you implied that the holding fragment is the HomeFragment. 

So the answer to your question is "it doesn't".

I haven't had time yet to add to the NavigationGraph examples. Have you checked them out yet? Because I could suggest where you could add a viewpager2 to the NavigationGraph5 example.

**Comment by gmck** [comment] 2022-08-08 08:28
@swsquire 

I forgot to hit the submit button when I wrote the above comment early this morning. In the meantime, I thought it may be easier if I just went ahead and started modifying NavigationGraph5, so that it includes a viewpager2.

It is not finished as far as publishing on github, but I've now modified the project to include 3 fragments in a viewpager2 which are viewable when you tap the Leaderboard fragment. I'd be happy to send it to you as is but don't want to publically publish it here now, as it will eventually become a new project NavigationGraph6. Could you please contact me by email and I'll zip it up and send it to you?

**Comment by swsquire** [comment] 2022-08-08 11:41
@gmck - I got it working by moving your code example from my HomeFragment.cs file to the MainActivity.cs. The MainActivity has the ViewPager2 definition in the activity_main.xml so my ViewPager2 variable isn't null there. That's what the issue was.

**Comment by gmck** [comment] 2022-08-08 22:56
@swsquire - great - you got it sorted!!

**Comment by jpobst** [comment] 2022-08-11 18:10
Sounds like this is all good now.  Thanks to everyone who helped find a solution!

**Closed by jpobst** 2022-08-11 18:10 UTC
