### ISSUE TITLE
http request failed on android10 devices with wifi network specifier api use.

### ISSUE THREAD

**Issue by chaiyasitr** [xamarin/xamarin-android#4368] opened 2020-03-08 05:34 UTC
### Steps to Reproduce

1. On Android10 physical device using WiFi network specifier API to connect specified device AP SSID name and Password (no internet device) with below code.
```
var specifier = new WifiNetworkSpecifier.Builder()
  .SetSsid(sSID)
  .SetWpa2Passphrase(pAssword)
  .Build();
var request = new NetworkRequest.Builder()
  .AddTransportType(TransportType.Wifi)
  .SetNetworkSpecifier(specifier)
  .Build();
connectivityManager.RequestNetwork(request, _callback);
```
2. Request http to the step1 connected device with below code.
```
var uri = new Uri("https://192.168.1.1/info");
var client = newHttpClient();
client.MaxResponseContentBufferSize = 256000;
client.DefaultRequestHeaders.Accept.Add(newSystem.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
var response = awaitclient.GetAsync(uri);
```

### Expected Behavior
Step1: 
Android10 device shall connect to requested host network after user accept.

Step2:
http request to connected device shall be can request as normal without any problem.

### Actual Behavior
Step1: 
After user accept, Android10 device can connect to requested host network without any problem (on Android10 wifi connecting information we can see correct connected SSID name).

Step2: 
http request always fail with timeout exception. 

**On the other hand if we are replace step1 with Android manual wifi connecting setting (not use wifi network specifier api to connect), the http request on step2 is worked fine every times.**

### Version Information
=== Visual Studio Professional 2019 for Mac ===

Version 8.4.8 (build 2)
Installation UUID: 74423ffd-5aab-4531-a6ed-8e2d4c72e6e5
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000166

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.166 (2019-08/d9001b5ae70) (64-bit)
	Package version: 606000166

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.102/Sdks
SDK Versions:
	3.1.102
	3.1.101
	3.0.101
	3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.0.1
	3.0.0
	2.1.15
	2.1.14
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Mac ===

Version: 6.10.0.21 (Visual Studio Professional)
Hash: 02c4b3bdc
Branch: xcode11.3
Build date: 2020-02-18 14:13:31-0500

=== Xamarin.iOS ===

Version: 13.10.0.21 (Visual Studio Professional)
Hash: 02c4b3bdc
Branch: xcode11.3
Build date: 2020-02-18 14:13:32-0500

=== Xamarin Designer ===

Version: 16.4.0.479
Hash: 074544417
Branch: remotes/origin/d16-4
Build date: 2020-01-22 22:50:22 UTC

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Professional)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/tctcracwifi/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/tctcracwifi/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.10
Hash: 2c49a7d
Branch: remotes/origin/d16-4
Build date: 2020-02-20 19:25:52 UTC

=== Android Device Manager ===

Version: 16.4.0.32
Hash: 7a5cb8b
Branch: remotes/origin/d16-4
Build date: 2020-02-20 19:26:14 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 804080002
Git revision: 4f35aa7e44fb398379e512d0bfd6f8df8d34b5ac
Build date: 2020-02-27 16:16:52+00
Build branch: release-8.4
Xamarin extensions: 4f35aa7e44fb398379e512d0bfd6f8df8d34b5ac

=== Operating System ===

Mac OS X 10.15.3
Darwin 19.3.0 Darwin Kernel Version 19.3.0
    Thu Jan  9 20:58:23 PST 2020
    root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

### Log File

[Log4368.txt](https://github.com/xamarin/xamarin-android/files/4304444/Log4368.txt)

**Comment by grendello** [comment] 2020-03-09 19:53
@chaiyasitr Since you're using `HttpClient`, this is not likely a Xamarin.Android issue but Mono's BCL. However, I looked at your log and spotted this fragment:

```
03-09 09:22:58.849   790  1622 I netd    : interfaceSetMtu("wlan0", 1500) <0.13ms>
03-09 09:22:58.849  3094  3170 I QCNEJ/CndHalConnector: -> SND notifyWifiStatusChanged(RatInfo{type=1, subType=101, state=CONNECTING, v4=IfaceAddrPair{iface=, addr=}, v6=IfaceAddrPair{iface=, addr=}, timestamp=2020-03-09 09:22:58.849, isAndroidValidated=false, netHandle=995543142413, slotIdx=0} WifiInfo{freq=TWO_GHz, state=3, ssid=AC123456, bssid=50:5b:c2:20:ad:73, dns=[0.0.0.0, 0.0.0.0, 0.0.0.0, 0.0.0.0, ]})
03-09 09:22:58.849   790  1622 E Netd    : no such netId 232
03-09 09:22:58.849   790  1622 I netd    : networkAddRoute(232, "wlan0", "192.168.1.0/24", "") -> ServiceSpecificException(64, "Machine is not on the network") <0.02ms>
03-09 09:22:58.849  3094  3170 I QCNEJ/CndHalConnector: -> SND notifyRatConnectionStatusChanged(rat = 1, CONNECTING, v4 = , v6 = )
03-09 09:22:58.849  1288  2734 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: android.os.ServiceSpecificException: Machine is not on the network (code 64)
03-09 09:22:58.849   790  1622 E Netd    : no such netId 232
03-09 09:22:58.849   790  1622 I netd    : networkAddRoute(232, "wlan0", "0.0.0.0/0", "192.168.1.1") -> ServiceSpecificException(64, "Machine is not on the network") <0.01ms>
03-09 09:22:58.850  1288  2734 E ConnectivityService: Exception in addRoute for gateway: java.lang.IllegalStateException: android.os.ServiceSpecificException: Machine is not on the network (code 64)
03-09 09:22:58.851   790  1622 W ServiceManager: Permission failure: android.permission.NETWORK_STACK from uid=1073 pid=3020
03-09 09:22:58.851   790  1622 I netd    : interfaceSetCfg() <0.80ms>
```

It seems that the Android system doesn't consider the network broadcast (`192.168.1.0`) nor the likely router (`192.168.1.1`) to be on the wlan network you're connected to. Trying to access `192.168.1.2` with thus misconfigured network won't work. My guess is that the issue lies in the way you configure the network, which is also most likely beyond the scope of Xamarin.Android. I will assign this issue to the Mono team and mark as `need-info` - please test your connection code once more (perhaps also try to write an equivalent code fragment in Kotlin or Java to see if it works in a "native" Android app) and let us know about your findings. If you still continue to have problems, please create a small repro app and attach it zipped here, so that we can just build and run it ourselves. Thanks!

**Comment by grendello** [comment] 2020-03-11 08:19
Corresponding developer community issue: https://developercommunity.visualstudio.com/content/problem/942161/http-request-failed-on-android10-devices-with-wifi.html

**Comment by chaiyasitr** [comment] 2020-03-11 08:50
@grendello 
Thank you for your support.

As my reported,

> On the other hand if we are replace step1 with Android manual wifi connecting setting (not use wifi network specifier api to connect), the http request on step2 is worked fine every times.

I'm back to investigate what the difference from using api and found that during manual wifi connecting setting, android is popup to ask user for accept the "no internet network" at this step if we are not accept it the http request result is failed same as using api to connected.
I'm quite sure that this is not coming from  Xamarin.Android or Mono's BCL issue.


regards,

**Comment by grendello** [comment] 2020-03-11 09:29
Yes, it's unlikely that it's caused by anything in XA or Mono BCL. There must be some step (or steps) missing in the path currently leading to the failure. The reason why I assigned this issue to @steveisok and marked as being in Mono runtime/BCL is that `HttpClient` is 100% on the Mono side. Let's keep the issues open and wait for your investigation to conclude.

**Closed** 2020-04-15 18:56 UTC
Labels: Area: Mono Runtime, need-info
