### ISSUE TITLE
Please fix "Could not AOT the assembly: Google.ZXing.Core.dll"

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/xamarin-android#5994] opened 2021-06-04 11:31 UTC
Hi.

I am using the https://www.nuget.org/packages/Xamarin.Facebook.Android package and it pulls in Google.ZXing.Core as a dependency. Merely having it in a project prevents AOT + LLVM from working, as the build fails while deploying to device with the error: /`Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1961,3): error XA3001: Could not AOT the assembly: Google.ZXing.Core.dll`.

This is a duplicate of https://github.com/xamarin/xamarin-android/issues/5779, but as it prevents one from using AOT + LLVM if Facebook is used it is pretty much a showstopper for me, and there doesn't seem to be any action in said issue report. This report is an attempt to draw attention to that report, so please close this issue and either provide a workaround or a fix in https://github.com/xamarin/xamarin-android/issues/5779. Any kind of communication would be greatly appreciated.

Thank you.

**Comment by dellis1972** [comment] 2021-06-04 11:56
This is likely a duplicate of #5964 or #5764. 

The former (#5964) has a fix via #5979 which we are hoping will go out in the next d16.10 Service Release.

The latter #5764 see that in that case the Assembly being AOT'd has invalid IL in it which is breaking the compiler. See https://github.com/xamarin/xamarin-android/issues/5764#issuecomment-854339293. As yet we don't know what to do about that one. 

I am going to close this issue as a duplicate since we are tracking all the bug reports on #5964 or #5764.

**Closed by dellis1972** 2021-06-04 11:56 UTC
Labels: Area: App+Library Build, duplicate, needs-triage
