### ISSUE TITLE
Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.

### ISSUE THREAD

**Issue by acaliaro** [xamarin/xamarin-android#1742] opened 2018-05-29 15:36 UTC
### Steps to Reproduce

1. Upload a large `byte[]` with `MultipartFormDataContent`
2. HTTP and SSL settings are all set to `Default`

Reproduction test case: https://github.com/jonathanpeppers/HttpClientRepro

### Expected Behavior

The web request succeeds.

### Actual Behavior

Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.

  at System.Net.WebConnectionStream.EndWrite (System.IAsyncResult r) [0x000b8] in <5a97d41d36694fb19855c17429527b10>:0 
  at System.IO.Stream+<>c.<BeginEndWriteAsync>b__53_1 (System.IO.Stream stream, System.IAsyncResult asyncResult) [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[TResult,TInstance].Complete (TInstance thisRef, System.Func`3[T1,T2,TResult] endMethod, System.IAsyncResult asyncResult, System.Boolean requiresSynchronization) [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Net.Http.MultipartContent+<SerializeToStreamAsync>d__8.MoveNext () [0x0025d] in <996a681f30a44cd685a4da54e11956e2>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0036e] in <996a681f30a44cd685a4da54e11956e2>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__49.MoveNext () [0x000ca] in <996a681f30a44cd685a4da54e11956e2>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at BeltrameClassificazioneRottami.Utilities.Http+<RankingUploadAsync>d__26.MoveNext () [0x00185] in /Users/alessandrocaliaro/Projects/Soluzione1/afv-app-classificazione-rottami/BeltrameClassificazioneRottami/Utilities/Http.cs:178 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at BeltrameClassificazioneRottami.Activities.MenuClassificazioneActivity+<<OnCreate>b__15_5>d.MoveNext () [0x002cd] in /Users/alessandrocaliaro/Projects/Soluzione1/afv-app-classificazione-rottami/BeltrameClassificazioneRottami/Activities/MenuClassificazioneActivity.cs:317 
### Version Information

=== Visual Studio Community 2017 for Mac ===

Version 7.5.1 (build 22)
Installation UUID: e9c85728-289a-4de3-8442-d551ea358311
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010047

=== NuGet ===

Versione: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Versioni runtime:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
Versioni SDK:
	2.1.4
	2.0.0
	1.0.3
SDK di MSBuild: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Versione: 1.6.2
Percorso: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

A valid Xcode installation was not found at the configured location: '/Applications/Xcode.app'

=== Xamarin.Mac ===

Version: 4.4.1.178 (Visual Studio Community)

=== Xamarin.Android ===

Versione: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/alessandrocaliaro/Library/Developer/Xamarin/android-sdk-macosx
	Versione di Android supportate:
		4.4 (livello API 19)
		5.0 (livello API 21)
		5.1 (livello API 22)
		6.0 (livello API 23)
		7.0 (livello API 24)
		7.1 (livello API 25)
		8.0 (livello API 26)
		8.1 (livello API 27)

Versione di SDK Tools: 25.2.5
Versione degli strumenti della piattaforma SDK: 27.0.1
Versione degli strumenti di compilazione SDK: 25.0.3

Java SDK: /usr
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Il codice EPL di Android Designer è disponibile qui:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 11.10.1.178 (Visual Studio Community)
Hash: 408d3574
Branch: d15-7
Build date: 2018-05-08 18:56:30-0400

=== Build Information ===

Release ID: 705010022
Git revision: 60442dd643a20c7a4ae1f8705b8d1de8972eee78
Build date: 2018-05-15 01:43:39+00
Xamarin addins: 4194ffe4868321e4c3477bd56aed579bda4c6fbb

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

EMDK for Xamarin 2.7.0.98
Internet of Things (IoT) development (Preview) 7.1

**Comment by jonathanpeppers** [comment] 2018-05-29 21:04
Hi @acaliaro can you post a snippet of your C# code that is not working? What project settings do you have under `Advanced | HttpClient Implementation` and `Advanced | SSL/TLS implementation`?

If there is a way you could make a reproduction project that would be great as well, including a sample video that shows the problem?

**Comment by acaliaro** [comment] 2018-05-29 21:32
This is the class I use.
There is some other code (tell me if you need it) but it is not important... I call the method with

`RankingUploadResponse rankingUploadResponse = await Http.GetInstance().RankingUploadAsync(Globali.GetInstance().Login, Utility.GetCurrentTruck(Globali.GetInstance().TruckDetails));`


```
using Android;
using Android.App;
using Android.Content;
using BeltrameClassificazioneRottami.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace BeltrameClassificazioneRottami.Utilities
{
    public class Http
    {
        static Http http = new Http();


        readonly HttpClient _httpClient = new HttpClient();

        const string BASE_URL = "http://0.000.147.10/api/";
        const string CONTEXT = "";

        const string RANKINGUPLOAD_URL = "ranking/upload";

        const int TIMEOUT = 200;
        const bool FAST = true;


        public static Http GetInstance()
        {
            return http; 
        }

        public async Task<RankingUploadResponse> RankingUploadAsync(Login login, TruckDetail truckDetail)
        {

            MultipartFormDataContent multipartFormDataContent = new MultipartFormDataContent();
            multipartFormDataContent.Add(new StringContent(truckDetail.Prscau.ToString()), "PRSCAU");
            multipartFormDataContent.Add(new StringContent(truckDetail.Prscam.ToString()), "PRSCAM");

            int countPhoto = Utility.CountPhoto(truckDetail);
            int countVideo = Utility.CountVideo(truckDetail);

            if(countPhoto > 0){
                // Prendo le photo
                string pathPhoto = Utility.GetPathPhoto(truckDetail);

                multipartFormDataContent = prepareForm(multipartFormDataContent, pathPhoto);
            }

            if(countVideo > 0)
            {
                // Prendo il video
                string pathVideo = Utility.GetPathVideo(truckDetail);

                multipartFormDataContent = prepareForm(multipartFormDataContent, pathVideo);

            }

            _httpClient.DefaultRequestHeaders.Authorization = authenticationHeaderValue("bearer", login.Token);



           /* This is the row that thrown exception */
            HttpResponseMessage httpResponseMessage = await  _httpClient.PostAsync(createUrl(RANKINGUPLOAD_URL, false), multipartFormDataContent);
            return await readStreamAndDeserialize<RankingUploadResponse>(httpResponseMessage);
        }

        MultipartFormDataContent prepareForm(MultipartFormDataContent multipartFormDataContent, string path)
        {
        


            string[] files = Directory.GetFiles(path, "*.*");
            foreach (string file in files)
            {
                byte[] imagebytearraystring = ImageFileToByteArray(file);
                string name = Path.GetFileName(file);
                string fileName = name;
                multipartFormDataContent.Add(new ByteArrayContent(imagebytearraystring, 0, imagebytearraystring.Length), "Files", fileName);

            }

            return multipartFormDataContent;
        
        }

        private byte[] ImageFileToByteArray(string fullFilePath)
        {
            FileStream fs = File.OpenRead(fullFilePath);
            byte[] bytes = new byte[fs.Length];
            fs.Read(bytes, 0, Convert.ToInt32(fs.Length));
            fs.Close();
            return bytes;
        }

        async Task<String> readStream(HttpResponseMessage response)
        {
            if (response.IsSuccessStatusCode)
            {
                using (var stream = await response.Content.ReadAsStreamAsync())
                using (var reader = new StreamReader(stream))
                {
                    string text = reader.ReadToEnd();
                    Debug.WriteLine("RECEIVED: " + text);
                    return text;

                }
            }

            return null;
        }

        AuthenticationHeaderValue authenticationHeaderValue(String type, String token)
        {
            return new AuthenticationHeaderValue(type, token);
        }

        async Task<T> readStreamAndDeserialize<T>(HttpResponseMessage response) where T : new()
        {

            if (response.IsSuccessStatusCode)
            {
                using (var stream = await response.Content.ReadAsStreamAsync())
                using (var reader = new StreamReader(stream))
                {
                    if (FAST)
                    {
                        using (var json = new JsonTextReader(reader))
                        {
                            return deserialize<T>(json);
                        }
                    }
                    else {
                        string text = reader.ReadToEnd();
                        Debug.WriteLine("RECEIVED: " + text);
                        return JsonConvert.DeserializeObject<T>(text);
                    }
                }
            }

            throw new Exception(String.Format( Application.Context.GetString(BeltrameClassificazioneRottami.Resource.String.EccezioneHttp), response.RequestMessage.RequestUri.PathAndQuery, response.StatusCode, response.ReasonPhrase.ToString()));

            //return default(T);
        }

        T deserialize<T>(JsonTextReader json) where T : new()
        {
            return new JsonSerializer().Deserialize<T>(json);
        }

        Uri createUri(String url, bool addContext)
        {
            return new Uri( createUrl(url, addContext));
        }

        string createUrl(String url, bool addContext)
        {
            return String.Format("{0}{1}{2}", BASE_URL,addContext ? CONTEXT : "", url);
        }

        StringContent createStringContent(object oggetto)
        {
            return new StringContent(JsonConvert.SerializeObject(oggetto), Encoding.UTF8, "application/json");
        }

    }
}

```

**Comment by jonathanpeppers** [comment] 2018-05-29 21:58
@acaliaro sorry the setting in VS for Mac is under `Project Options | Android Build | General` at the bottom.

VS for Windows there is an `Advanced` button in `Android Options` that pops a dialog with these settings.

**Comment by acaliaro** [comment] 2018-05-29 22:03
<img width="900" alt="screenshot 2018-05-30 00 03 24" src="https://user-images.githubusercontent.com/5759350/40688033-ec698f1c-639c-11e8-8ed5-b786333c8d40.png">

**Comment by jonathanpeppers** [comment] 2018-05-30 04:52
@acaliaro how large is this video file in bytes?

Have you tried using `StreamContent` instead of `ByteArrayContent`? Then you can remove the `ImageFileToByteArray` method and just do something like:

```csharp
multipartFormDataContent.Add (new StreamContent (File.OpenRead (path)), "Files", Path.GetFileName (path));
```

It is always more performant to stick with `Stream` throughout an HTTP request and not ever convert to a `byte[]` unless you absolutely have to.

**Comment by acaliaro** [comment] 2018-05-30 05:54
same problem... Size is 31,65 MB

**Comment by acaliaro** [comment] 2018-05-30 15:05
sometimes I receive this (with my app, not with yours)
  
at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <996a681f30a44cd685a4da54e11956e2>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__49.MoveNext () [0x000ca] in <996a681f30a44cd685a4da54e11956e2>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at BeltrameClassificazioneRottami.Utilities.Http+<RankingUploadAsync>d__25.MoveNext () [0x00185] in /Users/alessandrocaliaro/Projects/Soluzione1/afv-app-classificazione-rottami/BeltrameClassificazioneRottami/Utilities/Http.cs:172 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at BeltrameClassificazioneRottami.Activities.MenuClassificazioneActivity+<<OnCreate>b__15_5>d.MoveNext () [0x002cd] in /Users/alessandrocaliaro/Projects/Soluzione1/afv-app-classificazione-rottami/BeltrameClassificazioneRottami/Activities/MenuClassificazioneActivity.cs:319

**Comment by jonathanpeppers** [comment] 2018-05-30 15:50
@acaliaro does your app work properly if you make it send the request to `http://httpbin.org/anything`?

Docs here on that server: http://httpbin.org/#/Anything

If it is only happening with your server, you will need to compare the HTTP traffic using [Fiddler (Windows)](https://www.telerik.com/fiddler) or [CharlesProxy (Mac)](https://www.charlesproxy.com/). There might be a redirect, header, or something happening causing it to break

**Comment by acaliaro** [comment] 2018-05-30 16:05
I try and let you know.

**Comment by acaliaro** [comment] 2018-06-01 11:42
@jonathanpeppers it seems to be a IIS configuration problem. Now it should works. Do I have to close this issue or do you keep open ?

**Comment by jonathanpeppers** [comment] 2018-06-01 13:28
I'll close this for now, I think my emulator was messed up the other day (I have been upgrading/uninstalling VS/testing Hyper-V emulator).

**Closed by jonathanpeppers** 2018-06-01 13:28 UTC
Labels: Area: App Runtime, bug

**Comment by vyfster** [comment] 2018-07-15 06:22
I think this is a bug and is still an issue.  I have a test Xamarin.Forms project that reproduces this issue.  The problem is that the server returns `HTTP Status Code 413 - Payload too large`.  I'm using nginx as the http server (actually as a reverse proxy).  An exception is thrown regardless of whether the Default, Managed or the Android HttpClient is used.  

Error message when using the Default HttpClient

`System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.`

Error message when using the Android HttpClient

`Java.Net.SocketException: sendto failed: EPIPE (Broken pipe)`

Error message when using the Managed HttpClient (I thought this would be the same as default, but I get a different error message and once I get this error message I don't seem to get the 'Disposed object' error again.

`System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.IO.IOException: Error writing request ---> System.Net.Sockets.SocketException: The socket has been shut down`

I've attached the stack traces I received in the log while debugging this issue.

Let me know if you would like to use the test project I created that reproduces this issue.

[android.httpclient.stack-trace.txt](https://github.com/xamarin/xamarin-android/files/2195500/android.httpclient.stack-trace.txt)
[default.httpclient.stack-trace.txt](https://github.com/xamarin/xamarin-android/files/2195501/default.httpclient.stack-trace.txt)
[managed.httpclient.stack-trace.txt](https://github.com/xamarin/xamarin-android/files/2195502/managed.httpclient.stack-trace.txt)

**Comment by jonathanpeppers** [comment] 2018-07-15 15:18
Hi @vyfster ,

> the server returns HTTP Status Code 413 - Payload too large

If your server is returning a bad HTTP status, there is nothing your client (or Xamarin) can do to make the request successful. Perhaps Xamarin (or likely Mono) can improve the error message you are getting, but it won't be able to solve your issue.

HTTP servers generally have some kind of "maximum request size" setting, and it seems you are hitting it.

So my advice:
- Find the setting for your server and increase it
- GZip your request payload, this would require server-side code changes, I have an example in [this article](http://jonathanpeppers.com/Blog/improving-http-performance-in-xamarin-applications) but it was for ASP.Net on Windows.

**Comment by vyfster** [comment] 2018-07-15 16:49
@jonathanpeppers I think you have missed the point of my post.  I don't expect HttpClient to make my requests successful.  The server isn't returning a bad HTTP status as 413 is part of the spec.

I found the condition where HttpClient throws the exception as per the original post, so I am highlighting that there is a bug in HttpClient - see my stack trace and explanation in my first post above.  This is incorrect behaviour as it should return the HTTP status code generated by the server and not throw an exception.  Run the same code in a windows console and HttpClient does not throw an exception and the correct status code is returned.

Thanks for your advice, but please re-read my post.

**Comment by IndexOutOfLimit** [comment] 2020-07-08 19:24
Not sure what was the resolution here or was fixed with updated version..
