### ISSUE TITLE
Font from assets not rendering in PDF view which is downloaded and installed using dynamic feature.

### ISSUE THREAD

**Issue by jazzbpn** [xamarin/xamarin-android#5181] opened 2020-10-04 13:39 UTC
Detailed Question: https://stackoverflow.com/questions/64191100/using-dynamic-feature-module-fonts-downloaded-and-installed-in-asset-folder-but

**Comment by grendello** [comment] 2020-10-06 07:04
@jazzbpn I don't see how this issue is related to Xamarin.Android? The SO link has Java code and no mention of Xamarin or C#. If you think it is somehow caused by Xamarin.Android, please provide a full, simple, C# Xamarin.Android application which reproduces the issue, thanks!

**Comment by moljac** [comment] 2020-11-06 11:13
Closing this issue because of the lack of the feedback

**Closed by moljac** 2020-11-06 11:13 UTC
Labels: need-info
