### ISSUE TITLE
[Bug] System.IO.IOException: The process cannot access the file '......android\assets\xxxx.dll' because it is being used by another process. - Visual Studio

### ISSUE THREAD

**Issue by pmahend1** [xamarin/xamarin-android#4647] opened 2020-04-30 22:49 UTC
### Description
Android project in Xamarin forms does not build 
Gives the error System.IO.IOException: The process cannot access the file 'C:\Project\100\android\assets\xxxx.dll' because it is being used by another process. where xxxx is different every different try of build 
```log
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.IO.IOException: The process cannot access the file '

C:\Source\DevPrateek\src\ProjectName.Mobile.Droid\obj\Debug\100\android\assets\Plugin.Media.dll
' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at Xamarin.Android.Tools.Files.CopyIfChanged(String source, String destination)
   at Xamarin.Android.Tasks.MonoAndroidHelper.CopyAssemblyAndSymbols(String source, String destination)
   at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	ProjectName.Mobile.Droid			
```

I thought this is due to Windows max path issue so I even tried setting Enable Win32 long paths = Enabled in Local Policy Editor and added <UseShortFileNames>True</UseShortFileNames>  and <IntermediateOutputPath>C:\Project</IntermediateOutputPath>

Every time it shows error message with different dll. 'C:\ProjectNameTemp\100\android\assets\NUglify.dll'

'C:\ProjectNameTemp\100\android\assets\AndUHD.dll' and so on…

Also ran [Get File Locking Process](https://stackoverflow.com/questions/958123/powershell-script-to-check-an-application-thats-locking-a-file#answer-31616378)  but found nothing.
```
PS C:\Project> Get-LockingProcess .\100\android\
WARNING: No matching handles found
```

Wasted entire day on this with no luck. Please note the solution gets build fine and runs on Visual Studio for Mac  and also if I unload the Android project.

Also tried to change android build properties like dex compiler shared runtime etc but its the same. This is frustrating that IDE is not available.  Cant use Mac all the time
### Steps to Reproduce

1. Create new Xamarin forms project on Visual Studio Windows
2. Build 

### Expected Behavior
All projects should build

### Actual Behavior
Android project does not build only on VIsual Studio windows , but builds on Visual Studio Mac

### Basic Information

- Version with issue: NA
- Last known good version: NA
- IDE:only Visual Studio Windows 
- Platform Target Frameworks: 
  - iOS:   NA
  - Android:  10 SDK 29 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin forms Xamarin essentials latest
- Affected Devices: Android

### Reproduction Link
NA

### Workaround
No work around at this time, trying to build project varius changes and seeing if anything works.

This has been also reported at [Visual Studio Developer Community](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Fcontent%2Fproblem%2F1012892%2Fsystemioioexception-the-process-cannot-access-the-1.html&data=02%7C01%7Cprateek.mahendrakar%40healthstatinc.com%7Cdd563f2c1e1d4b9d659608d7ed41d840%7C9c6a0e7678f64af793e574ffc08ba30b%7C0%7C0%7C637238739374820102&sdata=zUjhbMgPlex0N1dfmAPQNMrSxWBrHaxD8RQNl0dOKK4%3D&reserved=0)

**Comment by brendanzagaeski** [comment] 2020-05-05 08:33
Thanks for the report. I'll assign this item for further investigation by the team.

In the mean time, I'll also include some data gathering steps that might reveal some useful information. No worries if you don't get through these steps right now. The other team members might have different diagnostic steps to suggest.

## Data gathering steps to try if you get a chance

1. Prepare your Visual Studio environment so that you are ready to reproduce the build error on the next build.

2. Download and install the Microsoft [PerfView](https://github.com/microsoft/perfview/releases) tool.

3. Open a command prompt.

4. Run a command similar to the following to start trace collection:

   ```
   PerfView.exe collect "%USERPROFILE%\Desktop\PerfViewData.etl" -ClrEvents:Exception,Stack,Codesymbols -KernelEvents:FileIOInit
   ```

5. Switch back to Visual Studio and repeat the steps you normally follow to see the build error.

6. After you get the build error, switch back to PerfView and click **Stop Collection**. If prompted about **Empty Symbol Path** after this step, it's OK to click **Use Empty Symbol Path**.

7. Wait for PerfView to complete processing the data and generating the _.etl.zip_ file.

8. Attach the output _.etl.zip_ file on this issue. Note that this trace will include potentially sensitive details such as the specific file names from your project, so if you need to attach it privately, you can attach it on the corresponding Developer Community item instead.

## Optional preliminary data analysis

If you like, you can also try exploring the trace data locally:

1. Double click the output _.etl.zip_ file in the file explorer window in PerfView and open the **Advanced Group > File I/O Stacks** item.
2. When the **Select Process Window** opens, click the **All Procs** button at the bottom of the window.
3. Select the **By Name** tab in the new window that opens.
4. Enter the name of the problematic file (like _Plugin.Media.dll_) in the **IncPats** field and press the enter key.
5. Under the **Name** column, find the _File Read:..._ item that matches the problematic path, and double-click it. This opens the **Callers** tab.
6. In the **Callers** tab, first clear out the **GroupPats** field. Then click the checkboxes in the data view to reveal the call stacks, and look for lines that mention Xamarin or Mono.

This is a way to search for methods that might be holding the file handle. One refinement on this is to check under **Advanced Group > Exception Stacks** to find the time when the `IOException` occurs and compare that to the times in **File I/O Stacks**.

**Comment by dellis1972** [comment] 2020-05-05 10:09
@garuma  @joj this might be of interest to you. We have VS locking files again. Any ideas?

**Comment by pmahend1** [comment] 2020-05-05 13:48
@brendanzagaeski when I run the command it fails `Error: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)` ,so I guess I will have to run it on GUI 

What should it be ? `Kernel Base Checkbox` errors out saying `Could not find Command Kernel on Path`

**Comment by pmahend1** [comment] 2020-05-05 14:06
@brendanzagaeski etl file is ready and has been uploaded at [Visual Studio Dev Community](https://developercommunity.visualstudio.com/content/problem/1012892/systemioioexception-the-process-cannot-access-the-1.html)

**Comment by brendanzagaeski** [comment] 2020-05-05 20:06
*Notes for the Xamarin team members:*

I took a first look at the ETL file, and it appears there might be some virus detection software that starts accessing the file between the `File.Copy()` call and the `File.SetLastWriteTimeUtc()` call. I've added some private notes on the [Developer Community item](https://developercommunity.visualstudio.com/content/problem/1012892/systemioioexception-the-process-cannot-access-the-1.html) with possible ideas about resolving the issue by adding the solution directory or `MSBuild.exe` to the exclusion list for the antivirus software.

I also started thinking a little about whether there might be any changes possible in Xamarin.Android to try to help complete `SetLastWriteTimeUtc()` if antivirus software happens to temporarily try to access the file after the `Copy()` call. Maybe `CopyIfChanged()` could retry `SetLastWriteTimeUtc()` after a timeout if the first attempt fails? But maybe that would be messy.

**Comment by henda79** [comment] 2020-08-12 14:00
Hey, this happens with me too. If I hit rebuild several time it will eventually work. I've tried disabling my Anti Virus Eset but makes no difference.

**Comment by nonameb3** [comment] 2020-08-25 04:28
Any update? I founded the same issue.

Microsoft Visual Studio Community 2019
Version 16.7.2

**Comment by dellis1972** [comment] 2020-08-25 09:20
For those of you hitting this issue, it would be very helpful if you would collect the data requested in https://github.com/xamarin/xamarin-android/issues/4647#issuecomment-623927700. This might allow us to narrow down what application is holding a lock on the files. 

Also it was suggested in https://github.com/xamarin/xamarin-android/issues/4647#issuecomment-622168539, that setting your max number of parallel build processes to 1 might also help.

**Comment by albertoha94** [comment] 2020-09-28 17:14
Having this issue too when making a release build on Xamarin.Android. Leaving the etl as requested.
[PerfViewData.etl.zip](https://github.com/xamarin/xamarin-android/files/5293939/PerfViewData.etl.zip)

**Comment by sbreatnach** [comment] 2020-10-16 13:49
I've also experienced this issue. I've privately uploaded the ETL data to the Developer Community item but I can confirm it's caused by the [Carbon Black Cloud](https://www.carbonblack.com/) agent mandated by my company's IT. Compiling the same code under a temporary Windows VM on the same machine has no problems.

**Comment by shahanur** [comment] 2021-09-16 07:26
I am having the same issue. Is there any solution for this yet? In my case it was all fine. All in a sudden it just started. I tried all the above that others have tried.
It's really shame for visual studio and Android.

**Comment by mr-rajeshrathod** [comment] 2022-06-09 15:33
> 1. Advanced

I am also facing the same issue and these steps were very much helpful to find the root cause. My organization installed McAfee EDR on workstation and that was causing the problem in my case. So, I have asked them to remove and it started working again.

**Comment by mr-rajeshrathod** [comment] 2022-06-09 15:34
> Thanks for the report. I'll assign this item for further investigation by the team.
> 
> In the mean time, I'll also include some data gathering steps that might reveal some useful information. No worries if you don't get through these steps right now. The other team members might have different diagnostic steps to suggest.
> 
> ## Data gathering steps to try if you get a chance
> 1. Prepare your Visual Studio environment so that you are ready to reproduce the build error on the next build.
> 2. Download and install the Microsoft [PerfView](https://github.com/Microsoft/perfview/blob/master/documentation/Downloading.md) tool.
> 3. Open a command prompt.
> 4. Run a command similar to the following to start trace collection:
>    ```
>    PerfView.exe collect "%USERPROFILE%\Desktop\PerfViewData.etl" -ClrEvents:Exception,Stack,Codesymbols -KernelEvents:FileIOInit
>    ```
> 5. Switch back to Visual Studio and repeat the steps you normally follow to see the build error.
> 6. After you get the build error, switch back to PerfView and click **Stop Collection**. If prompted about **Empty Symbol Path** after this step, it's OK to click **Use Empty Symbol Path**.
> 7. Wait for PerfView to complete processing the data and generating the _.etl.zip_ file.
> 8. Attach the output _.etl.zip_ file on this issue. Note that this trace will include potentially sensitive details such as the specific file names from your project, so if you need to attach it privately, you can attach it on the corresponding Developer Community item instead.
> 
> ## Optional preliminary data analysis
> If you like, you can also try exploring the trace data locally:
> 
> 1. Double click the output _.etl.zip_ file in the file explorer window in PerfView and open the **Advanced Group > File I/O Stacks** item.
> 2. When the **Select Process Window** opens, click the **All Procs** button at the bottom of the window.
> 3. Select the **By Name** tab in the new window that opens.
> 4. Enter the name of the problematic file (like _Plugin.Media.dll_) in the **IncPats** field and press the enter key.
> 5. Under the **Name** column, find the _File Read:..._ item that matches the problematic path, and double-click it. This opens the **Callers** tab.
> 6. In the **Callers** tab, first clear out the **GroupPats** field. Then click the checkboxes in the data view to reveal the call stacks, and look for lines that mention Xamarin or Mono.
> 
> This is a way to search for methods that might be holding the file handle. One refinement on this is to check under **Advanced Group > Exception Stacks** to find the time when the `IOException` occurs and compare that to the times in **File I/O Stacks**.

I am also facing the same issue and these steps were very much helpful to find the root cause. My organization installed McAfee EDR on workstation and that was causing the problem in my case. So, I have asked them to remove and it started working again.

**Comment by jonathanpeppers** [comment] 2022-06-09 15:36
Thanks!

If someone could comment they are still hitting this *and*:
1. They're using the latest VS 2022 17.2 release
2. Verified no antivirus software is the actual cause

We should look into it further if that isn't the case, thanks!

**Closed** 2022-06-16 16:01 UTC
Labels: need-info
