### ISSUE TITLE
LayoutBindings: 'PreserveAttribute' is obsolete warnings

### ISSUE THREAD

**Issue by rgroenewoudt** [xamarin/xamarin-android#7480] opened 2022-10-21 10:13 UTC
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS2022 17.3.6

### Description

We are using a lot of AndroidBoundLayout in our app but this results in 2 warnings per layout file:

```
warning CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'
```

```
[global::Android.Runtime.PreserveAttribute (Conditional=true)]
public AboutSequriX (
	global::Android.App.Activity client,
	global::Xamarin.Android.Design.OnLayoutItemNotFoundHandler itemNotFoundHandler = null)
		: base (client, itemNotFoundHandler)
{}

[global::Android.Runtime.PreserveAttribute (Conditional=true)]
public AboutSequriX (
	global::Android.Views.View client,
	global::Xamarin.Android.Design.OnLayoutItemNotFoundHandler itemNotFoundHandler = null)
		: base (client, itemNotFoundHandler)
{}
```

We would like to get to 0 build warnings :)

### Steps to Reproduce

-

**Comment by rgroenewoudt** [comment] 2022-10-21 14:00
@dellis1972 I don't have any nuget packages Xamarin.Android.Support or any referencing it. Only AndroidX.

Example project. I created a new .NET 6 Android project, changed activity_main.xml to AndroidBoundlayout and added an ID.
[AndroidApp2.zip](https://github.com/xamarin/xamarin-android/files/9839654/AndroidApp2.zip)
```
1>C:\git\AndroidApp2\AndroidApp2\obj\Debug\net6.0-android\generated\Binding.activity_main.g.cs(12,4,12,45): warning CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'
1>C:\git\AndroidApp2\AndroidApp2\obj\Debug\net6.0-android\generated\Binding.activity_main.g.cs(19,4,19,45): warning CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'
```

**Comment by dellis1972** [comment] 2022-10-21 14:05
Ah. Are you using LayoutBindings?

**Comment by dellis1972** [comment] 2022-10-21 14:08
Ignore that, yes you are :) sorry.

OK, that is where the issue is then.

**Comment by rgroenewoudt** [comment] 2022-10-26 10:31
I would guess that there would need to be an if added to support both classic with PreserveAttribute and .NET 6 with DynamicDependencyAttribute.
https://github.com/xamarin/xamarin-android/blob/ab6712a48e4b93e9c3d605c7b393814d477e2bc8/src/Xamarin.Android.Build.Tasks/Tasks/GenerateLayoutBindings.CSharpBindingGenerator.cs#L221

A additional property would be probably be needed to feed the MsBuild task, perhaps UsingAndroidNETSdk?
https://github.com/xamarin/xamarin-android/blob/ab6712a48e4b93e9c3d605c7b393814d477e2bc8/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1152

**Comment by dellis1972** [comment] 2022-10-26 12:28
`DynamicDependencyAttribute` works in the reverse manner to the old `PreserveAttribute`. The old system you placed the attribute at the code you wanted to preserver. The new `DynamicDependencyAttribute` you have to place it where the type is consumed. So we need to figure out the best way to deal with this without requiring the user to add the `DynamicDependencyAttribute` to the activity where its used.

**Comment by rgroenewoudt** [comment] 2022-10-27 12:21
Is the attribute even needed? This is the C# binding which is used by the developer so if unused constructors are removed it shouldn't be a problem?

The file should also contain the autogenerated comment so any warnings would be ignored.

**Comment by jpobst** [comment] 2022-11-28 22:43
> The file should also contain the autogenerated comment so any warnings would be ignored.

A little more information on that: 
- https://github.com/xamarin/java.interop/pull/1052.
- https://github.com/xamarin/java.interop/issues/1051#issuecomment-1282548008

**Comment by rgroenewoudt** [comment] 2023-03-13 14:07
I'm still seeing this issue in NET 7 Android 33, even though [#1051](https://github.com/xamarin/java.interop/issues/1051) is resolved.

There is no autogenerated comment in generated/Binding.xxx.g.cs

**Comment by jpobst** [comment] 2023-03-13 14:09
This change was too late to make it into .NET 7, I would suspect that it is fixed in .NET 8 Previews.

**Comment by rgroenewoudt** [comment] 2023-11-23 20:10
Same issue in .NET 8.
`
xxxx\obj\Debug\net8.0-android\codebehind\Binding.StartWorkShift.g.cs(19,4,19,45): warning CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'
`

**Comment by rgroenewoudt** [comment] 2023-12-21 12:49
Would it be possible to backport to .NET 8 if it's a limited change: only adding <auto-generated> comment?

**Comment by jonathanpeppers** [comment] 2024-01-03 14:59
Yes, we can consider taking this one to .NET 8 servicing after it's merged:

* https://github.com/xamarin/xamarin-android/pull/8529

**Closed** 2024-03-27 18:23 UTC
Labels: Area: App+Library Build
