### ISSUE TITLE
[net7-rc2] Building an app in Release configuration reports incorrect duplicate types

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-android#7473] opened 2022-10-20 01:15 UTC
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

net7.0-rc2

### Description

Building a net6.0-android app in Release configuration causes the following errors:

```
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): 
warning XA4214: The managed type `Microsoft.UI.Xaml.Controls.AnimatedIcon` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical. [C:\a\1\s\UnoAppAll\UnoAppAll.Mobile\UnoAppAll.Mobile.csproj::TargetFramework=net6.0-android]
```
then java-related errors:
```
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): 
error XA4215: The Java type `crc64a5a37c43dff01024.GridViewHeaderItem` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted. [C:\a\1\s\UnoAppAll\UnoAppAll.Mobile\UnoAppAll.Mobile.csproj::TargetFramework=net6.0-android]
```
 

### Steps to Reproduce

1. `dotnet new install Uno.ProjectTemplates.Dotnet`
1. `dotnet new unoapp -o testapp`
1. `cd testapp\testapp.Mobile`
1. `dotnet build -f net6.0-android -c Release`

Notice a very large number of errors after the AOT step:
```
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): 
warning XA4214: The managed type `Microsoft.UI.Xaml.Controls.AnimatedIcon` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical. [C:\a\1\s\UnoAppAll\UnoAppAll.Mobile\UnoAppAll.Mobile.csproj::TargetFramework=net6.0-android]
```
then java-related errors:
```
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): 
error XA4215: The Java type `crc64a5a37c43dff01024.GridViewHeaderItem` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted. [C:\a\1\s\UnoAppAll\UnoAppAll.Mobile\UnoAppAll.Mobile.csproj::TargetFramework=net6.0-android]
```
 

### Did you find any workaround?

No, bumping to net7.0-android did not fix the issue. Considering the number of times the duplicate assembly is found, this would look like the number of target CPU architectures ?

### Relevant log output

[msbuild.zip](https://github.com/xamarin/xamarin-android/files/9825382/msbuild.zip)

**Comment by dellis1972** [comment] 2022-10-20 13:50
We probably need to add some additional logic to check for assemblies in the different runtime directories.

**Comment by jeromelaban** [comment] 2022-10-20 14:01
@dellis1972 would you know of a possible workaround for this (even if it means changing the targets files) ?

**Comment by dellis1972** [comment] 2022-10-20 14:15
@jeromelaban the check is done without the Task GenerateJavaStubs. https://github.com/xamarin/xamarin-android/blob/main/src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs#L191

The problem is GenerateJavaStubs is getting ALL of the assemblies for each RuntimeIdentifier. So we end up with 4 entires for Uno.UI etc and others.  

I guess you could write a target which runs just before the `_GenerateJavaStubs` target which will remove those duplicates from `@(_ResolvedAssemblies)` and `@(_ResolvedUserMonoAndroidAssemblies)` .. but I'm not sure how that would effect the packaging as those same ItemGroups are used to package the final app. https://github.com/xamarin/xamarin-android/blob/main/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1477

You might be able to add a filter to that target locally and make copies of those ItemGroups which you then pass to `GenerateJavaStubs`. (effectively replacing the `@(_ResolvedAssemblies)` and `@(_ResolvedUserMonoAndroidAssemblies)`  for that target, but leaving those ItemGroups intack for the other targets.

**Comment by lukasf** [comment] 2022-11-08 21:25
I just installed the latest official Uno version and .NET 7 RTM, and I cannot compile Android as Release (empty app from template). This issue should have top priority.

**Comment by dellis1972** [comment] 2022-11-09 10:06
@jeromelaban  @lukasf we have a PR in progress which I think will work. However, what is blocking is a good unit test. I have been unable to replicate the envionment in a standard android app which does not rely on other external sources. 

Do you have any idea what Uno in particular is doing which might cause this issue? Is there something specific which the `Uno.UI` assembly has which results it in having a per abi assembly? Then I might be able to replicate that behaviour in a standard anroid app.

**Comment by dellis1972** [comment] 2022-11-09 11:17
ok I think I've managed to cobble together an managed android example. I'll try and convert that to a unit test.

**Comment by jeromelaban** [comment] 2022-11-09 12:30
@dellis1972 I do not think we're doing anything RID specific in Uno (the binary is the same for all `net6.0-android` and `net7.0-android`). Have you found out what the difference is? I'm very curious :)

**Comment by dellis1972** [comment] 2022-11-09 14:57
> @dellis1972 I do not think we're doing anything RID specific in Uno (the binary is the same for all `net6.0-android` and `net7.0-android`). Have you found out what the difference is? I'm very curious :)

I haven't found a difference yet. But I did manage to repo in a basic android app just by adding a reference to `Uno.WinUI`. So I'm hoping I can at least convert that project into a unit test so I can test the fix in the PR.

**Comment by jeromelaban** [comment] 2022-11-09 15:21
@dellis1972 Could it be a linker option that causes this? But even then, there's no RID specific changes here, unless the runtime has content that is removed or altered there with some internal dependency on the BCL?

**Comment by dellis1972** [comment] 2022-11-09 15:31
@jeromelaban so I just did a diff of the IL produced between the `android-arm/Uno.UI.dll` and the `android-arm64/Uno.UI.dll` and got this

```
diff arm.il arm64.il 
4686c4686
< // MVID: {16515C9E-2BDA-4300-AAB3-EBE9BE5FF5F5}
---
> // MVID: {B51D27AA-5ED2-4FC1-A974-FD6D86D4ED29}
121459c121459
<     IL_0000:  ldc.i4     0x4
---
>     IL_0000:  ldc.i4     0x8
```

So it looks like there is a difference between these two. It also means the fix I was hoping would work, wont. Since the MVID's are different.

**Comment by dellis1972** [comment] 2022-11-09 15:37
I would guess that is caused by https://github.com/unoplatform/uno/blob/bd2789df8f9a2014dacff88751dfe20117b5fa6b/src/Uno.UI/UI/Xaml/SpecializedResourceDictionary.cs#L118

**Comment by jeromelaban** [comment] 2022-11-09 19:00
I tried with the following, but it produces the same result:
```
dotnet build -f net7.0-android -c Release /p:AotAssemblies=true /p:AndroidLinkSkip=Uno.UI
```

**Comment by liveinvarun** [comment] 2022-11-14 22:24
error XA4215: The Java type `crc643f2b18b2570eaa5a.PlatformGraphicsView` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted. [D:\a\1\s\src\App\App.Application\App.App.csproj::TargetFramework=net7.0-android]


C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets(1476,3): error XA4215:   `crc643f2b18b2570eaa5a.PlatformGraphicsView` generated by: Microsoft.Maui.Graphics.Platform.PlatformGraphicsView, Microsoft.Maui.Graphics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null [D:\a\1\s\src\App\App.Application\App.App.csproj::TargetFramework=net7.0-android]


C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets(1476,3): error XA4215:   `crc643f2b18b2570eaa5a.PlatformGraphicsView` generated by: Microsoft.Maui.Graphics.Platform.PlatformGraphicsView, Microsoft.Maui.Graphics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null [D:\a\1\s\src\App\App.Application\App.App.csproj::TargetFramework=net7.0-android]


C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets(1476,3): error XA4215:   `crc643f2b18b2570eaa5a.PlatformGraphicsView` generated by: Microsoft.Maui.Graphics.Platform.PlatformGraphicsView, Microsoft.Maui.Graphics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null [D:\a\1\s\src\App\App.Application\App.App.csproj::TargetFramework=net7.0-android]


C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets(1476,3): error XA4215:   `crc643f2b18b2570eaa5a.PlatformGraphicsView` generated by: Microsoft.Maui.Graphics.Platform.PlatformGraphicsView, Microsoft.Maui.Graphics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null [D:\a\1\s\src\App\App.Application\App.App.csproj::TargetFramework=net7.0-android]


C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.4\tools\Xamarin.Android.Common.targets(1476,3): error XA4215:

**Comment by liveinvarun** [comment] 2022-11-28 06:34
@dellis1972  Any update on when this will be fixed. Currently the release build is broken when we target .net7 based workloads for android.

**Comment by dellis1972** [comment] 2022-11-28 10:30
We have a fix (see https://github.com/xamarin/xamarin-android/pull/7477) just having issues getting the unit tests green so it can be merged.

**Closed** 2022-11-29 16:34 UTC
Labels: Area: App+Library Build

**Comment by jeromelaban** [comment] 2022-12-15 03:23
@jonpryor Would you know when this update will be released? It does not seem to be part of an SR1 update (only iOS and macOS were updated, for what I could see). Thanks!

**Comment by jonathanpeppers** [comment] 2022-12-15 03:34
This fixed missed the cutoff date but should be in the next one.

The .NET 7 release branch is: https://github.com/xamarin/xamarin-android/tree/release/7.0.1xx

**Comment by queequac** [comment] 2023-01-10 20:31
Obviously also not fixed in today's VS 17.4.4 release. :(

**Comment by jeromelaban** [comment] 2023-01-19 21:29
Fixed in 17.5 Preview 3!

**Comment by jonathanpeppers** [comment] 2023-01-19 21:46
You also should be able to run `dotnet workload update`. This will also be in 17.5 GA.

**Comment by queequac** [comment] 2023-02-02 20:59
With updated workloads and Uno 4.7.37 it finally works even in VS17.4.4. I am able to publish targeting .net7 with AOT enabled. 😄
