### ISSUE TITLE
`Build -> Archive` command hangs, "Please ensure that you are using a release configuration and that "Use Shared Mono Runtime" option unchecked."

### ISSUE THREAD

**Issue by xufeipyxis** [xamarin/xamarin-android#1760] opened 2018-05-31 09:58 UTC
### Steps to Reproduce

1. Set a project to release and build, and then Build -> Archive

### Expected Behavior
Create an archive
### Actual Behavior
It never completes.

![capture](https://user-images.githubusercontent.com/33150084/40775792-82015028-64fb-11e8-9d21-cfe709a4d25e.PNG)

I'm using release configuration and "Use Shared Mono Runtime" option is unchecked
```
    <BundleAssemblies>true</BundleAssemblies>
    <AotAssemblies>false</AotAssemblies>
```
This is my release configuration. I know this options are not available in the community verison of VS2017, but I can change it manually and reloade the project. It used to compile ok in April and earlier. I'm not sure if something changed in recent VS update.

### Version Information
15.7.1

Microsoft Visual Studio Community 2017  (VS2017)
Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA302
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40501.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

C# Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   5.34.0.6830-9173b9a63
PreEmptive Protection - Dotfuscator CE

GorillaPlayerPackage Extension   1.0
GorillaPlayerPackage Visual Studio Extension Detailed Info

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2017.2.2    Build 109.0.20171006.122324
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.11027.3
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

OzCode   1.0
Your road to Magical Debugging. http://www.oz-code.com

OzCodePackage Extension   1.0
OzCodePackage Visual Studio Extension Detailed Info

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 16ecf5a30ad868d183c58e4a71a71c23d4ed3ba9.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Unity   3.7.0.1
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.27703.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

WiX Toolset Visual Studio Extension   0.9.21.62588
WiX Toolset Visual Studio Extension version 0.9.21.62588
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   4.10.0.442 (396b18cef)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.264 (fc37cd02e)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.177 (7e782c1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by xufeipyxis** [comment] 2018-05-31 11:57
When I check the output of Xamarin, it says:

```
Shared Mono runtime is enabled for ''.
The selected build configuration is using the shared Mono runtime for faster deployment. Apps cannot be archived with this setting enabled.
Please ensure that you are using a release configuration and that the "Use Shared Mono Runtime" option in your project's build options is unchecked.
```

**Comment by JonDouglas** [comment] 2018-05-31 15:53
@xufeipyxis Can you please provide your most recent `ide` logs after encountering this issue found inside the `Help -> Xamarin -> Zip Logs` option? This should have a few more clues as to why this is failing.

You should be able to build on the command line via:

`msbuild <project.csproj> /t:SignAndroidPackage /p:Configuration=Release`

If that fails, it should give a proper error message as to what's wrong.

**Comment by xufeipyxis** [comment] 2018-06-01 05:55
[15.0.zip](https://github.com/xamarin/xamarin-android/files/2061192/15.0.zip)

**Comment by JonDouglas** [comment] 2018-06-01 19:43
@xufeipyxis I see two different issues here.

1. It seems that when loading your AndroidManifest.xml it is finding an undeclared element. Perhaps this is causing the build to fail and thus the archive? Are you able to build normally without using the archive step?

2. Archiving fails with the following:

```
Xamarin.VisualStudio.Publishing.Presentation.ViewModels.ArchiveListViewModel|Error|0|System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Xamarin.VisualStudio.Publishing.Presentation.ViewModels.ArchiveListViewModel.<<SubscribeToEvents>b__56_5>d.MoveNext() in E:\A\_work\5\s\src\Core\VisualStudio.Publishing\Presentation\ViewModels\ArchiveListViewModel.cs:line 262
```

Please also update to 15.7.3 that we released yesterday that include a few bug fixes.

**Comment by xufeipyxis** [comment] 2018-06-02 08:08
I created a new Xamarin.Android project and it achieved ok. I will check my project.

**Comment by EmilAlipiev** [comment] 2018-06-14 10:51
I just tried using command line and it looks like that it is working fine. Not sure if that it is just building or also archiving. but no error at all

**Comment by EmilAlipiev** [comment] 2018-06-14 11:20
Ok i see that he has something regarding manifest in his log bu in my log, i dont have anything related to it.
@JonDouglas  please find my log file. 
in the log, i dont understand these lines below. I am not building or archiving Ios Project and I even unchecked build and deploy option for ios, why would i get something like below. is there something messed up between Android and Ios in the latest xamarin or vs update? I am on latest xamarin forms update.

> 
> Xamarin.VisualStudio.IOS.MonoTouchFlavoredProject|Information|0|Beggining Build for C:\Git\myApp\myApp\myApp.iOS\myApp.iOS.csproj. Properties: ContinueOnDisconnected: True, ServerAddress: 
> Xamarin.VisualStudio.Publishing.Presentation.ViewModels.ArchiveListViewModel|Error|0|System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

[2018-06-14_12-42-08.71040.Ide.log](https://github.com/xamarin/xamarin-android/files/2102060/2018-06-14_12-42-08.71040.Ide.log)

**Comment by EmilAlipiev** [comment] 2018-06-14 22:59
I have just tested my application an VS2017 enterprise version and this error is not happening. this is only error for Community and Professional versions. so basically archiving 

**- Enterprise** : Bundle into native assemblies works, without bundling works
**-Pro and Community:** without Bundling works, Bundle into native assemblies=true fails with this error message.

**Comment by EmilAlipiev** [comment] 2018-06-23 18:31
Latest version 15.7.4 also has this problem

**Comment by flyingxu** [comment] 2018-06-25 03:56
This is actually very easy to reproduce:


1. Use Visual Studio Community 15.7.4

2. Create a Xamarin.Forms Android project (everything default)

3. Switch to Release configuration, build and archive, -> OK

4. Edit the project file to be `<AotAssemblies>true</AotAssemblies>`

5. Reload project, clean, rebuild

6. Try to archive again.

Then the archiving process hangs and never ends.

**Comment by xufeipyxis** [comment] 2018-06-25 04:27
It seems that it's also related to the `code sharing strategy`. When it's `shared project`, it's ok; but it failed for `.net standard` project.

**Comment by joj** [comment] 2018-06-25 12:14
I'll take a look and post back here. We usually don't make any checks for Enterprise/Community/Professional (except for the few components that are Enterprise only) but something might have gone wrong. I'll keep you posted.

**Comment by joj** [comment] 2018-06-25 13:31
BTW, the exception mentioned above

> Xamarin.VisualStudio.Publishing.Presentation.ViewModels.ArchiveListViewModel|Error|0|System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

has been fixed. The fix will be in preview soon.

**Comment by joj** [comment] 2018-06-25 17:11
I tried the repro. It looks like the UI is not super clear, but an error message is shown about Shared Use Runtime (which is unchecked, too). Now I need to understand why this only happens in community/pro, and what we can do to make that error message clear. This looks like it's hanged, but it's actually not going to go through because of that error.

**Comment by joj** [comment] 2018-06-25 19:53
Found the bug. It manifests in Community for some reason but has nothing to do with community. The good news is that restarting VS is a valid workaround. It works after that, with the correct settings. I'll be working on a fix.

**Comment by joj** [comment] 2018-06-27 19:35
Still on this. It seems the bug exceeds Xamarin and I may need to forward it. I'll keep updating here, though.

**Comment by EmilAlipiev** [comment] 2018-07-12 16:56
It still problem with the latest 15.7.8 update.

**Comment by ubidyanand** [comment] 2018-08-02 13:04
Remove the "Use Shared Runtime" from Debug mode as well. It don't work in Release mode if "use shared runtime" is enable for Debug configuration.

**Comment by xufeipyxis** [comment] 2018-09-19 08:10
15.8.4 still does not work.

**Closed** 2018-09-19 09:26 UTC
Labels: bug

**Comment by dfoulk** [comment] 2018-09-19 17:19
I'm experiencing this is VS2017 Pro. All that we had to do was (close Visual Studio) delete the **.vs** folder and restart Visual Studio.

**Comment by kkarakk** [comment] 2018-09-27 06:38
I experienced the same issue while trying to deploy an application to the play store. the error(unable to sign app) and the solution are completely unrelated to me as a beginner in xamarin android, really frustrating bug

**Comment by Denny966** [comment] 2018-09-27 11:31
Got the same problem, closing visual studio and deleting .vs folder works, but it's quite annoying to do that every time. 

Microsoft Visual Studio Enterprise 2017 
Version 15.8.2
VisualStudio.15.Release/15.8.2+28010.2016
Microsoft .NET Framework
Version 4.7.03056

**Comment by derekwheeler-tylertech** [comment] 2018-10-02 20:28
Same problem here. Deleting .vs folder worked. 

Microsoft Visual Studio Enterprise 2017 
Version 15.8.5
VisualStudio.15.Release/15.8.5+28010.2036
Microsoft .NET Framework
Version 4.7.03056

Xamarin   4.11.0.776 (d15-8@1ae9b59d7)
Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)

**Comment by erdmenchen** [comment] 2018-10-08 13:34
Same here, a simple restart without deleting the .vs folder worked, too.

**Comment by llauderesv** [comment] 2018-10-11 07:59
Same problem here. Closing Visual Studio and delete .vs folder under my project. Resolve this issue

**Comment by ianvink** [comment] 2018-11-21 17:23
Same problem with VS 15.9.2 - Restarted VS fixed it. Note that I built a release branch first and pushed it to a device, then archived. Perhaps that previous release build had something to do with it.

**Comment by thomasgalliker** [comment] 2018-12-11 22:35
Same problem with VS 15.9.3 - Restarted VS fixed it. 4h of troubleshooting wasted on this...

**Comment by kyle-john** [comment] 2018-12-19 09:03
Same problem with VS 15.9.3

1. Exit VS
2. Delete .vs folder
3. Start VS and Archive it.

**Comment by Umar3x** [comment] 2019-01-09 14:45
Got the same issue. Don't know when it appeared but I updated VS one week ago ... VS 15.9.4

**Comment by JeetR** [comment] 2019-01-10 07:05
> Got the same issue. Don't know when it appeared but I updated VS one week ago ... VS 15.9.4

Did You try deleting obj, bin and .vs folder and restarting visual studio and rebuilding your project?
You can also restart your system once after deleting the folders.(once restarting helped me fix the issue)

**Comment by Umar3x** [comment] 2019-01-10 16:36
Yep. It did the job (deleting .vs folder & restart). My post was informative :). Thanks

**Comment by dfoulk** [comment] 2019-01-10 17:13
@JeetR's solution will fix 99% of issues that arise in projects that have worked previously.

**Comment by Thijmen** [comment] 2019-02-01 13:45
Having this problem too. Sometimes it looks like the compiler doesn't even compile my new written code, e.g. click events not working in my app. A clean of the whole project will fix it. 

It works, but really annoying.

**Comment by BladeMF** [comment] 2019-05-09 17:45
Having the same problem too.

**Comment by EmilAlipiev** [comment] 2019-05-31 21:25
15.9.12 on VS2017, it is still problem.

**Comment by tigreye007** [comment] 2019-09-17 14:19
Agreed.  In 15.9.12, I reproduced this myself.  Simply closing and restarting VS2017 (Community) works as a workaround.  The only thing I can note is that I was doing a LOT of debugging in the same session I performed a Release Clean/Rebuild/Archive in - is it possible that this has something to do with it?

**Comment by createS0ftware** [comment] 2020-05-14 12:35
What i found is that you need to select Release in Build->Configuration Manager  in the menu.
