### ISSUE TITLE
Unable to resolve RegisterForActivityResult

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#7537] opened 2022-11-07 22:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-resolve-RegisterForActivityRes/10189797)._

---
[severity:I'm unable to use this version]
 I'm using Visual Studio 2022 Version 17.3.6 on a Windows 11 pro machine and I'm updating a working app that had targeted android API 9 (Pie) to android API 33 (Tiramisu) using Xamarin.Android (not Xamarin.Forms).  The call to StartActivityForResult always returns Result.Cancelled in the OnActivityResult code, I discover that the StartActivityForResult is deprecated and that one should use ActivityResultLauncher.  I found an example [here](https://stackoverflow.com/questions/62671106/onactivityresult-method-is-deprecated-what-is-the-alternative) and I updated my code to use the ActivityResultLauncher.  However I am unable to resolve the line:

 _activityResultLauncher = RegisterForActivityResult(new ActivityResultContracts.StartActivityForResult(), _activityResultCallback);

The error is: The name 'RegisterForActivityResult' does not exist in the current context.

I have no idea how to resolve this and I cannot find any information on it anywhere, I assume that's because android API 33 is relatively new.  In any even, how can I resolve this issue?

R/
Prescott ....

---
#### Feedback Bot on 11/3/2022, 07:44 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment] 2022-11-08 15:47
Duplicate of https://github.com/xamarin/AndroidX/issues/648.

**Closed by jpobst** 2022-11-08 15:47 UTC
Labels: needs-triage
