### ISSUE TITLE
Can't install Xamarin Forms via NuGet

### ISSUE THREAD

**Issue by SpiegelSoft** [xamarin/xamarin-android#1690] opened 2018-05-16 15:55 UTC
### Steps to Reproduce

1. Create a new Android app (single page).
2. Type "install-package Xamarin.Forms" in Package Manager Console.
3. Observe the following error message:

install-package : NU1107: Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the 
project to resolve this issue. 
App5 -> Xamarin.Android.Support.Design 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2) 
App5 -> Xamarin.Forms 3.0.0.482510 -> Xamarin.Android.Support.v4 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).
At line:1 char:1

install-package Xamarin.Forms
~~~~~~~~~
CategoryInfo : NotSpecified: (:) [Install-Package], Exception
FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
install-package : Package restore failed. Rolling back package changes for 'App5'.
At line:1 char:1

<!--
If you have a repro project, you may drag & drop the .zip/etc. onto the issue editor to attach it.
-->

### Expected Behavior
I should be able to add NuGet packages, specifically, Xamarin Forms

### Actual Behavior
Unable to add Xamarin.Forms.

This is a blocker.

### Version Information

<!--
1. On macOS and within Visual Studio, select Visual Studio > About Visual Studio, then click the Show Details button, then click the Copy Information button.

2. Paste below this comment block.
-->

### Log File

<!--
1. On macOS and within Visual Studio:
    a. Click **Tools** > **SDK Command Prompt**.
    b. Within the launched `Terminal.app` window, run:

            adb logcat -d | pbcopy

2. Paste below this comment block
-->



<!--
Switch to the "Preview" tab to ensure your issue renders correctly.

Please add an appropriate "Area:" label in the Labels section.
-->

**Comment by JonDouglas** [comment] 2018-05-16 17:09
This is a NuGet limitation and this issue is now being tracked internally to ensure our templates provide a better experience. The issue is that Xamarin.Forms has a constraint on a package that is already installed in the template based on our recent revamp of templates:

https://blog.xamarin.com/new-xamarin-android-ios-templates/

As mentioned on Slack, you first need to uninstall any support libraries in your project, then install Xamarin.Forms so it can properly include the dependency. Optionally, you can use the Xamarin.Forms template instead of the Android one which will include this by default.

Thus I am closing this issue as it does not pertain to the Xamarin.Android SDK, but rather NuGet and our Templates.

Thank you for the report!

**Closed by JonDouglas** 2018-05-16 17:09 UTC
