### ISSUE TITLE
Crash to desktop on Android 11 (Pixel 5) with latest packages through nuget.

### ISSUE THREAD

**Issue by norton287** [xamarin/xamarin-android#5671] opened 2021-03-01 13:36 UTC
### Version Information

- Visual Studio version (eg. 16.8 or 8.8):  16.8.6
- Xamarin.Android version (eg. 11.1):  10
- Using AndroidX or Support Libraries:  AndroidX
- If Support Libraries, version (eg 28.0.0): 

### Describe your Issue:
After updating the nugets for AndroidX.Browser, AndroidX.Legacy.Support.V4, AndroidX.MediaRouter, AndroidX.Palette, and AndroidX.Material I get a crash to desktop on app load on Android 11 on my Pixel phone.  Without them, the app works fine.  Also tested with simulator running Android Pie and it works with these packages.  It just crashes on my Pixel 5 with 11.

### Include any relevant Exception Stack traces, build logs, adb logs:

ADB Log, crash is at tail end

sRetrieverApiService.START pkg=com.google.android.gms }
03-01 07:23:31.545  4244  4431 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.554  4244  9879 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.565  4244  9879 I chatty  : uid=1001(radio) Binder:4244_10 identical 2 lines
03-01 07:23:31.574  4244  9879 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.579  4244  4431 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.590  1546  1681 I Tycho.can: Active Data Subscription Id changed to 1
03-01 07:23:31.600  4244  4431 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.601  4244  9879 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.604  4244  4431 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.604  4244  9879 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.609  4244  4447 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.613  4244  4431 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.615  4244  4447 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.617  1666  1732 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{56add5b u0 com.spindlecrank.grocerylist/crc64ee4aab6e8d7d38a2.SplashActivity t-1 f}}
03-01 07:23:31.620  4244  4431 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.621  4244  9879 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.625  4244  4431 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.632  4244  4431 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.637  4244  4447 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.655  4244  4447 I chatty  : uid=1001(radio) Binder:4244_5 identical 2 lines
03-01 07:23:31.659  4244  4447 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.667  4244  4431 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.671  1666  1732 I DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:19260504575090817", 1080 x 2340, modeId 1, defaultModeId 2, supportedModes [{id=1, width=1080, height=2340, fps=90.0}, {id=2, width=1080, height=2340, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], HdrCapabilities HdrCapabilities{mSupportedHdrTypes=[2, 3, 4], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, allmSupported false, gameContentTypeSupported false, density 440, 435.428 x 433.839 dpi, appVsyncOff 2333333, presDeadline 11500000, cutout DisplayCutout{insets=Rect(0, 136 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(0, 0 - 136, 136), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]}}, touch INTERNAL, rotation 0, type INTERNAL, address {port=129, model=0x446d53ad64a0}, deviceProductInfo DeviceProductInfo{name=, manufacturerPnpId=QCM, productId=1, modelYear=null, manufactureDate=ManufactureDate{week=27, year=2006}, relativeAddress=null}, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
03-01 07:23:31.672   604   604 I SDM     : HWDeviceDRM::UpdateMixerAttributes: Mixer WxH 1080x2340-1 for Peripheral
03-01 07:23:31.672   604   604 I SDM     : DisplayBase::SetActiveConfig: Active configuration changed to: 1
03-01 07:23:31.673   604   604 I SDM     : StrategyImpl::SetIdleTimeoutMs: Idle timeout set to zero for command mode panels
03-01 07:23:31.686  4244  4447 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.689   986  2159 I sensors-hal: [ssc_utils]get_qmi_debug_flag:244, support_qmi_debug : false
03-01 07:23:31.691  4244  4447 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.google.android.apps.tycho:getSubscriptionInfoList:-1
03-01 07:23:31.724   986  1094 W ASH     : @ 949865.026: Unhandled msg ID 999: line 1277
03-01 07:23:31.724   986  1094 E ASH     : @ 949865.026: No pb callback assigned
03-01 07:23:31.724   986  1094 E ASH     : @ 949865.026: Nanopb error: callback failed:1588
03-01 07:23:31.789   986  2159 I sensors-hal: [ssc_utils]get_qmi_debug_flag:244, support_qmi_debug : false
03-01 07:23:31.804   986  1094 W ASH     : @ 949865.106: Unhandled msg ID 999: line 1277
03-01 07:23:31.804   986  1094 E ASH     : @ 949865.106: No pb callback assigned
03-01 07:23:31.804   986  1094 E ASH     : @ 949865.106: Nanopb error: callback failed:1588
03-01 07:23:31.844   996  1031 D rlsservice: MonitorDisplayStatus client num 1, display status 1, sensor status 1
03-01 07:23:31.954  1666  3677 D ConnectivityService: NetReassign [no changes]
03-01 07:23:32.478  1666  3670 W NetworkPolicy: shared quota unsupported; generating rule for each iface
03-01 07:23:32.641  1666  1732 W WindowManager: Unable to start animation, surface is null or no children.
03-01 07:23:32.652   986  2159 I sensors-hal: [ssc_utils]get_qmi_debug_flag:244, support_qmi_debug : false
03-01 07:23:32.684   986  1094 W ASH     : @ 949865.986: Unhandled msg ID 999: line 1277
03-01 07:23:32.684   986  1094 E ASH     : @ 949865.986: No pb callback assigned
03-01 07:23:32.684   986  1094 E ASH     : @ 949865.986: Nanopb error: callback failed:1588
03-01 07:23:32.745   986  2159 I sensors-hal: [ssc_utils]get_qmi_debug_flag:244, support_qmi_debug : false
03-01 07:23:32.764   986  1094 W ASH     : @ 949866.066: Unhandled msg ID 999: line 1277
03-01 07:23:32.764   986  1094 E ASH     : @ 949866.066: No pb callback assigned
03-01 07:23:32.764   986  1094 E ASH     : @ 949866.066: Nanopb error: callback failed:1588
03-01 07:23:34.990  1666  3677 D ConnectivityService: NetReassign [no changes]

Debug Log:
Tried debugging but it kept failing to deploy, got this error
Synchronizing assemblies...
ADB1000:  Deployment failed
Xamarin.AndroidTools.AndroidDeploymentException: FailedToSynchronizeFastDevAssemblies ---> Mono.AndroidTools.AdbException: fchown failed: Operation not permitted
   at Mono.AndroidTools.Util.AggregateAsyncResult.CheckError(CancellationToken token) in C:\A\1\81\s\External\androidtools\Mono.AndroidTools\Util\AggregateAsyncResult.cs:line 72
   at Mono.AndroidTools.Adb.AdbSyncClient.EndPushSyncItems(IAsyncResult result) in C:\A\1\81\s\External\androidtools\Mono.AndroidTools\Adb\AdbSyncClient.cs:line 1070
   at Mono.AndroidTools.Internal.AdbClientTaskExtensions.InnerInvoke(TaskCompletionSource`1 tcs, Func`2 endMethod, IAsyncResult l) in C:\A\1\81\s\External\androidtools\Mono.AndroidTools\Internal\AdbClientTaskExtensions.cs:line 256
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Xamarin.AndroidTools.AndroidDeploySession.<InstallAssemblies>d__121.MoveNext() in C:\A\1\81\s\External\androidtools\Xamarin.AndroidTools\Sessions\AndroidDeploySession.cs:line 614
   --- End of inner exception stack trace ---
   at Xamarin.AndroidTools.AndroidDeploySession.<InstallAssemblies>d__121.MoveNext() in C:\A\1\81\s\External\androidtools\Xamarin.AndroidTools\Sessions\AndroidDeploySession.cs:line 622
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.AndroidTools.AndroidDeploySession.<FastDevAsync>d__118.MoveNext() in C:\A\1\81\s\External\androidtools\Xamarin.AndroidTools\Sessions\AndroidDeploySession.cs:line 514
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Xamarin.AndroidTools.AndroidDeploySession.<RunAsync>d__110.MoveNext() in C:\A\1\81\s\External\androidtools\Xamarin.AndroidTools\Sessions\AndroidDeploySession.cs:line 229
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.AndroidTools.AndroidDeploySession.<RunLoggedAsync>d__108.MoveNext() in C:\A\1\81\s\External\androidtools\Xamarin.AndroidTools\Sessions\AndroidDeploySession.cs:line 123
Done building project "GroceryList.Android.csproj" -- FAILED.
Build FAILED.

**Comment by dellis1972** [comment] 2021-03-01 19:59
This looks like a duplicate of https://github.com/xamarin/xamarin-android/issues/4996. The Shared runtime system and external override directory it uses are not compatible with Android 11.

The options are to disable Fast Deployment, or try d16-9 Preview 5. In Preview 5 we completely rewrote the fast deployment system so it will work on Android 11.

**Comment by norton287** [comment] 2021-03-02 18:29
This is fixed in 16.9 released today.  Can this be moved back to the original repo I still have issues updating to the latest AndroidX packages released in the last 2 weeks.

Here is a screenshot
![Screenshot 2021-03-02 122005](https://user-images.githubusercontent.com/42098364/109696630-dff76800-7b52-11eb-9857-fc8a38c4aa9c.png)
[debug.txt](https://github.com/xamarin/xamarin-android/files/6070906/debug.txt)

:

**Comment by jpobst** [comment] 2021-03-02 19:11
It would be better to open a new issue in AndroidX containing the relevant information.  This one mainly contains information about the original deployment crash.

**Comment by norton287** [comment] 2021-03-02 19:18
Will do

**Closed** 2021-03-02 20:55 UTC
