### ISSUE TITLE
"fast deploy" can't recover from uninstall

### ISSUE THREAD

**Issue by XavierAP** [xamarin/xamarin-android#3946] opened 2019-11-21 17:17 UTC
### Steps to Reproduce
1. Start with a Debug configuration. There may be many combinations between debug/release and several project deploy options (detailed at next point).
1. Enable (or leave enabled as default) project settings > Android options > packaging properties > "Use Shared Runtime"; "Use Fast Deployment (debug mode only)"; and "Use incremental Android packaging system".
1. Deploy an Android project to a device. One fresh from the VS wizard is [attached](https://github.com/xamarin/xamarin-android/files/3875890/bug-android-fast_deploy-uninstalled.zip)
1. Uninstall deployed app manually from the device.
1. Optionally, deploy again: if no code changes, it is reported successful, but the app is not back in the device.
1. Try debugging; deployment fails, with error message: «ADB0000: Could not determine the installation path for package com.[companyname].[projectname]. `adb shell pm path com.companyname.test` returned ''.»

### Expected Behavior
- After trying deploying the second time (optional step), the build should realize the end result is not ok, because the app can't be found.
- When encountering the exception while debugging, the build should recover from it and try a regular slow deployment. (Or at the very, very least, provide an error message that points to the options that may be changed to try and solve the issue.)

### Actual Behavior
As described,
- deployment reports success (at least in case of no code changes) even if the previously uninstalled app is not deployed; and
- debugging keeps failing

### Version Information
Version with issue: 16.3.0.278
IDE: VS Community 2019 16.3.8

**Comment by XavierAP** [comment] 2019-11-21 17:18
I'm not sure if this can be duplicate or related to #1555.

**Comment by XavierAP** [comment] 2019-11-21 17:18
In any case

**Comment by brendanzagaeski** [comment] 2019-11-23 01:53
Thanks for the report and the detailed steps to reproduce! This behavior should be resolved by the fix for <https://github.com/xamarin/xamarin-android/issues/3727>. Barring unexpected complications, that fix will be included in the upcoming Visual Studio 2019 version 16.5 Preview 1.

I will close this item as a duplicate of <https://github.com/xamarin/xamarin-android/issues/3727> for further tracking.

**Comment by brendanzagaeski** [comment] 2019-11-23 01:53
Duplicate of #3727

**Closed by brendanzagaeski** 2019-11-23 01:53 UTC
Labels: Area: App+Library Build
