### ISSUE TITLE
AndroidLibrary property for transient aar creation (from referencing jars) doesn't work for net8 as it was for net7

### ISSUE THREAD

**Issue by awattar** [xamarin/xamarin-android#8627] opened 2024-01-11 11:51 UTC
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VSMac 17.6.8, .NET 8.0.101

### Description

When switching binding library that contains referencing jars from net7-android33.0 to net8-android34.0 (no other changes) the part of binding library definition stopped to work as expected:

```
<AndroidLibrary Include="JarsAndAars/*.jar">
	<Bind>false</Bind>
	<Pack>true</Pack>
	<PackagePath>lib/$(TargetFramework)</PackagePath>
</AndroidLibrary>
```

Resulting transient LibraryName.aar in /Users/XXX/Proj/bin/Proj/Release/net8.0-android34.0/Proj.aar is 331 bytes only when normal (for net7) is 503 KB (in my jars configuration).

According to the documentation `AndroidLibrary` property should pack jars into transient aar. A Xamarin.Android class library, Foo.csproj will place native libraries in the Foo.aar file by default - https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetEmbeddedResources.md#native-libraries.

It also states that "We could simplify much of the above with a new @(AndroidLibrary) item group." and it used to work for net7 as stated - https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetEmbeddedResources.md#msbuild-item-groups

Changing `AndroidLibrary` to more specific `AndroidJavaLibrary` solves the issue.

### Steps to Reproduce

1. Create net8 binding project.
2. Reference some jars.
3. Include jars into resulting library using `AndroidLibrary` property.
4. Observe transient aar in bin project subdirectory for both net7 and 8.

### Did you find any workaround?

Switch `AndroidLibrary` to `AndroidJavaLibrary` for net8.

**Comment by jpobst** [comment] 2024-01-11 18:14
Given the following binding project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net7.0-android;net8.0-android</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnableDefaultItems>false</EnableDefaultItems>
	</PropertyGroup>
	
	<ItemGroup>
		<TransformFile Include="Metadata.xml" />
		<Compile Include="Additions.cs" />
		<AndroidLibrary Include="volley-1.2.1.aar" />
		<AndroidLibrary Include="tink-android-1.9.0.jar" Bind="false" Pack="true" />
	</ItemGroup>
</Project>
```

I end up with the ~same output in the `bin` directory for `net7.0-android` and `net8.0-android`:

![image](https://github.com/xamarin/xamarin-android/assets/179295/24a74884-2e7f-4082-83c7-6f6541e4c20b)

The `tink` library is 2MB, making it clear that it is inside the `binding1.aar`.

**Comment by awattar** [comment] 2024-01-11 18:30
@jpobst Would you try with specific API versions - net7-android33.0 / net8-android34.0?

**Comment by jpobst** [comment] 2024-01-11 18:37
Looks the same with API specific versions:

![image](https://github.com/xamarin/xamarin-android/assets/179295/96c9590c-5b3e-4fc6-b857-3b0f4a385b71)

I don't have a Mac so I can't try it there, but here's my project you can try with `dotnet build`:

[binding1.zip](https://github.com/xamarin/xamarin-android/files/13907071/binding1.zip)

**Comment by awattar** [comment] 2024-01-11 19:03
@jpobst Sure will do.

**Comment by awattar** [comment] 2024-01-11 20:59
@jpobst I was not able to reproduce it on your project even though I have tried several configurations and different additional aars/jars.

But I'm still able to reproduce it on my setup - it seems to be timing and VSMac related as my project is bigger and perhaps some targets works in parallel and could interfere with each other. For `AndroidJavaLibrary` it works in all configurations.

For `AndroidLibrary` I have following paths:
1. bin & obj empty -> Build:
Bin folder is empty.
Build log:
```Building GoodDynamics.Android (Release)

========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

Build successful.
```
VSMac bottom bar shows "Packages successfully restored".
So it is build without a build.
 2. Additional build to above.
Still nothing happens except the VSMac bottom bar immediately shows "Build successful." but the bin is empty and nothing really happens.
3. Pack in addition to above.
During the process there is visible Project.aar in the bin dir with correct size but after the process it is replaced with the new one 331 bytes only.
4. Bin & obj empty -> Restore -> Build (does nothing) -> Rebuild (correct size) -> Pack (incorrect size).

Will try with CLI and VSWin to confirm.

**Comment by awattar** [comment] 2024-01-11 22:42
Unfortunately it works the same - with error - from CLI (Mac terminal).

**Comment by jpobst** [comment] 2024-04-17 18:34
This appears to be working as intended with the default case.  Unfortunately, without a repro that shows the error there isn't much more we can do.

Closing as not enough info.

**Closed by jpobst** 2024-04-17 18:34 UTC
Labels: Area: Bindings
