### ISSUE TITLE
Need to use a FIPS compliant algorithm instead of MD5 in `GetAdditionalResourcesFromAssemblies.cs`

### ISSUE THREAD

**Issue by kealist** [xamarin/xamarin-android#3427] opened 2019-08-01 16:39 UTC
Many uses of MD5 throughout build process cause problems with FIPS.  These are not the only examples:

https://github.com/xamarin/xamarin-android/blob/28e1f9308c8697bc47e9e3220ffb5bd32c961620/src/Xamarin.Android.Build.Tasks/Tasks/CalculateAdditionalResourceCacheDirectories.cs#L29

https://github.com/xamarin/xamarin-android/blob/63710e632bac3bc29c9805834e2164c4087fba8b/src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs#L54

This leads to problems with building on Windows with FIPS Group Policy enabled

**Comment by kealist** [comment] 2019-08-01 19:10
#1580

**Comment by jonathanpeppers** [comment] 2019-08-02 16:08
Is this just a duplicate of #1580? Let me know otherwise, thanks!

**Closed by jonathanpeppers** 2019-08-02 16:08 UTC
Labels: Area: App+Library Build
