### ISSUE TITLE
Warning when publishing an android app. How do I fix it?

### ISSUE THREAD

**Issue by developer9969** [xamarin/xamarin-android#6183] opened 2021-08-13 11:02 UTC
hi all
When publishing an app in android (Xamarin forms) I get the following 2 warnings .. 
Can someone explain what am I missing?

thanks

> 2 MESSAGES FOR VERSION CODE 109537
Warning
There is no deobfuscation file associated with this App Bundle. If you use obfuscated code (R8/proguard), uploading a deobfuscation file will make crashes and ANRs easier to analyze and debug. Using R8/proguard can help reduce app size. Learn More

> Warning
> This App Bundle contains native code, and you've not uploaded debug symbols. We recommend you upload a symbol file to make your crashes and ANRs easier to analyze and debug. Learn More

**Comment by dellis1972** [comment] 2021-08-13 13:41
This is a duplicate of https://github.com/xamarin/xamarin-android/issues/5378.

**Closed by dellis1972** 2021-08-13 13:41 UTC
