### ISSUE TITLE
Skipping target "_Sign" because all output files are up-to-date with respect to the input files.

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#6479] opened 2021-11-10 23:07 UTC
VS 2022 17.1.0 P1.0
I got the impression that the above had been fixed a while back, however, it still occurs with a release build. Maybe it was just discussed on Discord and the fix hasn't made it into a release yet!

This was on a deploy where the app had already been manually uninstalled.

```
Skipping target "_Sign" because all output files are up-to-date with respect to the input files.
"C:\Program Files (x86)\Android\android-sdk\platform-tools\adb" -s 0B251JEC218062 uninstall -k "com.glmsoftware.OBDNowPro"
The -k option uninstalls the application while retaining the data/cache.
At the moment, there is no way to remove the remaining data.
You will have to reinstall the application with the same signature, and fully uninstall it.
If you truly wish to continue, execute 'adb shell cmd package uninstall -k'.
The command ""C:\Program Files (x86)\Android\android-sdk\platform-tools\adb" -s 0B251JEC218062 uninstall -k "com.glmsoftware.OBDNowPro"" exited with code 1.
The previous error was converted to a warning because the task was called with ContinueOnError=true.
The "Exec" task returned false but did not log an error.
The previous error was converted to a warning because the task was called with ContinueOnError=true.
```

**Comment by jpobst** [comment] 2022-09-14 01:17
Appears to be a duplicate of https://github.com/xamarin/xamarin-android/issues/6342.

Keeping that one because it has discussion on it.

**Closed by jpobst** 2022-09-14 01:17 UTC
Labels: Area: App+Library Build, needs-triage
