### ISSUE TITLE
R8 : warning : Missing class: com.google.android.gms.location.LocationListener

### ISSUE THREAD

**Issue by srdmnc** [xamarin/xamarin-android#3824] opened 2019-10-21 08:59 UTC
### Steps to Reproduce
1. Setup OneSignal version 3.5.0 (install via nuget )
2. Build in **release mode** the XF application with D8 and ProGuard enabled (with "Link SDK assemblies" only)

### Expected Behavior
Build Successfully

### Actual Behavior
Build Failed with the following error:
 
```
    R8 : warning : Missing class: com.google.android.gms.location.LocationListener
    R8 : error : Compilation can't be completed because some library classes are missing.
    Compilation failed
```
### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.3.1 (build 18)
Installation UUID: d4eb8fa7-46fb-411e-b083-6d568c3677ec
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000198

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
	Package version: 604000198

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.2.300
	2.1.701
	2.1.700
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.2.5
	2.1.13
	2.1.12
	2.1.11
	2.1.2

=== Xamarin.Profiler ===

Version: 1.6.11.16
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.1 (15405)
Build 11A1027

=== Xamarin.Mac ===

Version: 6.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin.Android ===

Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/kaiserdominictorrevillas/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
1.8.0_121
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

=== Android Device Manager ===

Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

=== Xamarin.iOS ===

Version: 13.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin Designer ===

Version: 16.3.0.244
Hash: e15b2ee97
Branch: remotes/origin/d16-3
Build date: 2019-09-25 00:03:16 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803010018
Git revision: 272ab73f00ab2b13ec97dc8b31d02980cf66d47f
Build date: 2019-09-27 19:26:51+00
Build branch: release-8.3
Xamarin extensions: 451b00e65052c11c16b79e6d31a24c4cf0d1b794

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

XAML Styler 1.1.5

**Comment by jonathanpeppers** [comment] 2019-10-24 14:06
@srdmnc do you have this in your `AndroidManifest.xml`:
```xml
  <uses-library android:name="org.apache.http.legacy" android:required="false" />
</application>
```

Details on this here: https://github.com/xamarin/xamarin-android/commit/b08240ee50e941cb326688cc0dcf5969ebfe5473

**Comment by srdmnc** [comment] 2019-10-25 01:43
@jonathanpeppers yes, I have that in my Android Manifest.

> @srdmnc do you have this in your `AndroidManifest.xml`:
> 
> ```
>   <uses-library android:name="org.apache.http.legacy" android:required="false" />
> </application>
> ```
> 
> Details on this here: [b08240e](https://github.com/xamarin/xamarin-android/commit/b08240ee50e941cb326688cc0dcf5969ebfe5473)

**Comment by srdmnc** [comment] 2019-10-25 01:45
Btw, this error does not occur anymore after I restarted my Mac.

**Comment by VladislavAntonyuk** [comment] 2019-12-24 23:04
The issue is reproduced on Windows only. I can build app on macOS

**Comment by jonathanpeppers** [comment] 2020-01-02 13:58
@VladislavAntonyuk can you file a new issue including a build log? The error mentioned about would happen on both platforms.

@srdmnc I wonder if just doing a Clean or Rebuild at some point is actually what fixed this. Closing for now, but let us know if you hit it again.

**Closed by jonathanpeppers** 2020-01-02 13:58 UTC
Labels: Area: App+Library Build

**Comment by justintoth** [comment] 2020-03-24 19:29
I ran into a similar R8 build error just now after upgrading all of my nuget packages to the latest versions:

```
R8 : warning : Missing class: com.google.android.gms.gcm.GcmTaskService
R8 : error : Compilation can't be completed because some library classes are missing.
```

Here is the build log: [https://gist.github.com/justintoth/ec2a96d9b8abdd81749671fe7bf6a70f](https://gist.github.com/justintoth/ec2a96d9b8abdd81749671fe7bf6a70f)

For me, the solution was to install the Xamarin.GooglePlayServices.Gcm nuget package. I'm glad it worked but it's a little concerning because Gcm is deprecated, so this shouldn't be required.

**Comment by APIWT** [comment] 2020-08-07 14:12
I've run into this issue on my Mac and have tried the above steps. I might not be able to put together a repro. Would love some suggestions if possible!

**Comment by jonathanpeppers** [comment] 2020-08-07 14:31
@APIWT file a new issue with a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output), thanks!

**Comment by APIWT** [comment] 2020-08-07 14:33
@jonathanpeppers Is there any way to DM these logs to you guys? I can't share them publicly.

**Comment by jonathanpeppers** [comment] 2020-08-07 14:40
@APIWT file an issue with part of the log and we can go from there. It would be helpful to know which classes are in the error message and which `.aar` file it came from.

**Comment by APIWT** [comment] 2020-08-07 15:00
@jonathanpeppers Thanks! #4988
