### ISSUE TITLE
Case sensitivity issues on Linux builds

### ISSUE THREAD

**Issue by gamesguru** [xamarin/xamarin-android#2296] opened 2018-10-15 12:21 UTC
### The issue
Build is failing on Linux without adjusting some file names to fix case issues.

On Xamarin.Forms the situation is even worse because the Resource.designer.cs is not generated til middle of the build, so you have to actually run the build twice and rename that file for the second go.  A new one gets generated again the second time with the wrong case, which I find hilarious.

... I am wondering if this is an issue with the targets or the toolchain, and how easy it would be to address from either perspective?

#### Affected Files

- Strings.xml
- Resource.Designer.cs

**Comment by dellis1972** [comment] 2018-10-16 09:17
I suspect this is in part a problem with the template.  
The "name" of the designer file is controlled by the following MSbuild property which is in the `csproj`

`AndroidResgenFilename`

If this value in the csproj contains `Resource.Designer.cs` that might well be part of the problem.
In our codebase we prefer `Resource.designer.cs`. 

As for `Strings.xml` that is 100% controlled from the csproj. 

Can you post a gist of the csproj of the problem project?

**Comment by gamesguru** [comment] 2018-10-16 16:10
I will update it with a gist later today.  I am seeing this problem certainly on Xamarin projects generated on a Windows machine with any recent version of Visual Studio, and I am sure a majority of Xamarin projects are probably generated in this fashion.

If I am catching your drift, this is rather an issue with Visual Studio and the mono targets than xamarin-android itself, which is just playing catch up?  If so and if it is believed this is a valid issue, please show me specifically where to transfer the issue.

Thanks.

**Comment by grendello** [comment] 2018-10-18 06:37
@gamesguru This is, as @dellis1972 states, a problem with the templates and, as such, it will take the IDEs updating them in order to really fix this issue. However, for a quick fix you can enable Mono's `IOMAP` feature which will make the build slower (by much it depends on your system, usually not much) but will eliminate invalid filename case issues. To enable the feature please export the following variable in your environment before building the project:

    MONO_IOMAP=all

@sgmunn, @joj would you mind checking templates in VS for inconsistencies between filename casing in the project file(s) and the filesystem? Thanks!

**Comment by joj** [comment] 2018-10-18 10:06
I'm seeing inconsistencies in Strings.xml in the templates, but Resource.designer.cs always has this casing (capital R, lower case the rest). I'll fix the strings. All the AndroidResgenFile's are correct too. This might have been from a previous version. I know I fixed this issue at some point. I'll keep this open to track the Strings.

**Comment by joj** [comment] 2018-10-18 10:37
Fixed in WIndows, although it might be a while until this gets released (because of the place we're in right now for releases in Windows).

**Comment by gamesguru** [comment] 2018-10-18 11:08
Resource.designer does NOT always have the capital.  Please see the gist, the formsapp gist the lovely Xamarin Forms.  On line 13 there is a Resgen with the capital D, clearly on line 61 a compile include with a lowercase d.

And it's great that the issue will be fixed soon on Windows!  And the suggestion for `MONO_IOMAP` is interesting... but I am curious if there will be a full fix for Linux and for case-sensitive macOS systems?  Because _that_ is where the problem exists for us lol

**Comment by joj** [comment] 2018-10-18 11:11
RE casing in Resource.designer, I'm talking about the templates, in the version I have in master. It used to be wrong. I just wanted to confirm it's correct now.

**Comment by gamesguru** [comment] 2018-10-18 11:13
someone should be aware the same thing might going on with Visual Studio for Mac and the templates there

**Comment by sgmunn** [comment] 2018-10-25 13:48
Resource.designer.cs appears to be correct for android (native) projects, I've fixed strings.xml and for Forms projects we will pick up the changes from the above fixes once we bump to the latest templates.

**Comment by gamesguru** [comment] 2018-10-25 14:21
that is 110% correct that the Resource.designer issue was peculiar to xamarin forms

good jobs guys. thanks

**Comment by jonathanpeppers** [comment] 2018-11-26 17:38
@gamesguru I believe the issue is fixed, but our templates are not public on Github.

These are likely coming in the next major release of Visual Studio (no public release date yet that I know of). Feel free to comment when those come out if you still see this issue, thanks!

**Closed by jonathanpeppers** 2018-11-26 17:38 UTC
Labels: need-info
