### ISSUE TITLE
Multi thread run on multi thread safe native library crash

### ISSUE THREAD

**Issue by amdlopes** [xamarin/xamarin-android#4384] opened 2020-03-11 17:14 UTC
### Steps to Reproduce

1. Compile a lib.so with C code that is multi thread safe (in this case minpack) on Android Studio
2. Implement bindings to lib.so using JNIEnv and Java NIO buffers
3. On Xamarin.Android use multi Task/Thread launches of methods of lib.so

### Expected Behavior
The Xamarin.Android app should be able to launch different threads and run the code inside the lib.so generating always the same results/outcome

### Actual Behavior
Segmentation Fault (SIGSEV 11)
[libc] Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa0000004 in tid 26711 (HeapTaskDaemon)

### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.3.11 (build 1)
Installation UUID: 070c4b16-8b5b-4000-8272-4c53e64dbd3f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.101/Sdks
SDK Version: 3.0.101
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.1
	2.1.14

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.3 (15712)
Build 11C29

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.Android ===

Version: 10.0.6.2 (Visual Studio Community)
Commit: xamarin-android/d16-3/c407838
Android SDK: /Users/antoniolopes/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		7.0 (API level 24)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@476d72b9e32
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/antoniolopes/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:22 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-11-19 20:33:42 UTC

=== Xamarin Designer ===

Version: 16.3.0.256
Hash: 8a223bfd7
Branch: remotes/origin/d16-3
Build date: 2019-11-01 21:02:02 UTC

=== Xamarin.iOS ===

Version: 13.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:08-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803110001
Git revision: 6ee6ad2ec46ae5a08a1999ee4c815ac656a35b91
Build date: 2019-12-05 16:09:27+00
Build branch: release-8.3
Xamarin extensions: 56bd70ef2e327f71c615cfc29a47fd50685fadcb

=== Operating System ===

Mac OS X 10.15.1
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Thu Oct 17 16:17:15 PDT 2019
    root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

### Log File

```
[mono-rt] /proc/self/maps:
[mono-rt] 12c00000-52c00000 rw-p 00000000 00:01 21373                              /dev/ashmem/dalvik-main space (region space)_3400_3400 (deleted)
[mono-rt] 6f00c000-6f2a4000 rw-p 00000000 fe:01 196671                             /data/dalvik-cache/arm64/system@framework@boot.art
[mono-rt] 6f2a4000-6f3aa000 rw-p 00000000 fe:01 196728                             /data/dalvik-cache/arm64/system@framework@boot-core-libart.art
[mono-rt] 6f3aa000-6f3df000 rw-p 00000000 fe:01 196729                             /data/dalvik-cache/arm64/system@framework@boot-conscrypt.art
[mono-rt] 6f3df000-6f41c000 rw-p 00000000 fe:01 196730                             /data/dalvik-cache/arm64/system@framework@boot-okhttp.art
[mono-rt] 6f41c000-6f420000 rw-p 00000000 fe:01 196731                             /data/dalvik-cache/arm64/system@framework@boot-legacy-test.art
[mono-rt] 6f420000-6f463000 rw-p 00000000 fe:01 196732                             /data/dalvik-cache/arm64/system@framework@boot-bouncycastle.art
[mono-rt] 6f463000-6f49e000 rw-p 00000000 fe:01 196734                             /data/dalvik-cache/arm64/system@framework@boot-ext.art
[mono-rt] 6f49e000-6fdbe000 rw-p 00000000 fe:01 196736                             /data/dalvik-cache/arm64/system@framework@boot-framework.art
[mono-rt] 6fdbe000-6fe72000 rw-p 00000000 fe:01 196742                             /data/dalvik-cache/arm64/system@framework@boot-telephony-common.art
[mono-rt] 6fe72000-6fe7b000 rw-p 00000000 fe:01 196743                             /data/dalvik-cache/arm64/system@framework@boot-voip-common.art
[mono-rt] 6fe7b000-6fe83000 rw-p 00000000 fe:01 196745                             /data/dalvik-cache/arm64/system@framework@boot-ims-common.art
[mono-rt] 6fe83000-6fea7000 rw-p 00000000 fe:01 196747                             /data/dalvik-cache/arm64/system@framework@boot-apache-xml.art
[mono-rt] 6fea7000-6fed3000 rw-p 00000000 fe:01 196749                             /data/dalvik-cache/arm64/system@framework@boot-org.apache.http.legacy.boot.art
[mono-rt] 6fed3000-6fed8000 rw-p 00000000 fe:01 196751                             /data/dalvik-cache/arm64/system@framework@boot-smartbondingservice.art
[mono-rt] 6fed8000-6fedf000 rw-p 00000000 fe:01 196752                             /data/dalvik-cache/arm64/system@framework@boot-sprengine.art
[mono-rt] 6fedf000-6fee0000 rw-p 00000000 fe:01 196754                             /data/dalvik-cache/arm64/system@framework@boot-android.hidl.base-V1.0-java.art
[mono-rt] 6fee0000-6fee3000 rw-p 00000000 fe:01 196756                             /data/dalvik-cache/arm64/system@framework@boot-android.hidl.manager-V1.0-java.art
[mono-rt] 6fee3000-6feed000 rw-p 00000000 fe:01 196758                             /data/dalvik-cache/arm64/system@framework@boot-timakeystore.art
[mono-rt] 6feed000-6fef6000 rw-p 00000000 fe:01 196760                             /data/dalvik-cache/arm64/system@framework@boot-fipstimakeystore.art
[mono-rt] 6fef6000-6fef7000 rw-p 00000000 fe:01 196762                             /data/dalvik-cache/arm64/system@framework@boot-ucmopensslenginehelper.art
[mono-rt] 6fef7000-6fefb000 rw-p 00000000 fe:01 196764                             /data/dalvik-cache/arm64/system@framework@boot-esecomm.art
[mono-rt] 6fefb000-6fefc000 rw-p 00000000 fe:01 196766                             /data/dalvik-cache/arm64/system@framework@boot-SemAudioThumbnail.art
[mono-rt] 6fefc000-6ff37000 rw-p 00000000 fe:01 196768                             /data/dalvik-cache/arm64/system@framework@boot-knoxsdk.art
[mono-rt] 6ff37000-6ff65000 rw-p 00000000 fe:01 196770                             /data/dalvik-cache/arm64/system@framework@boot-sec_edm.art
[libc] Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa0000004 in tid 26711 (HeapTaskDaemon)
```

**Comment by grendello** [comment] 2020-03-11 18:33
Hi,

We are going to need more information to see what's going on here. If it's possible, please provide a sample app that reproduces the issue. Please also provide a full logcat output for the failed session which includes the full stack trace(s) for the crash. Also, is there a reason why you use JNIEnv to access the C library instead of using the .NET p/invoke mechanism?

**Comment by jonpryor** [comment] 2020-03-11 18:50
I don't know what these mean:

> 2. Implement bindings to lib.so using JNIEnv and Java NIO buffers
> 3. On Xamarin.Android use multi Task/Thread launches of methods of lib.so

**Comment by amdlopes** [comment] 2020-03-11 21:57
Thanks for the quick feedback @grendello and @jonpryor.

@grendello Unfortunately what you see in my report is the full stack of the log (obtained by Visual Studio Application output). This was from a SGS8 but I can try see if another device throws more info.
You raise a good question about JNIEn. And PInvoke. I use NDK to call native methods on Android and decided to bind to the java native methods. Is it possible to bind NDK code with PInvoke?

@jonpryor First of all it's always great to hear from you. We have been discussing some stuff that I raised over time since the very early days of monodroid/touch (circa 2011/12).
Sorry I didn't elaborate enough. 
2. Like I said above I do NDK code in the Android Studio project. I use java NIO direct buffers to pass big data structures to the native NDK functions. I then use the output .so library in the Xamarin Android project. I do the bindings using JNIEnv.CallMethod routines and using Java NIO direct buffers as well on c# side. I do it this way because it's really fast for speed of transfer of the big data structures from C# to Java/NDK.
3. On the Xamarin.Android project I launch multiple tasks(threads) with calls to one of the methods of that .so library and the issue happens.

Like I said, the C code I use is MT safe. Also I do the equivalent of this in iOS (bind to a native lib) and the issue doesn't happen...

I'll try to put a pack example project together without violating IP code we have. Would you need the Android native project or could it be only the Xamarin.Android project?

Regards

**Comment by grendello** [comment] 2020-03-12 07:46
@amdlopes any project which will reproduce the issue is fine :)

**Comment by amdlopes** [comment] 2020-03-12 20:30
Thanks @grendello.

I need to investigate a bit further myself during tomorrow and the weekend. 

By early next week if i don't find anything useful i'll post here an app example showing the crash.

**Comment by amdlopes** [comment] 2020-03-19 13:44
@grendello @jonpryor 

Sorry for the delay in getting back. I was investigating the issue myself in a bit more depth.

There is no need to provide you with a test case (for now). 

I can confirm that this is not a Xamarin.Android/JNI bindings issue. 
I realised now that the usage of the Java NIO Buffers is not thread safe. Using a lock around the NIO operations/bindings removes the crash.

This is unfortunate because it means we either gain a overhead by using locks or completely change the way we do bindings.

**Comment by VincentDondain** [comment] 2020-04-21 19:35
Hi @amdlopes, I'm glad to hear you found the cause of your issue and given that it does not look like a Xamarin.Android bug I'll be closing this issue.

I believe for the team to answer you about why the multi thread test case works on Android Studio and not with Xamarin.Android we'd need said test case to see what's happening on our side, a way to compare (:

You could always open a new issue as "question" to avoid mixing different problems.

**Closed by VincentDondain** 2020-04-21 19:35 UTC
Labels: need-info
