### ISSUE TITLE
Project crashes with gc bridge tarjan and runs fine with the old or new gc bridge implementation.

### ISSUE THREAD

**Issue by lexboss93** [xamarin/xamarin-android#2518] opened 2018-12-11 13:34 UTC
### Steps to Reproduce

1. Run a [sample project](https://github.com/lexboss93/tarjan_issue_reproduce).
2. Swipe ImageView left and right.
3. See app crashes with one of the following:
```
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Widget.Toast'.
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Graphics.Matrix'.
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Views.GestureDetector'.
```
then:
4. open /objdisposed/environment.txt and change it's contents to:
`MONO_GC_PARAMS=bridge-implementation=new`
or
`MONO_GC_PARAMS=bridge-implementation=old`
5. Clean project.
6. Run project again.
7. Make sure bridge implementation has switched to new (or old), i.e. see **GC_NEW_BRIDGE** tag in console:
`[Mono] GC_NEW_BRIDGE num-objects 15.....`
8. Swipe ImageView left and right.
9. See app runs okay.

### Expected Behavior
App doesn't crash when using tarjan gc

### Actual Behavior
App crashes when using tarjan gc, but runs fine with old and new gc

### Version Information

[gist](https://gist.github.com/lexboss93/33de42aeeda17c0ee5fc097ff313dbea)

### Log File

[gist](https://gist.github.com/lexboss93/02f2362d01ad540e72dc5d68f4433d8a)

**Comment by lexboss93** [comment] 2018-12-13 11:04
Originally I posted this on [bugzilla](https://bugzilla.xamarin.com/show_bug.cgi?id=56902) in the middle of 2017

**Comment by BrzVlad** [comment] 2020-01-07 14:59
Fixed by https://github.com/mono/mono/pull/18239

**Closed by BrzVlad** 2020-01-07 14:59 UTC

**Comment by brendanzagaeski** [comment] 2020-04-08 21:17
Duplicate of #2049
