### ISSUE TITLE
TrustFailure exception with inner exception: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED on android and xamarin-forms on android

### ISSUE THREAD

**Issue by xanderh** [xamarin/xamarin-android#4688] opened 2020-05-14 09:43 UTC
### Steps to Reproduce

(See attached project)
1. Click floating action button
2. App will attempt to enroll on our servers 10 times
3. App reports number of failures, and posts the exception to logcat

[EnrollmentTest.zip](https://github.com/xamarin/xamarin-android/files/4627081/EnrollmentTest.zip)

### Expected Behavior

App successfully enrolls 10 times in a row, and reports no errors, every time.

### Actual Behavior

App will somewhat consistently fail to enroll at first, but eventually succeed. The first attempt will almost always fail with a TrustFailure exception, but after a few tries will succeed. 

The error started occurring this week out of nowhere. It's been happening to apps in development, but also published apps that haven't been updated since March. 
Additionally, the error is only happening on Android, not on xamarin.iOS apps. We're seeing the issue on multiple versions of Android (confirmed on 4.4, 7.1, 8.1, and 9.0), and in apps made in xamarin.android and xamarin.forms. 

The certificates for the server look fine at a glance, but I have attached the certs as they appear in logcat in case they're the problem. The certificates are the same, no matter if it succeeds or fails. 

### Version Information

Microsoft Visual Studio Community 2019
Version 16.5.4
VisualStudio.16.Release/16.5.4+30011.22
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA425
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.5.236.49856
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.5.236.49856
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.5.236.49856
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.5.236.49856
Azure Functions and Web Jobs Tools

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30207.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.25+gdacdb9b7a1
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.5.514 (c4f36a9)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62003.05170
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20225.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.8.0.0 for F# 4.7   16.5.0-beta.20181.6+85af456066acd4e76d2bc7821b44a325e46f2fca
Microsoft Visual F# Tools 10.8.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.5.000.533 (d16-5@9152e1b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.5.0.470 (remotes/origin/d16-5@681de3fd6)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.5.49 (0904f41)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.0.100 (d16-5/988c811)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c0c5c78
    Java.Interop: xamarin/java.interop/d16-5@fc18c54
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.16.0.13 (b75deaf)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File

[cert logs.txt](https://github.com/xamarin/xamarin-android/files/4627222/cert.logs.txt)

Lastly, I apologize for not adding a label, I couldn't find a way to do so for some reason.

**Comment by radekdoulik** [comment] 2020-05-14 14:50
Looks like duplicate of https://github.com/xamarin/xamarin-android/issues/3682#issuecomment-535834783 and https://github.com/xamarin/xamarin-android/issues/3705

Please try to use the `HttpClientHandler.ServerCertificateCustomValidationCallback`

**Comment by xanderh** [comment] 2020-05-15 07:16
I'm not sure this is actually a duplicate of those issues. They seem to be about custom validation handlers not working. The problem is, we don't _have_ any custom validation handlers for SSL certificates, the built-in one worked fine up until the start of this week. Additionally, the version that worked in 9.0 but not in 10.0 still works just fine for us. 
On top of that, it started happening in apps that haven't been updated since March, but we didn't see any issues before Monday of this week.

If we add the following code, the issue stops happening:
`System.Net.ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicy) => { return true; };`
This is obviously bad practice as it completely bypasses any validation of the SSL certificate, opening us up to man-in-the-middle attacks. We could write our own code here, but it would likely not be as secure as something coming from Microsoft.

**Comment by radekdoulik** [comment] 2020-05-15 07:25
@baulig could you please take a look at this issue?

**Comment by Euler-KB** [comment] 2020-05-30 16:43
Same issue here for Xamarin.Android apps built in March. Failing to connect backend

**Comment by Euler-KB** [comment] 2020-05-30 17:33
> Same issue here for Xamarin.Android apps built in March. Failing to connect backend

Ooops. Just found the cause. Was an issue with  expired CA certificate (Issue might occur for all Positive SSL's purchased on Namecheap ) - Expiry date for CA was May 2020

**Comment by lsuarez5280** [comment] 2020-06-01 20:34
@Euler-KB we're having this problem during runtime due to (it seems) the CA bundle shipped with the Mono Droid instance of BoringSSL (see https://github.com/mono/mono/issues/12406#issuecomment-453998125) having an expired Sectigo cert for use with validation of our Sectigo-issued certificate. Using the Android native implementation of HttpClient and accompanying TLS 1.2 lib is causing failures in our HTTP requests. Do you have any suggestions as to what's to be done to remedy this?

**Comment by derekwheeler-tylertech** [comment] 2020-06-25 17:03
I can confirm this is also happening with certs from Sectigo. Only on android. I also debugged the cert chain and confirmed it is terminating in the root cert "AddTrust External CA Root" that expired on 5/30/2020 rather than their cross-signed root cert "USERTrust RSA Certification Authority", (which does exist in my version of android). This article, [https://www.cmu.edu/iso/service/cert-auth/addtrust.html](url) suggests ssl client implementations based on OpenSSL v1.1.1 or before might have this issue. Is it possible the version of BoringSSL that Xamarin uses is based on an older OpenSSL fork? I would also point out that this is a serious problem that we can't fix via code, short of disabling all SSL certificate validation, which obviously we can't do. This is currently affecting at least one of our clients (an entire large US city). Thanks

**Comment by visuall** [comment] 2020-06-26 10:34
I have been able to go around this by using the native Android http handler - AndroidClientHandler. It is properly validating the certificate in such case.

**Comment by derekwheeler-tylertech** [comment] 2020-06-26 18:38
Thanks @visuall . I tried that and still have the problem. I did a clean/rebuild, uninstalled the app, and rebooted the phone. But I appreciate the suggestion! 
I was able to find a not-so-great solution. In the phone, if I disable the now expired "AddTrust External CA Root" root cert the problem is fixed. The problem with this solution is trying to get this information to the end users. The way to set this in the phone Settings is different in each android version and also differs from phone vendor to vendor.

**Comment by skacofonix** [comment] 2020-07-15 15:25
I encountered a similar problem with Sectigo CA root expiration.
As @visuall say, i changed the implementation of HTTP handler from managed to Android.
This perfectly solved the problem for me

----

Implementation **before**
Fail to validate certificate chain with expired Sectigo cert.
```
public class HttpClientProvider
{
    public HttpClient Get()
    {
        return new HttpClient(new HttpClientHandler());    // Use legacy managed implementation
    }
}
```

----

Implementation **after** (Forms side)
Successfully validates the flawed certificate chain
```
public class HttpClientProvider
{
	public HttpClient Get()
	{
		var nativeHttpMessageHandler = DependencyService.Get<INativeHttpMessageHandlerProvider>().Get();
		return new HttpClient(nativeHttpMessageHandler);    // nativeHttpMessageHander is injected from Android project
	}
}
````
````
public interface INativeHttpMessageHandlerProvider
{
	HttpMessageHandler Get();
}
````
Implementation **after** (Android side)
_Don't forget to add dependency `System.Net.Http` from NuGet_
````
[assembly: Dependency(typeof(AndroidHttpMessageHandlerProvider))]
namespace SmartConnect.Droid.PlatformSpecific
{
    public class AndroidHttpMessageHandlerProvider : INativeHttpMessageHandlerProvider
    {
        public HttpMessageHandler Get()
        {
            return new AndroidClientHandler();
        }
    }
}
````

**Comment by derekwheeler-tylertech** [comment] 2020-07-15 16:23
Thanks @skacofonix for those details. 

For the xamarin team:

 I think my problem is that I'm using the SOAP classes that the wsdl generator spits out in visual studio, It's not clear to me whether those use the HttpClient internally or something else. An example class that gets produced is:

 // 
 // This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
 // 
<snip>
 public partial class MyExampleService : System.Web.Services.Protocols.SoapHttpClientProtocol { <snip> }

I had set the HttpClient to Android in the build settings, (https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows), thinking that that setting would be used by these SOAP classes but I guess that was wishful thinking? 

Thanks

**Comment by gerricom** [comment] 2021-09-30 18:38
Hello everybody. I came across this problem today when the [DST Root CA X3](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) expired earlier this day. Our Xamarin App on Android stopped working with the exact inner exception mentioned above. This CA was longtime used with let's encrypt certificates which we are using for our service.

Chrome and other browsers on Android had no problem in opening websites from on of our servers but the Xamarin app has. I renewed our current certificate and switched to the ISRG Root X2 chain which is not terminating in a DST Root but this had no impact.

I switched from the managed HTTPClient to the Android option but this has not changed the behavior either. 

Our current workaround is to not use LE for our certificates, but I'm not absolutely happy with that. So can somebody explain, why this is a problem? Am I doing something wrong? I guess that there must be others using Let's Encrypt with their Xamarin Apps and I guess they are in kind of trouble too? Or is it just us...?

**Comment by cvb941** [comment] 2021-09-30 19:25
Can confirm we have the same problem. We switched from a Sectigo certificate that ceased to work last week to Caddy which uses Let's Encrypt certificates, and today that one stopped working too 😐.

I will try the switch to the AndroidClientHandler to see if it changes something.

**Comment by gerricom** [comment] 2021-09-30 20:00
This is also reported in #6351.

**Comment by cvb941** [comment] 2021-09-30 20:08
We fixed it by using ZeroSSL instead of Let's Encrypt.

Here's how to set it up with Caddy https://caddy.community/t/using-zerossls-acme-endpoint/9406

**Comment by angelru** [comment] 2021-09-30 21:22
any solution??

**Comment by stereoa** [comment] 2021-10-01 00:58
Also seeing this issue today.

**Comment by darrenctlo** [comment] 2021-10-01 02:14
I have seen this with an app talking to an Akamai fronted service (uses LetsEncrypt for SSL certs).

You'll need to do two things:

1] Update your code to use AndroidClientHandler (long term belt & braces solution)
2] Update the trust chain for the SSL certificates on the server you're attempting to talk to (immediate fix)

Thanks to @skacofonix for the solution posted above.

**Comment by angelru** [comment] 2021-10-01 05:52
I use refit to access the api and the implementation is in Android

**Comment by Martinn2** [comment] 2021-10-01 06:04
The same issue with new lets encrypt root cert !

**Comment by uzairali001** [comment] 2021-10-01 07:42
I'm was also having the same issue but after some research trials and errors I found out the solution well it's more like a workaround.
The root certificate of Let's encrypt is expired so just remove it from the `yourcert-chain.prem`.
- Open the file in any text editor
- Locate the last `-----BEGIN CERTIFICATE-----` at the end of the file
- Delete it from `-----BEGIN CERTIFICATE-----` to `-----END CERTIFICATE-----`
- Save and reload the nginx

**Comment by daltonks** [comment] 2021-10-01 08:38
How to fix this when you generate new certs can be found at https://github.com/xamarin/xamarin-android/issues/6351#issuecomment-932022947

**Comment by kapsiR** [comment] 2021-10-01 08:39
I can confirm this issue with the [expiration of the DST Root CA X3](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/), which is still used for cross-signing ISRG Root X1.

An immediate fix on the server side is to force the ISRG Root X1.  
e.g. with Certbot `certbot renew --force-renewal --preferred-chain "ISRG Root X1"`

**Comment by lafin716** [comment] 2021-10-01 08:52
> How to fix this when you generate new certs can be found at [#6351 (comment)](https://github.com/xamarin/xamarin-android/issues/6351#issuecomment-932022947)

@uzairali001 This is perfect answer for our services. even if generate new certs with `ISRG ROOT X1` somehow there is legacy keychain data in .pem files so we removed it and reload the servere and it worked in xamarin-android

**Comment by igoras1993** [comment] 2021-10-01 11:47
@kapsiR I can confirm that this sovled the issue, TY very much!

For anyone that is experiencing the issue with running `certbot renew --force-renewal --preferred-chain "ISRG Root X1"` that sounds more or less like:
```
certbot: error: unrecognized arguments: --preferred-chain ISRG Root X1
```
It is probably corelated with old version of certbot. Certbot is shipped outdated with many systems.
You can check the certbot version with `certbot --version`. You should have at least `1.6.0` certbot version to use `--preferred-chain` flag ([click](https://community.letsencrypt.org/t/certbot-1-6-0-release/127841)).

[Here](https://certbot.eff.org/lets-encrypt/snap-nginx.html) You can find the steps for instaling the newest version of certbot using `snap`.

**Comment by Martinn2** [comment] 2021-10-01 20:11
I solved it by setting HttpClient implementation to Android and SSL/TLS implementation to Native TLS 1.2+ . It can by set by right clicking Android project, Properties -> Android Options -> Advanced. Link: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows

**Comment by angelru** [comment] 2021-10-02 07:59
> I solved it by setting HttpClient implementation to Android and SSL/TLS implementation to Native TLS 1.2+ . It can by set by right clicking Android project, Properties -> Android Options -> Advanced. Link: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows

This does not work for me and I use refit

**Comment by agusibrahim** [comment] 2021-10-02 16:35
its totaly break my apps with 1k active customer.
i was change httpclient impl to android and ssl to native. its doesnt work
anyone pls help

**Comment by uzairali001** [comment] 2021-10-02 16:37
> its totaly break my apps with 1k active customer. i was change httpclient impl to android and ssl to native. its doesnt work anyone pls help

You can try workaround I've posted https://github.com/xamarin/xamarin-android/issues/4688#issuecomment-931987246

**Comment by agusibrahim** [comment] 2021-10-03 03:30
> > its totaly break my apps with 1k active customer. i was change httpclient impl to android and ssl to native. its doesnt work anyone pls help
> 
> You can try workaround I've posted [#4688 (comment)](https://github.com/xamarin/xamarin-android/issues/4688#issuecomment-931987246)

thnx, i was handle in client app.
Issue is solved 🎉 thnx to all
i using custom httpclienthandler for logging purpose, without me knowing, it ignore the androidclienthandler that I have selected in the android project options.

**Comment by angelru** [comment] 2021-10-03 07:12
How is it possible that a call from flutter works and xamarin doesn't? this makes me rethink many things ...

**Comment by uzairali001** [comment] 2021-10-03 07:20
> How is it possible that a call from flutter works and xamarin doesn't? this makes me rethink many things ...

Probably because Xamarin doesn't have any update in last 6 months they are focusing on Maui

**Comment by juwens** [comment] 2021-11-26 17:39
> > How is it possible that a call from flutter works and xamarin doesn't? this makes me rethink many things ...
> 
> Probably because Xamarin doesn't have any update in last 6 months they are focusing on Maui

@jfversluis for your attention

**Comment by jfversluis** [comment] 2021-11-26 18:48
@juwens thanks for the ping!

@angelru 
> How is it possible that a call from flutter works and xamarin doesn't? this makes me rethink many things ...

Very simple, they work on a different tech stack and one has a bug right now. Not sure what comparing these two products, or this comments as a whole adds to this discussion to be honest. If you are considering changing careers, you're more than welcome to do so but please don't disrupt an otherwise constructive conversation.

@uzairali001 
> Probably because Xamarin doesn't have any update in last 6 months they are focusing on Maui

I understand that you're frustrated with this bug, I'm sorry about that. However this seems to be a bug in the mono runtime. That team is pretty far from the .NET MAUI team and has nothing to do with each other in terms of what is keeping us busy right now. And right now you are looking at the Xamarin.Android repo, which is still not the .NET MAUI team. Lastly, not having updates for 6 months is simply not true, but I get that it could be perceived as weird that we're focussing on the next thing while you have issues with the current thing.

Like above, I also don't see what this adds to the conversation here.

Please try to not derail this issue (or any issue) with things like these because not only will it not speed up fixing these bugs, it will also make people working hard on this feel bad, and potentially makes you look like a not so nice person to others on the internet.

If you have any complaints or remarks, feel free to find my email address on my GitHub profile so we can have a chat or I can put you in touch with the right person.

Unfortunately, I don't know anything about this bug so I can't add anything of value there.

**Comment by juwens** [comment] 2021-11-26 19:39
@jfversluis as a dev on the team, i think it's a bad idea to write 18! months after the bug was created, and several people posting here too, that nothing can be done, because you work on MAUI and "it's not a XF bug", and the author should create an issue for the mono runtime.

**1. you cannot ignore bugs of a production release, with the argument that you are working on the next version**
2. if it's a problem of the mono runtime, it should have been redirected by an MS employee, when you triaged it back in may 2020

![image](https://user-images.githubusercontent.com/11560817/143623459-dafc4c9e-b19b-4979-9440-92362fc4cfdb.png)

These things is what makes people more and more aggressive in there communication.

Complaining about severe nuisances (without any insight of the XF team) is the last resort devs have, before giving up and turning away from XF and moving to a competitor like Flutter.

//cc @maddymontaquila

**Comment by jfversluis** [comment] 2021-11-29 08:03
This is the last thing I will post about it here or anywhere, because this is still derailing this issue. As already mentioned: if you have something to see do it on an appropriate channel like a discussion. I am also kind of disappointed that I spend a lot of time talking to you about this @juwens and you still choose this approach.

> 1. you cannot ignore bugs of a production release, with the argument that you are working on the next version
I'm sorry you understood it this way, but that is not what I said nor meant.

> 2. if it's a problem of the mono runtime, it should have been redirected by an MS employee, when you triaged it back in may 2020

As already pointed out, there is a bug for this on the Mono repo, so if anything this should've been probably closed. But as I am not on this team, do not have any insights on how they work nor do I have even any rights to do anything on this repo, that is up to them.

> These things is what makes people more and more aggressive in there communication.

Aggression is _never_ the answer. If you are frustrated with something and you think Xamarin is no longer the right option for you, that is of course not what we want. But being bitter on the internet is never a good look on anyone.

**Comment by juwens** [comment] 2022-01-04 11:22
@radekdoulik
this is still an issue

**Comment by lmataf** [comment] 2022-01-20 03:45
![image](https://user-images.githubusercontent.com/20095895/150269681-21840edd-44b8-471a-9176-31e6af06b27d.png)
Solucionado en Visual Studio

**Comment by marek-safar** [comment] 2022-01-20 11:22
@steveisok please take a look

**Comment by naman20sharma** [comment] 2022-02-16 14:04
> Thanks @skacofonix for those details.
> 
> For the xamarin team:
> 
> I think my problem is that I'm using the SOAP classes that the wsdl tool, (i.e. Web References->Add Web Reference), spits out in visual studio, It's not clear to me whether those use the HttpClient internally or something else. An example class that gets produced is:
> 
> // // This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000. // public partial class MyExampleService : System.Web.Services.Protocols.SoapHttpClientProtocol { }
> 
> I had set the HttpClient to Android in the build settings, (https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows), thinking that that setting would be used by these SOAP classes but I guess that was wishful thinking?
> 
> Thanks

Hi Could you please help how were you able resolve this issue ? I am facing similar one as the we application is using Cert from Secticgo, and I am using an sdk that is internally using HttpClient.

**Comment by derekwheeler-tylertech** [comment] 2022-02-16 14:22
Sorry @naman20sharma. We never got any support on fixing this bug. We ended up giving instructions to the android users to delete the expired root cert (see my other earlier post) so that the cert chain ended up finding the valid root cert. A terrible solution. This bug caused the app to be broken for hundreds of our government app users.

**Comment by Nikola43** [comment] 2022-03-10 23:12
> I'm was also having the same issue but after some research trials and errors I found out the solution well it's more like a workaround. The root certificate of Let's encrypt is expired so just remove it from the `yourcert-chain.prem`.
> 
> * Open the file in any text editor
> * Locate the last `-----BEGIN CERTIFICATE-----` at the end of the file
> * Delete it from `-----BEGIN CERTIFICATE-----` to `-----END CERTIFICATE-----`
> * Save and reload the nginx

works for me

**Comment by Meekohi** [comment] 2022-10-20 17:48
Appears to still be an issue - cert is valid in e.g. Chrome but am getting `Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED` when trying to make a call from a Xamarin app on Android.

I worked around this by creating a custom https handler for the specific domain I was having an issue with (only used in local testing for us):
```C#
private HttpClient CreateHttpClient()
{
    if (Common.Helpers.EnvironmentVariables.APIPath.Contains("ngrok"))
    {
        var httpClientHandler = new HttpClientHandler();
        httpClientHandler.ServerCertificateCustomValidationCallback = (msg, cert, chain, errors) => { return true; }; // Ignore SSL errors for local development
        return new HttpClient(httpClientHandler);
    }
    return new HttpClient();
}
```

**Comment by awesome1128** [comment] 2023-02-15 18:21
> I'm was also having the same issue but after some research trials and errors I found out the solution well it's more like a workaround. The root certificate of Let's encrypt is expired so just remove it from the `yourcert-chain.prem`.
> 
> * Open the file in any text editor
> * Locate the last `-----BEGIN CERTIFICATE-----` at the end of the file
> * Delete it from `-----BEGIN CERTIFICATE-----` to `-----END CERTIFICATE-----`
> * Save and reload the nginx

What do you mean by "yourcert-chain.prem"?
I have cert.pem, chain.pem, fullchain.pem and privkey.pem files only. No any file that file extension is .prem
I deleted last `-----BEGIN CERTIFICATE-----` at the end of the file from fullchain.pem file.
Is that correct?

I am using visual studio 2019 and it's configured with remote server, but I keep getting "**System.Exception:** 'Something went wrong with cert validation" error.
I am spending much time to fix this problem, but no idea.

Please let me know your thoughts, thanks!

**Comment by jpobst** [comment] 2024-05-13 23:28
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.

**Closed by jpobst** 2024-05-13 23:28 UTC
Labels: Area: HTTP

**Comment by derekwheeler-tylertech** [comment] 2024-05-14 00:35
This was one of the final straws that made us decide to abandon the Microsoft mobile tech stack. We had apps in the field with thousands of corporate users that were affected by this bug. There was no work around. As a Microsoft Partner that was hard to swallow.

**Comment by juwens** [comment] 2024-05-21 13:32
This is hilarious, despite the name change from Xamarin.Android to `.Net for Android`, this repository is exactly the same as before. Even the target files provided by “.Net for Android” are still the same “xamarin.android….target”

But this ticket obviously needs to be closed, cause the issue is with Xamarin.Android.

'If you encouter a “similar” issue in the latest version of maui, please open a new ticket for “.Net for Android” in the same repository, which was formerly named “Xamarin.Android”'
😉

**Comment by jpobst** [comment] 2024-05-21 17:54
While they certainly share a good amount of code, two of the biggest changes between Xamarin.Android and .NET for Android are:

- .NET for Android now uses the exact same Base Class Libraries (BCL) as desktop .NET instead of Mono's BCL clone used by Xamarin.Android.
- The Android integration HTTP stack was completely rewritten.

These two changes should eliminate a large class of bugs that occurred on Xamarin.Android.
