### ISSUE TITLE
Open AndroidDeviceManager: System.Xml.XmlException: '.', Hexadecimal value 0x00, is an invalid character. Line 1, position 1.

### ISSUE THREAD

**Issue by Adlbert** [xamarin/xamarin-android#2335] opened 2018-10-24 13:37 UTC
### Steps to Reproduce

1. Install Visual Studio Version 15.8.7 on Windows 10 Home
2. Create new Xamarin project
3. Start Android Device Manager
3.1. Start Android SdkManager

### Expected Behavior
Android Device Manager or Android SdkManager should open

### Actual Behavior
Android Device Manager or Android SdkManager crash
No further information displayed

### Version Information

Visual Studio Version 15.8.7 
Android Device Manager Version 1.0.624.20
jdk1.8.0_191
Windows 10 v10.0.17134 64 bit

### Log File

`[18-10-24 13:21:18.96] Android Device Manager version 1.0.624.20 (1.0.624.20+7361af75d162a09d91b3af3b287c187c805161d1)
[18-10-24 13:21:18.96] Operating system: Windows 10 v10.0.17134 (Windows 10 Home; Microsoft Windows 10 v10.0.17134 (Windows 10 Home; 64-bit)), 64-bit
[18-10-24 13:21:19.03] [AppInfo] Detected Android SDK path: C:\Program Files (x86)\Android\android-sdk
[18-10-24 13:21:19.11] [ConfigManager] Config file path: <USER_HOME>\AppData\Local\Xamarin\AndroidDevices.exe_Url_xc3zboekagxckk4zetm2vqdih4yy0yl2\1.0.624.20\user.config
[18-10-24 13:21:19.11] [AppInfo] Set ANDROID_SDK_ROOT: C:\Program Files (x86)\Android\android-sdk
[18-10-24 13:21:19.12] [AppInfo] Picking up ANDROID_AVD_HOME: D:\Android\avd
[18-10-24 13:21:19.12] [AppInfo] Set JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0_191
[18-10-24 13:21:19.13] Unhandled exception occured
[18-10-24 13:21:19.14] System.Xml.XmlException: '.', hexidezimaler Wert 0x00, ist ein ungültiges Zeichen. Zeile 1, Position 1.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   bei System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   bei System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   bei System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   bei System.Xml.XmlTextReaderImpl.Read()
   bei System.Xml.XmlReader.MoveToContent()
   bei System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   bei System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   bei Xamarin.Installer.AndroidSDK.Manager.ConfigManager.LoadProperties()
   bei Xamarin.Installer.AndroidSDK.Manager.Helper..ctor(String cacheFolder)
   bei Xamarin.Installer.AndroidSDK.Manager.AndroidSDKManager.get_Helper()
   bei Xamarin.Installer.AndroidSDK.Manager.AndroidSDKManager.Initialize(IProgressMonitorFactory progressMonitorFactory, ILogAdapter logger)
   bei Xamarin.DeviceManager.AppInfo.Init()
   bei Xamarin.DeviceManager.XamarinAndroidDeviceManagerApplicationBase.App_Startup(Object sender, StartupEventArgs e)
   bei System.Windows.Application.OnStartup(StartupEventArgs e)
   bei Xamarin.DeviceManager.XamarinAndroidDeviceManagerApplication.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei Xamarin.DeviceManager.XamarinAndroidDeviceManagerApplicationBase.OnStartup(StartupEventArgs e)
   bei Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   bei Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   bei Xamarin.DeviceManager.XamarinAndroidDeviceManagerApplicationBase.Main(String[] args)
[18-10-24 13:21:19.14] Runtime terminating: True
`

Sry for german log.
The exception says: 
System.Xml.XmlException: '.', Hexadecimal value 0x00, is an invalid character. Line 1, position 1.

I worked around by creating an avd with the ../android-sdk/tools/bin/avdmanager.bat

> VS bug [#723620](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/723620)

**Comment by grendello** [comment] 2018-10-26 08:18
@joj can you please assign this bug to whoever is responsible for Android {SDK,Device} Manager in VS4W? Thanks!

**Comment by Keboo** [comment] 2019-01-04 20:09
Just ran into this situation on a fresh install on a new computer.
Received an error similar to the log file posted above.

After diagnosing through the AndroidDevices.exe it turned out that the problem was the file:
`%APPDATA%\Config\AndroidSDKManager\properties.xml` 
The file contents had somehow been set to 132 zero bytes (file attached for reference)
[properties.zip](https://github.com/xamarin/xamarin-android/files/2728385/properties.zip)

Replacing this file with a clean copy (shown below) fixed the issue:
```xml
<?xml version="1.0" encoding="utf-8"?><SDKManagerProperties><Property key="ManifestType" value="Xamarin" /></SDKManagerProperties>
```

## Sytem Information ##
Microsoft Visual Studio Professional 2017 
Version 15.9.4
VisualStudio.15.Release/15.9.4+28307.222
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA353
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.14.11009.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.9.02046.0
Azure Functions and Web Jobs Tools

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61810.11040
Microsoft SQL Server Data Tools

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Apache Cordova   15.123.7408.1
Visual Studio Tools for Apache Cordova

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.208
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.77 (d15-9@e3f40b477)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.4.2 (HEAD/8255f42fc)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

## Log File ##
```
[19-01-04 18:50:34.74] Android Device Manager version 1.0.642.13 (1.0.642.13+dd6b1cc3997e2cb18888343406fefc9af48bc05c)
[19-01-04 18:50:34.75] Operating system: Windows 10 v10.0.17134 (Windows 10 Pro; Microsoft Windows 10 v10.0.17134 (Windows 10 Pro; 64-bit)), 64-bit
[19-01-04 18:50:34.78] [AppInfo] Detected Android SDK path: C:\Program Files (x86)\Android\android-sdk
[19-01-04 18:50:34.82] [ConfigManager] Config file path: <USER_HOME>\AppData\Local\Xamarin\AndroidDevices.exe_Url_kuxt5xsmgfwoffj1jx5ldbtpdv0k4sk4\1.0.642.13\user.config
[19-01-04 18:50:34.84] Unhandled exception occured
[19-01-04 18:50:34.84] System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at Xamarin.Installer.AndroidSDK.Manager.ConfigManager.LoadProperties()
   at Xamarin.Installer.AndroidSDK.Manager.Helper..ctor(String cacheFolder)
   at Xamarin.Installer.AndroidSDK.Manager.AndroidSDKManager.get_Helper()
   at Xamarin.Installer.AndroidSDK.Manager.AndroidSDKManager.Initialize(IProgressMonitorFactory progressMonitorFactory, ILogAdapter logger)
   at Xamarin.DeviceManager.Common.AndroidSDKManagerWrapper.Init()
   at Xamarin.DeviceManager.AppInfo.Init()
   at Xamarin.DeviceManager.XamarinAndroidDeviceManagerApplicationBase.App_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at Xamarin.DeviceManager.XamarinAndroidDeviceManagerApplication.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Xamarin.DeviceManager.XamarinAndroidDeviceManagerApplicationBase.OnStartup(StartupEventArgs e)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at Xamarin.DeviceManager.XamarinAndroidDeviceManagerApplicationBase.Main(String[] args)
[19-01-04 18:50:34.84] Runtime terminating: True
```

**Comment by Letslearnxamarin** [comment] 2019-01-10 19:57
I had the same issue above.. clean installs of everything could not get it to work. The solution presented above resolved it for me to! Thank you!!

I believe running the uninstall.exe in the Android SDK folder might be what causes the corrupt xml file. not confirmed though.

**Comment by tanayayt** [comment] 2019-03-06 18:50
@Keboo desperately tried to fix the issue, with XmlException, and even reinstalled VS + Xamarin. Thanks a lot for saving my life, almost reinstall windows as my last resort :)

**Closed** 2019-04-22 15:21 UTC
Labels: Area: Device Manager, bug, vs-sync
