### ISSUE TITLE
Profiled AOT fails using d16-2

### ISSUE THREAD

**Issue by JonDouglas** [xamarin/xamarin-android#3168] opened 2019-06-04 19:48 UTC
### Steps to Reproduce

1. Create a new Forms application (Shell Template) in Visual Studio 2019 16.2
2. Turn on AOT and Enable Startup Tracing
![image](https://user-images.githubusercontent.com/1288848/58908701-7b358200-86ce-11e9-8851-6e8a048fe218.png)
3. Build fails with assembly could not be AOT'd - https://gist.github.com/JonDouglas/926759503764aa668c2f3d7cd11701c7

[ProfiledAOTForms.zip](https://github.com/xamarin/xamarin-android/files/3254219/ProfiledAOTForms.zip)

### Expected Behavior
Profiled AOT compiles and runs!

### Actual Behavior
Profiled AOT fails to compile.

### Version Information

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.2.0 Preview 3.0 [29003.217.d16.2stg]
VisualStudio.16.IntPreview/16.2.0-pre.3.0+29003.217.d16.2stg
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

Azure App Service Tools v3.0.0   16.2.154.3618
Azure App Service Tools v3.0.0

C# Tools   3.2.0-beta3-19281-01+3f10ddd4e64013c8e1627b24e766f9c84ef853a5
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.2.3 (373927b)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.2.0-beta3-19281-01+3f10ddd4e64013c8e1627b24e766f9c84ef853a5
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.2.0-beta.19277.5+42c125e3cbb5cb06256a413c4e742199fb0df1f3
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.2.0.63 (d16-2@559c0f212)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.2.0.261 (remotes/origin/d16-2@bf0ac3e07)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.111 (df1a265)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.4.0.26 (d16-2/9454caa)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e113ce925ba
    Java.Interop: xamarin/java.interop/d16-2@b2b2610
    LibZipSharp: grendello/LibZipSharp/master@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@4f717b6

Xamarin.iOS and Xamarin.Mac SDK   12.14.0.83 (f08d4e3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
### Log File

https://gist.github.com/JonDouglas/926759503764aa668c2f3d7cd11701c7

**Comment by brendanzagaeski** [comment] 2019-06-11 06:22
For searchability, I'll add that the MSBuild property associated with **Enable Startup Tracing** is: `$(AndroidEnableProfiledAot)`, and an example error message from the attached log file is:

```
[aot-compiler stdout] Mono Ahead of Time compiler - compiling assembly C:\ProfiledAOTForms\ProfiledAOTForms\ProfiledAOTForms.Android\obj\Release\90\android\assets\ProfiledAOTForms.Android.dll
[aot-compiler stdout] AOTID E1508391-3849-3C2D-2F0E-231C8A0BD12C
[aot-compiler stdout] Using profile data file 'C:\PROGRA~2\MICROS~1\2019\INTPRE~1\MSBuild\Xamarin\Android\startup-xf.aotprofile'
[aot-compiler stdout] * Assertion at /Users/builder/jenkins/workspace/archive-mono/2019-02/android/release/mono/mini/aot-compiler.c:11933, condition `res == 1' not met
[aot-compiler stdout] 
```

and then later:

```
XA3001: Could not AOT the assembly: Xamarin.Android.Arch.Core.Runtime.dll
```

**Comment by JonDouglas** [comment] 2019-06-11 14:04
Notes:

**_This is specific to Profiled AOT, this behavior is not exhibited with Regular AOT._**

**Comment by radekdoulik** [comment] 2019-06-11 14:57
Looks like problem when reading the profile.

```
static int
profread_int (FILE *infile)
{
	int i, res;

	res = fread (&i, 4, 1, infile);
	g_assert (res == 1);
	return i;
}
```

Might be Windows specific as we run the tests with profiled AOT on Mac jenkins builds.

**Comment by vargaz** [comment] 2019-06-11 15:06
Can you attach the profile file ?

**Comment by JonDouglas** [comment] 2019-06-11 15:31
@vargaz https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/startup-xf.aotprofile should help!

**Comment by vargaz** [comment] 2019-06-12 00:09
I can't reproduce on osx, looks like a windows problem.

**Comment by vargaz** [comment] 2019-06-12 00:14
Hopefully fixed by the PR.

**Closed** 2019-06-12 06:31 UTC
Labels: Area: Mono Runtime, Area: Mono runtime or AOT Compiler
