### ISSUE TITLE
Xamarin Android CookieManager ignores cookies with samesite value set

### ISSUE THREAD

**Issue by MdNaushad** [xamarin/xamarin-android#2284] opened 2018-10-10 18:14 UTC
### Steps to Reproduce

1. Create a new Xamarin Forms/Android Project.
2. In the MainActivity OnCreate, create a cookie by setting the value for samesite as "samesite=lax".
3. Add the cookie to the CookieManager:
```
var cookie = new Cookie
            {
                Name = ".WithSameSite.Cookies",
                Value = "13456789jhsvfshvdfjksDg48484751458sfgdfgdfg",
                Domain = ".example.com",
                Path = "/",
                HttpOnly = true,
                Secure = true,
                Expires = DateTime.UtcNow.AddHours(1)
            };
var cookieValue = $"{cookie.Name}={cookie.Value};domain={cookie.Domain};path={cookie.Path};secure;httponly;samesite=lax;";
            CookieManager.Instance.SetCookie("https://www.example.com/", cookieValue);
```
4) Try to fetch the cookie :
```
//fetch cookies with same site
            var fetchCookie = CookieManager.Instance.GetCookie("https://www.example.com/");
            Console.WriteLine($"Cookie fetched:{fetchCookie 

}");
```

### Expected Behavior
The cookie should be fetched
### Actual Behavior
The cookie is not getting fetched

**Comment by jonathanpeppers** [comment] 2018-10-15 14:21
@MdNaushad I think we just need to reflect upon your code a little.

A couple points:
* It looks like you create a `System.Net.Cookie` object, that is a BCL type (not Android)?
* It looks like you are calling the `Android.WebKit.CookieManager` class to set the cookie, which only takes a string?

I'm not sure what using this `Cookie` object is doing for you? Also you might be running into this semi-colon issue as mentioned here: https://medium.com/@ericluapp/something-might-be-confused-about-cookiemanager-setcookie-422e6e28aacf

I just changed the code to this and it's working for me:
```csharp
var manager = CookieManager.Instance;
manager.SetCookie ("https://www.example.com/", "abcd=1234");
var cookie = manager.GetCookie ("https://www.example.com/");
Android.Util.Log.Debug ("MyApp", $"Cookie: {cookie}");
```

I'm not sure this will persist between app launches or not (you didn't mention in your steps). Closing this for now, as I think it is an Android API usage issue and not an issue with Xamarin.Android. If you have further questions about Android APIs, I think StackOverflow would be a better place for those.

Hope this helps, thanks!

**Closed by jonathanpeppers** 2018-10-15 14:21 UTC

**Comment by MdNaushad** [comment] 2018-10-15 14:35
Hey @jonathanpeppers : Thank you for looking into this.
In my issue I have mentioned just the important steps of the flow. To answer your questions:
* It looks like you create a `System.Net.Cookie` object, that is a BCL type (not Android)?
Yes, the project I am using is `Xamarin.Forms`, I also created a new project to replicate the issue, unfortunately I am not able to attach my test project here.

It looks like you are calling the `Android.WebKit.CookieManager` class to set the cookie, which only takes a string?

Yes I am using `Android.WebKit.CookieManager` to set the cookie. The `SetCookie `method accepts two parameters, first one is URL and second one is Cookie, the cookie has to be string with ";" separated properties.
If you see in this line of code, I am forming a cookie by extracting the values from the System.Net.Cookie object:
`var cookieValue = $"{cookie.Name}={cookie.Value};domain={cookie.Domain};path={cookie.Path};secure;httponly;samesite=lax;";`
The final cookie looks something like this:
`.WithSameSite.Cookies=13456789jhsvfshvdfjksDg48484751458sfgdfgdfg;domain=.example.com;path=/;secure; httponly; samesite=lax;`

In the code that you have written, it's working of course because the "samesite=lax;" value is not set for the cookie that you created. 
Here is your modified code:
```
var manager = CookieManager.Instance;
manager.SetCookie ("https://www.example.com/", "abcd=1234;samesite=lax;httponly;secure");
var cookie = manager.GetCookie ("https://www.example.com/");
Android.Util.Log.Debug ("MyApp", $"Cookie: {cookie}");
```

Can you please try this and let me know if it stills work?

**Comment by jonathanpeppers** [comment] 2018-10-15 16:31
> Also you might be running into this semi-colon issue as mentioned here: https://medium.com/@ericluapp/something-might-be-confused-about-cookiemanager-setcookie-422e6e28aacf

Android's API here doesn't like multiple semi-colons at once, take a look at the above article written by a Java/Android dev. I think you are hitting a problem with how to use Android APIs, and this is not a bug in Xamarin.Android, thanks!

**Comment by vd3d** [comment] 2020-07-08 22:03
Hi @jonathanpeppers , it is very interesting... but in my case, the web site I visit set the cookie (not my xamarin app). So, I have no control on this ! If I use a Desktop Chrome it works fine, but with the Xamarin+WebView then I got this issue too !

By example, the web site do something like this:

`document.cookie = '{cname}={cvalue}' + expires + ';SameSite=None;Secure;path=/';`

And so, all my cookies are deleted and replaced with this one :-(

**Comment by vd3d** [comment] 2020-07-08 22:15
I'm not 100% sure my problem is the same, but in my case, I do the following:

1) [from Xamarin.Android.WebView] I set a cookie with 

```
CookieManager.Instance.SetCookie(cookieDomain, cookieName + "=" + cookieValue);
CookieManager.Instance.Flush();
```

2) [from my HTML/Javascript app] The web application do a Javascript call to set a cookie, like this:

`document.cookie = cname + "=" + cvalue + expires + ";Secure;path=/";`

3) [from Xamarin.Android.WebView] An finally, I try to read all the cookies like this:

`string cookieHeader = CookieManager.Instance.GetCookie(url);`

But the cookieHeader does not contains the Javacript-cookie, only the first one !!

**Comment by jonathanpeppers** [comment] 2020-07-09 00:01
@vd3d I think you are having an issue on the JavaScript side, looking at this post:

https://stackoverflow.com/a/16842361

It seems like you need to set `document.cookie` multiple times for multiple key-value pairs.

I know nothing about JavaScript, though!

![image](https://user-images.githubusercontent.com/840039/86981880-6cc95d80-c14d-11ea-96e6-9e36af72f42d.png)

**Comment by vd3d** [comment] 2020-07-09 05:54
LOL :-)

The javascript side works perfectly. The in Xamarin, I cannot read all the cookies that are added by the website,
when I do:

string cookieHeader = CookieManager.Instance.GetCookie(url);

I only get my cookies... I don't see all the "AspNet" cookies by example!

**Comment by brendanzagaeski** [comment] 2020-07-10 00:47
This is a little outside the scope of what is typically addressed in GitHub issues for Xamarin.Android because it is part of the upstream Android API behavior rather than anything specific to Xamarin, but note that when using [`WebView`](https://developer.android.com/reference/android/webkit/WebView) and [`CookieManager`](https://developer.android.com/reference/android/webkit/CookieManager), there are at least 2 pieces required to see cookies that are set via JavaScript.

1. The WebView must finish loading the URL before the cookies are read. For example, create a custom WebViewClient:

    ```csharp
    public class MyWebViewClient : Android.Webkit.WebViewClient
    {
        public override void OnPageFinished(WebView view, string url)
        {
            var cookie = CookieManager.Instance.GetCookie(url);
            Android.Util.Log.Debug("MyApp", $"Cookie: {cookie}");
            base.OnPageFinished(view, url);
        }
    }
    ```

    And set it on the WebView:

    ```csharp
    webView.SetWebViewClient(new MyWebViewClient());
    ```

2. JavaScript must be enabled for the WebView:

   ```csharp
   webView.Settings.JavaScriptEnabled = true;
   ```
