### ISSUE TITLE
AccountManager::AddAccount sometimes throws a Java.Lang exception

### ISSUE THREAD

**Issue by bgavrilMS** [xamarin/xamarin-android#4898] opened 2020-07-07 15:56 UTC
### Steps to Reproduce

MSAL.NET is the official Azure identity SDK and we have xamarin android 9 and 10 bindings.

1. See code snippet [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/2a90d37c0b83213e64e40d0ac1948ceb8e0f9ce1/src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerHelper.cs#L130)
2. AddAccount sometimes fails when calling `GetResult` on the `IAccountManagerFutureInvoker` object

Call stack: 

Java.Lang.Exception: Exception of type 'Java.Lang.Exception' was thrown.

JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms)
IAccountManagerFutureInvoker.GetResult (System.Int64 timeout, Java.Util.Concurrent.TimeUnit unit)

### Expected Behavior
No Java.Lang exceptions should reach consumer libraries and apps.

### Actual Behavior
Java.Lang exception

### Version Information

Microsoft Visual Studio Enterprise 2019
Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA866
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.6.948.25768
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.6.948.25768
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.948.25768
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.6.948.25768
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.6000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   11.1.209
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.6.20100.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.11.104.25275
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.6000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.6000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.6000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.6.20100.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - IronPython support   16.6.20100.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.6.20100.1
Profiling support for Python projects.

Python - VC Project Support   16.1.19129.1
Provides support for launching C++ projects with Python debugging enabled.

SmartPaster2013   1.0
Paste clipboard into comments or string builder

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SonarLint for Visual Studio   4.23.0.19399
SonarLint is an extension to your favorite IDE that provides on-the-fly feedback to developers on new bugs and quality issues injected into their code.

SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.30020
Visual C++ for Linux Development

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Extension for Azure Sphere   20.4.7.49790
Visual Studio Extension for Azure Sphere

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.6.000.1061 (d16-6@8e68aa8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by grendello** [comment] 2020-07-09 07:18
Hi, we will need more information in order to diagnose the issue. It would be great if you could attach a small, full, application which reproduces the issue. If not possible, please attach a full logcat output of the application run when the crash happens after configuring your device to log more information:

```shell
> adb shell setprop debug.mono.log default,assembly,timing=bare
```

If you can't obtain a full logcat, we will need to at least see the entire exception stack trace with several lines of output preceding it in the log. Thanks!

**Comment by rosrivas** [comment] 2020-07-09 20:20
This issue was reported in the prod, so we dont have access to logcat logs. I have attached the stack trace.
[callstack.txt](https://github.com/xamarin/xamarin-android/files/4899308/callstack.txt)

**Comment by grendello** [comment] 2020-08-11 07:52
There's a very, very weird stack trace in there:

```
  Java.Lang.Exception: Exception of type 'Java.Lang.Exception' was thrown.                                                                                                                                                                                                                             
    at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <40381f92a1394637b9b13a141c88a815>:0                                                               
    at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <ad035f4251a648c6ba5e857eec18e322>:0                                                                                                                         
    at Android.Accounts.IAccountManagerFutureInvoker.GetResult (System.Int64 timeout, Java.Util.Concurrent.TimeUnit unit) [0x0006d] in <ad035f4251a648c6ba5e857eec18e322>:0                                                                                                                            
    at Android.Accounts.IAccountManagerFutureExtensions+<>c__DisplayClass0_0.<GetResultAsync>b__0 () [0x00000] in <ad035f4251a648c6ba5e857eec18e322>:0                                                                                                                                                 
    at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <68c3eac6351b443daaf90802f851fd62>:0                                                                                                                                                                                         
    at System.Threading.Tasks.Task.Execute () [0x00000] in <68c3eac6351b443daaf90802f851fd62>:0                                                                                                                                                                                                        
    at null.null                                                                                                                                                                                                                                                                                       
    at Microsoft.Identity.Client.Platforms.Android.AndroidBrokerHelper.GetBrokerAuthTokenSilentlyAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload, Android.App.Activity callerActivity) [0x000de] in <62c5f81aa08b40f6a5628154f09a4f0a>:0                                    
    at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenInternalAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload) [0x0034f] in <62c5f81aa08b40f6a5628154f09a4f0a>:0                                                                                     
    at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenUsingBrokerAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] brokerPayload) [0x00091] in <62c5f81aa08b40f6a5628154f09a4f0a>:0                                                                                   
    at android.accounts.OperationCanceledException                                                                                                                                                                                                                                                     
    at android.accounts.AccountManager$AmsTask.internalGetResult(AccountManager.java:2328)                                                                                                                                                                                                             
    at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2340)                                                                                                                                                                                                                     
    at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2252)
```

Note the `at null.null` bit

**Comment by jonpryor** [comment] 2020-08-25 16:56
> ### Expected Behavior
> 
> No Java.Lang exceptions should reach consumer libraries and apps.

I do not understand how you would find this to be "expected".

The [`AccountManagerFuture.getResult()`](https://developer.android.com/reference/android/accounts/AccountManagerFuture#getResult()) method is documented as potentially throwing one of three exception types:

  * `android.accounts.OperationCanceledException`
  * `android.accounts.AuthenticatorException`
  * `java.io.IOException`

*All* of these exception types will inherit, eventually, `Java.Lang.Exception`.

In a Release build of an app, when the linker is run, it is entirely possible -- plausible, even! -- that the above types may be linked away.  Consequently, when a Java exception type enters managed code and Xamarin.Android needs to wrap & throw the exception, it is thus entirely possible that `Java.Lang.Exception` is the closest existing (post-linking) exception type within the app.

It thus makes *perfect sense* (to me) that a `Java.Lang.Exception` could be thrown from the `IAccountManagerFuture.GetResult()` method.

If you want a more concrete type, you'll need to ensure that those types exist after linking, e.g. by using those types in a `catch` block:

```csharp
try {
    var r = result.GetResult (…);
}
catch (Android.Accounts.OperationCanceledException e) {
    // …
}
```

Thus, *given* that a Java exception *is documented as being potentially thrown* from the method in question, *how* is it at all reasonable to expect *no* Java exception to be thrown from the method?

I do not understand the bug report.

**Comment by jonpryor** [comment] 2020-08-25 17:01
…that said, the [stack trace](https://github.com/xamarin/xamarin-android/issues/4898#issuecomment-671789696) *is* weird; why is one of the stack trace entries a *type*, and not a method?  How does a type *call* a method?

```
…
    at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenUsingBrokerAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] brokerPayload) [0x00091] in <62c5f81aa08b40f6a5628154f09a4f0a>:0
    at android.accounts.OperationCanceledException
…
```

Confusing as that may be, it *does* mention one of the documented exception types, `android.accounts.OperationCanceledException`, leading me to infer that Java threw an `OperationCanceledException` instance…and then various bits of `async`/`await` "machinery" entered the picture and made the stack trace ever more confusing.  (I'll throw the `null.null` line at the feet of `async`/`await` as well, for good measure!)

It thus certainly looks like Java code threw an exception, and we marshaled the `OperationCanceledException` as a `Java.Lang.Exception`, in all likelihood because that was the only post-linker Exception type present in `Mono.Android.dll` to use, so this all "makes sense," if you squint just right.

…and again, if you want `OperationCanceledException` to be the actual runtime type, you need to ensure that `OperationCanceledException` survives the linking process.  A `catch(OperationCanceledException)` block will do that, among other things.

**Comment by trwalke** [comment] 2020-09-03 18:13
Do you have a code sample or a doc that can help us understand this better?

**Comment by trwalke** [comment] 2020-09-03 23:42
Thanks @jonpryor. I think this makes sense to me, we will try catching these exceptions so that we can get the runtime types and diagnose further if needed.

**Comment by grendello** [comment] 2020-10-06 07:14
@trwalke I am going to close this issue under assumption that it is resolved for you. If not, please reopen it, thanks!

**Closed by grendello** 2020-10-06 07:14 UTC
Labels: Area: App Runtime, need-info
