### ISSUE TITLE
[Bug] Deploy failed

### ISSUE THREAD

**Issue by SkyQuant** [xamarin/xamarin-android#3683] opened 2019-09-25 10:49 UTC
Why can't I emulate simple "Hello world" Xamarin.Forms application with VS2019 16.3, AMD FX3200 CPU (no Hyper-V)?

![image](https://user-images.githubusercontent.com/6097882/65594108-c5eb4a80-df9a-11e9-873c-299de1224a21.png)

**Comment by grendello** [comment] 2019-09-25 13:05
@SkyQuant The problem is both frustrating and with a simple explanation. The Android emulator (built on top of QEMU) requires that the host operating system supports accelerated virtualization (e.g. KVM on Linux, HyperVisor Framework or HAXM on macOS, HyperV or HAXM on Windows) and will refuse to work if none is found. In your case there's no HyperV so you have just one option left - HAXM. However, here be dragons - HAXM does **not** support non-Intel CPUs (HAXM is an Intel product and the reasons why it doesn't support AMD CPUs is probably not related to technical matters) and since your machine uses an AMD CPU the result is what you experienced. Your only option (assuming you don't want to buy an Intel-based computer) is to enable HyperV. Alas, there's not much we can do except to offer this explanation and so I'm going to close the issue, thanks for reporting!

**Comment by grendello** [comment] 2019-09-25 13:06
OTOH, I'm puzzled as to how you even started the emulator without HyperV :) - are you using an older version?

**Closed by grendello** 2019-09-25 13:05 UTC
