### ISSUE TITLE
DateTime.Now is paused the Thread/Task after set time/date

### ISSUE THREAD

**Issue by VasenevEA** [xamarin/xamarin-android#4612] opened 2020-04-24 10:41 UTC
### Steps to Reproduce

1. Run task
`
await Task.Run(async () =>
            {
                while (!is_cancelTimeUpdater)
                {
                    var dt = DateTime.Now;
                    Debug.WriteLine(dt);
                    await Task.Delay(1000);
                }
            });`
2. Set date and time earlier then Current
`
var date = e.Value.Date;
Calendar c = Calendar.Instance;
c.Set(2019, 1, 1, 10, 10, 0);  
var alarmManager = Activity.GetSystemService(Context.AlarmService).JavaCast<AlarmManager>();
alarmManager.SetTime(c.TimeInMillis);`

3. After that DateTime.Now does'nt return value and Task is is paused

### Expected Behavior
DateTime.Now return value
### Actual Behavior
DateTime.Now does'nt return value, and Task is paused
### Version Information
Android 8.1

**Comment by grendello** [comment] 2020-04-24 16:05
@VasenevEA please attach a small application which reproduces the issue. Very often other factors influence the behavior of the app, not just the code. Thanks!

**Comment by grendello** [comment] 2020-05-28 07:23
Since the requested information hasn't been provided, I'm going to close this issue. Please reopen if the information becomes available, thanks!

**Closed by grendello** 2020-05-28 07:23 UTC
Labels: need-info
