### ISSUE TITLE
NO ARCHIVING possible using AOT or Traced AOT on VS 2019 16.2 nor on VS4Mac 8.3 preview

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/xamarin-android#3394] opened 2019-07-26 23:15 UTC
### Steps to Reproduce

1. create xamarin.forms app with configuration as below in android
2. rebuild and archieve for publish
3. 

```
 <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>false</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidUseSharedRuntime>False</AndroidUseSharedRuntime>
    <DebugType>
    </DebugType>
    <AndroidLinkMode>Full</AndroidLinkMode>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidCreatePackagePerAbi>true</AndroidCreatePackagePerAbi>
    <JavaMaximumHeapSize>1G</JavaMaximumHeapSize>
    <AotAssemblies>true</AotAssemblies>
    <EnableLLVM>true</EnableLLVM>
    <AndroidAotAdditionalArguments>no-write-symbols,nodebug</AndroidAotAdditionalArguments>
    <DebugSymbols>false</DebugSymbols>
    <BundleAssemblies>true</BundleAssemblies>
    <Debugger>Xamarin</Debugger>
    <AndroidEnableMultipleDex>true</AndroidEnableMultipleDex>
    <AndroidExplicitCrunch>true</AndroidExplicitCrunch>
    <AndroidKeyStore>True</AndroidKeyStore>    <AndroidSigningKeyStore>../../Keystore/app_cert/app_cert.keystore</AndroidSigningKeyStore>
    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidSupportedAbis>armeabi-v7a;x86;x86_64;arm64-v8a</AndroidSupportedAbis>
  </PropertyGroup>
```

### Expected Behavior
it creates apk
### Actual Behavior
 It doesnt work. it fails with various reasons. 
On Windows it fails as cannot AOT xx package. because it randomly throws for different nuget packages. I dont believe that it is any package but general AOT process.
on mac throws different error as below sample project and log file.

**Comment by EmilAlipiev** [comment] 2019-07-28 15:00
I have created a test project that fails on both using AOT or traced AOT. please try both by enabling. It fails not always. sometimes it works sometimes it fails. more often fails. once it fails, it show "package creation failed", do another archiving straight away without building and it works but apk is corrupt or single apks per abis are missing.
here is it log from failed archiving https://gist.github.com/EmilAlipiev/c4ff008bd7308bc8813d184457461dbe


[testapp.zip](https://github.com/xamarin/xamarin-android/files/3439295/testapp.zip)

**Comment by brendanzagaeski** [comment] 2019-07-29 17:26
Thanks for the report and the test case!

**For the issue on Windows:**

Curiously, running **Build > Archive** succeeded for me with the attached test case in the Release configuration on Visual Studio 2019 version 16.2. I also tried with a new project using the **Mobile Forms (Xamarin.Android)** template, pasting in the Release configuration properties mentioned, removing the keystore properties (since they wouldn't match my local configuration), and running **Build > Archive**. That also worked OK.

As a next step for the issue on Windows, if you could collect and attach back the diagnostic MSBuild output for a failed build that runs the `SignAndroidPackage` MSBuild target, that would be perfect:

 1. In a [Developer Command Prompt](https://docs.microsoft.com/dotnet/framework/tools/developer-command-prompt-for-vs), use the `cd` command to change to the directory containing your *.sln* file.
 2. Run a command similar to the following to perform the build:

    ```cmd
    msbuild -restore -t:SignAndroidPackage -p:Configuration=Release -bl
    ```

 3. Assuming the build fails as before with an error related to a NuGet package, zip up and attach back the *msbuild.binlog* file that is generated in the solution directory alongside the *.sln* file.

    Note that this log file does contain environment variables, including the Windows user name, so if you prefer to attach it privately a few options are:

      * Upload the *msbuild.binlog* file to a temporary private GitHub repository, and add me (brendanzagaeski) as a collaborator.
      * Or use **Help > Send Feedback > Report a Problem** from within Visual Studio to create an item on [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Those allow private attachments. Then you can link to the Developer Community item here, and I'll close the Developer Community item to point to this GitHub issue and we can continue the discussion here.
      * Or send a one to one message to me on Gitter, for example using a `/query @brendanzagaeski` command from within the [Xamarin.Android Gitter channel](https://gitter.im/xamarin/xamarin-android), and we can coordinate on another way to send the file non-publicly.

(To make one wild guess about the failures you're seeing on Windows, a scenario where I have seen failures for builds with AOT enabled is when I had the virtual memory paging file disabled on Windows and one of the AOT compilation consumed all of the available system memory. If you are seeing failures during the AOT compilation step itself, there's a chance that watching the system memory usage during the build might reveal some useful info too.)

* * *

**For the issue on macOS:**

For the issue on macOS, I was able to reproduce the "The "FilterAssemblies" task failed unexpectedly." error using a new **Master-Detail Forms App**. So far it looks like it is unrelated to the behavior on Windows. Interestingly, I only saw the error using a new app. For some reason, the attached *testapp.zip* example archived successfully. I will investigate a bit more to see if I can identify the difference between the projects, and I will plan to report a follow-up issue.

**Comment by EmilAlipiev** [comment] 2019-07-29 18:30
Hi @brendanzagaeski
thanks for looking into this. I created this issue mainly for Vs4Mac indeed as it is my main dev environment. I tested intensively on Mac using my own large project which fails every time and wanted to see on a test project which also fails but not often.
Here is the funny case, I try to achieve and it throws this exception. Straight away you do another archive and it works without error but when you look into the generated archive, it has only one unified apk although I have split into abis true, it doesn't generate. I dont know this apk is weather healthy as well. I didn't verify that
On Windows I had also failed but I usually get typical "xxx library cannot be AOT", you are familiar with this error I believe. it is not specific Nuget because every time it returned different Nuget package.
I hope that we can find a quick solution on VS4Mac as it prevents releases for us.

**Comment by EmilAlipiev** [comment] 2019-07-29 19:30
on Mac, I get also below error message. I believe that this is related to EmbedAssembliesIntoApk. when I turn this off, archiving worked

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3045,3): error MSB4018: The "BuildApk" task failed unexpectedly.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3045,3): error MSB4018: System.IO.FileNotFoundException: Could not find file "/Users/user/Projects/DevOps/myapp/myapp/myapp.Droid/obj/Release/android/bin/packaged_resources-armeabi-v7a"
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3045,3): error MSB4018: File name: '/Users/user/Projects/DevOps/myapp/myapp/myapp.Droid/obj/Release/android/bin/packaged_resources-armeabi-v7a'
```

**Comment by EmilAlipiev** [comment] 2019-07-29 22:54
On Windows VS2019 16.2 i have just tried build my app and It throw cannot AOT exception. here is the full log file.

https://gist.github.com/EmilAlipiev/6604cfac03cb2a0ef5691fcd88f44a88

**Comment by brendanzagaeski** [comment] 2019-07-30 01:53
**For the first symptom on macOS:**

The cause of the `The "FilterAssemblies" task failed unexpectedly.` error on macOS turned out to be fairly subtle, so it took me a bit of time to make sure I had figured out the best team to investigate. I have now reported the problem for further investigation by the team who works on the **Archive for Publishing** feature:

<https://developercommunity.visualstudio.com/content/problem/666127/first-archive-for-publishing-attempt-after-loading.html>

As you noticed, it appears that rerunning the **Archive for Publishing** command after the initial failure does correctly complete the archiving process and is a valid workaround.

**For the other symptom on macOS:**

> on Mac, I get also below error message. I believe that this is related to EmbedAssembliesIntoApk. when I turn this off, archiving worked
> 
> ```
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3045,3): error MSB4018: The "BuildApk" task failed unexpectedly.
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3045,3): error MSB4018: System.IO.FileNotFoundException: Could not find file "/Users/user/Projects/DevOps/myapp/myapp/myapp.Droid/obj/Release/android/bin/packaged_resources-armeabi-v7a"
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3045,3): error MSB4018: File name: '/Users/user/Projects/DevOps/myapp/myapp/myapp.Droid/obj/Release/android/bin/packaged_resources-armeabi-v7a'
> ```

This looks like <https://github.com/xamarin/xamarin-android/issues/3083>. The expected way to stop that problem would be to disable AAPT2 (for example by unchecking **Use incremental Android packaging system (aapt2)** in the **Android Build** section of the **Project Options**). 

On the other hand, I see you've commented on <https://github.com/xamarin/xamarin-android/issues/3083>. So if you are seeing this error in a scenario where you have already disabled AAPT2, then the next best step would be to report a [new separate issue](https://github.com/xamarin/xamarin-android/issues/new) with the command line diagnostic MSBuild output for the `SignAndroidPackage` target (as you collected on Windows for the AOT issue) and if possible also a test case that demonstrates that issue. (I tried a quick experiment with the *testapp.zip* project from this report, but that archived successfully for me.) Thanks in advance for your patience with reporting the additional information for that problem in a new issue!

(Side note just to be thorough: For a Release build, you will need `EmbedAssembliesIntoApk` to be `true` so that all of the managed code will be included as part of the APK file instead of uploaded separately to the application's data directory. Having `EmbedAssembliesIntoApk` set to `false` is only meant for the fast deployment mode in the Debug configuration.)

**Comment by brendanzagaeski** [comment] 2019-07-30 04:23
**For the issue on Windows:**

Thanks for the Windows build output. It looks like none of the LLVM build steps are getting through the `opt` step to the `llc` step. Those steps work successfully in the test projects I've tried in my local environment so far. If you're interested in further troubleshooting this issue, what kind of output do you get if you run one of the `opt` commands by hand in a `cmd.exe` command prompt? For example, after you run the build in Visual Studio, you can launch a **Command Prompt** from the Windows Start menu and then run the following command at the prompt:

```cmd
"C:\PROGRA~2\MICROS~1\2019\ENTERP~1\MSBuild\Xamarin\Android\opt" -f -O2 -disable-tail-calls -o "C:\Git\MYWORK~1\MYWORK~1\MYWORK~1.DRO\obj\Release\90\aot\ARMEAB~1\Newtonsoft.Json.dll\temp.opt.bc" "C:\Git\MYWORK~1\MYWORK~1\MYWORK~1.DRO\obj\Release\90\aot\ARMEAB~1\Newtonsoft.Json.dll\temp.bc"
```

If that command completes without any output, you run also try running:

```cmd
echo %errorlevel%
```

You can send back the output from those 2 commands.

You can also attach back the input bitcode file: *"C:\\Git\\MYWORK\~1\\MYWORK\~1\\MYWORK\~1.DRO\\obj\\Release\\90\\aot\\ARMEAB\~1\\Newtonsoft.Json.dll\\temp.bc"*

For completeness, you can also copy and paste your Visual Studio version information from **Help > About Microsoft Visual Studio > Copy Info**.

But no worries if you're all set with using macOS for now and aren't interested in further troubleshooting the issue on Windows.

**Comment by EmilAlipiev** [comment] 2019-07-30 08:54
@brendanzagaeski thanks for your detailed answer. I will test it later when i have access to my windows machine and provide you more logs. 
Regarding MacOS, it was working with settings above including aapt2, I have a stable branch released on android playstore at 29th June. I dont know which version was the latest for Vs4Mac that day but it was working without any problem. I always use Preview channel and I am always up to date so, it should be either 8.2 or 8.1 pre, if it is any help for Mac team you can provide. Thus they can compare the changes may cause this issue.

**Comment by EmilAlipiev** [comment] 2019-08-06 21:04
I have just tested with vs 2019 16.2 version and it throws error for AOT build. i attached the full diagnostic logs. 

[vs2019logs.zip](https://github.com/xamarin/xamarin-android/files/3474158/vs2019logs.zip)

**Comment by brendanzagaeski** [comment] 2019-08-15 20:15
Thanks for the new log file! It looks like that new log matches the behavior from [before](https://github.com/xamarin/xamarin-android/issues/3394#issuecomment-516192428), where the LLVM steps are stopping after the call to `opt`. So if you get a chance, I'd still be curious to know what happens if you try to run `opt` by hand in a **Command Prompt** (following the [steps from earlier](https://github.com/xamarin/xamarin-android/issues/3394#issuecomment-516255037)). But no worries if you won't have a chance to test those steps at the moment. Thanks again!

**Closed** 2020-06-23 01:25 UTC
Labels: regression
