### ISSUE TITLE
IntermediateOutputPath project attribute does not respect standard macros.

### ISSUE THREAD

**Issue by ezverev** [xamarin/xamarin-android#2245] opened 2018-10-01 11:09 UTC
### Steps to Reproduce

1. Append the following parameter into yout Xamarin.Android .csproj file for the launched app. For instance, let it be MyProject.Android.csproj

```
  <PropertyGroup>
    <UseShortFileNames>True</UseShortFileNames>
    <IntermediateOutputPath>C:\Temp\$(ProjectName)</IntermediateOutputPath>
  </PropertyGroup>
```

2.  Initiate a rebuild.

### Expected Behavior
The directory C:\Temp\MyProject.Android is expected to get created and contain what was previously held in obj directory next to the project source.

### Actual Behavior
The directory C:\Temp\MonoAndroid81 is created and contains what was previously held in obj directory next to the project source and thus several projects use the same directory.

### Version Information

[VS_version_info.txt](https://github.com/xamarin/xamarin-android/files/2433675/VS_version_info.txt)

### Log File

[adb_logcat.txt](https://github.com/xamarin/xamarin-android/files/2433676/adb_logcat.txt)

**Comment by grendello** [comment] 2018-10-02 07:32
Hi @ezverev, would you mind ataching a zip file with a small project that reproduces the issue you've described? Having an actual project will let us reproduce the issue locally and examine the build process in detail to determine what's causing the behavior and how to fix it. Thanks!

**Comment by ezverev** [comment] 2018-10-03 09:39
Well, I really this the issue is ... obvious. 

[Problem1.Android.zip](https://github.com/xamarin/xamarin-android/files/2441431/Problem1.Android.zip)
Here is the repro.
Mind that the `<IntermediateOutputPath>C:\Temp\$(ProjectName)</IntermediateOutputPath>` targets particion **C**.

**Comment by grendello** [comment] 2018-10-03 15:17
@ezverev Thanks for the repro! The *result* of the issue may be obvious, but the *cause* very often isn't - that's we we ask for repros from reporters, thanks!

**Comment by dellis1972** [comment] 2018-11-05 16:47
@ezverev I have investigated this issue. It seems to be an `msbuild` issue rather than something specific to Xamarin.Android. A standard .net console app with the same `PropertyGroup` entry (in the same place) results in the exact behaviour. 

The only workaround I can see at the moment is to add

`<ProjectName>Problem1.Android</ProjectName>`

just before the `IntermediateOutputPath` definition. 

I suspect the problem is at the time that property is defined, `ProjectName` has not yet been defined by MSbuild. This is probably because the main `CSharp` target import is done at the end of the project file (this is what all net templates do).

**Comment by dellis1972** [comment] 2018-11-05 19:46
From our `msbuild` team, if you use `$(MSBuildProjectName)` rather than `$(ProjectName)` it will work. The other alternative is to move the property group after the `Import` at the bottom of the csproj.

**Comment by ezverev** [comment] 2018-11-06 10:21
> From our `msbuild` team, if you use `$(MSBuildProjectName)` rather than `$(ProjectName)` it will work. The other alternative is to move the property group after the `Import` at the bottom of the csproj.

Thanks, it works for me.

**Comment by dellis1972** [comment] 2018-11-06 13:12
ok cool. Closing this issue as we have a valid workaround and this in kinda expected behaviour.

**Closed by dellis1972** 2018-11-06 13:12 UTC
