### ISSUE TITLE
System.IO.IOException Process cannot access file R.java 

### ISSUE THREAD

**Issue by Nivedita-Puneet** [xamarin/xamarin-android#5590] opened 2021-02-04 00:34 UTC
### Steps to Reproduce

1. Visual studio 2019 community edition  Version 16.5.4
2. Created a new project and installed Nuget Packages Xamarin.googleservices.Basement v117.1.0 and Xamarin.Googleservices.Base v117.1.0 and android Target framework is Android Q , xamarin forms version is v5.0.0.1931 and Xamarin download build solution version is 0.9
3. Build the solution am getting following error

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unhandled exception: System.IO.IOException: The process cannot access the file 'C:\HelloFirebasePush\HelloFirebasePush\HelloFirebasePush.Android\obj\Debug\100\android\src\com\google\android\gms\common\R.java' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination)
   at Xamarin.Android.Tasks.GenerateLibraryResources.GenerateJava(Library library)
   at Xamarin.Android.Tasks.AsyncTaskExtensions.<>c__DisplayClass0_1`1.<WhenAll>b__0()	HelloFirebasePush.Android

I wanted to upgrade Xamarin firebase push to latest version this upgrade is costing a lot of time. Can someone please help

**Comment by dellis1972** [comment] 2021-02-12 15:26
This is a duplicate of #5591

**Closed by dellis1972** 2021-02-12 15:26 UTC
Labels: Area: App+Library Build
