### ISSUE TITLE
Xamarin Forms application error java.lang.ArrayIndexOutOfBoundsException :  Index 4 out of bounds for length 4

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6632] opened 2022-01-10 17:53 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-Forms-application-error-javalan/1575830)._

---
I'm getting the below error in VS2022 when trying to debug/deploy a Xamarin Forms app on Android emulator.
The same works on VS2019 on the same machine with the same jdk and adk (from the same directories).

java.lang.ArrayIndexOutOfBoundsException :  Index 4 out of bounds for length 4

---
#### Feedback Bot on 11/9/2021, 05:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jacques on 11/15/2021, 10:36 PM: 

<p>Hi,</p>
<p>I’m also getting this error for my Xamarin Forms Project. When using VS 2019 it compile 100%, but with 2022 it gives the ‘java.lang.ArrayIndexOutOfBoundsException : Index 4 out of bounds for length 4’ error. Note My project is set to ‘release’/‘debug’ and for 'Android and this is only on compiling the code. I did not test with iOS and emulators yet.</p>
<p>Both VS 2019 and 2022 are fresh installs on a new computer.</p>
<p>Kind Regards,</p>

#### Michalis Kanios on 11/17/2021, 04:50 AM: 

<p>Same error in 17.0.1</p>

#### John Aquilina Alamango on 11/19/2021, 06:01 AM: 

<p>Same error in 17.0.1</p>

#### Michalis Kanios on 12/16/2021, 10:22 AM: 

<p>17.0.4 and still the same.<br>
Any update?</p>

#### Trevor Chadwick on 12/21/2021, 09:32 AM: 

<p>We are also struggling with this one, any rough time frame to resolution or at least identification of issue? (17.0.4)</p>

#### Tesifonte Lazcano Moreno on 12/21/2021, 06:57 PM: 

<p>Same here (17.0.4)</p>

#### Norman Lough on 12/22/2021, 06:35 AM: 

(private comment, text removed)
#### Rodrigo Juarez on 1/4/2022, 07:58 PM: 

<p>Same for me, on Windows 11, with VS Enterprise 2022 17.0.4</p>

#### Norman Lough on 1/6/2022, 01:36 AM: 

<p>Could really do with an update on this asap please</p>

#### Andrew Munro on 1/7/2022, 02:08 AM: 

<p>Same for me on VS 2022 with the latest version</p>

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment] 2022-01-20 22:40
Can someone provide a complete error message with stack trace?

I can't determine where the error is coming from, and thus which team to assign this to.

**Comment by tchadwick** [comment] 2022-01-24 16:25
I'm looking for how to turn on more verbose logging, because currently, this is the full extent of the error message:
1>  Error: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
1>  Compilation failed
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\Xamarin.Android.D8.targets(79,5): error : java.lang.ArrayIndexOutOfBoundsException :  Index 4 out of bounds for length 4

**Comment by jpobst** [comment] 2022-01-24 16:29
See if a Diagnostic build log contains any more information:
https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output

**Comment by jpobst** [comment] 2022-01-24 16:36
👍  At least seeing the command line helps me to assign this to the correct team for further investigation.

**Comment by tchadwick** [comment] 2022-01-24 17:18
I found the error in Diagnostic mode, it doesn't appear to be any more helpful, but:
Task "R8" skipped, due to false condition; ( '$(_UseR8)' == 'True' ) was evaluated as ( 'False' == 'True' ).
Task "D8"
Task Parameter:JavaMaximumHeapSize=1G
Task Parameter:JarPath=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\r8.jar
Task Parameter:OutputDirectory=obj\Debug\100\android\bin\
Task Parameter:
    JavaLibrariesToEmbed=
        C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v10.0\mono.android.jar
        C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\java_runtime_fastdev.jar
        obj\Debug\100\lp\0\jl\formsviewgroup.jar
        obj\Debug\100\lp\10\jl\bin\classes.jar
        obj\Debug\100\lp\11\jl\bin\classes.jar
        obj\Debug\100\lp\12\jl\bin\classes.jar
        obj\Debug\100\lp\13\jl\bin\classes.jar
        obj\Debug\100\lp\14\jl\com.android.support.support-annotations.jar
        obj\Debug\100\lp\15\jl\bin\classes.jar
        obj\Debug\100\lp\16\jl\com.android.support.collections.jar
        obj\Debug\100\lp\17\jl\bin\classes.jar
        obj\Debug\100\lp\18\jl\bin\classes.jar
        obj\Debug\100\lp\19\jl\bin\classes.jar
        obj\Debug\100\lp\20\jl\bin\classes.jar
        obj\Debug\100\lp\21\jl\bin\classes.jar
        obj\Debug\100\lp\22\jl\bin\classes.jar
        obj\Debug\100\lp\23\jl\bin\classes.jar
        obj\Debug\100\lp\24\jl\bin\classes.jar
        obj\Debug\100\lp\25\jl\bin\classes.jar
        obj\Debug\100\lp\26\jl\bin\classes.jar
        obj\Debug\100\lp\27\jl\bin\classes.jar
        obj\Debug\100\lp\28\jl\bin\classes.jar
        obj\Debug\100\lp\29\jl\bin\classes.jar
        obj\Debug\100\lp\30\jl\bin\classes.jar
        obj\Debug\100\lp\31\jl\bin\classes.jar
        obj\Debug\100\lp\32\jl\bin\classes.jar
        obj\Debug\100\lp\33\jl\bin\classes.jar
        obj\Debug\100\lp\34\jl\bin\classes.jar
        obj\Debug\100\lp\35\jl\bin\classes.jar
        obj\Debug\100\lp\37\jl\bin\classes.jar
        obj\Debug\100\lp\38\jl\bin\classes.jar
        obj\Debug\100\lp\39\jl\bin\classes.jar
        obj\Debug\100\lp\4\jl\__reference__pass-v1.2.0.jar
        obj\Debug\100\lp\4\jl\__reference__sdk-v1.0.0.jar
        obj\Debug\100\lp\40\jl\bin\classes.jar
        obj\Debug\100\lp\41\jl\bin\classes.jar
        obj\Debug\100\lp\42\jl\bin\classes.jar
        obj\Debug\100\lp\43\jl\bin\classes.jar
        obj\Debug\100\lp\44\jl\bin\classes.jar
        obj\Debug\100\lp\6\jl\android.arch.core.common.jar
        obj\Debug\100\lp\7\jl\bin\classes.jar
        obj\Debug\100\lp\8\jl\android.arch.lifecycle.common.jar
        obj\Debug\100\lp\9\jl\bin\classes.jar
Task Parameter:AndroidManifestFile=obj\Debug\100\android\AndroidManifest.xml
Task Parameter:EnableDesugar=True
Task Parameter:JavaPlatformJarPath=C:\Program Files (x86)\Android\android-sdk\platforms\android-29\android.jar
Task Parameter:Debug=True
Task Parameter:ToolPath=C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin
Task Parameter:ClassesZip=obj\Debug\100\android\bin\classes.zip
  processing ClassesZip, JavaLibrariesToEmbed...
C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\java.exe -Xmx1G -classpath "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\r8.jar" com.android.tools.r8.D8 --debug --min-api 19 --output obj\Debug\100\android\bin\ --lib "C:\Program Files (x86)\Android\android-sdk\platforms\android-29\android.jar" obj\Debug\100\android\bin\classes.zip "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v10.0\mono.android.jar" "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\java_runtime_fastdev.jar" obj\Debug\100\lp\0\jl\formsviewgroup.jar obj\Debug\100\lp\10\jl\bin\classes.jar obj\Debug\100\lp\11\jl\bin\classes.jar obj\Debug\100\lp\12\jl\bin\classes.jar obj\Debug\100\lp\13\jl\bin\classes.jar obj\Debug\100\lp\14\jl\com.android.support.support-annotations.jar obj\Debug\100\lp\15\jl\bin\classes.jar obj\Debug\100\lp\16\jl\com.android.support.collections.jar obj\Debug\100\lp\17\jl\bin\classes.jar obj\Debug\100\lp\18\jl\bin\classes.jar obj\Debug\100\lp\19\jl\bin\classes.jar obj\Debug\100\lp\20\jl\bin\classes.jar obj\Debug\100\lp\21\jl\bin\classes.jar obj\Debug\100\lp\22\jl\bin\classes.jar obj\Debug\100\lp\23\jl\bin\classes.jar obj\Debug\100\lp\24\jl\bin\classes.jar obj\Debug\100\lp\25\jl\bin\classes.jar obj\Debug\100\lp\26\jl\bin\classes.jar obj\Debug\100\lp\27\jl\bin\classes.jar obj\Debug\100\lp\28\jl\bin\classes.jar obj\Debug\100\lp\29\jl\bin\classes.jar obj\Debug\100\lp\30\jl\bin\classes.jar obj\Debug\100\lp\31\jl\bin\classes.jar obj\Debug\100\lp\32\jl\bin\classes.jar obj\Debug\100\lp\33\jl\bin\classes.jar obj\Debug\100\lp\34\jl\bin\classes.jar obj\Debug\100\lp\35\jl\bin\classes.jar obj\Debug\100\lp\37\jl\bin\classes.jar obj\Debug\100\lp\38\jl\bin\classes.jar obj\Debug\100\lp\39\jl\bin\classes.jar obj\Debug\100\lp\4\jl\__reference__pass-v1.2.0.jar obj\Debug\100\lp\4\jl\__reference__sdk-v1.0.0.jar obj\Debug\100\lp\40\jl\bin\classes.jar obj\Debug\100\lp\41\jl\bin\classes.jar obj\Debug\100\lp\42\jl\bin\classes.jar obj\Debug\100\lp\43\jl\bin\classes.jar obj\Debug\100\lp\44\jl\bin\classes.jar obj\Debug\100\lp\6\jl\android.arch.core.common.jar obj\Debug\100\lp\7\jl\bin\classes.jar obj\Debug\100\lp\8\jl\android.arch.lifecycle.common.jar obj\Debug\100\lp\9\jl\bin\classes.jar 
Error: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
Compilation failed
java.lang.ArrayIndexOutOfBoundsException :  Index 4 out of bounds for length 4
Done executing task "D8" -- FAILED.
Done building target "_CompileToDalvik" in project "efcMobileApp.Droid.csproj" -- FAILED.

**Comment by jonathanpeppers** [comment] 2022-01-24 17:39
It looks like you are hitting an issue with `r8.jar`, this is some underlying Android tooling we redistribute in Xamarin.Android:

https://mvnrepository.com/artifact/com.android.tools/r8

We recently updated r8: https://github.com/xamarin/xamarin-android/commit/862ea3930956dc3744392847de649a648c16d10b

Would you be able to try one of these newer builds?

* Mac: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/5661586/main/5762b45d1f1f8cd894dc7616f05c83447ef895bd/xamarin.android-12.2.99.52.pkg
* Windows: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/5661586/main/5762b45d1f1f8cd894dc7616f05c83447ef895bd/Xamarin.Android.Sdk-12.2.99.52.vsix

And see if the problem goes away?

**Comment by tchadwick** [comment] 2022-01-24 19:01
The error after installing that newer build is: 
3>Using "D8" task from assembly "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\Xamarin.Android.Build.Tasks.dll".
3>Task "D8"
3>    processing ClassesZip, JavaLibrariesToEmbed...
3>  C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\java.exe -Xmx1G -classpath "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\r8.jar" com.android.tools.r8.D8 --debug --min-api 19 --output obj\Debug\100\android\bin\ --lib "C:\Program Files (x86)\Android\android-sdk\platforms\android-29\android.jar" obj\Debug\100\android\bin\classes.zip "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v10.0\mono.android.jar" "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\java_runtime_fastdev.jar" obj\Debug\100\lp\0\jl\formsviewgroup.jar obj\Debug\100\lp\10\jl\bin\classes.jar obj\Debug\100\lp\11\jl\bin\classes.jar obj\Debug\100\lp\12\jl\bin\classes.jar obj\Debug\100\lp\13\jl\bin\classes.jar obj\Debug\100\lp\14\jl\com.android.support.support-annotations.jar obj\Debug\100\lp\15\jl\bin\classes.jar obj\Debug\100\lp\16\jl\com.android.support.collections.jar obj\Debug\100\lp\17\jl\bin\classes.jar obj\Debug\100\lp\18\jl\bin\classes.jar obj\Debug\100\lp\19\jl\bin\classes.jar obj\Debug\100\lp\20\jl\bin\classes.jar obj\Debug\100\lp\21\jl\bin\classes.jar obj\Debug\100\lp\22\jl\bin\classes.jar obj\Debug\100\lp\23\jl\bin\classes.jar obj\Debug\100\lp\24\jl\bin\classes.jar obj\Debug\100\lp\25\jl\bin\classes.jar obj\Debug\100\lp\26\jl\bin\classes.jar obj\Debug\100\lp\27\jl\bin\classes.jar obj\Debug\100\lp\28\jl\bin\classes.jar obj\Debug\100\lp\29\jl\bin\classes.jar obj\Debug\100\lp\30\jl\bin\classes.jar obj\Debug\100\lp\31\jl\bin\classes.jar obj\Debug\100\lp\32\jl\bin\classes.jar obj\Debug\100\lp\33\jl\bin\classes.jar obj\Debug\100\lp\34\jl\bin\classes.jar obj\Debug\100\lp\35\jl\bin\classes.jar obj\Debug\100\lp\37\jl\bin\classes.jar obj\Debug\100\lp\38\jl\bin\classes.jar obj\Debug\100\lp\39\jl\bin\classes.jar obj\Debug\100\lp\4\jl\__reference__pass-v1.2.0.jar obj\Debug\100\lp\4\jl\__reference__sdk-v1.0.0.jar obj\Debug\100\lp\40\jl\bin\classes.jar obj\Debug\100\lp\41\jl\bin\classes.jar obj\Debug\100\lp\42\jl\bin\classes.jar obj\Debug\100\lp\43\jl\bin\classes.jar obj\Debug\100\lp\44\jl\bin\classes.jar obj\Debug\100\lp\6\jl\android.arch.core.common.jar obj\Debug\100\lp\7\jl\bin\classes.jar obj\Debug\100\lp\8\jl\android.arch.lifecycle.common.jar obj\Debug\100\lp\9\jl\bin\classes.jar 
3>  Error: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
3>  Compilation failed with an internal error.
3>  Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
3>  	at com.android.tools.r8.utils.w.a(SourceFile:92)
3>  	at com.android.tools.r8.D8.main(D8.java:4)
3>  Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
3>  	at Version.fakeStackEntry(Version_3.0.73.java:0)
3>  	at com.android.tools.r8.utils.w.a(SourceFile:68)
3>  	at com.android.tools.r8.utils.w.a(SourceFile:28)
3>  	at com.android.tools.r8.utils.w.a(SourceFile:27)
3>  	at com.android.tools.r8.utils.w.b(SourceFile:3)
3>  	at com.android.tools.r8.D8.a(D8.java:17)
3>  	at com.android.tools.r8.D8.a(D8.java:15)
3>  	at com.android.tools.r8.utils.w.a(SourceFile:84)
3>  	... 1 more
3>  Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
3>  	at com.android.tools.r8.internal.U6.a(SourceFile:4175)
3>  	at com.android.tools.r8.internal.U6.a(SourceFile:1857)
3>  	at com.android.tools.r8.internal.U6.a(SourceFile:1019)
3>  	at com.android.tools.r8.graph.H0.a(SourceFile:33)
3>  	at com.android.tools.r8.graph.H0.G(SourceFile:8)
3>  	at com.android.tools.r8.internal.d6.a(SourceFile:5)
3>  	at com.android.tools.r8.D8.a(D8.java:27)
3>  	at com.android.tools.r8.utils.V.a(SourceFile:36)
3>  	at com.android.tools.r8.utils.V.a(SourceFile:41)
3>  	at com.android.tools.r8.utils.V.a(SourceFile:35)
3>  	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
3>  	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
3>  	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
3>  	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
3>  	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
3>  	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
3>  	Suppressed: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
3>  		at com.android.tools.r8.D8.d(D8.java:209)
3>  		at com.android.tools.r8.D8.c(D8.java:1)
3>  		at com.android.tools.r8.utils.w.a(SourceFile:24)
3>  		at com.android.tools.r8.utils.w.b(SourceFile:3)
3>  		at com.android.tools.r8.D8.a(D8.java:17)
3>  		at com.android.tools.r8.D8.a(D8.java:15)
3>  		at com.android.tools.r8.utils.w.a(SourceFile:84)
3>  		at com.android.tools.r8.D8.main(D8.java:4)
3>  	Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
3>  		at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
3>  		at com.android.tools.r8.utils.V.a(SourceFile:11)
3>  		at com.android.tools.r8.utils.V.a(SourceFile:40)
3>  		at com.android.tools.r8.utils.V.a(SourceFile:38)
3>  		at com.android.tools.r8.utils.V.a(SourceFile:37)
3>  		at com.android.tools.r8.D8.d(D8.java:24)
3>  		... 7 more
3>  	Caused by: java.lang.ArrayIndexOutOfBoundsException
3>  		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
3>  		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
3>  		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
3>  		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
3>  		at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
3>  		... 13 more
3>  	Caused by: [CIRCULAR REFERENCE: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4]
3>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\Xamarin.Android.D8.targets(79,5): error : java.lang.ArrayIndexOutOfBoundsException :  Index 4 out of bounds for length 4

**Comment by jonathanpeppers** [comment] 2022-01-25 14:33
@tchadwick is just seems like r8 is failing the same way. Are you able to make a sample project that hits this issue & share it? Maybe it's a specific NuGet package causing it?

**Comment by tchadwick** [comment] 2022-01-27 19:00
I'm afraid not, it's a fairly involved project and I was able to go back to 2019 and have it compile without issue.

**Comment by jonathanpeppers** [comment] 2022-01-27 20:38
> I was able to go back to 2019

Can you share a working `.binlog` and a failing `.binlog`?

Try building at the command-line, such as:

```
"C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\MSBuild.exe" YourAndroid.csproj -t:Clean,SignAndroidPackage -bl:2022.binlog
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" YourAndroid.csproj -t:Clean,SignAndroidPackage -bl:2019.binlog
```
And send the two `.binlog` files.

That might help us narrow down what changed. Thanks!

**Comment by tchadwick** [comment] 2022-01-27 21:00
2019 bin log: https://1drv.ms/u/s!Ao4R2pf2_-GmpL9ezqqnPd59Cktl6w?e=m6Xl08
2022 bin log: https://1drv.ms/u/s!Ao4R2pf2_-GmpL9f6Xp_1he11wHQuw?e=2NOy2U

**Comment by jonathanpeppers** [comment] 2022-01-28 23:43
If you use the older version of `r8.jar`, does the error go away in 2022?

Add to your `.csproj`:
```xml
<PropertyGroup>
  <AndroidR8JarPath>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\r8.jar</AndroidR8JarPath>
</PropertyGroup
```

The failing `.binlog` uses `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\r8.jar`.

**Comment by tchadwick** [comment] 2022-01-31 16:37
Hello @jonathanpeppers switching to the old version of r8.jar did indeed fix the issue.  There must be a change in the r8.jar, the version of Xamarin.Android SDK is 12.0.0.3, the rest of the version information is as follows:
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@476bb5b
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

**Comment by jonathanpeppers** [comment] 2022-01-31 16:40
You could report a bug for r8: https://developer.android.com/studio/report-bugs

Any chance you can make a sample app that hits the issue, and we can narrow it down? It might be easier for us to make a small command-line repro that takes Xamarin out of the equation?

**Comment by ognamala** [comment] 2022-03-24 13:36
Hey everyone, has there been any update on this issue since end of January? Thanks !

**Comment by jonathanpeppers** [comment] 2022-03-24 13:52
@ognamala can you share a sample project that hits this issue? We would need to construct a repro from that to send to Google.

**Comment by ognamala** [comment] 2022-03-24 15:35
@jonathanpeppers unfortunately this is currently happening on a work repo which I cannot share, I will try to see if I can create a mock repo to share

**Comment by andrewmarimosa** [comment] 2022-04-15 14:09
Was there a solution for this issue found? I'm having the same issue now.

**Comment by jonathanpeppers** [comment] 2022-04-15 15:07
@andrewmarimosa we updated r8 in 9f3ee589d9a8cf9eb0d9d0dbe6c6e6acc8fc7f96.

Can you try one of these builds with that change?
* https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/6022518/main/2c696c47e729e664162215a7b2beff8b4f99b753/xamarin.android-12.3.99.37.pkg
* https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/6022518/main/2c696c47e729e664162215a7b2beff8b4f99b753/Xamarin.Android.Sdk-12.3.99.37.vsix

Worth checking if the problem goes away.

Otherwise, we need a sample app to look into this further. I suspect we'll need to narrow down what's happening -- take Xamarin out of the equation and send the repro to Google.

**Comment by andrewmarimosa** [comment] 2022-04-16 18:12
@jonathanpeppers I tried you're suggestion and it didn’t seem to work for me, but i have spent some time trying to diagnose this issue on my app and it was linked to a nuget package i had installed.
It turned out version 1.4.9 of this nuget package was causing the issue for me, i updated it to the latest release (2.1.5) and the problem has gone away.

https://github.com/smstuebe/xamarin-fingerprint

I hope this can help others who are having the same issue.

**Closed** 2022-06-01 16:01 UTC
Labels: need-info, Area: App+Library Build
