### ISSUE TITLE
android.util.SuperNotCalledException: 

### ISSUE THREAD

**Issue by altalker** [xamarin/xamarin-android#1414] opened 2018-03-13 21:05 UTC
### Steps to Reproduce

1.  Application running on emulator or test devices - no errors
2.  Application released through Google Play - only several devices get error
3. 

### Actual Behavior

```
Crash Error
android.util.SuperNotCalledException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3209)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3349)
  at android.app.ActivityThread.access$1100 (ActivityThread.java:221)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1794)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:158)
  at android.app.ActivityThread.main (ActivityThread.java:7224)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

### Version Information
Android 4.1-7.1

### Log File

Xiaomi Redmi 4 Pro (markw), 3072MB RAM, Android 6.0

```
android.util.SuperNotCalledException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2411)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2515)
  at android.app.ActivityThread.access$1000 (ActivityThread.java:154)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1379)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:157)
  at android.app.ActivityThread.main (ActivityThread.java:5555)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:745)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:635)
```

on another device:
Samsung Galaxy A5(2017) (a5y17lte), 3072MB RAM, Android 7.0
Report 1 of 1

```
android.util.SuperNotCalledException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2930)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3045)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1642)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1518)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)
```

**Comment by jonpryor** [comment] 2018-03-13 23:10
All that exception means is that you e.g. override `Activity.OnCreate()`, but didn't call `base.OnCreate(bundle)` somewhere.

Unfortunately, that's not much to go on: presumably you *are* calling `base.OnCreate(bundle)` -- otherwise it would fail consistently *everywhere*, which isn't the case -- so unfortunately we're going to need a consistent repro. :-(

**Comment by altalker** [comment] 2018-03-15 10:19
It does not happen on Android versions above 6.0. All code methods with 'override void OnCreate(Bundle savedInstanceState)' had  base.OnCreate(bundle).  However, I suspect it can be caused by one of the installed packages:
SQLite.Net.Core-PCL
SQLite.Net.Platform.XamarinAndroidN
Xamarin.GooglePlayServices.Base
Xamarin.GooglePlayServices.Maps
Xam.Plugin.Contacts
Xam.Plugins.Settings

Is there a way to find out which package may cause this crash or when it does happen? (it seems like on app start)

**Comment by patook** [comment] 2018-04-06 22:02
We have very high frequency repros on Android 8.0 in the play store so this might be a good starting point (in fact it looks like it crashes most of the time). I do not have a 8.0 capable device though. This started happening only in the latest version of Mono/Xamarin Android

android.util.SuperNotCalledException: Activity {com.xxx.yyy/md5772a35d98782517b430c7cfa7d5634a5.MainActivity} did not call through to super.onCreate()

and here is MainActivity

```
public class MainActivity : AppCompatActivity
    { 
       protected override async void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
```

Has there been any progress on this since it was opened?

**Comment by JohannesSchmidt42** [comment] 2018-04-25 22:20
We rolled out an update for our app (~30000 active installs) on Tuesday. Since then we also see this bug (mostly on Android 8.0). We did not add new Activites with the update. We just upgraded to VS to 15.6.6 (API 27 SDK). We always call base.OnCreate and there are no ifs and early returns. 
![image](https://user-images.githubusercontent.com/7668232/39275740-a4d83598-48e6-11e8-8b13-5e333b383cc0.png)

The bug only occurs in our arm64-v8a apk (we put an apk for each abi in to the playstore release).
99% only on Android 8.0.

What can i do to help investigate the issue? People start to uninstall our app.

**Comment by jalbertSyncroTech** [comment] 2018-04-26 13:34
@jonpryor @atsushieno any updates?  There's now five other users who have reported this or similar issues.  All of us are invested in getting this fixed, so let us know if there's any we can do to help with the investigation.

As far as I've discovered it's related to startup performance - we have an intel i5 that it's 100% reproducible on, while running the exact same code on an intel i7 it's not reproducible at all.  Putting in a work-around for #1544 solved the issue for most of our systems, but not the i5.  However something did change between VS 15.5 and 15.6 that's exacerbated the issue, as the same intel i5 didn't have this issue at all with VS 15.5.  

Also interesting that a Rebuild All resolves the issue, as we also saw the behavior reported in #1585. simply doing any Build would trigger the issue, but followed by a Rebuild All would resolve it.  Why are Build and Rebuild All producing different code?

**Comment by JonDouglas** [comment] 2018-05-02 16:42
For us to further investigate this issue, we will need a reliable way to reproduce this issue. For more information on what to report, please see the following:

https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests#bug-reports

Given that reports are both in Xamarin.Forms and regular Xamarin.Android, this issue might be related to `bin/obj` state. If you are able to reproduce this locally on a specific device or API level, please include the `bin/obj` folders when attaching a reproduction as it will potentially keep the integrity of the reliable reproduction. The symptom of "rebuilding fixes the issue" seems like also manually clearing out the `bin/obj` folders will fix this issue as well. 

Can anyone confirm this is the case with their app?

**Comment by marcb777** [comment] 2018-05-15 06:42
Not sure if it is exactly the same issue, but I experienced the SuperNotCalledException today.  We were able to reliably reproduce it when we built targetting the API27 SDK, and deployed to devices running Android 8.0 (wouldn't happen on Android 8.1 or Android earlier than 8.0).

After a fair bit of digging and attempting to isolate the issue to an app for submission here - I realised that this was an exception being thrown on creation of the activity due to an issue in the activity declaration in the AndroidManifest (i.e. so I guess the exception is happening in OnCreate, and is in effect blocking the base.OnCreate call).  Somewhat misleading, since there was no further information as to what the root cause was.

Either way - in our case the issue was caused by an ActivityAttribute on the launch activity containing a screen orientation with a theme specifying a transparent background.  From Android O, this will cause an exception (relevant SO post: https://stackoverflow.com/a/48072720 ).

Whilst this might not resolve the issue for the original reporter - perhaps it might help point someone in the right direction.

**Comment by veletron2** [comment] 2018-05-15 13:30
I too have this issue in Oreo. My application has a service which I had to load with StartForegroundService for Oreo, the application launches a certain Xamarin.Forms page based on the Android Intent received, my intents come from notification taps, BLE characteristics and from NFC tags. The app has error screens eg 'invalid NFC Tag Scanned', these, I display to the user using rg.plugins.popup. The theme is chosen dynamically in MainActivity the popup appears either transparent over any existing app, or as a popup over my own app if it is running. 

**Dynamic setting of themes is what is broken in Oreo** - If I try and set the theme dynamically in MainActivity, I get the error 'did not call through to Super.OnCreate()'. 

my dynamic theme setting code is thus:

`var payload = choosePageToLoad(false, Intent);

            if (payload.RequestedPageId == PageId.RequestedPageId.ErrorScreen)
                Theme.ApplyStyle(Resource.Style.ProteusPopupTheme, true);
            else
                Theme.ApplyStyle(Resource.Style.MainTheme_Base, true);

            RequestWindowFeature(WindowFeatures.NoTitle);
            base.OnCreate(bundle);
            LoadApplication(new App(payload));`

My MainActivity decoration is thus:

`[Activity(Name = "com.Spacelabs.ProteusPatientApp.Android.MainActivity", Label = "ProteusPatientApp", Icon = "@drawable/icon",  MainLauncher = true, ScreenOrientation = ScreenOrientation.Portrait, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation, LaunchMode = LaunchMode.SingleTask, ExcludeFromRecents = true, NoHistory = true)]`

Note that lack of a Theme = line in the above.

To make this work in Oreo, I have to ditch the dynamic theme setting, replacing the decoration with:

`[Activity(Name = "com.Spacelabs.ProteusPatientApp.Android.MainActivity", Label = "ProteusPatientApp", Icon = "@drawable/icon", MainLauncher = true, Theme = "@style/MainTheme", ScreenOrientation = ScreenOrientation.Portrait, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation, LaunchMode = LaunchMode.SingleTask, ExcludeFromRecents = true, NoHistory = true)]`

and loose the following code:

`if (payload.RequestedPageId == PageId.RequestedPageId.ErrorScreen)
                Theme.ApplyStyle(Resource.Style.ProteusPopupTheme, true);
            else
                Theme.ApplyStyle(Resource.Style.MainTheme_Base, true);`

The difference in how my app displays error screens where the App's MainActivity is not running is shown below. On Android 8 it looks rubbish, but if I cant dynamically change the theme then I can't easily fix. Maybe I need a second Android activity (transparent by default) with another Shared App behind it simply to display the error pages - Yuk!

![android7](https://user-images.githubusercontent.com/34792184/40059458-fe65572a-584b-11e8-80c4-c56a536dec2b.png)

![android8](https://user-images.githubusercontent.com/34792184/40059543-39662bec-584c-11e8-9646-5d7b8c1dc398.jpg)

**Comment by veletron2** [comment] 2018-05-16 10:18
Hi

Further to the above, I moved to a separate activity for my error popup, but had the same errors re Super.OnCreate() with my transparent theme. Further reading revealed that Oreo 8.0 restricts the flags that may be used when:

`  <item name="android:windowIsTranslucent">true</item>
    <item name="android:windowBackground">@android:color/transparent</item>
    <item name="android:statusBarColor">@android:color/transparent</item>`

Is specified for the theme. Specifically, in the Activity decoration, the following is NOT ALLOWED when a transparent theme is used:

`ScreenOrientation = ScreenOrientation.Portrait`

Either of removing the screen orientation stuff or removing the transparency  from the [Activity] decoration cleared the Super.OnCreate() error. Pretty annoying to get such a meaningless exception for this issue.

Now to see if I even needed a separate Activity for Oreo or whether simply dynamically assigning the theme in OnCreate() would have done the job...

Nigel

**Comment by jonathanpeppers** [comment] 2019-02-13 14:10
We haven't had activity on this issue for a while, and I think the right idea is: https://github.com/xamarin/xamarin-android/issues/1414#issuecomment-389167054

If anyone is still having trouble with this issue:
- See if you can reproduce in a quick sample project
- If there is a specific API level it fails on, it should reproduce in the emulator
- Save a [device log](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log), which will contain the full stack trace

Closing for now, thanks!

**Closed by jonathanpeppers** 2019-02-13 14:10 UTC
Labels: need-info

**Comment by MagicAndre1981** [comment] 2020-08-13 12:27
I also got it after update from 16.6 to 16.7.1:

```
	at android.util.SuperNotCalledException: Activity {com.foo.bar/crc64667f7340da0588a5.MainActivity} did not call through to super.onStop() in :0
	at at android.app.Activity.performStop(Activity.java:8045) in :0
	at at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4616) in :0
	at at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4594) in :0
	at at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4669) in :0
	at at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41) in :0
	at at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) in :0
	at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) in :0
	at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) in :0
	at at android.os.Handler.dispatchMessage(Handler.java:107) in :0
	at at android.os.Looper.loop(Looper.java:214) in :0
	at at android.app.ActivityThread.main(ActivityThread.java:7356) in :0
	at at java.lang.reflect.Method.invoke(Native Method) in :0
	at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) in :0
	at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) in :0
```

Info:

```
Version 16.7.1
VisualStudio.16.Release/16.7.1+30406.217
Microsoft .NET Framework
Version 4.8.03752

Xamarin   16.7.000.440 (d16-7@358f3c6)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.0.3 (d16-7/aca845b)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f


Xamarin.iOS and Xamarin.Mac SDK   13.20.2.2 (817b6f72a)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

happens when I switch away from app. OnStop() is empty, I haven't added anything:

```
        protected override void OnStop()
        {

        }
```

`base.OnCreate(bundle);` is called

**Comment by jonathanpeppers** [comment] 2020-08-13 12:51
@MagicAndre1981 the error message: 

    Activity {com.foo.bar/crc64667f7340da0588a5.MainActivity} did not call through to super.onStop()

It's saying you need to call `base.OnStop();` if you override `OnStop()`.

**Comment by MagicAndre1981** [comment] 2020-08-13 12:59
this was the automatically generated code from VS when I started the app. Will do this tomorrow and check what happens

**Comment by jonathanpeppers** [comment] 2020-08-13 13:04
@MagicAndre1981 I did a quick search through the Xamarin templates (sorry, not open source), and they don't override `OnStop()` in any activities.

Can you share a screenshot of what you mean when VS generated it?

**Comment by MagicAndre1981** [comment] 2020-08-14 06:12
now I used VS2017 where I work most time and removed the override methods (which was in my initial commit for what ever reason and later I only added 1 commit with UserDialogs.Init(this); method), now I only have the `public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity` but in device log I still see the SuperNotCalledException:

```
	Google Pixel 3a	Error	5530	AndroidRuntime	android.util.SuperNotCalledException: Activity {com.foo.bar/crc64667f7340da0588a5.MainActivity} did not call through to super.onStop()
	at android.app.Activity.performStop(Activity.java:8045)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4616)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4594)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4669)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Compared to VS2019 the debugger did not break here. So maybe the [break on exception settings](https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2019#tell-the-debugger-to-break-when-an-exception-is-thrown) are different so I never seen this before in VS2017 but noticed it yesterday in VS2019.
