### ISSUE TITLE
Bundle Assemblies Causes App To Crash on Startup

### ISSUE THREAD

**Issue by brminnick** [xamarin/xamarin-android#1672] opened 2018-05-11 06:12 UTC
### Steps to Reproduce Crash

1. Clone/download the "Bundle-Assemblies-Crash-Repro" branch of the FaceOff repo from GitHub: https://github.com/brminnick/FaceOff/tree/Bundle-Assemblies-Crash-Repro
2. Set the Android project as the Startup Project
3. Set the build configuration to Release
4. Build/Deploy to a physical Android device (I am using a Samsung Galaxy S5 running Android 6.0.1)
5. The app will crash after displaying the splash screen

### Workaround
1. In the Android Build Settings for the Release Configuration, set **Embed Assemblies in native code** to **false**
2. Build/Deploy to a physical Android device (I am using a Samsung Galaxy S5 running Android 6.0.1)
3. The app will run

### Version Information

=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.6 Preview (7.6 build 711)
Installation UUID: 56d2e5ea-4c82-4136-84d7-f16906698110
Runtime:
	Mono 5.12.0.226 (2018-02/9824e260f56) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 512000226

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.6
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.101/Sdks
SDK Versions:
	2.1.101
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.5.0.280 (Visual Studio Enterprise)
Hash: e85a7be8
Branch: master
Build date: 2018-05-03 11:35:01-0400

=== Xamarin.iOS ===

Version: 11.11.0.280 (Visual Studio Enterprise)
Hash: e85a7be8
Branch: master
Build date: 2018-05-03 11:35:00-0400

=== Xamarin.Android ===

Version: 8.3.0.19 (Visual Studio Enterprise)
Android SDK: /Users/bramin/Library/Android/sdk
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706000711
Git revision: 634060c6c105fd3ee36678fe547680fd258cbf45
Build date: 2018-05-04 16:11:06-04
Xamarin extensions: c6720450018cb69a3da7c6d0aa0715c013783595
Build lane: monodevelop-lion-master

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

AddinMaker 1.4.2
NuGet Package Management Extensions 0.12.6
Template Creator 0.2
WakaTime 3.0.2
Redth's Addins 1.0.9
Internet of Things (IoT) development (Preview) 7.1

### Application Output Log (When **Embed Assemblies in native code** is set to **true**)
> am start -n "com.minnick.faceoffapp/md5209b3c07f94349b9292de56ac330a488.SplashActivity"
> Starting: Intent { cmp=com.minnick.faceoffapp/md5209b3c07f94349b9292de56ac330a488.SplashActivity }

**Comment by brminnick** [comment] 2018-05-11 06:45
Confirmed the same behavior happens on Android 8.3.0.19

=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.6 Preview (7.6 build 747)
Installation UUID: 147dc9d5-5906-4c13-8901-03b92896af43
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010047

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.6
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.101/Sdks
SDK Versions:
	2.1.101
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.4.1.176 (Visual Studio Enterprise)
Hash: 7e782c1e
Branch: master
Build date: 2018-04-25 15:27:14-0400

=== Xamarin.iOS ===

Version: 11.10.1.177 (Visual Studio Enterprise)
Hash: 7e782c1e
Branch: d15-7
Build date: 2018-04-25 15:27:13-0400

=== Xamarin.Android ===

Version: 8.3.0.19 (Visual Studio Enterprise)
Android SDK: /Users/bramin/Library/Android/sdk
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706000747
Git revision: 7756dcb4069a809dd9ae87cd6810c51ebcef6ba7
Build date: 2018-05-09 10:46:34+00
Build branch: master
Xamarin extensions: 32cc296ab8dab6740559a7fb6d8fca1a87cbc1e9

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

AddinMaker 1.4.2
NuGet Package Management Extensions 0.12.6
Template Creator 0.2
WakaTime 3.0.2
Redth's Addins 1.0.9
Internet of Things (IoT) development (Preview) 7.1

**Comment by jonpryor** [comment] 2018-05-11 16:58
While trying to signup for Azure, it "perma-hanged" on the **Identity verification by card** step.

What is the `adb logcat` output when it crashes?

By any chance, is this a duplicate of Issue #1651, which crashes with:

```
monodroid-bundle	bundled app initialization error: dlopen failed: cannot locate symbol "mono_jit_set_aot_mode" referenced by "libmonodroid_bundle_app.so"
```

**Comment by brminnick** [comment] 2018-05-11 17:25
Hey @jonpryor! Yea, #1651 looks like the same regression.

**Closed** 2018-05-11 19:00 UTC
Labels: need-info
