### ISSUE TITLE
Maui(7.0) Android AOT Compile Error

### ISSUE THREAD

**Issue by pulmuone** [xamarin/xamarin-android#8252] opened 2023-08-08 07:37 UTC
### Android application type

Not applicable

### Affected platform version

vs2022 maui .net7 android aot compile error.

### Description

maui(.net7) An error occurs when you compile aot on Android.

### Steps to Reproduce

1.Maui
2.Android
3.Release Mode
4.build

### Relevant log output

```shell
Error		Precompiling failed for D:\01.SourcePrivate\BarcodeScanner4Maui#3\BarcodeScanner\BarcodeScanner\obj\Release\net7.0-android33.0\android-arm64\linked\Microsoft.Maui.Controls.dll with exit code 1.
Failed to load method 0x6002df6 from 'D:\01.SourcePrivate\BarcodeScanner4Maui#3\BarcodeScanner\BarcodeScanner\obj\Release\net7.0-android33.0\android-arm64\linked\Microsoft.Maui.Controls.dll' due to Could not resolve type with token 01000245 from typeref (expected class 'AndroidX.AppCompat.Graphics.Drawable.DrawableWrapper' in assembly 'Xamarin.AndroidX.AppCompat.AppCompatResources, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Xamarin.AndroidX.AppCompat.AppCompatResources, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:AndroidX.AppCompat.Graphics.Drawable.DrawableWrapper member:(null).
Mono Ahead of Time compiler - compiling assembly D:\01.SourcePrivate\BarcodeScanner4Maui#3\BarcodeScanner\BarcodeScanner\obj\Release\net7.0-android33.0\android-arm64\linked\Microsoft.Maui.Controls.dll
Using profile data file 'C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\7.0.86\Sdk\maui.aotprofile'
Using profile data file 'C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\7.0.86\Sdk\maui-blazor.aotprofile'
Run with MONO_LOG_LEVEL=debug for more information.
AOT of image obj\Release\net7.0-android33.0\android-arm64\linked\Microsoft.Maui.Controls.dll failed.	BarcodeScanner	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.46\targets\Microsoft.Android.Sdk.Aot.targets	91
```

**Comment by jpobst** [comment] 2023-08-08 13:43
@jonathanpeppers @dellis1972 
I'm not sure if we want to look at this in XA, or pass it to MAUI or Mono.  I am pretty sure this is an AOT issue and not caused by AndroidX itself.

**Comment by pulmuone** [comment] 2023-08-11 04:01
> @pulmuone can you share an MSBuild `.binlog` of the failure? https://aka.ms/binlog

add file "out.binlog"

**Comment by jonathanpeppers** [comment] 2023-08-11 18:45
The `.binlog` above is from a `Debug` build and has no error inside. Do you need to share a log from a `Release` build instead?

I suspect your locale could be related to the problem, as the MSBuild `.binlog` viewer even has trouble opening this:

![image](https://github.com/xamarin/xamarin-android/assets/840039/eafde057-baf8-4ceb-beef-b23d4581579b)

**Comment by dellis1972** [comment] 2023-08-11 22:00
This is a known issue see https://github.com/xamarin/xamarin-android/pull/7710.
Using non-ASCII characters for project names or in the full path to the project can cause both the AOT compiler and the google tools (like aapt2) to fail.

**Comment by pulmuone** [comment] 2023-08-11 22:52
> This is a known issue see #7710. Using non-ASCII characters for project names or in the full path to the project can cause both the AOT compiler and the google tools (like aapt2) to fail.

Same if I change the folder name.
D:\Project\BarcodeScanner4Maui3

**Comment by pulmuone** [comment] 2023-08-11 22:54
I re-added the Release option to generate logs.
msbuild.exe BarcodeScanner.sln /bl:out.binlog -p:Configuration=Release
[outlog#2.zip](https://github.com/xamarin/xamarin-android/files/12325797/outlog.2.zip)

**Comment by jonathanpeppers** [comment] 2023-08-14 13:50
This looks like the same API that moved from one package to another here: https://github.com/xamarin/AndroidX/issues/690#issuecomment-1414325720

```
Precompiling failed for D:\Project\BarcodeScanner4Maui3\BarcodeScanner\obj\Release\net7.0-android33.0\android-arm\linked\Microsoft.Maui.Controls.dll with exit code 1.
Failed to load method 0x6002df9 from 'D:\Project\BarcodeScanner4Maui3\BarcodeScanner\obj\Release\net7.0-android33.0\android-arm\linked\Microsoft.Maui.Controls.dll' due to Could not resolve type with token 01000245 from typeref (expected class 'AndroidX.AppCompat.Graphics.Drawable.DrawableWrapper' in assembly 'Xamarin.AndroidX.AppCompat.AppCompatResources, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Xamarin.AndroidX.AppCompat.AppCompatResources, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:AndroidX.AppCompat.Graphics.Drawable.DrawableWrapper member:(null).
```

@jpobst have you seen this issue in a .NET 7 app?

**Comment by jpobst** [comment] 2023-08-14 14:12
I don't think I've seen this in a MAUI app, all the other reports were from Xamarin.Forms/Classic.

However, it does look like MAUI was on the old version (1.5.*) previously at some point: https://github.com/dotnet/maui/commit/d3f78c8faab11ec6a148d033f5a78e46fe4a5620.

So it could happen there too I guess.

**Comment by pulmuone** [comment] 2023-08-17 02:31
https://github.com/sasa-bobic/Xamarin.AndroidX.AppCompat.AppCompatResources
I solved it with this content.

**Comment by pulmuone** [comment] 2023-08-17 09:35
https://github.com/xamarin/AndroidX/pull/775

Maui (net 7) Is this also resolved on Android?

**Comment by jpobst** [comment] 2024-05-17 19:02
This should be fixed in newer versions of MAUI.

**Closed by jpobst** 2024-05-17 19:02 UTC
Labels: Area: App+Library Build
