### ISSUE TITLE
AndroidMessageHandler disposes request MultipartFormDataContent inner JsonContent immediately after sending request

### ISSUE THREAD

**Issue by DenisLaky** [xamarin/xamarin-android#7086] opened 2022-06-10 17:02 UTC
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS for Mac 8.10.23 (build 7)

### Description

AndroidMessageHandler disposes HttpContents buffered streams after [request content was written to HttpConnection.OutputStream](https://github.com/xamarin/xamarin-android/blob/944f88a8b6f1c30eaf43f56cfbebf0f8cd7a547f/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L455)

```
    var multipartFormDataContent = new MultipartFormDataContent();
    var jsonContent = JsonContent.Create(stringValue);
    multipartFormDataContent.Add(jsonContent,
				 "Name");
    var request = new HttpRequestMessage(HttpMethod.Post, $"{httpClient.BaseAddress}{SEND_REQUEST_URI}")
    {
        Content = multipartFormDataContent,
    };

    _ = await httpClient.SendAsync(request);
   
    // Throws exception
    var contentValue = await jsonContent.ReadAsStringAsync();
```

### Steps to Reproduce

1. Select AndroidClientHandler in Project options -> Android build -> HttpClientImplementation;
2. Create MultipartFormDataContent and JsonContent;
3. Create HttpRequestMessage and add MultipartFormDataContent to its content;
4. Call HttpClient.SendAsync with created request;
5. Call JsonContent ReadAsStringAsync();
6. ObjectDisposed exception is raised;

### Did you find any workaround?

Override AndroidClientHandler WriteRequestContentToOutput method. This allows us to prevent content buffered stream from disposing after writing to httpConnection.OutputStream:

```
	public class CustomAndroidHandler : AndroidClientHandler
	{
		protected override async Task WriteRequestContentToOutput(HttpRequestMessage request, HttpURLConnection httpConnection, CancellationToken cancellationToken)
		{
			var stream = await request.Content.ReadAsStreamAsync().ConfigureAwait(false);
			await stream.CopyToAsync(httpConnection.OutputStream!, 4096, cancellationToken).ConfigureAwait(false);

			if (stream.CanSeek)
			{
				_ = stream.Seek(0, SeekOrigin.Begin);
			}
		}
	}

```
AndroidClientHandler getting disposed HttpRequestMessage.Content immediately after sending

### Relevant log output

```shell
  at System.IO.MemoryStream.EnsureNotClosed () [0x00008] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/IO/MemoryStream.cs:121 
  at System.IO.MemoryStream.get_Length () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/IO/MemoryStream.cs:333 
  at System.Net.Http.HttpContent.ReadBufferedContentAsString () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/HttpContent.cs:175 
  at System.Net.Http.HttpContent+<>c.<ReadAsStringAsync>b__36_0 (System.Net.Http.HttpContent s) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/HttpContent.cs:168 
  at System.Net.Http.HttpContent.WaitAndReturnAsync[TState,TResult] (System.Threading.Tasks.Task waitTask, TState state, System.Func`2[T,TResult] returnFunc) [0x0006b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/HttpContent.cs:727 
```

**Comment by tipa** [comment] 2024-02-22 21:02
@grendello this bug still exists in the new AndroidMessageHandler and makes my app's logic way more complicated that it should be. I have a retry-logic for failed http requests and on iOS/macOS/Windows I can re-use the HttpContentfor multiple requests /  `HttpRequestMessage`s - except on Android.

The exception can be very easily reproduced:
```
var jsonContent = JsonContent.Create("{}");
var request = new HttpRequestMessage(HttpMethod.Post, "https://httpbin.org/post") { Content = jsonContent };
_ = await new HttpClient().SendAsync(request);
var contentValue = await jsonContent.ReadAsStringAsync();
```

Ar there any plans to change this is is it "working as expected"?

**Comment by tipa** [comment] 2024-02-25 10:52
@grendello @simonrozsival I believe the problem lies here:
https://github.com/xamarin/xamarin-android/blob/a82ac4e5608b9745916db320f4ff36921d4d6dee/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L539-L562

- I believe the stream shouldn't be disposed of with a `using` block, especially because the comment in it doesn't make much sense when doing so. Why is the stream rewound when it's disposed of right after? 
- Additionally, would it make sense to call the `ReadAsStreamAsync` overload with a CancellationToken that was added with .NET? https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpcontent.readasstreamasync?view=net-8.0#system-net-http-httpcontent-readasstreamasync(system-threading-cancellationtoken)

Some background on why this fix would help me simplifying my apps' logic. I currently need to do something like this:

```
async Task<HttpResponseMessage> SendRequest(Func<HttpContent> contentFunc, int attempt = 1)
{
    using var requestMessage = new HttpRequestMessage(HttpMethod.Post, "https://someurl.com") { Content = contentFunc.Invoke() };
    var response = await httpClient.SendAsync(requestMessage);

    if (!response.IsSuccessStatusCode && attempt < 3)
    {
        await Task.Delay(2000 * attempt * attempt);
        return await SendRequest(contentFunc, attempt + 1);
    }
    return response;
}

await SendRequest(() => new ByteArrayContent(data));
```

But I would prefer to use something like this (which works without issues on other platforms (iOS, macOS, Windows):
```
async Task<HttpResponseMessage> SendRequest(HttpContent content, int attempt = 1)
{
    using var requestMessage = new HttpRequestMessage(HttpMethod.Post, "https://someurl.com") { Content = content };
    var response = await httpClient.SendAsync(requestMessage);

    if (!response.IsSuccessStatusCode && attempt < 3)
    {
        await Task.Delay(2000 * attempt * attempt);
        return await SendRequest(content, attempt + 1);
    }
    return response;
}

await SendRequest(new ByteArrayContent(data));
```

**Comment by simonrozsival** [comment] 2024-02-26 10:52
@tipa I can confirm that removing that `using` fixes this use-case. You're right that rewinding the stream just before disposing it seems weird. `SocketsHttpHandler` doesn't assume it owns the request message and it doesn't dispose the content. This code seems to be quite old (the rewinding was implemented in https://github.com/xamarin/xamarin-android/pull/608, the `using` was introduced even earlier in https://github.com/xamarin/xamarin-android/commit/0c3597869bc4493895e755bda8a26f778e4fe9e0).

@grendello it seems that disposing the content stream is a bug, especially since the sockets handler doesn't do it.

**Comment by simonrozsival** [comment] 2024-02-26 11:18
Related: https://github.com/xamarin/xamarin-macios/pull/16341

**Comment by grendello** [comment] 2024-02-26 11:39
@simonrozsival would you mind opening a PR? I can't even build `XA` today, getting segfaults when building Mono.Android :(

**Comment by tipa** [comment] 2024-02-27 07:53
I found that there are related bug reports to the same issue, that can be closed as well once the fix is merged:
https://github.com/xamarin/xamarin-android/issues/4476
https://github.com/xamarin/xamarin-android/issues/2901

As you can see, a long-standing bug ;)

**Closed** 2024-02-27 10:33 UTC
Labels: Area: HTTP
