### ISSUE TITLE
Designer should generate constants

### ISSUE THREAD

**Issue by MihaMarkic** [xamarin/xamarin-android#3437] opened 2019-08-02 14:22 UTC
### Steps to Reproduce

1.  Checkout out Resource.designer.cs file
2. It contains classes with fields like 
`public static int xxx = 2131034112;`

### Expected Behavior

The generated fields should be constants, like
`public const int xxx = 2131034112;`

### Actual Behavior
`public static int xxx = 2131034112;`

If fields are constants, they can't change and one could use them with switch statements. Perhaps I'm missing something?

**Comment by brendanzagaeski** [comment] 2019-08-07 02:38
Thanks for the report!

I took a quick look at the *Resource.designer.cs* files in newly created projects in Visual Studio 2019 version 16.2, Visual Studio 2019 version 16.3 Preview 1, and Visual Studio 2019 for Mac version 8.2. I didn't find any `public static int` types in the *Resource.designer.cs* files for those newly created projects. (I did notice `public static int[]` types, but that's as expected since arrays can't be `const`.)

If you might be able to zip up and attach back an example project that is generating `public static int` types instead of `public static const` types so the team can investigate further, that would be excellent. (Or if you see this behavior even with a new project, a next step could be to collect and attach back your version information from **Help > About Microsoft Visual Studio > Copy Info**.) Thanks in advance!

**Comment by MihaMarkic** [comment] 2019-08-07 07:52
@brendanzagaeski You are right. However I've found what's going on. It seems that my problem appears only in Android libraries, not apps. You'll see it if you create an Android Class Library (Xamarin).

**Comment by atsushieno** [comment] 2019-08-09 10:16
It is explicitly designed to be static NON-readonly fields by apps, because those resource IDs can be overwritten by users app build process. At least it what how Android builds behaved when I made it so.

**Comment by MihaMarkic** [comment] 2019-08-09 10:27
@atsushieno Good point and yes, they can be _overwritten_. But from what I see, they are not exactly overwritten, they are recreated in the latest Resource.designer.cs file - last values are always consts. Perhaps there is a mechanism that updates the library values at runtime that I'm missing? It'd make sense.

**Comment by brendanzagaeski** [comment] 2019-08-09 21:11
Thanks for the additional info! This is indeed the expected behavior. You can see how it works with the following steps:

1. Create a new Android app project.
2. Create a new Android class library project.
3. Add a reference to the Android class library project from the Android app project.
4. Build the app project.
5. Look in the *Resource.designer.cs* file in the app project.

You'll see a `public static void UpdateIdValues()` method that sets the various `static` fields from the class library project to use the final resource IDs that were generated by AAPT (or AAPT2) during the app project build. For example, for the default `hello` string resource that's part of the Android class library template, there will be a line similar to:

```csharp
global::AndroidClassLibrary1.Resource.String.hello = global::AndroidApp1.Resource.String.hello;
```

This allows the class library itself and any projects that reference the class library to use the `AndroidClassLibrary1.Resource.String.hello` name from the class library's namespace for the resource instead of the `AndroidApp1.Resource.String.hello` name from the app project's namespace while still getting the correct final resource ID when the app is running on a device.

Thanks again for the report. I'll close this issue as working as expected, but let me know if I've missed anything. Thanks!

**Closed by brendanzagaeski** 2019-08-09 21:11 UTC
Labels: need-info
