### ISSUE TITLE
String.MissingMethod exception occurs while using String.Split method

### ISSUE THREAD

**Issue by shivagurunathan** [xamarin/xamarin-android#3078] opened 2019-05-07 06:59 UTC
Hi Team,

We at Syncfusion develop data visualization controls for Xamarin and we have more than 90 controls spread across all platforms of Xamarin. Please refer the below link for a description about us.
UserGuide: https://help.syncfusion.com/xamarin/sfdatagrid/overview
FeatureTour: https://www.syncfusion.com/products/xamarin.

We would like to bring to your notice a bug that we encountered as follows.

I have a custom Android library project which has split method as follows.

namespace CustomAndLibrary   
{ 
    public static class CustomStringSplit     
     {
         public static void Split(string s,char c)         
          {              
                 s.Split(c);       
          }    
      } 
}

The above project is built in a machine which has **.Net Core** installed in it.

Now i am referring the above split method in an Android application in another machine which does not have NetCore installed by referring the CustomAndLibrary Dll. While referring it “String.MissingMethod Exception” occurs. 

namespace StringSplitExp
{
    [Activity(Label = "StringSplitExp", MainLauncher = true, Icon = "@mipmap/icon")]
    public class MainActivity : Activity
    {
        string name = "Sync";
        TextView label;

        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            label = new TextView(this);
            label.Text = name;

            CustomAndLibrary.CustomStringSplit.Split(name, 'c');

            // Set our view from the "main" layout resource
            SetContentView(label);                      
        }
    }
}

--

### Steps to Reproduce

1. Run the sample
2. Note String.Missing method exception occurs in the sample link.

### Expected Behavior

Exception should not occur.

### Basic Information

- Version with issue: Issue occurs in machine in which Netcore is not installed.

While getting method declaration information for **String.Split method ** from .Netcore installed machine, I get the below information.

public String[] Split(char separator, StringSplitOptions options = StringSplitOptions.None);

On the other hand, if get the method declaration information for**String.Split method ** from a machine where .Netcore is not installed, I get the below information.

Public string[] Split (params char[] separator); 

The Api information in the below link:
**Xamarin.Android:** https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=xamarinandroid-7.1

**.Net core :** https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=netcore-3.0#System_String_Split_System_Char_System_Int32_System_StringSplitOptions_

### Screenshots

Exception Screenshot:
![image](https://user-images.githubusercontent.com/31398953/57277869-a6728480-70c2-11e9-82b6-c90c9a792ca4.png)

### Reproduction Link

You can download the CustomAndLibrary and sample in the below link.
Librabry project link: http://www.syncfusion.com/downloads/support/directtrac/general/ze/CustomAndLibrary-2090802213

Sample link: http://www.syncfusion.com/downloads/support/directtrac/general/ze/StringSplitExp268735194

I have also attached the Mscorlib Dll for your reference.
MsCorlib dll: http://www.syncfusion.com/downloads/support/directtrac/general/ze/Mscorlib_Dll1940088283

**Comment by grendello** [comment] 2019-05-09 10:24
Hi @shivagurunathan,

So I see two main problems here:

  1. Why a Xamarin.Android library references dotnet assemblies when built? This **may** be an msbuild problem on the machine with both Xamarin.Android and DotNet installed /cc @radical 
  2. The crash you're seeing is partly because of the above (because of the inadvertent reference to `String.Split (char, StringSplitOptions)`) because your Xamarin.Android versions between the two machines differ (see below).

Compare the following outputs for `mscorlib.dll` you provided:

 * `mscorlib` on the machine **with** DotNet installed (note the entry with token id `1590` - that's the signature of the method your DotNet core machine build of the library references):

```
$ monodis --method mscorlib.dll | grep Split
1590: instance default string[] Split (char separator, [opt] class System.StringSplitOptions options)  (param: 1963 impl_flags: cil managed )
1591: instance default string[] Split (char separator, int32 count, [opt] class System.StringSplitOptions options)  (param: 1965 impl_flags: cil managed )
1592: instance default string[] Split (char[] separator)  (param: 1968 impl_flags: cil managed )
1593: instance default string[] Split (char[] separator, int32 count)  (param: 1969 impl_flags: cil managed )
1594: instance default string[] Split (char[] separator, class System.StringSplitOptions options)  (param: 1971 impl_flags: cil managed )
1595: instance default string[] Split (char[] separator, int32 count, class System.StringSplitOptions options)  (param: 1973 impl_flags: cil managed )
1597: instance default string[] Split (string separator, [opt] class System.StringSplitOptions options)  (param: 1979 impl_flags: cil managed )
1598: instance default string[] Split (string separator, int32 count, [opt] class System.StringSplitOptions options)  (param: 1981 impl_flags: cil managed )
1599: instance default string[] Split (string[] separator, class System.StringSplitOptions options)  (param: 1984 impl_flags: cil managed )
1600: instance default string[] Split (string[] separator, int32 count, class System.StringSplitOptions options)  (param: 1986 impl_flags: cil managed )
```

* `mscorlib` from the machine **without** DotNet installed (note that there are only standard .NET overloads of the `Split` method present. In this case your call to `String.Split('c')` is resolved to the `char[]` overload with token id `4812`):

```
$ monodis --method mscorlib.dll | grep Split
4812: instance default string[] Split (char[] separator)  (param: 7084 impl_flags: cil managed )
4813: instance default string[] Split (char[] separator, int32 count)  (param: 7085 impl_flags: cil managed )
4814: instance default string[] Split (char[] separator, class System.StringSplitOptions options)  (param: 7087 impl_flags: cil managed )
4815: instance default string[] Split (char[] separator, int32 count, class System.StringSplitOptions options)  (param: 7089 impl_flags: cil managed )
4817: instance default string[] Split (string[] separator, class System.StringSplitOptions options)  (param: 7095 impl_flags: cil managed )
4818: instance default string[] Split (string[] separator, int32 count, class System.StringSplitOptions options)  (param: 7097 impl_flags: cil managed )
```

So while problem `1.` should be fixed, your issue can be worked around by using the newer version of `Xamarin.Android` from your machine **with** DotNet installed. I downloaded your samples, I did **not** rebuild the library, just the sample (using `Xamarin.Android` from the master branch) and the app ran without problems. I don't know which Xamarin.Android version started to include the DotNet core overloads, but it's a safe bet that whatever version you have installed on your machine wtht DotNet core is the one you should use (or any newer than that).

@jonpryor, @marek-safar - are you able to tell which Xamarin.Android version started to include mono with portions of the DotNet APIs?

**Comment by grendello** [comment] 2019-05-09 15:48
The referenced library (from the sample) references Xamarn.Android's mscorelib:

```
$ monodis --assemblyref CustomAndLibrary.dll 
AssemblyRef Table
1: Version=2.0.5.0
	Name=mscorlib
	Flags=0x00000000
	Public Key:
0x00000000: 7C EC 85 D7 BE A7 79 8E 
2: Version=0.0.0.0
	Name=Mono.Android
	Flags=0x00000000
	Public Key:
0x00000000: 84 E0 4F F9 CF B7 90 65 
3: Version=2.0.5.0
	Name=System
	Flags=0x00000000
	Public Key:
0x00000000: 7C EC 85 D7 BE A7 79 8E 
```

**Comment by softlion** [comment] 2019-05-09 18:44
You can+must not reference .NET core libs in Xamarin.Android apps. Only netstandard libs are supported. This seems obvious but...

**Comment by shivagurunathan** [comment] 2019-05-16 04:19
Thanks for the reply and confirming that it is an issue regarding mismatching of the versions. So can you please let me know when would the fix will be included.

**Comment by grendello** [comment] 2019-05-20 08:34
@shivagurunathan There's no fix we can implement here. The only solution to the problem is to ensure that both sides of your build system use a version of `Xamarin.Android` which has the `String.Split` overload in question present.

**Closed by grendello** 2019-05-20 08:34 UTC
Labels: Area: App+Library Build, Under Investigation, bug

**Comment by shivagurunathan** [comment] 2019-06-27 03:33
Hi @grendello ,
Ensuring to have the same version may be a temporary solution. But deploying in a machine with NetCore installed, and again deployed in a machine without NetCore installed would cause the crash. However, I guess the crashing of the application should not occur. Would there be any permanent solution or any fix will be appreciated.
