### ISSUE TITLE
AndroidManifest merger ignores 'tools:node="remove"'

### ISSUE THREAD

**Issue by mayhammf** [xamarin/xamarin-android#4662] opened 2020-05-07 12:35 UTC
### Steps to Reproduce

1. Create a new Xamarin Android project
2. Set the property AndroidManifestMerger to manifestmerger.jar in the csproj file
3. Add a permission in the AndroidManifest.xml width the attribute 'tools:node="remove"'. Ex: `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />`
4. Build the app.
5. Find the merged AndroidManifest.xml file under obj\100\debug

Sample project [App1.zip](https://github.com/xamarin/xamarin-android/files/4592931/App1.zip)

### Expected Behavior
The permission "WRITE_EXTERNAL_STORAGE" you added above must be removed after merge 

### Actual Behavior
The permission "WRITE_EXTERNAL_STORAGE" remains 

### Version Information
Microsoft Visual Studio Community 2019
Version 16.5.4
VisualStudio.16.Release/16.5.4+30011.22
Xamarin.Android SDK   10.2.0.100 (d16-5/988c811)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c0c5c78
    Java.Interop: xamarin/java.interop/d16-5@fc18c54
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

### Log File
N/A

### Related 
- Release note [announcing new merger](https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.2#improved-android-manifest-merging)
- Feature request closed as the new [merging tool has been implemented ](https://github.com/xamarin/xamarin-android/issues/1335#issuecomment-609835997)
- Official Android docs [regarding tools:node](https://developer.android.com/studio/build/manifest-merge#node_markers)

**Comment by brendanzagaeski** [comment] 2020-06-23 22:11
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.4.0.0.

Fix included on Windows in Visual Studio 2019 version 16.7 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 3. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment] 2020-08-05 22:26
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android SDK version 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.7. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by ChrisWortley** [comment] 2021-01-14 19:16
Hi. I understand this problem has been fixed – which is great - but I seem to be getting the same symptoms. I’m hoping someone can suggest what I’m doing wrong. Maybe I’ve misunderstood the fix/solution? Thank you

Visual Studio - 16.8.3
Xamarin.Android SDK - 11.1.0.17 (d16-8/c0e2b8e)

In Visual Studio, I created a brand new (empty) solution

In csproj, I added:
<PropertyGroup>
	<AndroidManifestMerger>manifestmerger.jar</AndroidManifestMerger>
</PropertyGroup>

In AndroidManifest.xml I added:
<manifest xmlns:tools="http://schemas.android.com/tools”
… and also added …
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />

But when I archive the project (for release), I still see the following inside the AndroidManifest.xml inside the apk: android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by ChrisWortley** [comment] 2021-01-14 19:24
Sorry - in my post of 7 mins ago I missed an important line:-
I also added <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />
to AndroidManifest.xml

**Comment by ChrisWortley** [comment] 2021-01-14 19:27
Sorry again - Each time I write the line, github iremoves it?? Trying again:- <uses-permission
android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />

**Comment by ChrisWortley** [comment] 2021-01-14 19:28
I don't understand why the lines I type are disappearing. Anyway, I'm trying to say that I added the same line as in the example at the top of this issue

**Comment by dellis1972** [comment] 2021-01-15 11:57
@ChrisWortley you need to escape things which are code using three back ticks ```<foo>```  :) I updated your first post. You can edit it to see what I did. 

As for the AndroidManifest.xml we have an example for removing permissions in one of our unit tests
https://github.com/xamarin/xamarin-android/blob/d794534cebc3378326f6220dc54218616b9e5850/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs#L190
Take a look and see if there is any difference between what you are doing and what we do in the test.

**Comment by dellis1972** [comment] 2021-01-15 12:00
Also double check your don't have that permissions in the AssemblyInfo.cs as a Permission Attribute. That might be injected after the manifest merger has been run.

**Comment by ChrisWortley** [comment] 2021-01-16 08:07
Thank you very much for coming back to me – and for helping with my query and also with my posting difficulties :) 
Yes, there are some UserPermission lines in my AssemblyInfo.cs - but they are commented-out.
So, the next step is for me to look at the unit test and compare it with what I’m doing. Thank you for the link. I’m afraid I’ve not done this before and I’m struggling to see how to load it into Visual Studio. I tried ‘clone a repository’ (after enabling the link between github and Visual Studio) - but during the clone process I get a fatal error. Can you set me on the right path? Thank you.

**Comment by ivanicin** [comment] 2021-01-19 11:17
I can confirm that this still doesn't work just like @ChrisWortley  says. I don't have anything in AssemblyInfo.cs related to permissions, it is actually the default file. If you closed the bug I assume that it works in some situations. But probably something can override this and add the permission again after you remove it.

So please reopen this.

**Comment by ivanicin** [comment] 2021-01-19 11:22
Thinking some more, if nuget packages can add permissions through AssemblyInfo.cs and they probably can, then it is obvious why this is happening. And that can't be treated like developer's problem, it is a tool problem that needs to be resolved. Please reopen and fix it, thanks.

**Comment by dellis1972** [comment] 2021-01-19 13:39
@ChrisWortley / @ivanicin  can you upload a sample solution you have a problem with?

The New One you mentioned in this comment https://github.com/xamarin/xamarin-android/issues/4662#issuecomment-760411514 would be helpful. There is possibly a test case which we don't have covered in our unit tests. 

@ChrisWortley don't worry about building the tests, that link was just for reference so you could see what we used for the manifest.

**Comment by ChrisWortley** [comment] 2021-01-19 14:55
Thank you @dellis1972 

I’ve attached my “test_merger_without_obj_or_bin_in_android_project” solution as a zip file. (I had to remove the obj and bin files to make the solution small enough to post. Maybe I was supposed to do it another way??)

Inside the files, I’ve added comments (all beginning ‘CW’) to indicate the test lines, the expected results, and the actual results. Hopefully it all makes sense.

BTW, I realise that it’s confusing trying to experiment with different user-permission lines in the manifest because (a) whenever a solution is loaded into Visual Studio, the manifest file gets tidied up – and, at the same time, the permission lines in the file are interpreted and then indicated by ticks in the permissions list in the project properties tab. And then (b) if you then untick anything in the permissions list, all lines in the manifest that have that permission seem to be affected, including ‘remove’ lines. 

[test_merger_without_obj_or_bin_in_android_project.zip](https://github.com/xamarin/xamarin-android/files/5836615/test_merger_without_obj_or_bin_in_android_project.zip)

**Comment by dellis1972** [comment] 2021-01-20 14:37
@ChrisWortley thanks for the test project. I believe I now know where the confusion is.

Firstly the test project did not have the manifest merger enabled. The current stable release does not have this enabled by default. You have to "opt in" using the following in your csproj.

```
<AndroidManifestMerger>manifestmerger.jar</AndroidManifestMerger>
```

This will then allow the `tools:node="remove"` entires to be processed. That said one of the assumptions you mentioned in the comments are currently incorrect.

```
<!--CW This line added to test what happens when the CAMERA permission is removed lower down -->
<uses-permission android:name="android.permission.CAMERA" />
<!--CW I would expect this line to make sure the CAMERA permission (added above) doesn't appear in the final manifest (inside the apk), -->
<uses-permission android:name="android.permission.CAMERA" tools:node="remove" />
```

Having the permission declared and removed in the same manifest will not work. The manifest merger tool will not remove any permission which is declared in the same file. The `tools:node="remove"` will only work for permissions/entries which are pulled in from "other" sources. Like third party libraries or aar files.

This next section
```
<!--CW I would expect this line to make sure the WRITE_EXTERNAL_STORAGE permission doesn't appear in the final manifest (inside the apk), even if the permission gets added by a library earlier in the manifest merge -->
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />	
```

Is 100% correct. This is what it is designed to do. It will remove permissions which have been declared in "other" libraries.
When I added the `AndroidManifestMerger` element to the project and un commented the `[assembly: UsesPermission(Android.Manifest.Permission.WriteExternalStorage)]` line in AssemblyInfo.cs it behaved as expected. The `android.permission.WRITE_EXTERNAL_STORAGE` did not appear in the final AndroidManifest.xml.

You can see the result of the merge by looking at the following file `obj/Release/android/AndroidManifest.xml` in your build tree.

Again currently the manifest merger tool is not on by default. You need to add

```
<AndroidManifestMerger>manifestmerger.jar</AndroidManifestMerger>
```

to the `PropertyGroup` in your android app csproj to get this new functionality to work.

**Comment by dellis1972** [comment] 2021-01-20 14:48
@ivanicin I hope the above [comment](https://github.com/xamarin/xamarin-android/issues/4662#issuecomment-763648874) helps you as well. 

If there is a specific test case that is not working please provide me a test project or details of which NuGet/Library packages you are referencing and which permission is not being removed so that I can reproduce your issue.

**Comment by ChrisWortley** [comment] 2021-01-20 15:55
Thank you, again, @dellis1972 for taking the time to analyse my test file :) 

I understand what you’re saying about needing to switch on the manifest merger tool, but I’m puzzled because I thought I’d done just that? I have the same line of code as you. You can see it in my “test_merger\test_merger.csproj” file, inside a PropertyGroup tag. So, I’m confused. Have I put the code in the wrong place? Or is it possible there’s something missing from my development setup, something that is needed to get at the merger tool?

**Comment by dellis1972** [comment] 2021-01-20 16:20
@ChrisWortley you put it in the Xamarin.Form netstandard project, not the Main Android app project. NetStandard doesn't know anything about the android stuff which is why it didn't work. So in your example you needed to put it in the `test_merger.Android.csproj` not the `test_merger.csroj`

**Comment by ChrisWortley** [comment] 2021-01-20 18:52
Ahhr. So, that’s what I was doing wrong. Yes, it’s working now. Thank you, @dellis1972

I should say, I looked in vain for a way to edit ‘test_merger.android.csproj’ from within Visual Studio. (Sorry, I’m not as familiar with the Visual Studio as I should be.) Instead, I had to edit the file outside Visual Studio. After that, Visual Studio detected the file-date change - and then told me that it had successfully reloaded the file. (Although, I still don’t know where). I then archived the project again – and now, sure enough, the ‘remove’ line works as expected. Thank you for explaining. 

(I am very pleased to have got this problem sorted. I’m almost ready to release my very first app. It uses no permissions - and I was worried that extraneous ‘required’ permissions – all of which get listed on google play – would put off potential purchasers.)

**Comment by dellis1972** [comment] 2021-01-20 19:13
@ChrisWortley  glad its working :). To Edit "old" style csprojs like Android ones in Visual Studio, you have to use the Unload menu item. You get that when you right click on the project in the solution explorer. Once you do that you can then right click and get access to the Edit menu.

**Comment by ivanicin** [comment] 2021-01-21 11:40
> Again currently the manifest merger tool is not on by default. You need to add
> 
> ```
> <AndroidManifestMerger>manifestmerger.jar</AndroidManifestMerger>
> ```
> 
> to the `PropertyGroup` in your android app csproj to get this new functionality to work.

I was missing this, thanks.

**Comment by dellis1972** [comment] 2021-01-21 13:10
ok cool :D I'm closing this issue for now.

**Closed by dellis1972** 2021-01-21 13:10 UTC
Labels: Area: App+Library Build, need-info
