### ISSUE TITLE
AOT compilation failure - VS2019 16.4.0 Preview 1.0 

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#3681] opened 2019-09-24 23:59 UTC
[aot-compiler stderr] '""C:\Program' is not recognized as an internal or external command,
[aot-compiler stderr] operable program or batch file.
[aot-compiler stderr] AOT of image D:\ProjectsVS2019Preview\NavXApp\obj\Release\90\android\assets\Xamarin.AndroidX.Annotation.dll failed.
XA3001: Could not AOT the assembly: Xamarin.AndroidX.Annotation.dll

[BuildLogNavXappFailedAOT.zip](https://github.com/xamarin/xamarin-android/files/3649915/BuildLogNavXappFailedAOT.zip)

Looks like it is not quoted properly.

**Comment by brendanzagaeski** [comment] 2019-09-25 00:59
Many thanks for trying this new preview already and reporting this! There's a fix upcoming for this issue in the next preview.

**Comment by brendanzagaeski** [comment] 2019-09-25 00:59
Duplicate of https://github.com/xamarin/xamarin-android/issues/3619

**Closed by brendanzagaeski** 2019-09-25 00:59 UTC
