### ISSUE TITLE
Xamarin.Android.Support.v4  version="25.4.0.2" targetFramework="monoandroid71" 

### ISSUE THREAD

**Issue by cctvbnm1111** [xamarin/xamarin-android#1215] opened 2018-01-22 03:58 UTC
### Steps to Reproduce

1. Add nuget
```
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Annotations" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Compat" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.UI" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.Utils" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Fragment" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Media.Compat" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Transition" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="25.4.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="25.4.0.2" targetFramework="monoandroid71" />
```
2.  mainactivity :AppCompatActivity
Android.Support.V7.App.AppCompatDelegate.CompatVectorFromResourcesEnabled = true;
3. 
```
[mono] 
[mono] Unhandled Exception:
[mono] Android.Content.Res.Resources+NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052 ---> Org.XmlPull.V1.XmlPullParserException: Binary XML file line #15: invalid drawable tag vector
[mono]    --- End of inner exception stack trace ---
[mono]   --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---
[mono] android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
[mono] 	at android.content.res.Resources.loadDrawable(Resources.java:2096)
[mono] 	at android.content.res.Resources.getDrawable(Resources.java:700)
[mono] 	at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:74)
[mono] 	at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:437)
[mono] 	at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:67)
[mono] 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
[mono] 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
[mono] 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
[mono] 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
[mono] 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
[mono] 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
[mono] 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
[mono] 	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:155)
[mono] 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
[mono] 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
[mono] 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
[mono] 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
[mono] 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
[mono] 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
[mono] 	at md5d4650294d969630d3e35ba1924da8f51.LogoActivity.n_onCreate(Native Method)
[mono] 	at md5d4650294d969630d3e35ba1924da8f51.LogoActivity.onCreate(LogoActivity.java:40)
[mono] 	at android.app.Activity.performCreate(Activity.java:5231)
[mono] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
[mono] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
[mono] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
[mono] 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
[mono] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
[mono] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[mono] 	at android.os.Looper.loop(Looper.java:136)
[mono] 	at android.app.ActivityThread.main(ActivityThread.java:5001)
[mono] 	at java.lang.reflect.Method.invokeNative(Native Method)
[mono] 	at java.lang.reflect.Method.invoke(Method.java:515)
[mono] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
[mono] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
[mono] 	at dalvik.system.NativeStart.main(Native Method)
[mono] Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #15: invalid drawable tag vector
[mono] 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
[mono] 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
[mono] 	at android.content.res.Resources.loadDrawable(Resources.java:2092)
[mono] 	... 34 more
[mono] 
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Android.Content.Res.Resources+NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052 ---> Org.XmlPull.V1.XmlPullParserException: Binary XML file line #15: invalid drawable tag vector
[mono-rt]    --- End of inner exception stack trace ---
[mono-rt]   --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---
[mono-rt] android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
[mono-rt] 	at android.content.res.Resources.loadDrawable(Resources.java:2096)
[mono-rt] 	at android.content.res.Resources.getDrawable(Resources.java:700)
[mono-rt] 	at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:74)
[mono-rt] 	at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:437)
[mono-rt] 	at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:67)
[mono-rt] 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
[mono-rt] 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
[mono-rt] 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
[mono-rt] 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
[mono-rt] 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
[mono-rt] 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
[mono-rt] 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
[mono-rt] 	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:155)
[mono-rt] 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
[mono-rt] 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
[mono-rt] 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
[mono-rt] 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
[mono-rt] 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
[mono-rt] 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
[mono-rt] 	at md5d4650294d969630d3e35ba1924da8f51.LogoActivity.n_onCreate(Native Method)
[mono-rt] 	at md5d4650294d969630d3e35ba1924da8f51.LogoActivity.onCreate(LogoActivity.java:40)
[mono-rt] 	at android.app.Activity.performCreate(Activity.java:5231)
[mono-rt] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
[mono-rt] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
[mono-rt] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
[mono-rt] 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
[mono-rt] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[mono-rt] 	at android.os.Looper.loop(Looper.java:136)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:5001)
[mono-rt] 	at java.lang.reflect.Method.invokeNative(Native Method)
[mono-rt] 	at java.lang.reflect.Method.invoke(Method.java:515)
[mono-rt] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
[mono-rt] 	at dalvik.system.NativeStart.main(Native Method)
[mono-rt] Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #15: invalid drawable tag vector
[mono-rt] 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
[mono-rt] 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
[mono-rt] 	at android.content.res.Resources.loadDrawable(Resources.java:2092)
[mono-rt] 	... 34 more
```

SDK:
Mono 
5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
Xamarin.Android
8.0.2.1 (Visual Studio Enterprise)

[OP edited for clarity (quoting)]

**Comment by JonDouglas** [comment] 2018-01-22 22:39
@cctvbnm1111 Can you please include the version of `build-tools` you are using? You can find this information in a [Diagnostic Build Output](https://developer.xamarin.com/guides/android/troubleshooting/troubleshooting/#Diagnostic_MSBuild_Output).

I believe you need to use a minimum of `build-tools` v25+ for proper support of this version of support library. With that said, it's easiest to just use the latest version of `build-tools` as they are typically additive.

**Comment by JonDouglas** [comment] 2018-01-23 03:07
@cctvbnm1111 I was not able to reproduce this with the steps you've provided. Can you please upload a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve)?

I tested this both against v26 and v25 support library versions and was able to deploy & run an app against > API 19 and <= API 19. 

Please also include what API level of android you are deploying to(Device/Emulator).

**Comment by jonpryor** [comment] 2018-06-05 23:09
Closing due to non-response.

**Closed by jonpryor** 2018-06-05 23:09 UTC
