### ISSUE TITLE
App crashes with debugger attached but only sometimes

### ISSUE THREAD

**Issue by DiogoMartinh0** [xamarin/xamarin-android#3456] opened 2019-08-07 17:49 UTC
I am sorry for not following the issue template, but couldn't get my mind around that with this current problem.

After updating Android's Support Libraries (v28.0+) to get targeted with monoandroid90, the app crashes sometimes with the stack trace I provided bellow. If there are breakpoints active this won't happen.

Different versions of Xamarin.Android were tested, the current one I'm using is the latest 9.4.1.0 that comes with the default vs19. I was not able to reproduce this on a fresh install of the vs17 with the default XA that comes with it (9.1.7.0)

**Using versions**
Visual Studio 2019 v16.2 or 16.2.1
Xamarin 16.2.0.91
Xamarin.Android.SDK 9.4.1.0

The following stack trace shows the current problem I'm facing.

First thing that strike the eyes is that "Thread Pool Worker". No settings for thread pools were changed, we're running defaults.

```
"Thread Pool Worker"  at <unknown> <0xffffffff>
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x00007>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) [0x0002b] in <ff07eae8184a40a08e79049bbcb31a0e>:0

"Finalizer"08-06 16:26:25.748 E/mono    (11487): Full thread dump:


"Thread Pool Worker"  at <unknown> <0xffffffff>
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x00007>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) [0x0002b] in <ff07eae8184a40a08e79049bbcb31a0e>:0

"Debugger agent"

"Timer-Scheduler"  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Threading.WaitHandle.Wait_internal (intptr*,int,bool,int) <0x00007>
  at System.Threading.WaitHandle.WaitOneNative (System.Runtime.InteropServices.SafeHandle,uint,bool,bool) [0x0001f] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Threading.WaitHandle.InternalWaitOne (System.Runtime.InteropServices.SafeHandle,long,bool,bool) [0x00019] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Threading.WaitHandle.WaitOne (long,bool) [0x00010] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Threading.WaitHandle.WaitOne (int,bool) [0x0001d] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Threading.WaitHandle.WaitOne (int) [0x00003] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Threading.Timer/Scheduler.SchedulerThread () [0x00043] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (object) [0x0001f] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00073] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00004] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) [0x0002f] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Threading.ThreadHelper.ThreadStart () [0x00014] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x00067] in <ff07eae8184a40a08e79049bbcb31a0e>:0

"<unnamed thread>"
08-06 16:26:35.755 I/libc    (11487): Requested dump for tid 11487 (ler.challengeme)
```

Possible related issues:
https://github.com/xamarin/xamarin-android/issues/2920
https://github.com/xamarin/xamarin-android/issues/3222
https://github.com/mono/mono/issues/14772

**Comment by Strifex** [comment] 2019-08-08 02:26
Hey just wanted to say I've had this exact same issue! Mine happens when debugging and calling cancel() on a cancelationtokensource - but I've also seen it happen randomly in other scenarios.

**Comment by mariajoserabaza** [comment] 2019-08-08 14:39
I started facing the same issue yesterday. In my case it also happen in randomly scenarios. 

I'm using:
VS 2019 16.2.1
Xamarin 16.2.0.91
Xamarin.Android.SDK 9.4.1.0
Mono Debugging for Visual Studio 16.2.6

`"Thread Pool Worker"  at <unknown> <0xffffffff>
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x00012>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) [0x00028] in <ff07eae8184a40a08e79049bbcb31a0e>:0
08-07 19:17:23.620 E/mono    ( 9986): Full thread dump:

"Thread Pool Worker"  at <unknown> <0xffffffff>
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x00012>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) [0x00028] in <ff07eae8184a40a08e79049bbcb31a0e>:0

"Debugger agent"
"Thread Pool I/O Selector"
"Finalizer"
"Timer-Scheduler"

"Thread Pool Worker"

"<unnamed thread>"  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.Assembly.LoadFrom (string,bool,System.Threading.StackCrawlMark&) <0x00015>
  at System.Reflection.Assembly.InternalGetSatelliteAssembly (string,System.Globalization.CultureInfo,System.Version,bool,System.Threading.StackCrawlMark&) [0x000b3] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly (System.Globalization.CultureInfo,System.Threading.StackCrawlMark&) [0x0005d] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet (System.Globalization.CultureInfo,System.Collections.Generic.Dictionary`2<string, System.Resources.ResourceSet>,bool,bool,System.Threading.StackCrawlMark&) [0x00035] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo,bool,bool,System.Threading.StackCrawlMark&) [0x000a6] in <ff07eae8184a40a08e7904
9bbcb31a0e>:0
  at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo,bool,bool) [0x00008] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at System.Resources.ResourceManager.GetString (string,System.Globalization.CultureInfo) [0x0005e] in <ff07eae8184a40a08e79049bbcb31a0e>:0
  at SkyMobile.Core.Localization.TranslateExtension.ProvideValue (System.IServiceProvider) [0x00035] in E:\SkyMobileGit\skyjunxionmobile\SkyMobile\SkyMobile\SkyMobile.Core\Localization\TranslateExtension.cs:34
  at SkyMobile.Core.Views.Trip.TripSummaryView/<InitializeComponent>_anonXamlCDataTemplate_54.LoadDataTemplate () [0x012a2] in <6a6853ed928441888813de2e999dbcc4>:0
  at Xamarin.Forms.ElementTemplate.CreateContent () [0x00026] in D:\a\1\s\Xamarin.Forms.Core\ElementTemplate.cs:82
  at SkyMobile.Core.Views.RepeaterView.ViewFor (object) [0x0002f] in E:\SkyMobileGit\skyjunxionmobile\SkyMobile\SkyMobile\SkyMobile.Core\Views\Components\RepeaterView.cs:80
  at SkyMobile.Core.Views.RepeaterView.ItemsChanged 
(Xamarin.Forms.BindableObject,object,object) [0x00058] in E:\SkyMobileGit\skyjunxionmobile\SkyMobile\SkyMobile\SkyMobile.Core\Views\Components\RepeaterView.cs:113
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty,Xamarin.Forms.BindableObject/BindablePropertyContext,object,bool,Xamarin.Forms.Internals.SetValueFlags,bool) [0x00120] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:624
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty,object,Xamarin.Forms.Internals.SetValueFlags,Xamarin.Forms.BindableObject/SetValuePrivateFlags) [0x00179] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:422
  at Xamarin.Forms.BindingExpression.ApplyCore (object,Xamarin.Forms.BindableObject,Xamarin.Forms.BindableProperty,bool) [0x00220] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:167
  at Xamarin.Forms.BindingExpression.Apply (object,Xamarin.Forms.BindableObject,Xamarin.Forms.BindableProperty) [0x0006b] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:78
  at X
amarin.Forms.Binding.Apply (object,Xamarin.Forms.BindableObject,Xamarin.Forms.BindableProperty,bool) [0x00057] in D:\a\1\s\Xamarin.Forms.Core\Binding.cs:131
  at Xamarin.Forms.BindableObject.ApplyBindings (bool,bool) [0x00041] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:453
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject,object) [0x0005a] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:158
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:486
  at Xamarin.Forms.Element.<OnBindingContextChanged>b__74_0 (Xamarin.Forms.BindableObject,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:294
  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext<T_REF> (Xamarin.Forms.BindableObject,System.Collections.Generic.IList`1<T_REF>,System.Action`2<Xamarin.Forms.BindableObject, object>) [0x0002c] in D:\a\1\s\Xamarin.Forms.Core\BindableObjectExtensions.cs:28
  at Xam
arin.Forms.Element.OnBindingContextChanged () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:292
  at Xamarin.Forms.View.OnBindingContextChanged () [0x0000c] in D:\a\1\s\Xamarin.Forms.Core\View.cs:158
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject,object) [0x00062] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:159
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:486
  at Xamarin.Forms.Element.<OnBindingContextChanged>b__74_0 (Xamarin.Forms.BindableObject,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:294
  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext<T_REF> (Xamarin.Forms.BindableObject,System.Collections.Generic.IList`1<T_REF>,System.Action`2<Xamarin.Forms.BindableObject, object>) [0x0002c] in D:\a\1\s\Xamarin.Forms.Core\BindableObjectExtensions.cs:28
  at Xamarin.Forms.Element.OnBindingContextChanged () [0x00000] in D:\a\1\s\Xamari
n.Forms.Core\Element.cs:292
  at Xamarin.Forms.View.OnBindingContextChanged () [0x0000c] in D:\a\1\s\Xamarin.Forms.Core\View.cs:158
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject,object) [0x00062] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:159
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:486
  at Xamarin.Forms.Element.<OnBindingContextChanged>b__74_0 (Xamarin.Forms.BindableObject,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:294
  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext<T_REF> (Xamarin.Forms.BindableObject,System.Collections.Generic.IList`1<T_REF>,System.Action`2<Xamarin.Forms.BindableObject, object>) [0x0002c] in D:\a\1\s\Xamarin.Forms.Core\BindableObjectExtensions.cs:28
  at Xamarin.Forms.Element.OnBindingContextChanged () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:292
  at Xamarin.Forms.View.OnBindingContextChange
d () [0x0000c] in D:\a\1\s\Xamarin.Forms.Core\View.cs:158
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject,object) [0x00062] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:159
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:486
  at Xamarin.Forms.Element.<OnBindingContextChanged>b__74_0 (Xamarin.Forms.BindableObject,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:294
  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext<T_REF> (Xamarin.Forms.BindableObject,System.Collections.Generic.IList`1<T_REF>,System.Action`2<Xamarin.Forms.BindableObject, object>) [0x0002c] in D:\a\1\s\Xamarin.Forms.Core\BindableObjectExtensions.cs:28
  at Xamarin.Forms.Element.OnBindingContextChanged () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:292
  at Xamarin.Forms.View.OnBindingContextChanged () [0x0000c] in D:\a\1\s\Xamarin.Forms.Core\View.cs:158
  at Xamarin.For
ms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject,object) [0x00062] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:159
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:486
  at Xamarin.Forms.Element.<OnBindingContextChanged>b__74_0 (Xamarin.Forms.BindableObject,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:294
  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext<T_REF> (Xamarin.Forms.BindableObject,System.Collections.Generic.IList`1<T_REF>,System.Action`2<Xamarin.Forms.BindableObject, object>) [0x0002c] in D:\a\1\s\Xamarin.Forms.Core\BindableObjectExtensions.cs:28
  at Xamarin.Forms.Element.OnBindingContextChanged () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:292
  at Xamarin.Forms.View.OnBindingContextChanged () [0x0000c] in D:\a\1\s\Xamarin.Forms.Core\View.cs:158
  at Xamarin.Forms.Grid.OnBindingContextChanged () [0x00006] in D:\a\1\s\Xamarin.Forms.Cor
e\Grid.cs:147
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject,object) [0x00062] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:159
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:486
  at Xamarin.Forms.Element.<OnBindingContextChanged>b__74_0 (Xamarin.Forms.BindableObject,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:294
  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext<T_REF> (Xamarin.Forms.BindableObject,System.Collections.Generic.IList`1<T_REF>,System.Action`2<Xamarin.Forms.BindableObject, object>) [0x0002c] in D:\a\1\s\Xamarin.Forms.Core\BindableObjectExtensions.cs:28
  at Xamarin.Forms.Element.OnBindingContextChanged () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:292
  at Xamarin.Forms.View.OnBindingContextChanged () [0x0000c] in D:\a\1\s\Xamarin.Forms.Core\View.cs:158
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext
 (Xamarin.Forms.BindableObject,object) [0x00062] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:159
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:486
  at Xamarin.Forms.TemplatedView.SetChildInheritedBindingContext (Xamarin.Forms.Element,object) [0x00008] in D:\a\1\s\Xamarin.Forms.Core\TemplatedView.cs:67
  at Xamarin.Forms.Element.<OnBindingContextChanged>b__74_0 (Xamarin.Forms.BindableObject,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:294
  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext<T_REF> (Xamarin.Forms.BindableObject,System.Collections.Generic.IList`1<T_REF>,System.Action`2<Xamarin.Forms.BindableObject, object>) [0x0002c] in D:\a\1\s\Xamarin.Forms.Core\BindableObjectExtensions.cs:28
  at Xamarin.Forms.Element.OnBindingContextChanged () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:292
  at Xamarin.Forms.View.OnBindingContextChanged () [0x0000c] in D:\a\1\s\Xamarin.
Forms.Core\View.cs:158
  at Xamarin.Forms.ContentView.OnBindingContextChanged () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\ContentView.cs:16
  at SkyMobile.Core.Views.Trip.TripSummaryView.OnBindingContextChanged () [0x00001] in E:\SkyMobileGit\skyjunxionmobile\SkyMobile\SkyMobile\SkyMobile.Core\Views\Trip\TripSummary\TripSummaryView.xaml.cs:37
  at Xamarin.Forms.BindableObject.BindingContextPropertyChanged (Xamarin.Forms.BindableObject,object,object) [0x0000f] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:473
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty,Xamarin.Forms.BindableObject/BindablePropertyContext,object,bool,Xamarin.Forms.Internals.SetValueFlags,bool) [0x00120] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:624
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty,object,Xamarin.Forms.Internals.SetValueFlags,Xamarin.Forms.BindableObject/SetValuePrivateFlags) [0x00179] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:422
  at Xamarin.For
ms.BindingExpression.ApplyCore (object,Xamarin.Forms.BindableObject,Xamarin.Forms.BindableProperty,bool) [0x00220] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:167
  at Xamarin.Forms.BindingExpression.Apply (bool) [0x0003e] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:57
  at Xamarin.Forms.BindingExpression/BindingExpressionPart.<PropertyChanged>b__49_0 () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:618
  at Java.Lang.Thread/RunnableImplementor.Run () [0x0000e] in <b62c3fba3fe848f3bb323dbe33464223>:0
  at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x0000a] in <b62c3fba3fe848f3bb323dbe33464223>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.29 (intptr,intptr) [0x00011] in <b62c3fba3fe848f3bb323dbe33464223>:0
  at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.29 (intptr,intptr) [0x00030] in <b62c3fba3fe848f3bb323dbe33464223>:0
`

**Comment by DiogoMartinh0** [comment] 2019-08-08 15:02
Also happens on Xamarin.Android.SDK 9.4.0.51

**Comment by DiogoMartinh0** [comment] 2019-08-08 19:00
All the tests that were made with vs19 add the following non-standard extensions installed:

[HotReload for XF](https://github.com/AndreiMisiukevich/HotReload)
[.NET Portability Analyser](https://blogs.msdn.microsoft.com/dotnet/2014/08/06/leveraging-existing-code-across-net-platforms/)
[ResXManager](https://github.com/tom-englert/ResXResourceManager)
[XAML Styler](https://github.com/Xavalon/XamlStyler/)

**Comment by Evige** [comment] 2019-08-13 09:39
I am facing the same issue. 

Versions:
VS 2019 16.2.1
Xamarin 16.2.0.91
Xamarin.Android.SDK 9.4.1.0
Mono Debugging for Visual Studio 16.2.6

I am also getting the following error from Visual Studio which sometimes happens at the same time with the thread pool issue above:

> Value cannot be null.
> Parameter name: key
> System.ArgumentNullException: Value cannot be null.
> Parameter name: key
>    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>    at Mono.Debugging.VisualStudio.ExceptionsAdapter.GetState(String type) in E:\A\_work\3253\s\src\Debugging.VisualStudio.Vsix\Integration\ExceptionsAdapter.cs:line 135
>    at Mono.Debugging.VisualStudio.ExceptionsAdapter.OnExceptionThrown(Object sender, TargetEventArgs args) in E:\A\_work\3253\s\src\Debugging.VisualStudio.Vsix\Integration\ExceptionsAdapter.cs:line 52
>    at Mono.Debugging.Client.DebuggerSession.OnTargetEvent(TargetEventArgs args) in E:\A\_work\3253\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Client\DebuggerSession.cs:line 1144
>    at Mono.Debugging.Soft.SoftDebuggerSession.HandleBreakEventSet(Event[] es, Boolean dequeuing) in E:\A\_work\3253\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1906
>    at Mono.Debugging.Soft.SoftDebuggerSession.<>c__DisplayClass153_0.<DequeueEventsForFirstThread>b__0(Object <p0>) in E:\A\_work\3253\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2164

I also noticed that Xamarin.iOS is getting same kind of Visual Studio errors while debugging. I don't know if they are related in any way.

**Comment by mariajoserabaza** [comment] 2019-08-13 15:05
Please check this [link](https://developercommunity.visualstudio.com/content/problem/683582/xamarin-forms-application-failed-to-work-in-debug.html) out. It seems that Xamarin Forms application failed to work in debug mode in Version 16.2.X.

**Comment by brendanzagaeski** [comment] 2019-08-13 20:52
Thanks for the report! The team now has a test case for this issue and is investigating it. I will keep this issue updated with any potential workarounds as well as the release status of any candidate fixes.

**Comment by brendanzagaeski** [comment] 2019-08-13 20:55
Internal cross-referencing link for the Microsoft team:

> VS bug [#963580](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/963580)

**Comment by bcaceiro** [comment] 2019-08-21 13:59
Any news on this issue?

**Comment by techduggu** [comment] 2019-08-25 07:48
I have also got this issue today when I updated to VS v.16.3.0 and then it auto-updated the Android Tools SDK to v.28.0.3. I resolved it (just a workaround) by putting the breakpoint in my code before deploying it to emulator. After this, the issue went away even though if I put breakpoint or not. Weird!

**Comment by anpin** [comment] 2019-09-11 11:45
I believe I have a related issue, but it happens every time I'm running some code with debugger enabled.

Versions:
VS 2019 16.2.5
Xamarin 16.2.0.95
Xamarin.Android.SDK 9.4.1.1
Mono Debugging for Visual Studio 16.2.6

`Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Debugging.VisualStudio.ExceptionsAdapter.OnExceptionThrown(Object sender, TargetEventArgs args) in E:\A\_work\3253\s\src\Debugging.VisualStudio.Vsix\Integration\ExceptionsAdapter.cs:line 52
   at Mono.Debugging.Client.DebuggerSession.OnTargetEvent(TargetEventArgs args) in E:\A\_work\3253\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Client\DebuggerSession.cs:line 1144
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleBreakEventSet(Event[] es, Boolean dequeuing) in E:\A\_work\3253\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1906
   at Mono.Debugging.Soft.SoftDebuggerSession.<>c__DisplayClass153_0.<DequeueEventsForFirstThread>b__0(Object <p0>) in E:\A\_work\3253\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2164`

**Comment by drjaydenm** [comment] 2019-09-20 05:37
Hi there, is there any timeline or plans to get this issue resolved? It happens to us when debugging 2/3 times.
If I can provide any information to help out, please let me know

**Comment by Strifex** [comment] 2019-09-20 06:01
@brendanzagaeski any updates from the team on this issue? My team is forced to stay on VS16.1 until this is resolved or else we cannot debug a key feature of our app.....any updates would be appreciated as we'd love to be able to update VS in the future.......

**Comment by brendanzagaeski** [comment] 2019-09-20 19:44
Apologies for the lack of status updates on this item. I checked with the team and can add some new info.

Plans for fixes:

The current planned fixes carry some risk, so they are tentatively scheduled for inclusion in an upcoming Visual Studio 2019 Preview version. The behavior will be the same in the upcoming Visual Studio 2019 version 16.4 Preview 1, but a future preview after that will include candidate fixes. I will keep this item updated with the version numbers of future Preview and Release versions that include fixes.

Cause:

The team has identified that this problem happens when several exceptions are thrown (and caught) in a short time. Currently the Mono debugger is sending *all* of the exceptions to Visual Studio, and Visual Studio is then checking each one to determine whether Visual Studio is configured to break on the exception. The overhead of checking the exceptions is somewhat costly. When part of an app produces several exceptions in a short time, the app gets stuck waiting for Visual Studio to finish checking the exceptions.

Unfortunately, changing the exception settings in Visual Studio doesn't currently affect the overhead, so those settings won't help work around the issue at the moment.

**Comment by drjaydenm** [comment] 2019-09-20 20:55
Thanks for the update and great to hear to root cause is known. Do you know if VS for Mac will include these fixes when available too?

**Comment by brendanzagaeski** [comment] 2019-09-30 23:26
@drjaydenm, apologies for the slow reply. I checked with the team about Visual Studio for Mac, and they let me know that the current known issue does not affect Visual Studio for Mac. The change in exception checking behavior between Visual Studio 2019 versions 16.1 and 16.2 that caused a performance problem on Windows was only applied on Windows. (I also quickly checked the user test case that demonstrated the issue on Windows and verified that I was not able to reproduce the performance problem on Visual Studio for Mac.)

If you are seeing a similar behavior on Visual Studio for Mac, then the team would be interested to take a closer look at your scenario. When you get a chance, if you could open a new issue here or via **Help > Report a Problem** in the IDE and include a brief re-summarization of what you're seeing plus any example code you can share, that would be perfect. Thanks in advance!

**Comment by tebcssDev** [comment] 2019-10-16 09:42
Interestingly I can make it work if I just revert to older versions of the packages (e.g. Xamarin.Forms).

**Comment by KthProg** [comment] 2019-10-16 17:46
How is it going? It's been a long time since an update has been posted.

**Comment by brendanzagaeski** [comment] 2019-10-19 06:35
*Release status update*

A new Preview version has now been published that includes an initial improvement for this behavior. The improvement is intended to restore the debugging performance to be comparable to Visual Studio 2019 version 16.1, with a limitation that **All Common Language Runtime Exceptions not in this list** must be left unchecked under **Debug > Windows > Exception Settings**:

![image](https://user-images.githubusercontent.com/4934473/67138915-0ab37b80-f1ff-11e9-912d-7ce63077db11.png)

(An additional fix is planned to remove this limitation in the future.)

The improvement is included on Windows in Visual Studio 2019 version 16.4 Preview 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

The improvement is not yet included in a Release version. I will update this item again when a Release version is available that includes the improvement.

**Comment by tlhintoq** [comment] 2019-11-04 15:53
I have been struggling with these 'debug-time-only' crashes for a couple weeks and only just now stumbled across this issue thread.

We were updating our app from Android 5 to Android 9 compatibility, which also meant Visual Studio 2017 to VS2019.  So a lot of changes and I just though the newer tooling was bringing existing problems being swallowed up, to light.  In a way I guess it did - just not in a way that was intentional.

> Cause:
> The team has identified that this problem happens when several exceptions are thrown (and caught) in a short time.

Since the problem is caused by rapid exception throwing overwhelming Visual Studio... it forced me to audit code by the rest of the teams and resolve their bad practices.  How many places people don't do null checks and just wrap their code in `try/catch` for example. Or really tight repeating loops that start stomping on each other. (10 second loop on a web services call that takes 15 seconds with a 30 second timeout)

So while the _way_ this helped find bad code wasn't intentional I will say it forced the finding and fixing of code that I otherwise wouldn't have gotten the man-hour approval for if it hadn't been so bad it was crashing Visual Studio.  When you can say that to the bosses it makes them stand up and take notice
>That code is so bad it crashes Visual Studio, in debug.

While I applaud the dev team for finding and (hopefully) fixing the issue within Visual Studio - the rest of y'all might also be able to use this as a way to get approval to fix things.  We all have those situations of _"do it fast for now, we'll make it better later"_ that never ever get time later. So use this as leverage for time approval.

;)

**Comment by brendanzagaeski** [comment] 2019-12-09 16:53
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The latest fix removes the limitation around  **All Common Language Runtime Exceptions not in this list**. That setting can now be either checked or unchecked.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

* * *

*Additional information*

There is a new issue related to the fix. If a user has added a type that does not derive from `System.Exception` to the **Break When Thrown** exception list, a *Debuggee returned error code INVALID_ARGUMENT* error will appear:

<https://developercommunity.visualstudio.com/content/problem/842376/android-debugging-not-working-in-latest-release-16.html>

To work around that issue for now, navigate to **Debug > Windows > Exception Settings**, right-click **Common Language Runtime Exceptions**, and select **Restore Defaults**:

![image](https://user-images.githubusercontent.com/4934473/70455405-18e48200-1a61-11ea-8201-e3dae4004597.png)

**Closed by brendanzagaeski** 2019-12-09 16:53 UTC
Labels: regression

**Comment by burrowj** [comment] 2019-12-12 02:07
I had this issue with android debugger, The "Restore Defaults" workaround fixed the issue

**Comment by AmirImam** [comment] 2021-09-09 05:33
I have this issue now on VS 2019 Version 16.11.2
