### ISSUE TITLE
Failed linking references in Android project (Xamarin - Visual Studio Community 2019)

### ISSUE THREAD

**Issue by bharanidharan1707** [xamarin/xamarin-android#3822] opened 2019-10-18 18:12 UTC
```
Error		resource style/Theme.AppCompat.Light.DarkActionBar (aka com.companyname.xamapp:style/Theme.AppCompat.Light.DarkActionBar) not found.	XAMApp.Android			
Error		failed linking references.	XAMApp.Android			
Error		resource style/Theme.AppCompat.Light.Dialog (aka com.companyname.xamapp:style/Theme.AppCompat.Light.Dialog) not found.	XAMApp.Android			
Error		style attribute 'attr/windowNoTitle (aka com.companyname.xamapp:attr/windowNoTitle)' not found.	XAMApp.Android	D:\VS2019Projects\XAMApp\XAMApp.Android\Resources\values\styles.xml	2	
Error		style attribute 'attr/colorPrimary (aka com.companyname.xamapp:attr/colorPrimary)' not found.	XAMApp.Android	D:\VS2019Projects\XAMApp\XAMApp.Android\Resources\values\styles.xml	2	
Error		style attribute 'attr/windowActionBar (aka com.companyname.xamapp:attr/windowActionBar)' not found.	XAMApp.Android	D:\VS2019Projects\XAMApp\XAMApp.Android\Resources\values\styles.xml	2	
Error		style attribute 'attr/colorPrimaryDark (aka com.companyname.xamapp:attr/colorPrimaryDark)' not found.	XAMApp.Android	D:\VS2019Projects\XAMApp\XAMApp.Android\Resources\values\styles.xml	2	
Error		style attribute 'attr/colorAccent (aka com.companyname.xamapp:attr/colorAccent)' not found.	XAMApp.Android	D:\VS2019Projects\XAMApp\XAMApp.Android\Resources\values\styles.xml	3	
Error		style attribute 'attr/windowActionModeOverlay (aka com.companyname.xamapp:attr/windowActionModeOverlay)' not found.	XAMApp.Android	D:\VS2019Projects\XAMApp\XAMApp.Android\Resources\values\styles.xml	4	
Error		style attribute 'attr/colorAccent (aka com.companyname.xamapp:attr/colorAccent)' not found.	XAMApp.Android	D:\VS2019Projects\XAMApp\XAMApp.Android\Resources\values\styles.xml	4	
```

**Comment by jonpryor** [comment] 2019-10-21 15:28
Please attach a reproducible test case and a build log.

This is likely a NuGet restore issue.  Restoring packages in your project may fix the problem.

**Comment by NickyAsher** [comment] 2019-11-13 09:41
Apologies if this problem has already been fixed, but I found that this happened to me immediately after updating my android SDK platform.
I found that (within visual studio) cutting everything within <resources> in styles.xml, letting it build, pasting it all back in, then rebuilding the project rather than the regular build process fixed it for me.

**Comment by thisdarktao** [comment] 2019-11-26 12:38
This same issue occurred for me after updating the Android SDK, however deleting `bin` and `obj` folders in the Android project solved the problem.

**Comment by thaihuydang** [comment] 2019-12-26 04:38
> This same issue occurred for me after updating the Android SDK, however deleting `bin` and `obj` folders in the Android project solved the problem.

Deleting 'bin' and 'obj' not work with me

**Comment by bharanidharan1707** [comment] 2019-12-26 07:01
> > This same issue occurred for me after updating the Android SDK, however deleting `bin` and `obj` folders in the Android project solved the problem.
> 
> Deleting 'bin' and 'obj' not work with me

For me also not working.

**Comment by mgj** [comment] 2019-12-31 14:35
> Please attach a reproducible test case and a build log.
> 
> This is likely a NuGet restore issue. Restoring packages in your project may fix the problem.

On a brand new pc, brand new Visual Studio 2019 community install, this is a reproducable test case:
File -> New Project -> Mobile App (Xamarin.Forms) -> Select any of the templates (Blank, master/detail, etc)

Restoring nugets does not resolve the issue

**Comment by Olivier-Bouchoms** [comment] 2020-01-16 09:31
> > > This same issue occurred for me after updating the Android SDK, however deleting `bin` and `obj` folders in the Android project solved the problem.
> > 
> > 
> > Deleting 'bin' and 'obj' not work with me
> 
> For me also not working.

It is also not working for me. Cleaning and rebuilding the solution in VS also didn't work.

**Comment by HelenMamalaki** [comment] 2020-02-06 16:43
deleting bin and obj did nothing for me too. I tried a NuGet restore and it failed with something about a downgrade detected in my Android Support packages. Upgrading them fixes the issue. [Updating to VS2019 had me add an explicit reference to Xamarin.Essentials in Android.csproj which I think is what then caused Android Support package version issues.] However I can get the error to go away by upgrading then downgrading the Support packages so no idea what is happening. Prob not useful to anyone but wanted to share my experience just in case.

**Comment by thisdarktao** [comment] 2020-02-06 17:06
Sorry, I only offered the suggested fix because it worked for me. Perhaps there's multiple issues occurring here and deleting the intermediates solves it in a specific case?

**Comment by bondsy777** [comment] 2020-02-07 15:31
<img width="385" alt="Screenshot 2020-02-07 at 19 29 26" src="https://user-images.githubusercontent.com/55878329/74041998-2924c900-49e0-11ea-8cc6-a4c0eea0562e.png">
Hello. I managed to solve this problem by updating the nugget packages. Version of which you can see in the screenshot.

**Comment by xphacter** [comment] 2020-02-12 13:30
I ran the following in Package Manager Console to fix my issue:
Install-Package Xamarin.Android.Support.v7.AppCompat

**Comment by grendello** [comment] 2020-03-19 08:18
It appears the issue is fixed by restoring nuget packages as suggested by @jonpryor, therefore I'm closing the issue. @bharanidharan1707 if you still experience this and restoring nugets doesn't hepl, please reopen.

**Closed by grendello** 2020-03-19 08:18 UTC
Labels: Area: App+Library Build

**Comment by aroraarjita** [comment] 2020-10-13 12:48
@grendello 
Neither restoring the packages nor 'Install-Package Xamarin.Android.Support.v7.AppCompat' is working for me. Please find the attached screenshot of the errors. Any inputs will be highly appreciated
@xphacter @bondsy777 @thisdarktao @HelenMamalaki @olivierbouchomsfreshheads  @bharanidharan1707 @thaihuydang @NickyAsher  @jonpryor -

Severity	Code	Description	Project	File	Line	Suppression State
Error		failed linking references.	ScanbotBarcodeSDKFormsExample.Android			
Error		resource attr/flow_horizontalSeparator (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/flow_horizontalSeparator) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	269	
Error		resource attr/flow_verticalSeparator (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/flow_verticalSeparator) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	269	
Error		resource attr/flow_horizontalSeparator (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/flow_horizontalSeparator) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	270	
Error		resource attr/flow_verticalSeparator (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/flow_verticalSeparator) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	270	
Error		resource attr/motionProgress (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/motionProgress) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	272	
Error		resource attr/flow_verticalSeparator (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/flow_verticalSeparator) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	272	
Error		resource attr/flow_horizontalSeparator (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/flow_horizontalSeparator) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	272	
Error		resource attr/motionProgress (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/motionProgress) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	275	
Error		resource attr/motionProgress (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/motionProgress) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	276	
Error		resource attr/waveDecay (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/waveDecay) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	285	
Error		resource attr/motionProgress (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/motionProgress) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	285	
Error		resource attr/motionPathRotate (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/motionPathRotate) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	289	
Error		resource attr/motionProgress (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/motionProgress) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	291	
Error		resource attr/motionProgress (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/motionProgress) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	319	
Error		resource attr/duration (aka io.scanbot.example.sdk.barcode.xamarin.forms:attr/duration) not found.	ScanbotBarcodeSDKFormsExample.Android	C:\Users\user\Downloads\scanbot-barcode-scanner\scanbot-barcode-scanner-sdk-example-xamarin-master\Example.Forms\ScanbotBarcodeSDKFormsExample.Android\obj\Debug\90\lp\34\jl\res\values\values.xml	336	



![image](https://user-images.githubusercontent.com/41081674/95861930-c4e0b300-0d7f-11eb-9807-94d623836433.png)

**Comment by aroraarjita** [comment] 2020-10-13 12:54
> > > > This same issue occurred for me after updating the Android SDK, however deleting `bin` and `obj` folders in the Android project solved the problem.
> > > 
> > > 
> > > Deleting 'bin' and 'obj' not work with me
> > 
> > 
> > For me also not working.
> 
> It is also not working for me. Cleaning and rebuilding the solution in VS also didn't work.
> 
> Update:
> 
> In my case the error was in one of my resources, the 'Styles.xml' was not properly formatted. After I fixed it it managed to build.

Could you please let me know what change you did in Styles.xml? Would appreciate any leads to this issue.

**Comment by HemalathaMarikuma-syncfusion** [comment] 2020-11-08 15:18
Upgrade XF version to resolve this problem

**Comment by ajramos27** [comment] 2021-02-17 07:32
Consolidating the NuGet packages worked for me.

**Comment by OscarHMG** [comment] 2021-03-01 15:49
> This same issue occurred for me after updating the Android SDK, however deleting `bin` and `obj` folders in the Android project solved the problem.

It Work, thanks!! (Y)

**Comment by ssorey** [comment] 2021-09-22 13:42
I am having the same issue failed linking references (Xamarin -  Visual Studio Community 2019)

**Comment by pldeschamps** [comment] 2021-09-27 13:59
be careful to write in styles.xml:
`<?xml version="1.0" encoding="utf-8" ?>
<resources>
  <style name="AlmicantaratTheme" parent="Theme.AppCompat.NoActionBar">
      <item name="android:windowNoTitle">true</item>
      <item name="android:windowActionBar">false</item>
      <item name="android:colorPrimary">#15014E</item>
  </style>
</resources>`

Do not write:
`  <style name="AlmicantaratTheme" parent="@android:Theme.AppCompat.NoActionBar">`
see:
https://try2explore.com/questions/11211050
