### ISSUE TITLE
large mono.android even when linkMode is enabled in the new version of Xamarin

### ISSUE THREAD

**Issue by hanseul1795** [xamarin/xamarin-android#3566] opened 2019-08-30 19:36 UTC
### Steps to Reproduce

1. Build the `.aab` or the `.apk` file with `<AndroidLinkMode>SdkOnly</AndroidLinkMode>`, on Xamarin 10.0.0.4

2. Size of `Mono.Android.dll` got larger (from ~700kb to ~4mb).

### Expected Behavior
size of  `Mono.Android.dll`  should stay the same.

### Actual Behavior
size got larger.

### Version Information
Xamarin Android 10.0.0.4 
<!--
1. On macOS and within Visual Studio, select Visual Studio > About Visual Studio, then click the Show Details button, then click the Copy Information button.

**Comment by grendello** [comment] 2019-09-02 09:22
@hanseul1795 would you mind building your application from the developer prompt with the following command:

```
msbuild /bl /t:"Restore;SignAndroidPackage"
```

and attach the produced `msbuild.binlog` file? Thanks!

**Comment by hanseul1795** [comment] 2019-09-03 13:40
Hi, this is the produced binlog file. Thank you

**Comment by hanseul1795** [comment] 2019-09-04 13:15
[logFile.zip](https://github.com/xamarin/xamarin-android/files/3574644/logFile.zip)

This is our log file, thank you

**Comment by msioen** [comment] 2019-09-04 13:59
We're seeing the same issue. 
Our application (.apk) has grown by 6Mb. The only change is update from Xamarin.Android 9.4.0 to Xamarin.Android 9.4.1. Application has full linking and proguard.

Comparing the two apk files it looks like linking doesn't work properly. Not only Mono.Android has grown but all dll's in the application have significant size growth. In the native lib grouping libxamarin-app.so also has quadrupled.

Some screenshots from Android studio apk comparison:
![Screenshot 2019-09-04 at 15 57 54](https://user-images.githubusercontent.com/1830018/64261476-e2144280-cf2c-11e9-9ac1-f2232bc82355.png)
![Screenshot 2019-09-04 at 15 58 06](https://user-images.githubusercontent.com/1830018/64261475-e2144280-cf2c-11e9-9651-1a18bc406375.png)

**Comment by radekdoulik** [comment] 2019-09-04 14:11
Looks like duplicate of https://github.com/xamarin/xamarin-android/issues/3454

https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.0#known-issues-in-xamarinandroid-10004

**Closed by radekdoulik** 2019-09-04 14:11 UTC
Labels: Area: Linker, duplicate, need-info
