### ISSUE TITLE
Missing attributes from ActivityAttribute

### ISSUE THREAD

**Issue by MKuckert** [xamarin/xamarin-android#2099] opened 2018-08-24 07:10 UTC
### Expected Behavior

I want to set all attributes existing for an [`<activity>` element in the Android Manifest](https://developer.android.com/guide/topics/manifest/activity-element) using the `ActivityAttribute`.

### Actual Behavior

Some attributes are not available as properties on the `ActivityAttribute` class, e.g. `DocumentLaunchMode` is missing.

See corresponding issue in Bugzilla: https://bugzilla.xamarin.com/show_bug.cgi?id=58958

### Version Information

=== Visual Studio Community 2017 for Mac ===

Version 7.6.1 (build 9)
Installation UUID: fa56890d-29fb-40f7-bba3-8ae472aac8d0
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.1.0
	2.0.6
	2.0.5
	2.0.3
	2.0.0
	1.1.2
	1.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.300
	2.1.101
	2.1.4
	2.0.3
	2.0.0
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.6.0.13 (Visual Studio Community)
Hash: 373c313a
Branch: 
Build date: 2018-07-24 23:47:12-0400

=== Xamarin.iOS ===

Version: 11.14.0.13 (Visual Studio Community)
Hash: 373c313a
Branch: HEAD
Build date: 2018-07-24 23:47:12-0400

=== Xamarin.Android ===

Version: 9.0.0.19 (Visual Studio Community)
Android SDK: /Library/Developer/android-sdk
	Supported Android versions:
		5.1 (API level 22)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 28.0.1

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706010009
Git revision: 1916291c332d942d45f3d8a952cc315f7864abef
Build date: 2018-08-22 19:19:11+00
Build branch: release-7.6
Xamarin extensions: 53cd52a227bb91315389d4860f821fa4c3b396b3

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

AddinMaker 1.4.3
FileNesting 0.1.1
NuGet Package Explorer 0.2
Paket 0.3
Redth's Addins 1.0.9
SortAndRemoveOnSave 1.2
Internet of Things (IoT) development (Preview) 7.5

**Comment by JonDouglas** [comment] 2018-08-24 16:36
This is a duplicate of https://github.com/xamarin/xamarin-android/issues/1891

Please feel free to add a 👍 to the other issue to help us prioritize this issue.

**Closed by JonDouglas** 2018-08-24 16:36 UTC
Labels: duplicate
