### ISSUE TITLE
Incorrect parameter names for ArrayAdapter constructor

### ISSUE THREAD

**Issue by alaatm** [xamarin/xamarin-android#2865] opened 2019-03-22 13:30 UTC
There are 3 constructors of the array adapter where the 2nd parameter name is incorrect. According to [ArrayAdapter docs](https://developer.android.com/reference/android/widget/ArrayAdapter.html):

    ArrayAdapter(Context context, int resource)
    ArrayAdapter(Context context, int resource, T[] objects) 
    ArrayAdapter(Context context, int resource, List<T> objects) 

In Xamarin, though these 3 have the 2nd argument named `textViewResourceId` which is incorrect as the `resource` parameter refers to the resource id of the layout file rather than the id of the `TextView` within the layout resource.

**Comment by grendello** [comment] 2019-03-25 08:36
Looking at the generated sources in Xamarin.Android/master, we generate correct parameter names and signatures for the above 3 constructors:

```csharp
// Metadata.xml XPath constructor reference: path="/api/package[@name='android.widget']/class[@name='ArrayAdapter']/constructor[@name='ArrayAdapter' and count(parameter)=2 and parameter[1][@type='android.content.Context'] and parameter[2][@type='int']]"
[Register (".ctor", "(Landroid/content/Context;I)V", "")]
public unsafe ArrayAdapter (Android.Content.Context context, int resource)
     : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer) {}

// Metadata.xml XPath constructor reference: path="/api/package[@name='android.widget']/class[@name='ArrayAdapter']/constructor[@name='ArrayAdapter' and count(parameter)=3 and parameter[1][@type='android.content.Context'] and parameter[2][@type='int'] and parameter[3][@type='T[]']]"
[Register (".ctor", "(Landroid/content/Context;I[Ljava/lang/Object;)V", "")]
public unsafe ArrayAdapter (Android.Content.Context context, int resource, Java.Lang.Object[] objects)
    : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer) {}

// Metadata.xml XPath constructor reference: path="/api/package[@name='android.widget']/class[@name='ArrayAdapter']/constructor[@name='ArrayAdapter' and count(parameter)=3 and parameter[1][@type='android.content.Context'] and parameter[2][@type='int'] and parameter[3][@type='java.util.List&lt;T&gt;']]"
[Register (".ctor", "(Landroid/content/Context;ILjava/util/List;)V", "")]
public unsafe ArrayAdapter (Android.Content.Context context, int resource, System.Collections.IList objects)
     : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer) {}
```

@alaatm it appears the issue is no longer the case with the latest Xamarin.Android sources, therefore I'm going to close it, thanks for reporting!

**Closed by grendello** 2019-03-25 08:36 UTC
Labels: Area: App Runtime
