### ISSUE TITLE
Problom for publish for android with visual studio for mac 2022 version 17.4

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#7538] opened 2022-11-07 22:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Problom-for-publish-for-android-with-vis/10179306)._

---
Hi, when publish for android from visual studio foc mac, this show me next error:

```
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.465/tools/Xamarin.Android.Common.targets(1438,3): error XAGJS7004: System.ArgumentException: An item with the same key has already been added. Key: 33554445 [/Users/storo/Projects/Pulso_monkey/MonkeyFinder/MonkeyFinder.csproj::TargetFramework=net6.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.465/tools/Xamarin.Android.Common.targets(1438,3): error XAGJS7004:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) [/Users/storo/Projects/Pulso_monkey/MonkeyFinder/MonkeyFinder.csproj::TargetFramework=net6.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.465/tools/Xamarin.Android.Common.targets(1438,3): error XAGJS7004:    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value) [/Users/storo/Projects/Pulso_monkey/MonkeyFinder/MonkeyFinder.csproj::TargetFramework=net6.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.465/tools/Xamarin.Android.Common.targets(1438,3): error XAGJS7004:    at Xamarin.Android.Tasks.TypeMapGenerator.GenerateRelease(Boolean skipJniAddNativeMethodRegistrationAttributeScan, List`1 javaTypes, String outputDirectory, ApplicationConfigTaskState appConfState) [/Users/storo/Projects/Pulso_monkey/MonkeyFinder/MonkeyFinder.csproj::TargetFramework=net6.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.465/tools/Xamarin.Android.Common.targets(1438,3): error XAGJS7004:    at Xamarin.Android.Tasks.TypeMapGenerator.Generate(Boolean debugBuild, Boolean skipJniAddNativeMethodRegistrationAttributeScan, List`1 javaTypes, TypeDefinitionCache cache, String outputDirectory, Boolean generateNativeAssembly, ApplicationConfigTaskState&amp; appConfState) [/Users/storo/Projects/Pulso_monkey/MonkeyFinder/MonkeyFinder.csproj::TargetFramework=net6.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.465/tools/Xamarin.Android.Common.targets(1438,3): error XAGJS7004:    at Xamarin.Android.Tasks.GenerateJavaStubs.WriteTypeMappings(List`1 types, TypeDefinitionCache cache) [/Users/storo/Projects/Pulso_monkey/MonkeyFinder/MonkeyFinder.csproj::TargetFramework=net6.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.465/tools/Xamarin.Android.Common.targets(1438,3): error XAGJS7004:    at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res) [/Users/storo/Projects/Pulso_monkey/MonkeyFinder/MonkeyFinder.csproj::TargetFramework=net6.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.465/tools/Xamarin.Android.Common.targets(1438,3): error XAGJS7004:    at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask() [/Users/storo/Projects/Pulso_monkey/MonkeyFinder/MonkeyFinder.csproj::TargetFramework=net6.0-android]
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/32.0.465/tools/Xamarin.Android.Common.targets(1438,3): error XAGJS7004:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 22 [/Users/storo/Projects/Pulso_monkey/MonkeyFinder/MonkeyFinder.csproj::TargetFramework=net6.0-android]
Una señal terminó la aplicación: SIGHUP

dotnet publish ha devuelto 1
```

---
#### Feedback Bot on 10/23/2022, 07:14 PM: 

(private comment, text removed)
#### Zack Yang [MSFT] on 10/25/2022, 02:40 AM: 

(private comment, text removed)
#### Sergio Daniel Toro on 10/25/2022, 05:48 AM: 

(private comment, text removed)
#### Sergio Daniel Toro on 11/2/2022, 07:22 AM: 

(private comment, text removed)
#### Zack Yang [MSFT] on 10/25/2022, 07:52 PM: 

(private comment, text removed)
#### Feedback Bot on 11/2/2022, 01:21 AM: 

(private comment, text removed)
#### Sergio Daniel Toro on 11/2/2022, 07:39 AM: 

(private comment, text removed)
#### Zack Yang [MSFT] on 11/4/2022, 00:48 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jpobst** [comment] 2022-11-08 15:33
Duplicate of https://github.com/xamarin/xamarin-android/issues/7302

I would try the workaround listed here: https://github.com/xamarin/xamarin-android/issues/7302#issuecomment-1241993192.

**Closed** 2022-11-17 18:01 UTC
Labels: need-info, Area: App+Library Build
