### ISSUE TITLE
Setting android layout editor to wear round 454x454 causes unrecoverable error

### ISSUE THREAD

**Issue by ihorbond** [xamarin/xamarin-android#3948] opened 2019-11-21 23:27 UTC
### Steps to Reproduce

1. Launch visual studio 2019
2. Create a new android wear app (xamarin)
3. Open the activity_main.xml
4. Select device wear round 454x454

### Expected Behavior
Designer renders selected device
### Actual Behavior
Exception is thrown 
System.InvalidOperationException: Resource not found: wear-frame-round-454.png
   at Xwt.Backends.ImageBackendHandler.LoadFromResource(Assembly asm, String name) in E:\A\_work\129\s\Xamarin.Designer\external\xwt\Xwt\Xwt.Backends\ImageBackendHandler.cs:line 46
   at Xwt.Drawing.ResourceImageLoader.LoadImage(String fileName) in E:\A\_work\129\s\Xamarin.Designer\external\xwt\Xwt\Xwt.Drawing\Image.cs:line 1016
   at Xwt.Drawing.Image.LoadImage(ImageLoader loader, String fileName, ImageTagSet tagFilter) in E:\A\_work\129\s\Xamarin.Designer\external\xwt\Xwt\Xwt.Drawing\Image.cs:line 193
   at Xwt.Drawing.Image.FromResource(Assembly assembly, String resource) in E:\A\_work\129\s\Xamarin.Designer\external\xwt\Xwt\Xwt.Drawing\Image.cs:line 184
   at Xwt.Drawing.Image.FromResource(Type type, String resource) in E:\A\_work\129\s\Xamarin.Designer\external\xwt\Xwt\Xwt.Drawing\Image.cs:line 154
   at Xamarin.AndroidDesigner.Styles.GetWearBack(String resName) in E:\A\_work\129\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Styles.cs:line 417
   at Xamarin.AndroidDesigner.Styles.GetWearRoundBack(Int32 dimen, Int32 chinHeight) in E:\A\_work\129\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\Styles.cs:line 402
   at Xamarin.AndroidDesigner.Windows.WindowsAndroidSurfaceRenderer.SetupWearBack(DrawingContext context) in E:\A\_work\129\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner.Windows\WindowsAndroidSurfaceRenderer.cs:line 173
   at Xamarin.AndroidDesigner.Windows.WindowsAndroidSurfaceRenderer.RenderDesignerItemVisual(DesignerItem item) in E:\A\_work\129\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner.Windows\WindowsAndroidSurfaceRenderer.cs:line 106
   at Xamarin.Designer.Windows.WpfSurfaceRenderer.QueueRender(DesignerItem item) in E:\A\_work\129\s\Xamarin.Designer\Xamarin.Designer.Windows\WpfSurfaceRenderer.cs:line 453
   at Xamarin.Designer.Windows.WpfSurfaceRenderer.UpdateAllDesignerItems(DesignerItem item) in E:\A\_work\129\s\Xamarin.Designer\Xamarin.Designer.Windows\WpfSurfaceRenderer.cs:line 554
   at Xamarin.Designer.Windows.WpfSurfaceRenderer.QueueRenderWorld() in E:\A\_work\129\s\Xamarin.Designer\Xamarin.Designer.Windows\WpfSurfaceRenderer.cs:line 443
   at Xamarin.Designer.Windows.WpfSurfaceRenderer.OnViewportChanged(Boolean shouldFire) in E:\A\_work\129\s\Xamarin.Designer\Xamarin.Designer.Windows\WpfSurfaceRenderer.cs:line 95
   at Xamarin.Designer.Windows.WpfSurfaceRenderer.AdjustNativeViewport(Rectangle value, Boolean animated) in E:\A\_work\129\s\Xamarin.Designer\Xamarin.Designer.Windows\WpfSurfaceRenderer.cs:line 330
   at Xamarin.Designer.Windows.WpfSurfaceRenderer.SetViewport(Rectangle newViewport, Boolean animated) in E:\A\_work\129\s\Xamarin.Designer\Xamarin.Designer.Windows\WpfSurfaceRenderer.cs:line 272
   at Xamarin.Designer.DesignerSurface.ZoomFit(Boolean animate) in E:\A\_work\129\s\Xamarin.Designer\Xamarin.Designer\DesignerSurface.cs:line 2115
   at Xamarin.AndroidDesigner.AndroidDesignerSurface.HandleSessionImageChanged(Object sender, EventArgs e) in E:\A\_work\129\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\AndroidDesignerSurface.cs:line 252
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Xamarin.AndroidDesigner.AndroidDesignerSession.OnImageChanged() in E:\A\_work\129\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\AndroidDesignerSession.cs:line 1569
   at Xamarin.AndroidDesigner.AndroidDesignerSession.HandleRendered(Object sender, EventArgs e) in E:\A\_work\129\s\Xamarin.Designer.Android\Xamarin.AndroidDesigner\AndroidDesignerSession.cs:line 1404
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
### Version Information
Windows 10
Visual Studio Enterprise 2019 v16.3.9
[Project References ](https://paste.pics/e47e2d0f64ca763c1b18957847468100)

### Log File

> VS bug [#1026852](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1026852)

**Comment by brendanzagaeski** [comment] 2019-11-23 02:19
Thanks for the report! The team is investigating this issue in Visual Studio Developer Community:

https://developercommunity.visualstudio.com/content/problem/718384/xamarin-android-designer-after-select-specific-dev.html

If you get a chance, you can upvote that item to let the team know you're seeing the same problem too.

I'll close this GitHub issue to satisfy the automated tooling (xamarin-release-manager) that wants to close this issue so that there's only one canonical location to track the issue.

But I'll also subscribe to the Developer Community item and update this GitHub issue when the Developer Community item status indicates that a fix is available.

**Closed** 2019-11-23 02:21 UTC
Labels: android-designer

**Comment by EmilAlipiev** [comment] 2022-03-13 14:51
I dont really understand this DeveloperCommunity. Most developers like me have no fun to create ticket there even we see critical issues. Because we know that 70% of the time basic ticket is closed with not enough information. 
How this ticket is simply closed there boggles me. What more information they need i wonder really. Just open a simple project, open designer and change to 454x454 device and boom, designer crashes and you have no way to fix it back. it remains forever like that. after 3 years, this problem still exist.  Someone even commented it step by step how to reproduce it

<img width="448" alt="image" src="https://user-images.githubusercontent.com/10422347/158065279-3f0fd8bc-c7f1-40f8-8ec1-8c8bc690bba9.png">

**Comment by EmilAlipiev** [comment] 2022-03-13 19:45
quick workaround. After spending a few hours and reinstalling VS I found out that this setting is stored in the Project settings
inside the csproj.user file in your projects solution there is a setting called 

`    <AndroidDesignerPreferredDevice>wear_round_454</AndroidDesignerPreferredDevice>
`
Change this one to 

 `   <AndroidDesignerPreferredDevice>wear_round_360_300dpi</AndroidDesignerPreferredDevice>`
 
 designer recovers. at least works again but problem remains.
