### ISSUE TITLE
Builds fail with "Not a valid JDK directory"

### ISSUE THREAD

**Issue by SamuelDebruyn** [xamarin/xamarin-android#2663] opened 2019-01-29 20:26 UTC
### Steps to Reproduce

1. Run a build using MSBuild in the command line

### Expected Behavior

Build succeeds without issues.

### Actual Behavior

After updating to 9.1.5.1 the build fails with the following in the build log:

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(703,2): warning : Not a valid JDK directory: `` [/Users/vagrant/git/src/Droid/PlantsApp.Platform.Droid.csproj]
```

### Version Information

This is the current version on [Bitrise](https://www.bitrise.io/). You can find more info about the machine here: https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-vs4mac-stable.log

```
Visual Studio Community 2017 for Mac
Version 7.7.3 (build 43)
Installation UUID: 5c1dffe0-a7c6-4085-8960-d8c4206f554f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

Mono Framework MDK
Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

NuGet
Version: 4.8.0.5385

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Version: 5.2.1.13 (Visual Studio Community)
Hash: a4332c90
Branch: 
Build date: 2019-01-11 13:08:10-0500

Xamarin.iOS
Version: 12.2.1.13 (Visual Studio Community)
Hash: a4332c90
Branch: d15-9
Build date: 2019-01-11 13:08:09-0500

Xamarin.Android
Version: 9.1.5.1 (Visual Studio Community)
Android SDK: /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.2   (API level 17)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Microsoft Mobile OpenJDK
Java SDK: /Users/vagrant/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 7.7.1.0
Hash: 06ceaea1

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 707030043
Git revision: 5896ab2acba037c62271742e9e56b900c96c1d8f
Build date: 2019-01-15 21:18:33+00
Build branch: release-7.7
Xamarin extensions: e5b43ba963b7b407aa5b9f2c59018c32a709e6ab

Operating System
Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Wed Oct 10 23:06:14 PDT 2018
    root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64
```

### Log File

See above

**Comment by SamuelDebruyn** [comment] 2019-01-29 21:18
I ran the same build again (clean build, on Bitrise) and now it worked...

Side note: should I report this issue in the android-tools repo since the JDK changes happened over there?

**Comment by SamuelDebruyn** [comment] 2019-01-31 11:34
I now got a variant of this error saying that the Android SDK was not found. Build log with verbose setting attached.
[a0beef096d90397c.log](https://github.com/xamarin/xamarin-android/files/2816951/a0beef096d90397c.log)

**Comment by SamuelDebruyn** [comment] 2019-01-31 12:14
For comparison: the log file of a successful build on the exact same machine
[483e78b85375d4f7.log](https://github.com/xamarin/xamarin-android/files/2817112/483e78b85375d4f7.log)

**Comment by brendanzagaeski** [comment] 2019-02-02 00:38
Thanks for the report! I started an initial round of research to find more clues about what could be happening.

Long story short, if by chance you have the option to install the Xamarin.Android preview version 9.1.103.7 on one of your build machines to stress-test it for a while with your build conditions, that will hopefully verify that the fix in the latest Xamarin.Android preview resolves the problem for your scenario too. Thanks in advance!

### Background Info

I found that a Xamarin.Android team member saw the same stack trace for "Error finding Xamarin.Android SDK" on some of the continuous integration build machines that are used to build and test Xamarin.Android. A curious thing he noted was that the problematic `path1` argument to `Path.Combine()` in `GetCurrentSharedRuntimeVersion()` was coming from a class-scope property, and that property had just been set to the value of a local variable a few lines before the call to `GetCurrentSharedRuntimeVersion()`. What's more, the value of that local variable itself was definitely *not* null because another method call that explicitly passed in the local variable (rather than using the class-scope property) was able to call `Path.Combine()` *successfully* using the same value. So the team member updated the call to `GetCurrentSharedRuntimeVersion()` to pass in the local variable explicitly too. That change resolved the issue for the continuous integration build machines. The change is not yet included as of Xamarin.Android 9.1.5.1, but it *is* included in the latest preview version Xamarin.Android 9.1.103.7.

### Side Note

> should I report this issue in the android-tools repo since the JDK changes happened over there?

Reporting the issue here is perfect.

### Relevant Excerpt from *a0beef096d90397c.log*

```txt
Task "ResolveXamarinAndroidTools"
  DEBUG  ValidateAndroidSdkLocation: `/Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx`, result=True
  DEBUG  ValidateAndroidNdkLocation: `/Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle`, result=True
  DEBUG  ValidateJavaSdkLocation: `/Users/vagrant/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9`, result=True
    Found AndroidSdk at /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx
    Found AndroidNdk at /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle
    Found AndroidTools at /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/tools
   Did not find Xamarin.Android
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(109,2): error XA5300:  Error finding Xamarin.Android SDK [/Users/vagrant/git/src/Shared/Droid/BelgianRail.Edrive.Droid.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(109,2): error XA5300: System.ArgumentNullException: Value cannot be null. [/Users/vagrant/git/src/Shared/Droid/BelgianRail.Edrive.Droid.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(109,2): error XA5300: Parameter name: path1 [/Users/vagrant/git/src/Shared/Droid/BelgianRail.Edrive.Droid.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(109,2): error XA5300:   at System.IO.Path.Combine (System.String path1, System.String path2) [0x00003] in <98fac219bd4e453693d76fda7bd96ab0>:0  [/Users/vagrant/git/src/Shared/Droid/BelgianRail.Edrive.Droid.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(109,2): error XA5300:   at Xamarin.AndroidTools.MonoDroidSdkBase.GetCurrentSharedRuntimeVersion () [0x00006] in <4efb74c151c74f42b035d71af77a28f1>:0  [/Users/vagrant/git/src/Shared/Droid/BelgianRail.Edrive.Droid.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(109,2): error XA5300:   at Xamarin.AndroidTools.MonoDroidSdkBase.Initialize (System.String runtimePath, System.String binPath, System.String bclPath) [0x0011e] in <4efb74c151c74f42b035d71af77a28f1>:0  [/Users/vagrant/git/src/Shared/Droid/BelgianRail.Edrive.Droid.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(109,2): error XA5300:   at Xamarin.AndroidTools.MonoDroidSdk.Refresh (System.String runtimePath, System.String binPath, System.String bclPath) [0x0001e] in <4efb74c151c74f42b035d71af77a28f1>:0  [/Users/vagrant/git/src/Shared/Droid/BelgianRail.Edrive.Droid.csproj]
    Found RuntimePath at 
    Found FrameworkPath at /Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0
Done executing task "ResolveXamarinAndroidTools" -- FAILED.
```

**Comment by SamuelDebruyn** [comment] 2019-02-04 13:07
This version does not seem to be available on the [Bitrise beta stack](https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-vs4mac-beta.log) so I can't select it for my builds. I can't find it on my own machine in the beta channel either.

**Comment by brendanzagaeski** [comment] 2019-02-04 19:33
Ahh shoot. If the Bitrise hosts are configured by the Bitrise team, then it sounds like there might not be an easy way to verify that the fix works in that environment until the first non-preview version of Xamarin.Android 9.2 is released later this year. Since this next version of Xamarin.Android will be part of Visual Studio 2019 instead of Visual Studio 2017, it will be unusual compared to other preview versions of Xamarin.Android because it won't appear on the Beta channel of Visual Studio 2017 for Mac.

If by any luck you have seen the issue on your local machine, then you could test by installing the [Visual Studio 2019 for Mac Preview](https://visualstudio.microsoft.com/vs/preview/) and switching to the **Xamarin Preview** updater channel.

**Comment by brendanzagaeski** [comment] 2019-02-04 19:45
Actually, while skimming through the Bitrise documentation, I just saw that the build environments allow downloading and [installing additional packages](https://devcenter.bitrise.io/tips-and-tricks/install-additional-tools/), so in theory I think it will be possible to install the Xamarin.Android 9.1.103.7 preview after all. One way to do that would be to fetch and then install the two individual macOS packages needed for command-line builds:

  * [Mono Framework MDK version 5.18](https://download.visualstudio.microsoft.com/download/pr/8a32e9f4-fef7-40cf-8d26-890190a2e0ab/195d0218950c93e18f83247cc783624f/monoframework-mdk-5.18.0.245.macos10.xamarin.universal.pkg)
  * [Xamarin.Android version 9.1.103.7](https://download.visualstudio.microsoft.com/download/pr/4d15d6fe-28cc-4a5b-8e12-3f7fa3537e0c/848a3e49cca3b6486d6c9f78b276634c/xamarin.android-9.1.103-7.pkg)

**Comment by brendanzagaeski** [comment] 2019-02-04 22:15
The `installer` command will hopefully work, with an invocation similar to:

```sh
sudo /usr/sbin/installer -pkg "$HOME/Downloads/mdk-5.18.0.245.macos10.xamarin.universal.pkg" -target /
```

and:

```sh
sudo /usr/sbin/installer -pkg "$HOME/Downloads/xamarin.android-9.1.103-7.pkg" -target /
```

**Comment by SamuelDebruyn** [comment] 2019-02-05 15:23
Usually one out 5 builds fail with the error above. I ran 20 builds with the preview versions and they all succeeded. I suppose this is issue is fixed then.

However, I noticed a different issue with these preview versions. I measured the build time (complete solution, release mode, AOT, proguard, link all) of 10 builds. With the current stable versions, this results in an average build time of 7m15. With the preview versions, this results in an average build time of 9m26. Shortest build time on stable in these 10 builds is 6m26, with the preview versions this is 8m19. Longest in stable is 7m53, in preview 10m56.
Where should I report this? I can provide a few verbose build logs.

**Comment by brendanzagaeski** [comment] 2019-02-07 05:51
Perfect. Thanks for testing! I'll tentatively close this issue based on that result.

On the build times issues, I think the team would definitely be interested to take a look at a few build verbose build logs, comparing a few of the longer and shorter times from both Xamarin.Android 9.1.5 and Xamarin.Android 9.1.103.7. Though Xamarin.Android 9.1.103.7 has [improved the build times for some measured scenarios on Windows](https://github.com/xamarin/xamarin-android/wiki/Build-Performance-Results), it sounds like your build scenario on Bitrise is exposing useful information about a situation where the changes are having a more mixed effect. If you get a chance to attach a few verbose build logs on a new issue on this repository, that would be perfect. Thanks in advance!

**Closed by brendanzagaeski** 2019-02-07 05:51 UTC
Labels: Area: App+Library Build, need-info

**Comment by awattar** [comment] 2019-04-10 13:04
@brendanzagaeski Could you reference commit that fixed this?

**Comment by brendanzagaeski** [comment] 2019-04-10 19:56
I can record the commit information here, but in this particular case the fix was to a code path that is only used for the non-public commercial additions to Xamarin.Android, so the commit isn't in a public repository.

androidtools/d16-0@46b555ef58cb236bbc83b09e2e484cf003e59d8d
(Included in monodroid/d16-0@6b8f18a243a1fe3cd2ca13d227188af1e7daf73f)

**Comment by madhurig** [comment] 2019-07-09 21:06
Which version of Visual Studio 2017 is this fix be included in? Some customers are [seeing an error](https://developercommunity.visualstudio.com/content/problem/605318/random-xamarinandroid-failure-when-using-microsoft.html) in Hosted VMs on Azure Pipelines which appears to be the same issue. 

The VS2017 VMs in Azure Pipelines have [VisualStudio/15.9.12+28307.665](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md#visual-studio-2017-enterprise)

**Comment by brendanzagaeski** [comment] 2019-07-09 23:35
To date, the fix for this issue has not been considered for inclusion in Visual Studio 2017. Since the issue is somewhat uncommon, I believe the current best recommendations for users are:

 1. If possible, update to building with Visual Studio 2019.
 2. Or, if acceptable, ignore and retry builds that fail due to this particular error in Visual Studio 2017. Since the issue is intermittent, the next build is likely to succeed.
 3. Otherwise, a possible way to avoid this error in  Visual Studio 2017 Azure Pipelines builds could be to add the following lines to the end of the Android app project *.csproj* file (after `<Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />`):

    ```xml
    <PropertyGroup>
      <_OnResolveMonoAndroidSdks>$([MSBuild]::Unescape($(_OnResolveMonoAndroidSdks.Replace("_ResolveXamarinAndroidTools", ""))))</_OnResolveMonoAndroidSdks>
    </PropertyGroup>
    ```

    This configures the build to skip the `_ResolveXamarinAndroidTools` MSBuild target where the error occurs. That target is technically only relevant when using the fast device deployment feature in Debug configuration builds, so skipping it during Release configuration builds should be fine. I tried the change with a small test app in Azure Pipelines to verify that the build skipped the `_ResolveXamarinAndroidTools` target and completed without error, and it did work as desired for that little test.
