### ISSUE TITLE
Runinng Xamarin UITests with Archive made in VS2022 not working

### ISSUE THREAD

**Issue by Brosten** [xamarin/xamarin-android#6816] opened 2022-03-07 15:26 UTC
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 17.1.0

### Description

I create an .apk file with Android-project > Archive... 
Then I use this to run Xamarin UITests with.

This works perfect if the archive is made with VS2019

With VS2022, I get the following error:
  Message: 
System.Exception : Mono Shared Runtime is not supported. This can be resolved by changing the project configuration or using a Release build.

  Stack Trace: 
ApkFile.EnsureNoSharedRuntime()
AndroidAppInitializer.PrepareApkFiles(IAndroidAppConfiguration appConfiguration, ArtifactFolder artifactFolder)
AndroidApp.ctor(IAndroidAppConfiguration appConfiguration, IExecutor executor)
AndroidAppConfigurator.StartApp(AppDataMode appDataMode)

However, I have this in my .csproj
<AndroidUseSharedRuntime>False</AndroidUseSharedRuntime>

Any idéas?

### Steps to Reproduce

1. Build Android App
2. Create Android Archive
3. Try to run a Xamarin UITest
4. Fails with above error

### Did you find any workaround?

Using VS 2019

**Comment by dellis1972** [comment] 2022-03-07 15:38
This looks like a bug in https://github.com/xamarin/Xamarin.UITest. Your apk is probably using the assembly blob by default which means the apk will not contain things like `libmonoandroid.so` . So it thinks its a shared runtime build. 

https://github.com/xamarin/Xamarin.UITest will need to be updated to support our newer package formats.

**Comment by jonathanpeppers** [comment] 2022-03-07 15:57
A workaround is to set `<AndroidUseAssemblyStore>false</AndroidUseAssemblyStore>` in the configuration you are using with Xamarin.UITest.

I would still try to keep this on for builds sent to app stores, though. It will improve your startup performance.

**Comment by dellis1972** [comment] 2022-03-07 15:58
@Brosten can you confirm my hypotheses by providing a list of the contents of the apk ? my guess is it won't contain the files expected in https://github.com/xamarin/Xamarin.UITest/blob/d28cf144b9094fbaade6719d91852ec5cce6d8a7/src/Xamarin.UITest.Shared/Android/ApkFile.cs#L208

**Comment by dellis1972** [comment] 2022-03-07 16:03
So it looks for `libmonodroid.so`,`mscorlib.dll` or `libmonodroid_bundle_app.so`

**Comment by jpobst** [comment] 2022-03-07 19:33
There was discussion about this here: https://discordapp.com/channels/732297728826277939/732297837953679412/928429974363459604

**Comment by Brosten** [comment] 2022-03-08 05:50
@jonathanpeppers : Thank you! I can confirm that running with <AndroidUseAssemblyStore>false</AndroidUseAssemblyStore> solved the issue. 

@dellis1972: 
![image](https://user-images.githubusercontent.com/10629345/157174460-e8f6f8c8-6d3b-4644-9f76-a6673959b806.png)
This is the content of the root level of the apk. 
libmonodroid.so exists in the lib\<env> folder
mscorelib.dll exists in the assemblies folder
The apkfile.cs link you provided gave me 404

**Comment by dellis1972** [comment] 2022-03-08 09:54
The fact that `AndroidUseAssemblyStore` fixes the issue confirms my theory. 
I'll do a PR for UITests

**Comment by dellis1972** [comment] 2022-03-08 10:22
For reference there are two PRs 

https://github.com/xamarin/Xamarin.UITest/pull/1549
https://github.com/xamarin/Xamarin.UITest/pull/1544

**Comment by Hackmodford** [comment] 2022-05-05 17:36
@dellis1972 Any word on those PRs? I just ran into this issue today.

**Comment by dellis1972** [comment] 2022-05-06 12:36
The fix was merged. The Nuget was apparently published 23 days ago. Not sure if it included these fixes though.

**Comment by ehuna** [comment] 2022-05-06 19:48
We see the same issue -

Mac
VS 2019, Version 8.10.22 (build 11)
Mono 6.12.0.174 (2020-02/adf1bc4335d) (64-bit), Package version: 612000174

Error still happens with the latest Xamarin UITest version 3.2.7 (https://www.nuget.org/packages/Xamarin.UITest/3.2.7)

Workaround of adding <AndroidUseAssemblyStore>false</AndroidUseAssemblyStore> to the Droid project, for the configuration we are testing with, works.

**Comment by bpater-tp** [comment] 2022-05-30 07:53
@ehuna I have the same experience. Tests are run from mac and recent VS2019.

**Comment by LukasBajus** [comment] 2022-05-31 07:54
I have same issues, seems like there was no release of Xamarin UITest, so I am running on 3.2.7

**Comment by wakeboardfit** [comment] 2022-10-05 18:53
I was also getting this error and upgraded to 3.2.9 while switching our app from Xamarin to Maui and moving to 2022.  I no longer receive this error on 3.2.9 in Visual Studio 2022.

**Comment by jonathanpeppers** [comment] 2022-10-10 15:19
Yes, I believe the problem is now solved if you use:

https://www.nuget.org/packages/Xamarin.UITest/3.2.9

Thanks!

**Closed by jonathanpeppers** 2022-10-10 15:19 UTC
Labels: Area: App+Library Build
