### ISSUE TITLE
SQL Server pre-login handshake failed Android 5,6,8.1

### ISSUE THREAD

**Issue by Eilon** [xamarin/xamarin-android#6990] opened 2022-05-09 16:17 UTC
---
**Issue moved from dotnet/maui#6859**
- Please respond to @janseris.

---

_From @janseris on Thursday, May 5, 2022 12:39:34 PM_

### Description

SQL Server - the connection was established but pre-login handshake failed when calling database via Entity Framework

`**Microsoft.Data.SqlClient.SqlException:** 'A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)'`

What does not help:
- `Encrypt=false` in connection string
- `Encrypt=true` in connection string
- `Encrypt=false;TrustServerCertificate=true;` in connection string

The same works without any issue on Android 9 and up (both emulator and real device).
Tested: works on Android 9 for all TLS settings: `Native TLS 1.2+` and `Managed TLS 1.0` and also for `"no option"`.

![image](https://user-images.githubusercontent.com/64279914/166925248-fa97eea6-d9b2-444a-9e1f-7c968910d858.png)

The issue is in Debug (and thus probably also in Release) configuration.

Output for Android 5 (API 21):
`Microsoft.Data.SqlClient.SqlException: 'A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)'
`

Output for Android 8, for all TLS configuration options: `Native TLS 1.2+` and `Managed TLS 1.0` and also for `"no option"`.
```
[System.err] java.lang.IllegalStateException: Handshake has already been started
[System.err] 	at com.android.org.conscrypt.OpenSSLEngineImpl.beginHandshakeInternal(OpenSSLEngineImpl.java:335)
[System.err] 	at com.android.org.conscrypt.OpenSSLEngineImpl.beginHandshake(OpenSSLEngineImpl.java:325)
[System.err] 	at crc640ec207abc449b2ca.ShellSectionRenderer.n_onCreateView(Native Method)
[System.err] 	at crc640ec207abc449b2ca.ShellSectionRenderer.onCreateView(ShellSectionRenderer.java:42)
[System.err] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
[System.err] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
[System.err] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
[System.err] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
[System.err] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
[System.err] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
[System.err] 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
[System.err] 	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
[System.err] 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
[System.err] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
[System.err] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
[System.err] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
[System.err] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
[System.err] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
[System.err] 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
[System.err] 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
[System.err] 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
[System.err] 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
[System.err] 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
[System.err] 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
[System.err] 	at android.app.Activity.performStart(Activity.java:6992)
[System.err] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
[System.err] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
[System.err] 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
[System.err] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
[System.err] 	at android.os.Handler.dispatchMessage(Handler.java:105)
[System.err] 	at android.os.Looper.loop(Looper.java:164)
[System.err] 	at android.app.ActivityThread.main(ActivityThread.java:6541)
[System.err] 	at java.lang.reflect.Method.invoke(Native Method)
[System.err] 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
[System.err] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
**Microsoft.Data.SqlClient.SqlException:** 'A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)'

```

Similar issues:
https://github.com/dotnet/maui/issues/3522

### Steps to Reproduce

call database in a MAUI app with Android 8.1 or lower

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8.1 and below

### Did you find any workaround?

no

**Comment by Eilon** [comment] 2022-05-09 16:17
---
**Issue moved from dotnet/maui#6859**
- Please respond to @Redth.

---

_From @Redth on Thursday, May 5, 2022 1:25:46 PM_

Generally best practice would be to not connect directly to a database from a mobile application where you'll risk the server credentials being discoverable.

Aside from that, @jonpryor any ideas?

**Comment by Eilon** [comment] 2022-05-09 16:17
---
**Issue moved from dotnet/maui#6859**
- Please respond to @drasticactions.

---

_From @drasticactions on Thursday, May 5, 2022 2:37:53 PM_

This won't be MAUI specific in any case, right? Like with that other issue linked, this stack is entirely Android and that would point to it being a net6-android issue (or at least something you need to change at a project level).

**Comment by Eilon** [comment] 2022-05-09 16:17
---
**Issue moved from dotnet/maui#6859**
- Please respond to @Eilon.

---

_From @Eilon on Thursday, May 5, 2022 5:17:18 PM_

Should we move this to the xamarin-android repo?

**Comment by Eilon** [comment] 2022-05-09 16:17
---
**Issue moved from dotnet/maui#6859**
- Please respond to @Redth.

---

_From @Redth on Thursday, May 5, 2022 8:19:42 PM_

I'll let @jonpryor handle moving and closing as necessary.  Unfortunately we can't move issues across orgs with GitHub, it has to be 'manually' moved.

**Comment by Eilon** [comment] 2022-05-26 21:49
@janseris sorry this is not an area I'm familiar with at all.

@jonathanpeppers - do you know who could look at this or what milestone it might get slotted into for investigation?

**Comment by jonathanpeppers** [comment] 2022-05-27 20:24
@janseris I am not getting the same error using the sample project above. Does this app talk directly to a database? I wouldn't recommend doing this in a mobile app-- security best practice would be to put a web service in between.

To look into this further, I think we need [adb logcat](https://docs.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log#accessing-from-the-command-line) output of the full exception. Depending on what is wrong, we might need someone from the Mono runtime team to look into this. Thanks!

**Comment by jonathanpeppers** [comment] 2022-05-27 20:26
@steveisok there is a partial stack trace above, should `Microsoft.Data.SqlClient` work on Android?

**Comment by janseris** [comment] 2022-05-27 21:08
> @janseris I am not getting the same error using the sample project above. Does this app talk directly to a database? I wouldn't recommend doing this in a mobile app -- security best practice would be to put a web service in between.
> 
> To look into this further, I think we need [adb logcat](https://docs.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log#accessing-from-the-command-line) output of the full exception. Depending on what is wrong, we might need someone from the Mono runtime team to look into this. Thanks!

The error can be reproduced by any MAUI app talking to external sql server on Android 8.1 and lower for me. There is no specific code needed. Yes the situation is db call from Android to SQL Server. 
What result do you get if not what I got? BTW make sure there is a connection string to a valid SQL server to reproduce the issue. Otherwise invalid host name SQL Exception is received. 
As for safety yes I know and another possible use case might be running an Android server (thanks to MAUI single project this server can be run on any platform) or a microservice running on Android which talks to a db.

**Comment by jonathanpeppers** [comment] 2022-05-27 22:23
> BTW make sure there is a connection string to a valid SQL server to reproduce the issue.

Yes, since I do not have a SQL Server to interact with, I just ran the sample as-is.

**Comment by janseris** [comment] 2022-05-28 07:54
I read here https://github.com/netty/netty/issues/4718 that the issue might be that different implementations of SSL communication is used in different version of Android. Some of them tolerate multiple handshakes started and the one here throws an exception in that situation.
I however don't know what to do about it.
Btw I can see that the TLS/SSL version switch in .csproj properties for Android had disappeared since last time (RC 2). But it seem to have influenced only HTTP calls (was probably some test code for HttpClient, right?) 
Would it be possible if there was a switch in the properties for this case as well or any other workaround?

**Comment by janseris** [comment] 2022-06-06 10:50
@Eilon @jonathanpeppers I provided required info.

**Comment by Eilon** [comment] 2022-06-06 19:23
@janseris sorry about that. I think the MsftBot got confused because in this bug I am the original opener (I copied the bug from the other repo), so even though you did reply, the bot saw that _I_ didn't respond after a few days of the `need-info` label, so it thought I was ignoring it and closed the issue.

**Comment by jonathanpeppers** [comment] 2022-06-21 18:38
Closing in favor of: https://github.com/dotnet/SqlClient/issues/1656

I wish we could have just moved this issue around until we got it at the right place. Thanks!

**Closed by jonathanpeppers** 2022-06-21 18:38 UTC
Labels: Area: Mono Runtime
