### ISSUE TITLE
proguard rules embedded in binding projects are lost

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-android#4449] opened 2020-03-24 09:52 UTC
The proguard rules embedded in binding projects, pulled from nuget, are lost/ignored.

I have seen this behavior for many android binding libraries. It happens since Android have made possible to automatically include proguard rules of referenced android libraries in the final app, about 2 or 3 years ago.

### Steps to Reproduce

1. Create a demo xamarin android project
2. Add the OneSignal nuget, and follow the onesignal guides to configure it properly
3. Build in release mode, using d8, r8 and "link all" options

### Expected Behavior
The app should run fine on a device.
These proguard rules (still used by R8) should have been automatically imported by the nuget:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/consumer-proguard-rules.pro

### Actual Behavior
Some java classes from onesignal are missing, and the app is crashing.
Adding the content of the above rules to a local proguard.cfg file does fix the issue.

### Version Information
[Microsoft Visual Studio Enterprise 2019.txt](https://github.com/xamarin/xamarin-android/files/4374466/Microsoft.Visual.Studio.Enterprise.2019.txt)

**Comment by brendanzagaeski** [comment] 2020-03-25 05:54
*Notes to the Xamarin.Android team*

I think [Com.OneSignal](https://packages.nuget.org/packages/Com.OneSignal/) is the example NuGet package. The *lib/MonoAndroid10/OneSignal.Android.Binding.dll* file from that package has an embedded *\_\_AndroidLibraryProjects\_\_.zip* resource that contains:

  * *library_project_imports/proguard.txt*
  * *library_project_imports/bin/proguard.txt*

These files match the content of the [*consumer-proguard-rules.pro*](https://github.com/OneSignal/OneSignal-Android-SDK/blob/4e989f5470ee63a5135437f60fd4a26b2f3504d4/OneSignalSDK/onesignal/consumer-proguard-rules.pro) file from the OneSignal repository.

> Android have made possible to automatically include proguard rules of referenced android libraries in the final app

I'm not familiar with the corresponding Android Studio or Gradle behaviors. Maybe the default Gradle configuration automatically searches for *proguard.txt* files in referenced libraries and uses them?

As a quick point of comparison, the [Xamarin.Android.Support.v7.AppCompat](https://www.nuget.org/packages/Xamarin.Android.Support.v7.AppCompat/) NuGet package takes a different approach where it includes the ProGuard configuration file as a standalone *proguard/monoandroid90/proguard.txt* file within the NuGet package and then uses *build/monoandroid90/Xamarin.Android.Support.v7.AppCompat.targets* to add that file to the Xamarin.Android build process:

```xml
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ProguardConfiguration Include="$(MSBuildThisFileDirectory)..\..\proguard\monoandroid90\proguard.txt" />
  </ItemGroup>
</Project>
```

**Comment by softlion** [comment] 2020-03-25 09:55
ty @brendanzagaeski you get the point !

**Comment by jonathanpeppers** [comment] 2020-03-25 14:49
Yes, I think this is duplicate of: https://github.com/xamarin/xamarin-android/issues/3752

We just haven't gotten around to doing this quite yet.

**Comment by PatGet** [comment] 2020-09-29 07:11
Should the way @brendanzagaeski mention for Xamarin.Android.Support.v7.AppCompat work in a nuget right now?
Do I need do do anything besides adding the target and txt files to the nuspec?

**Comment by jonathanpeppers** [comment] 2020-09-29 13:21
All you should have to do is put a `.targets` or `.props` file in the `build` directory:

https://docs.microsoft.com/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory

I do believe the file has to be named the same as the package. So for `My.Package.nupkg` it would be `My.Package.targets`.

Here is a recent example of Xamarin.AndroidX.Migration:

https://github.com/xamarin/AndroidX/blob/34ca438ae886081cee595bf37ac9ac08b5be37f9/source/migration/BuildTasks/Xamarin.AndroidX.Migration.nuspec#L39-L40

**Comment by PatGet** [comment] 2020-09-29 17:36
I made a mistake and named it target instead of targets. Now it works! Thanks @jonathanpeppers!

**Comment by jpobst** [comment] 2022-09-13 14:59
Looks like this was fixed in https://github.com/xamarin/xamarin-android/pull/5310.

**Closed by jpobst** 2022-09-13 14:59 UTC
Labels: Area: App+Library Build, feature-request
