### ISSUE TITLE
Building and running a new .NET MAUI Blazor app on Android takes a very long time (~2min)

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#7318] opened 2022-08-26 22:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Building-and-running-a-new-NET-MAUI-Bla/10116423)._

---
Repro steps:

- Create a new .NET MAUI Blazor app with VS 17.3
- Have the Android emulator already running
- Run the app on Android using Ctrl-F5

Expected result: App builds and starts in less than a minute

Actual result: App takes about 2min to build and run

See attached binlogs

---
#### Daniel Roth [MSFT] on 8/10/2022, 08:54 AM: 

(private comment, text removed)
#### Daniel Roth [MSFT] on 8/10/2022, 08:54 AM: 

(private comment, text removed)
#### Daniel Roth [MSFT] on 8/10/2022, 08:54 AM: 

(private comment, text removed)
#### Feedback Bot on 8/11/2022, 00:15 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jonathanpeppers** [comment] 2022-08-29 19:49
I did some initial investigation on this, and  each `adb` operation was very slow when deploying. I need to test the Hyper-V emulator on my (old-ish) Windows 11 laptop and see if I get similar numbers.

**Comment by jonathanpeppers** [comment] 2022-09-12 15:19
The OP had a time of:

![image](https://user-images.githubusercontent.com/840039/189691812-39cd783e-65d8-44d5-9cfe-0580393c1af4.png)

I tried a similar test on my laptop, and I got:

<img width="191" alt="image" src="https://user-images.githubusercontent.com/840039/189692008-882d0ad2-0b2e-4fa4-b02b-6f1c91b158ef.png">

So there might be a performance issue when using Windows 11 + Hyper-V emulator + laptop on battery power? I'm not sure what we can do to address this, though.

We could do something to improve performance, in general?

**Comment by jonathanpeppers** [comment] 2022-09-12 15:28
[logs.zip](https://github.com/xamarin/xamarin-android/files/9549475/logs.zip)

**Comment by jonathanpeppers** [comment] 2022-09-12 15:44
A couple things I tried...

## Power mode

I was on the "balanced" power plan before, this one gets slightly better numbers:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/840039/189696501-56bc79a8-07a2-4011-9d30-af8c340dbe2c.png">

<img width="173" alt="image" src="https://user-images.githubusercontent.com/840039/189696303-719d17b0-c564-4a0b-8d93-29f41eaa06f0.png">

## WSA instead of emulator

<img width="150" alt="image" src="https://user-images.githubusercontent.com/840039/189697822-eb03b0c1-bf05-44d4-b319-7d0a8c7c1c57.png">

```
NotifySync CopyFile obj\Debug\net6.0-android\android\assets\Mono.Android.dll. [3716ms]
```

**Comment by jonpryor** [comment] 2023-07-24 14:59
Duplicate of #7572.

**Closed by jonpryor** 2023-07-24 14:59 UTC
Labels: Area: App+Library Build
