### ISSUE TITLE
VS 16.6.0 Prev 1.0 App crashes on "Cannot create instance of type ... no Java peer type found" after incremental build

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#4415] opened 2020-03-18 06:13 UTC
Sometimes after even just a small change in code. Click deploy, builds and deploys with no errors and then crashes at runtime. This is just a sample with this SettingsFragment, but it is regularly happening on two projects I'm working on.  Clean, rebuild and deploy and it is good again. Not dissimilar to the other problems reported with earlier previews where you had to clean/build/deploy way too much.

```
2020-03-18 16:53:03.399 12333-12333/com.glmsoftware.obdnowproto E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.glmsoftware.obdnowproto, PID: 12333
    android.runtime.JavaProxyThrowable: System.NotSupportedException: Cannot create instance of type 'com.glmsoftware.OBDNowProto.SettingsFragmentCompat': no Java peer type found.
      at Java.Interop.JniPeerMembers+JniInstanceMethods..ctor (System.Type declaringType) [0x0004b] in <e3e4dfa992a7411b85acfe193481be3e>:0 
      at Java.Interop.JniPeerMembers+JniInstanceMethods.GetConstructorsForType (System.Type declaringType) [0x00031] in <e3e4dfa992a7411b85acfe193481be3e>:0 
      at Java.Interop.JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters) [0x00038] in <e3e4dfa992a7411b85acfe193481be3e>:0 
      at AndroidX.Preference.PreferenceFragmentCompat..ctor () [0x00034] in <005e3ae6340747e1aea6d08b095cf286>:0 
      at com.glmsoftware.OBDNowProto.SettingsFragmentCompat..ctor () [0x00026] in <a8dbee4be1674aa08cce57b50f21e347>:0 
      at com.glmsoftware.OBDNowProto.SettingsActivity.OnCreate (Android.OS.Bundle bundle) [0x00083] in <a8dbee4be1674aa08cce57b50f21e347>:0 
      at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <c56099afccf04721853684f376a89527>:0 
        at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)
        at crc64596a13587a898911.SettingsActivity.n_onCreate(Native Method)
        at crc64596a13587a898911.SettingsActivity.onCreate(SettingsActivity.java:40)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by gugavaro** [comment] 2020-03-18 14:16
@dellis1972 who should take a look on this?

**Comment by grendello** [comment] 2020-03-19 08:08
@gmck can you provide a full logcat of a failed session, obtained by issuing these commands from command prompt:

```shell
adb shell setprop debug.mono.log=default,assembly,timing=bare
adb logcat -c
[run the application here]
adb logcat -d > log.txt
```

I'm assigning this to @dellis1972 and @jonathanpeppers for now since it happens on rebuilds, but it might just as well be an issue with the generator or typemaps. It would be best if you were able to provide a small repro application in addition to the logcat output, if at all possible. Thanks!

**Comment by gmck** [comment] 2020-03-19 20:51
@jonathanpeppers  I can assure you it was cleaned when I first opened it in 16.6.0 1.0. Mate, I do a lot of cleaning. My clean menu item is probably worn out!!! 

#4360 looks like it covers all this stuff.

The actual exception above was for real and nothing to do with cleaning. The exception is because of Android's wonderful new Navigation component (even 2.2.1) just cannot handle a PreferenceFragmentCompat fragment. According to their nav_graph and their docs all fragments in a nav_graph require tools:layout. Well, PrefereenceFragmentCompat doesn't use a layout. OnCreatePreferences either uses AddPreferencesFromResources or SetPreferencesFromResource, therefore no layout and I believe that is what is causing the exception. 

So if you use preferences in your app, it is not going to a their "holy grail" Single Activity app. Just for the Android Xamariners who haven't tried it. In a NavComponent app you can still use an activity just like you always did with StartActivity(intent).

You can even set up the activity in the nav_graph, so you can launch it directly via navController.Navigate(Resource.Id.action_settings). However, to make it work in the nav_graph, there is a specific requirement Xamarin requirement.

What you can't do in the nav_graph as you would do in Android Studio
<activity
  android:id="@+id/action_settings"
  android:name="com.companyname.appname.activities.SettingsActivity
  android:label ="Settings"
  tools:layout="@layout/activity_settings"/>

What to do with Xamarin.Android 
Replace the android:name with either

android:name="com.companyname.appname.activities.crc645....11.SettingsActivity
or just
android:name="crc645....11.SettingsActivity"

You can get your particular "crc...." of your activity from the obj/debug/100/manifest/AndroidManifest.xml file

@grendello I can provide you with this prototype app, because I think it covers most of the problems I've been experiencing during the last month, especially in relation to #4360. However, I can't upload it here, could you advise how to get it to you.

**Comment by jonathanpeppers** [comment] 2020-03-19 21:00
@gmck you should use:
```csharp
[Register ("com.companyname.appname.activities.SettingsActivity")]
public class SettingsActivity ...
```
Then you don't have to lookup what the `crc` value is.

**Comment by grendello** [comment] 2020-03-19 21:21
@gmck a link to a repository or an archive will do :)

**Comment by gmck** [comment] 2020-03-19 21:28
Thanks, Jonathan didn't know that. 

Wish I'd known that a couple of days ago, that's one day I'm never getting back figuring that one out.

I don't want to make it public, so can I have an email address.

**Comment by gmck** [comment] 2020-03-19 21:29
oops..
@grendello I don't want to make it public, so can I have an email address.

**Comment by brendanzagaeski** [comment] 2020-03-20 06:13
I was able to put together steps to reproduce from other reports of this issue.

### Steps to reproduce

1. Download the following sample: https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/customrenderers-map-circle/
2. `msbuild -restore -t:Install Droid\MapOverlay.Droid.csproj`
3. Update the timestamp of `Droid\MainActivity.cs`. For example, open the file in Notepad and save it.
4. `msbuild -restore -t:Install Droid\MapOverlay.Droid.csproj`
5. Launch the application by tapping the icon on the device.

### Expected behavior

The application launches successfully.

### Actual behavior with Xamarin.Android 10.2.100.7 (d16-6@69561a7))

The application crashes with the exception mentioned in the description of this issue. Excerpt from my local repro:

```
UNHANDLED EXCEPTION:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: Cannot create instance of type 'MapOverlay.Droid.CustomMapRenderer': no Java peer type found.
  at Java.Interop.JniPeerMembers+JniInstanceMethods..ctor (System.Type declaringType) [0x0004b] in <e3e4dfa992a7411b85acfe193481be3e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.GetConstructorsForType (System.Type declaringType) [0x00031] in 
```

### Actual behavior with Xamarin.Android 10.3.0.28 (d16-6@69561a7)

The application gets stuck in a crash and restart loop on the following exception:

```
Unhandled Exception:
System.MissingMethodException: Method not found: void .CreationOptions.set_JniAddNativeMethodRegistrationAttributePresent
[adblogcat_103028.txt](https://github.com/xamarin/xamarin-android/files/4358132/adblogcat_103028.txt)
(bool)
  at Android.Runtime.AndroidRuntime..ctor (System.IntPtr jnienv, System.IntPtr vm, System.Boolean allocNewObjectSupported, System.IntPtr classLoader, System.IntPtr classLoader_loadClass, System.Boolean jniAddNativeMethodRegistrationAttributePresent) [0x00000] in <003b7b299c604c84becae25f1bd49871>:0 
  at Android.Runtime.JNIEnv.Initialize (Android.Runtime.JnienvInitializeArgs* args) [0x000f9] in <003b7b299c604c84becae25f1bd49871>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method not found: void .CreationOptions.set_JniAddNativeMethodRegistrationAttributePresent(bool)
  at Android.Runtime.AndroidRuntime..ctor (System.IntPtr jnienv, System.IntPtr vm, System.Boolean allocNewObjectSupported, System.IntPtr classLoader, System.IntPtr classLoader_loadClass, System.Boolean jniAddNativeMethodRegistrationAttributePresent) [0x00000] in <003b7b299c604c84becae25f1bd49871>:0 
  at Android.Runtime.JNIEnv.Initialize (Android.Runtime.JnienvInitializeArgs* args) [0x000f9] in <003b7b299c604c84becae25f1bd49871>:0 
```

(This is probably a separate bug, but I'm not sure if it means the issue from 10.2.100.7 is fixed or just hidden, for example if this new issue happens earlier in the application init.)

### Version information

  * Xamarin.Android SDK   10.2.100.7 (d16-6@69561a7)
      * Mono: fc145be
      * Java.Interop: xamarin/java.interop/d16-6@178e849
      * ProGuard: xamarin/proguard/master@905836d
      * SQLite: xamarin/sqlite/3.31.1@49232bc
      * Xamarin.Android Tools: xamarin/xamarin-android-tools/master@bfb66f3

  * Xamarin.Android SDK   10.3.0.28 (d16-6/670668f)
      * Mono: d90665a
      * Java.Interop: xamarin/java.interop/d16-6@a84d19e
      * ProGuard: xamarin/proguard/master@905836d
      * SQLite: xamarin/sqlite/3.31.1@49232bc
      * Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

### Log files

[logs_10201007.zip](https://github.com/xamarin/xamarin-android/files/4358098/logs.zip)

MSBuild diagnostic build output for the second build, and the `adb logcat` output.

[adblogcat_103028.zip](https://github.com/xamarin/xamarin-android/files/4358134/adblogcat_103028.zip)

**Comment by brendanzagaeski** [comment] 2020-03-20 06:16
Cross-references for the Xamarin.Android team:

> VS bug [#1074168](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1074168)

<https://developercommunity.visualstudio.com/content/problem/956293/xamarinandroid-error-starting-application-after-pa.html>

**Comment by brendanzagaeski** [comment] 2020-03-20 06:32
To be thorough, I did a quick verification of Xamarin.Android 10.2.0.100, and, as expected, the app launches successfully after the second build in that case.

**Comment by jonathanpeppers** [comment] 2020-03-20 13:42
@grendello @brendanzagaeski I hit this crash on the _first_ build of this app:
https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/customrenderers-map-circle/
```
03-20 08:39:27.088 21460 21460 E mono    : Unhandled Exception:
03-20 08:39:27.088 21460 21460 E mono    : System.MissingMethodException: Method not found: void .CreationOptions.set_JniAddNativeMethodRegistrationAttributePresent(bool)
03-20 08:39:27.088 21460 21460 E mono    :   at Android.Runtime.AndroidRuntime..ctor (System.IntPtr jnienv, System.IntPtr vm, System.Boolean allocNewObjectSupported, System.IntPtr classLoader, System.IntPtr class
Loader_loadClass, System.Boolean jniAddNativeMethodRegistrationAttributePresent) [0x00000] in <9208d5fd0c8c43b7a00f304ba0f7c041>:0
03-20 08:39:27.088 21460 21460 E mono    :   at Android.Runtime.JNIEnv.Initialize (Android.Runtime.JnienvInitializeArgs* args) [0x000ed] in <9208d5fd0c8c43b7a00f304ba0f7c041>:0
03-20 08:39:27.090 21460 21460 E mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method not found: void .CreationOptions.set_JniAddNativeMethodRegistrationAttributePresent(bool)
03-20 08:39:27.090 21460 21460 E mono-rt :   at Android.Runtime.AndroidRuntime..ctor (System.IntPtr jnienv, System.IntPtr vm, System.Boolean allocNewObjectSupported, System.IntPtr classLoader, System.IntPtr class
Loader_loadClass, System.Boolean jniAddNativeMethodRegistrationAttributePresent) [0x00000] in <9208d5fd0c8c43b7a00f304ba0f7c041>:0
03-20 08:39:27.090 21460 21460 E mono-rt :   at Android.Runtime.JNIEnv.Initialize (Android.Runtime.JnienvInitializeArgs* args) [0x000ed] in <9208d5fd0c8c43b7a00f304ba0f7c041>:0
```

**Comment by jonathanpeppers** [comment] 2020-03-20 14:23
After playing some more, I can't reproduce this first error I got ☝️ .

But if you do this:
```
> touch .\Droid\MainActivity.cs
```
Then build again.

You get a new `MapOverlay.Droid.dll` with new type ids. So we get a new `libxamarin-app.so` native library.

But then this happened:
```
Skipping target "_CreateBaseApk" because all output files are up-to-date with respect to the input files.
```
This is _wrong_, but if we fix this it will severely impact incremental build times... We would effectively be creating a new APK, signing it, and installing it every time you change C# code.

The above problem goes away if you put `<Deterministic>True</Deterministic>` in the app's csproj. Because Roslyn will generate an identical assembly on every build. `$(Deterministic)` is set in the latest templates, so this is why we probably missed this in QA.

@grendello any ideas around this? Trying to think how we can ship ce2bc689a19cb45f7d7bfdd371c16c54b018a020 and not break anyone.

**Comment by jonathanpeppers** [comment] 2020-03-20 14:28
@jonpryor any ideas? Should we think about making `$(Deterministic)` required?

**Comment by grendello** [comment] 2020-03-20 14:38
@jonathanpeppers the first crash you got is because, somehow, the app has `Java.Interop.dll` that's too old. The property mentioned in the error message got added in [this commit](https://github.com/xamarin/java.interop/commit/b33d183deef0bb07272b30c58714ec8262551244).
Regarding `$(Deterministic)` - it is necessary **only** if the assemblies are for some reason modified after the typemaps are generated. So, perhaps, on incremental builds we should always set it to `true`?

**Comment by jonathanpeppers** [comment] 2020-03-20 15:07
@gmck can you put `<Deterministic>True</Deterministic>` in your main app's `.csproj` to see if the problem goes away for you?

Just add it at the top at the end of the first `</PropertyGroup>`.

**Comment by gmck** [comment] 2020-03-20 23:15
@grendello  You referred to GH email addresses for Jonathan and yourself. Could you please indicate where I can find those addresses and I'll provide you with a link

**Comment by grendello** [comment] 2020-03-20 23:26
@gmck click on our avatars :)

**Comment by gmck** [comment] 2020-03-20 23:47
@grendello Thanks. 
So you don't mean an actual GH address. eg. your twistedcode.net  address is what is required

**Comment by Lau69** [comment] 2020-03-22 08:54
Hello
I have the same issue : VS 16.6.0 Prev 1.0 App crashes on "Cannot create instance of type ... no Java peer type found" after incremental build
with this simple project (Default Xamarin Android project with Api 28) :

	public class JavaClass : Java.Lang.Object
	{
		/*
			reference assembly Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
			C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\Mono.Android.dll
		*/
	}

	public partial class App : Xamarin.Forms.Application
	{
		public App()
		{
			this.InitializeComponent();
			this.MainPage = new MainPage();
		}

		protected override void OnStart()
		{
			try
			{
				var TestNew = new JavaClass();
			}
			catch( System.Exception ex )
			{
				System.Diagnostics.Debug.WriteLine( ex );
				/*
					1) Visual Studio Start Debug	=> Application display "CrashTest"
					2) Visual Studio Stop Debug
					3) Modify file for force rebuild
					4) Visual Studio Start Debug	=> Exception
					5) Visual Studio Stop Debug
					6) Visual Studio Clean Solution
					7) Visual Studio Start Debug	=> Application display "CrashTest"

					System.NotSupportedException: Cannot create instance of type 'CrashTest.JavaClass': no Java peer type found.
					  at Java.Interop.JniPeerMembers+JniInstanceMethods..ctor (System.Type declaringType) [0x0004b] in <e3e4dfa992a7411b85acfe193481be3e>:0 
					  at Java.Interop.JniPeerMembers+JniInstanceMethods.GetConstructorsForType (System.Type declaringType) [0x00031] in <e3e4dfa992a7411b85acfe193481be3e>:0 
					  at Java.Interop.JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters) [0x00038] in <e3e4dfa992a7411b85acfe193481be3e>:0 
					  at Java.Lang.Object..ctor () [0x00034] in <03cab052cc7c4408a5b6127cbc405113>:0 
					  at CrashTest.JavaClass..ctor () <0x7276285750 + 0x0003b> in <1a8014a9b10847c2a184e69908dd94c4>:0 
					  at CrashTest.App.OnStart () [0x00002] in C:\Users\Famille\source\repos\CrashTest\CrashTest\CrashTest\App.xaml.cs:23
				*/
			}
		}
	}

	<?xml version="1.0" encoding="utf-8" ?>
	<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
	             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	             x:Class="CrashTest.MainPage">

		<Label Text="CrashTest" />

	</ContentPage>


I change to Api 29 and the exception disappears

**Comment by aqume** [comment] 2020-03-22 10:44
Hi,

I have the same issue. It started after upgrading to this version of VS
I need to rebuild the project every time to solve this. However, if I change any code then I have to rebuild it again.

**Comment by grendello** [comment] 2020-03-23 12:42
We know what's causing the issue and the fix is in the works. The problem stems from [this commit](ce2bc689a19cb45f7d7bfdd371c16c54b018a020), which implements a faster way of finding managed and Java peers, but requires that managed assembly MVID **and** type tokens do not change which, alas, is not always the case. [This suggestion](https://github.com/xamarin/xamarin-android/issues/4415#issuecomment-601748487) by @jonathanpeppers **may** work sometimes but it will most likely fail when a new type is added/removed or when a type is renamed (as that changes the layout of the type definition table in the assembly). The fix will be part of the next preview in ~3 weeks, until then if @jonathanpeppers suggested workaround doesn't work for you, a full rebuild may be necessary from time to time.

**Comment by jonathanpeppers** [comment] 2020-03-23 12:50
@Lau69 @aqume did you try the workaround in your main app's `.csproj`?
```xml
  <Deterministic>True</Deterministic>
</PropertyGroup>
```

**Comment by aqume** [comment] 2020-03-23 14:38
@jonathanpeppers @grendello 

No. It's not working.
I made changes to my apps main .csproj however it's not working.

BTW: Is there any way to rollback to previous version?

**Comment by jonathanpeppers** [comment] 2020-03-23 14:46
Stable and Preview versions of Visual Studio install side-by-side on Windows.

For Visual Studio for Mac you can switch channels to Stable, but it doesn't install side-by-side.

**Comment by Lau69** [comment] 2020-03-23 18:04
@jonathanpeppers

No. It's not working.
CrashTest.csproj:

	<Project Sdk="Microsoft.NET.Sdk">

	  <PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
		<Deterministic>True</Deterministic>
	  </PropertyGroup>

	  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<Deterministic>True</Deterministic>
	  </PropertyGroup>

	  <ItemGroup>
		<PackageReference Include="Xamarin.Forms" Version="4.5.0.356" />
		<PackageReference Include="Xamarin.Essentials" Version="1.3.1" />
	  </ItemGroup>

	  <ItemGroup>
		<Reference Include="Mono.Android">
		  <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\Mono.Android.dll</HintPath>
		</Reference>
	  </ItemGroup>
	</Project>

@grendello
it's interesting but why does it work with MonoDroid v10 ?

**Comment by grendello** [comment] 2020-03-23 18:36
@Lau69 I don't see a reason why it would be different with Android 10. The cause of the issue is behavior of the C# compiler, unrelated to Android target platform.

**Comment by Lau69** [comment] 2020-03-23 18:43
yes hence my question !!!
do you want my test project ?

**Comment by grendello** [comment] 2020-03-23 18:56
@Lau69 I need to focus on the fix implementation, there's not much time to do it, but please link to or upload your project here, I'm sure @jonathanpeppers will take a look at it, thanks!

**Comment by Lau69** [comment] 2020-03-23 19:04
Ok thanks,
My project :
[CrashTest.zip](https://github.com/xamarin/xamarin-android/files/4371400/CrashTest.zip)

**Comment by jonathanpeppers** [comment] 2020-03-23 20:11
@Lau69 I don't understand how a project like this would work:

https://github.com/xamarin/xamarin-android/issues/4415#issuecomment-602765577

You are building a `netstandard2.0` library, but trying to reference `Mono.Android.dll`? In general, this is not right. Can you start from the File->New Project dialog in Visual Studio instead? You probably want a Xamarin.Android class library.

**Comment by Lau69** [comment] 2020-03-24 04:03
@jonathanpeppers I created my project with the standard model
![image](https://user-images.githubusercontent.com/62498660/77386969-6ecd0380-6d8c-11ea-90af-d31426aa3124.png)
![image](https://user-images.githubusercontent.com/62498660/77386994-7ab8c580-6d8c-11ea-897a-68354c7a741b.png)
![image](https://user-images.githubusercontent.com/62498660/77387001-80161000-6d8c-11ea-8558-2143c788c5d6.png)
I only clean the Xaml and the Application class

**Comment by aqume** [comment] 2020-03-24 07:15
> Stable and Preview versions of Visual Studio install side-by-side on Windows.
> 
> For Visual Studio for Mac you can switch channels to Stable, but it doesn't install side-by-side.

Thanks,

I've installed VS 2019 SxS. It's working.
I was using 2019 Preview.

**Comment by jonathanpeppers** [comment] 2020-03-24 14:25
@Lau69 don't reference `Mono.Android.dll` from a `netstandard2.0` project like this:
```xml
  <ItemGroup>
        <!-- This is wrong -->
	<Reference Include="Mono.Android">
	  <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\Mono.Android.dll</HintPath>
	</Reference>
  </ItemGroup>
```
You only reference `Mono.Android.dll` from a Xamarin.Android application project or a Xamarin.Android class library project.

**Comment by gmck** [comment] 2020-03-25 04:28
@jonathanpeppers . Deterministic true seemed to work over the weekend. However today I'm back to cleaning before building/deploying for each change of code - even if it is just commenting a single line and then uncomment it.

**Comment by Lau69** [comment] 2020-03-25 06:04
@jonathanpeppers Does this mean that the Visual Studio project creation templates are wrong ?

**Comment by jonathanpeppers** [comment] 2020-03-25 14:46
@Lau69 the template didn't include this did it?

```xml
  <ItemGroup>
        <!-- This is wrong -->
	<Reference Include="Mono.Android">
	  <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\Mono.Android.dll</HintPath>
	</Reference>
  </ItemGroup>
```

**Comment by Lau69** [comment] 2020-03-25 18:13
@jonathanpeppers You are right. It's not the template. I was not vigilant enough, thank you

**Closed** 2020-04-06 18:31 UTC
Labels: Area: App Runtime, regression

**Comment by brendanzagaeski** [comment] 2020-04-17 03:35
*Release status update*

A Preview version has now been published on Windows that includes the fix for this item.

The fix is not yet available on macOS. I will update this item again when a Preview version with the fix is available on macOS.

Fix included in Xamarin.Android 10.3.0.74

Fix included on Windows in Visual Studio 2019 version 16.6 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix not yet available on macOS.

**Comment by brendanzagaeski** [comment] 2020-04-17 21:22
*Release status update*

A Preview version of Xamarin.Android has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.3.0.74.

Fix included on macOS in Visual Studio 2019 for Mac version 8.6 Preview 2. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
