### ISSUE TITLE
Initialize Dependency Injector on Android (X509Certificate PlatformNotSupportedException on VS2019 Preview 2 with Android)

### ISSUE THREAD

**Issue by KelleyRicker** [xamarin/xamarin-android#2679] opened 2019-02-01 00:26 UTC
We've been testing our Xamarin projects against the new VS2019 Previews, and since Preview 2 we've noticed a bug in Xamarin.Forms on Android and Xamarin.Android when creating a X509Certificate.  For us simply calling the following causes an exception.

`X509Certificate appCert = new X509Certificate(pubCertBytes); `-> exception System.PlatformNotSupportedException: Cannot get `ISystemDependencyProvider`. occurred
 
It appears to be a regression based on some older related issues:
[https://github.com/mono/mono/issues/9623](https://github.com/mono/mono/issues/9623)
[https://github.com/mono/mono/pull/9472#issuecomment-405732761](https://github.com/mono/mono/pull/9472#issuecomment-405732761)
Here is the changeset fix from before:
[https://github.com/mono/mono/commit/4c8d3505ed5bad8ef1c8b7e355a8cc257b3e2f1b](https://github.com/mono/mono/commit/4c8d3505ed5bad8ef1c8b7e355a8cc257b3e2f1b)
 
The same code/project works normally on VS2017, so it seems like it's some issue with Xamarin Android in VS2019 Preview 2 and 2.1.

> VS bug [#798117](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/798117)

**Comment by jonathanpeppers** [comment] 2019-02-05 14:54
@baulig not sure if you are aware of this happening on Android? it mentioned iOS on: https://github.com/mono/mono/pull/9472#issuecomment-405732761

**Comment by pjcollins** [comment] 2019-02-20 20:04
This issue is still present in the `d16-0` branch, here's a trivial repro: https://gist.github.com/pjcollins/db52513a4d1d5f6f73c0fbfbc121de0c

**Comment by baulig** [comment] 2019-02-20 20:51
The problem is that the dependency injector is not initialized properly.  We need to add the equivalent of this https://github.com/xamarin/xamarin-macios/blob/master/src/ObjCRuntime/Runtime.cs#L256 to the runtime startup code.

**Comment by baulig** [comment] 2019-02-20 22:38
The fix is to call `SystemDependencyProvider.Initialize()` during startup, just like we're doing it in [xamarin-macios/src/ObjCRuntime/Runtime.cs](https://github.com/xamarin/xamarin-macios/blob/master/src/ObjCRuntime/Runtime.cs#L256).

To do so, we need to first make `System.dll` internals visible to `Mono.Android`; PR for this is up: https://github.com/mono/mono/pull/13106.  After landing, this PR then needs to be backported all the way up to 2018-08.

Then we can bump Mono in `xamarin-android` and land this one: https://github.com/xamarin/xamarin-android/pull/2753.

**Comment by marek-safar** [comment] 2019-02-21 20:36
We have a fix for this and it's quite self-contained but it requires Mono bump with only "one line" change.

@AdrianMurphy @Aguilex could you confirm whether we can still get it in?

**Comment by jonpryor** [comment] 2019-02-21 22:07
Stack trace thrown when it fails:

```
MonoDroid: UNHANDLED EXCEPTION:
MonoDroid: System.PlatformNotSupportedException: Cannot get `ISystemDependencyProvider`.
MonoDroid:   at Mono.DependencyInjector.get_SystemProvider () [0x00033] in <58604b4522f748968296166e317b04b4>:0
MonoDroid:   at System.Security.Cryptography.X509Certificates.X509Helper.get_CertificateProvider () [0x00000] in <58604b4522f748968296166e317b04b4>:0
MonoDroid:   at System.Security.Cryptography.X509Certificates.X509Helper.Import (System.Byte[] rawData) [0x00000] in <58604b4522f748968296166e317b04b4>:0
MonoDroid:   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor (System.Byte[] data) [0x00023] in <58604b4522f748968296166e317b04b4>:0
MonoDroid:   at App7.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00036] in C:\Users\peter\source\repos\App7\App7\MainActivity.cs:27
MonoDroid:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <aafbe4b23f2449219f7d521f09de5720>:0
MonoDroid:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)
Mono    : DllImport searching in: '__Internal' ('(null)').
Mono    : Searching for 'java_interop_jnienv_new_string'.
Mono    : Probing 'java_interop_jnienv_new_string'.
Mono    : Found as 'java_interop_jnienv_new_string'.
App7.App7: JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
Mono    : DllImport searching in: '__Internal' ('(null)').
Mono    : Searching for 'java_interop_jnienv_throw'.
Mono    : Probing 'java_interop_jnienv_throw'.
Mono    : Found as 'java_interop_jnienv_throw'.
ActivityManager: Launch timeout has expired, giving up wake lock!
android.hardware.power@1.2-service.wahoo-libperfmgr: LAUNCH OFF
ActivityManager: Killing 32709:com.google.process.gapps/u0a20 (adj 906): empty #17
libprocessgroup: kill(-32709, 9) failed: No such process
Finsky  : [2] com.google.android.finsky.scheduler.JobSchedulerEngine$PhoneskyJobSchedulerJobService.onStartJob(8): onJobSchedulerWakeup with jobId 9001
Zygote  : Process 32709 exited due to signal (9)
libprocessgroup: kill(-32709, 9) failed: No such process
libprocessgroup: Successfully killed process cgroup uid 10020 pid 32709 in 45ms
mono    :
mono    : Unhandled Exception:
mono    : System.PlatformNotSupportedException: Cannot get `ISystemDependencyProvider`.
mono    :   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)
mono    :   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)
mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.PlatformNotSupportedException: Cannot get `ISystemDependencyProvider`.
mono-rt :   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)
mono-rt :   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)
```

**Comment by KelleyRicker** [comment] 2019-02-26 20:44
Do you have an ETA for when this fix will become available?

**Closed** 2019-03-04 02:43 UTC
Labels: Area: Mono Runtime, bug, regression, vs-sync
