### ISSUE TITLE
[Bug] New Visual Studio Update Crash Android

### ISSUE THREAD

**Issue by lvenchi** [xamarin/xamarin-android#3178] opened 2019-06-06 10:10 UTC
### Description
App crashes after vs 2019 16.1.2 update
### Steps to Reproduce
Passing a binding context to a view

### Expected Behavior
App doesn't crash
### Actual Behavior
App crashes with SIGSEGV 
### Basic Information

- Version with issue: 16.1.2
- Last known good version: 16.1
- Platform Target Frameworks:  Android 9

- Affected Devices: Samsung note 9

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x761418d678):0x761418d668  00 1c 40 b9 c0 03 5f d6 fd 7b bf a9 fd 03 00 91  ..@..._..{......
0x761418d678  08 20 40 b9 a8 00 c8 37 88 01 e0 37 00 00 40 f9  . @....7...7..@.
0x761418d688  fd 7b c1 a8 c0 03 5f d6 60 08 00 b0 01 0a 00 f0  .{...._.`.......
0x761418d698  03 0a 00 f0 00 24 06 91 21 80 08 91 63 8c 0a 91  .....$..!...c...

No native Android stacktrace (see debuggerd output).

===============================================06-06 11:58:01.045 E/mono-rt (11997): 12c00000-12d00000 rw-p 00000000 00:01 18428                              /dev/ashmem/dalvik-main space (region space)_4577_4577 (deleted)

==================
	Managed Stacktrace:
=================================================================
=================================================================06-06 11:58:01.045 E/mono-rt (11997): 12d00000-12d80000 ---p 00100000 00:01 18428                              /dev/ashmem/dalvik-main space (region space)_4577_4577 (deleted)

06-06 11:58:01.045 E/mono-rt (11997): 12d80000-13000000 rw-p 00180000 00:01 18428                              /dev/ashmem/dalvik-main space (region space)_4577_4577 (deleted)
06-06 11:58:01.045 E/mono-rt (11997): 13000000-13a40000 ---p 00400000 00:01 18428                              /dev/ashmem/dalvik-main space (region space)_4577_4577 (deleted)
06-06 11:58:01.045 E/mono-rt (11997): 13a40000-32c00000 rw-p 00e40000 00:01 18428                              /dev/ashmem/dalvik-main space (region space)_4577_4577 (deleted)
06-06 11:58:01.045 E/mono-rt (11997): 70eaf000-71189000 rw-p 00000000 fe:03 121                                /data/dalvik-cache/arm64/system@framework@boot.art
06-06 11:58:01.045 E/mono-rt (11997): 71189000-7119f000 r--p 002da000 fe:03 121                                /data/dalvik-cache/arm64/system@framework@boot.art
06-06 11:58:01.045 E/mono-rt (11997): 7119f000-712d4000 rw-p 00000000 fe:03 124                                /data/dalvik-cache/arm64/system@framework@boot-core-libart.art
06-06 11:58:01.045 E/mono-rt (11997): 712d4000-712e6000 r--p 00135000 fe:03 124                                /data/dalvik-cache/arm64/system@framework@boot-core-libart.art
06-06 11:58:01.045 E/mono-rt (11997): 712e6000-71326000 rw-p 00000000 fe:03 127                                /data/dalvik-cache/arm64/system@framework@boot-conscrypt.art
06-06 11:58:01.045 E/mono-rt (11997): 71326000-71329000 r--p 00040000 fe:03 127                                /data/dalvik-cache/arm64/system@framework@boot-conscrypt.art
06-06 11:58:01.045 E/mono-rt (11997): 71329000-71370000 rw-p 00000000 fe:03 130                                /data/dalvik-cache/arm64/system@framework@boot-okhttp.art
06-06 11:58:01.045 E/mono-rt (11997): 71370000-71374000 r--p 00047000 fe:03 130                                /data/dalvik-cache/arm64/system@framework@boot-okhttp.art
06-06 11:58:01.045 E/mono-rt (11997): 71374000-713da000 rw-p 00000000 fe:03 133                                /data/dalvik-cache/arm64/system@framework@boot-bouncycastle.art
06-06 11:58:01.045 E/mono-rt (11997): 713da000-713e1000 r--p 00066000 fe:03 133                                /data/dalvik-cache/arm64/system@framework@boot-bouncycastle.art
06-06 11:58:01.045 E/mono-rt (11997): 713e1000-71442000 rw-p 00000000 fe:03 136                                /data/dalvik-cache/arm64/system@framework@boot-apache-xml.art
06-06 11:58:01.045 E/mono-rt (11997): 71442000-71449000 r--p 00061000 fe:03 136                                /data/dalvik-cache/arm64/system@framework@boot-apache-xml.art
06-06 11:58:01.045 E/mono-rt (11997): 71449000-7148d000 rw-p 00000000 fe:03 139                                /data/dalvik-cache/arm64/system@framework@boot-ext.art
06-06 11:58:01.045 E/mono-rt (11997): 7148d000-71498000 r--p 00044000 fe:03 139                                /data/dalvik-cache/arm64/system@framework@boot-ext.art
06-06 11:58:01.045 E/mono-rt (11997): 71498000-720a4000 rw-p 00000000 fe:03 143                                /data/dalvik-cache/arm64/system@framework@boot-framework.art
06-06 11:58:01.045 E/mono-rt (11997): 720a4000-72104000 r--p 00c0c000 fe:03 143                                /data/dalvik-cache/arm64/system@framework@boot-framework.art
06-06 11:58:01.045 E/mono-rt (11997): 72104000-7228c000 rw-p 00000000 fe:03 146                                /data/dalvik-cache/arm64/system@framework@boot-telephony-common.art
06-06 11:58:01.045 E/mono-rt (11997): 7228c000-722aa000 r--p 00188000 fe:03 146                                /data/dalvik-cache/arm64/system@framework@boot-telephony-common.art
06-06 11:58:01.045 E/mono-rt (11997): 722aa000-722b9000 rw-p 00000000 fe:03 149                                /data/dalvik-cache/arm64/system@framework@boot-voip-common.art
06-06 11:58:01.045 E/mono-rt (11997): 722b9000-722bb000 r--p 0000f000 fe:03 149                                /data/dalvik-cache/arm64/system@framework@boot-voip-common.art
06-06 11:58:01.046 F/libc    (11997): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 11997 (.MyApp), pid 11997 (.MyApp)

**Comment by brendanzagaeski** [comment] 2019-06-11 01:21
Thanks for the report! This is likely a duplicate of <https://github.com/xamarin/xamarin-android/issues/3112>. To help confirm that, if you get a chance, if you could provide one of the following, that would be perfect:

* [Follow the recent comment on #3112](https://github.com/xamarin/xamarin-android/issues/3112#issuecomment-500648563) to install the candidate development installer package that includes the candidate fix for that issue, and check if it resolves the issue you are seeing with your app.

* Or collect and attach back the `adb logcat` log from the crash:

    1. Open **Tools > Android > Android Adb Command Prompt**.
    2. Run the following command to clear the log on the device:

        ```cmd
        adb logcat -c
        ```

    3. Repeat the app crash once more.
    4. Run the following command to collect the log from the device:

        ```
        adb logcat -d > "%USERPROFILE%\Desktop\adblogcat.txt"
        ```

    5. Attach back the *adblogcat.txt* file from your desktop, or if you prefer, copy and paste just the section of it that starts with the "E/mono-rt" lines you included in the original description and ends after the section that starts with a "Build fingerprint:" line and includes a "backtrace:" section (the native backtrace).

    The additional "backtrace:" information will often contain the name of the native function where the app exited unexpectedly, which can be helpful to distinguish among different native crashes.

* Or zip up and attach a small self-contained project that demonstrates the issue.

**Comment by lvenchi** [comment] 2019-06-11 13:17
Well i have solved the problem last week and the problem were a binding to a datepicker and a binding with an FFimageLoading's cachedimage's source.
The problem with the datepicker was that the item bound was a string instead of a datetime. While the image source problem was the binding mode which had to be set to one-way.
( those bindings were working before the updates).
 Hope it helps.

**Comment by brendanzagaeski** [comment] 2019-06-12 04:28
Thanks for the information, and happy to hear you resolved the issue for your project! I suspect what was happening was that the two-way binding mechanism was using exceptions internally that were triggering <https://github.com/xamarin/xamarin-android/issues/3112>. That's what happens if I modify the XAML page from <https://developer.xamarin.com/samples/xamarin-forms/ScaleAndRotate/> to include `TwoWay` bindings. Based on that, I'll close this issue as a duplicate of <https://github.com/xamarin/xamarin-android/issues/3112>. If you run across a crash that looks the same again and the builds with the candidate fixes from <https://github.com/xamarin/xamarin-android/issues/3112> don't help with the issue, feel free to reopen this item for further investigation. Thanks again!

**Closed by brendanzagaeski** 2019-06-12 04:28 UTC
Labels: need-info

**Comment by lvenchi** [comment] 2019-06-14 15:37
Just a little update : binding mode two way an entry with numeric keyboard input bound to an int, makes the app crash. To fix it i had to bound it to a string. ( I think the general problem is converting values in two-way binding).
