### ISSUE TITLE
Tasks and ThreadPools stop working if the Android app was kept in the background for 4-5 days

### ISSUE THREAD

**Issue by tejas-ad** [xamarin/xamarin-android#2295] opened 2018-10-14 16:26 UTC
### Steps to Reproduce

The app has a foreground service and the app is kept running in the background for 4-5 days. After some duration, the MvvmCross references get de-initialized but the foreground services keep running. When the app is brought back to the foreground after 4-5 days, MvvmCross initialization starts but gets stuck at the point that queues a work item in the threadpool. Here is the code snippet from MvxAndroidSetupSingleton class inside MvvmCross Framework, that tries to enqueue a work item:

            _setup.InitializePrimary();
            **ThreadPool.QueueUserWorkItem(ignored =>
            {
                _setup.InitializeSecondary();
                lock (LockObject)
                {
                    _initialized = true;
                    if (_currentSplashScreen != null)
                    {
                        _currentSplashScreen.InitializationComplete();
                    }
                }
            });**
The code enqueued in the ThreadPool never seems to get executed if the app gets in this situation. As the foreground services are running, the only option is to force stop the app. We could only reproduce the exact scenario by removing the code segment in bold. Currently, there seems to be no other way to reproduce than to wait for 5 days to reproduce it. We have tried kicking the app out of memory by filling up the memory using a different app. The adb shell commands to put the device/app in doze/deep sleep have also been tried, without any success.
A detailed search on ThreadPool shows people have had problems with it especially with Xamarin. For some, the issue was resolved by switching to Task.Run, but in our case, that did not help either. Here is a similar issue that was observed on iOS, but was never resolved by Xamarin. The developer ended up removing all the mono threadpools and Task.Run instances to get his app working. Link: https://bugzilla.xamarin.com/show_bug.cgi?id=58633 . See [comment #18](https://bugzilla.xamarin.com/show_bug.cgi?id=58633#c18) that confirms this.

More issues faced by people with ThreadPools on Xamarin:
1. https://forums.xamarin.com/discussion/23818/threadpool-is-driving-me-nuts-how-do-i-diagnose-where-the-threads-are-started
2. https://stackoverflow.com/a/42245625/2501621

### Expected Behavior
The work item should be queued in the threadpool and executed.

### Actual Behavior
The work item never gets executed.

### Version Information

=== Visual Studio Enterprise 2017 for Mac ===
 
Version 7.5.1 (build 22)
Installation UUID: 60692d15-b5ef-4ab8-8316-035366dc3940
Runtime:
                Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
                GTK+ 2.24.23 (Raleigh theme)
                Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)
                Package version: 510010047
 
=== NuGet ===
 
Version: 4.3.1.4445
 
=== .NET Core ===
 
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
                2.0.5
                2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
                2.1.4
                2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks
 
=== Xamarin.Profiler ===
 
Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
 
=== Apple Developer Tools ===
 
Xcode 9.4.1 (14161)
Build 9F2000
 
=== Xamarin.Mac ===
 
Version: 4.4.1.178 (Visual Studio Enterprise)
 
=== Xamarin.iOS ===
 
Version: 11.10.1.178 (Visual Studio Enterprise)
Hash: 408d3574
Branch: d15-7
Build date: 2018-05-08 18:56:30-0400
 
=== Xamarin.Android ===
 
Version: 8.3.0.19 (Visual Studio Enterprise)
Android SDK: /Users/.../Library/Developer/Xamarin/android-sdk-macosx
                Supported Android versions:
                                2.3   (API level 10)
                                4.0.3 (API level 15)
                                5.0   (API level 21)
                                5.1   (API level 22)
                                6.0   (API level 23)
                                7.0   (API level 24)
                                7.1   (API level 25)
                                8.0   (API level 26)
                                8.1   (API level 27)
 
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.0
SDK Build Tools Version: 27.0.3
 
Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
 
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
 
=== Xamarin Inspector ===
 
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1
 
=== Build Information ===
 
Release ID: 705010022
Git revision: 60442dd643a20c7a4ae1f8705b8d1de8972eee78
Build date: 2018-05-15 01:43:39+00
Xamarin addins: 4194ffe4868321e4c3477bd56aed579bda4c6fbb
 
=== Operating System ===
 
Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
 
=== Enabled user installed addins ===
 
Internet of Things (IoT) development (Preview) 7.5

### Log File

Not attaching a log file as the app needs to be in the background for 4-5 days for this issue to be seen.

**Comment by jgold6** [comment] 2018-10-14 19:40
I was able to reproduce the issue on a Nougat and Oreo emulator and on an LG device by setting the max number of ThreadPool threads to 4 and then spinning up 5 threads that run an infinite loop inside a lock:

           ThreadPool.SetMaxThreads(4, 10);

            for (int i = 0; i < 5; i++)
            {
                ThreadPool.QueueUserWorkItem(ignored =>
                {
                    lock (LockObject)
                    {
                        while (keeplooping) // keeplooping set to true initially, set it to false to allow the 5 threads to run and complete
                        {

                        }
                    }
                });
            } 

so the first thread locks the other 4. Then when the code indicated in the issue description is hit, the new ThreadPool thread is queued but does not run since there are no available threads in the ThreadPool. If I then let the first five threads complete (by setting keep looping to false) then the code in question does run.

However the reporting customer reported that the above did not reproduce the issue on their Samsung devices. Not sure if Samsung somehow changes how threading is handled?

**Comment by grendello** [comment] 2018-11-06 13:54
@jgold6 can you attach your full repro solution? Thanks!

**Comment by jgold6** [comment] 2018-11-06 18:12
@grendello I cannot. It was a customer's full solution. 

The issue was finally tracked down to some fire and forget async method that was deadlocking, and over time more and more of these deadlocked threads were spun up such that after 4-5 days the threadpool hit its max threads and prevented the work item in question from running, though it does get queued. 

You can likely close this issue.

**Closed as completed** 2018-12-10 14:29 UTC
Labels: need-info, Area: App Runtime, Area: Mono Runtime
