### ISSUE TITLE
[Bug] Build failed in Android with Forms 4.5 / 4.6 (UpdateIdValues()' in assembly: 'PROJECTNAME.Android.dll')

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-android#4463] opened 2020-03-26 01:27 UTC
Moving issues from Xamarin.Forms 
https://github.com/xamarin/Xamarin.Forms/issues/9852

### Steps to Reproduce

https://github.com/xamarin/Xamarin.Forms/issues/9852#issuecomment-599970481

**Comment by radekdoulik** [comment] 2020-03-26 11:27
@dellis1972 not sure whether this is yours or designer?

**Comment by Depechie** [comment] 2020-03-26 12:39
Did an update of our dev environment yesterday but problem still exists.
Here are the details of my configuration:

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.5 (build 3183)
Installation UUID: 38a3a5c8-1ddd-4886-ac02-b22df33fe958
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)

	Package version: 608000123

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)
	Package version: 608000123

=== Roslyn (Language Service) ===

3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e

=== NuGet ===

Version: 5.4.0.6315

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.101
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	2.1.16
	2.1.15

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.2.0.100 (Visual Studio Enterprise)
Commit: xamarin-android/d16-5/988c811
Android SDK: /Users/glv/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/glv/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-03-24 09:56:08 UTC

=== Android Device Manager ===

Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5
Build date: 2020-03-24 09:56:00 UTC

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.14.1.39 (Visual Studio Enterprise)
Hash: 30e8706b4
Branch: d16-5
Build date: 2020-02-20 16:41:48-0500

=== Xamarin Designer ===

Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-03-24 09:52:53 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 805003183
Git revision: 60e06e010baa677204535600661dda3fb4677c2f
Build date: 2020-03-20 06:18:03-04
Build branch: release-8.5
Xamarin extensions: 60e06e010baa677204535600661dda3fb4677c2f

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Visual Studio Toolset For Mac 1.0.44

**Comment by dellis1972** [comment] 2020-03-31 14:30
This looks like a problem in the `TeeChart` nugget package.

```
TeeChart.PCL.Droid.Resource::UpdateIdValues()' in assembly: 'TeeChart.PCL.Android.dll'
Failed to resolve System.Int32 Xamarin.Forms.Platform.Android.Resource/Animation::btn_checkbox_to_checked_box_inner_merged_animation
```

so this means that `TeeChart.PCL.Android.dll` has code in it which is trying to set or read the value of `btn_checkbox_to_checked_box_inner_merged_animation` in the Xamarin.Forms.Platform.Android.dll. So the fix in this case would be to update TeeChart to a newer version of Xamarin.Forms. Or we completely ignore this error in the linker (for `Resource` type fields).

@radekdoulik thoughts?

**Comment by Depechie** [comment] 2020-03-31 14:36
hey @dellis1972 2 things to note!

1. The original reporter ( https://github.com/xamarin/Xamarin.Forms/issues/9852 ) is not using that TeeChart lib! I do, and provided that as a small repro... so I think the issue is broader

2. With the older tooling, we are able to do an AOT build! ( So older Xamarin Forms version and Xamarin Android running DX compiler instead of D8 ) The problem only comes up after doing upgrades.

**Comment by brendanzagaeski** [comment] 2020-04-02 23:48
Out of curiosity, I took a look at the Steema.TeeChart.NET.Xamarin.Forms scenario. It turns out the problem in that case is actually that the latest version of Steema.TeeChart.NET.Xamarin.Forms is *already* built against Xamarin.Forms version 4.5, and in particular it's built against the MonoAndroid10.0 target framework moniker version of *Xamarin.Forms.Platform.Android.dll*. That's the version where `btn_checkbox_to_checked_box_inner_merged_animation` first appears.

So the compatible way to use Steema.TeeChart.NET.Xamarin.Forms version 4.2020.3.11 is to use it in Xamarin.Android app that has **Compile using Android version: (Target Framework)** set to **Android 10.0 (Q)**.

I verified that I was able to reproduce the error in a new empty project when targeting **Android 9.0 (Pie)** and was able to build successfully when I switched the project to target **Android 10.0 (Q)**.

I think this might mean that Steema.TeeChart.NET.Xamarin.Forms would need to adjust the NuGet package to provide at least two target framework moniker versions to enable compatibility with Android app projects targeting Android 9.0 Pie as well as Android 10.0.

* * *

The Plugin.Media.Resource case from the original reporter of https://github.com/xamarin/Xamarin.Forms/issues/9852 sounds like its own separate but similar scenario. I'm not sure if the original reporter is still seeing that, or if subsequent NuGet package updates might have changed or resolved what that user was seeing.

**Comment by brendanzagaeski** [comment] 2020-04-03 01:14
> Or we completely ignore this error in the linker (for `Resource` type fields).

To pitch in a little extra info on this topic, I think these errors would in most cases indicate that the library is really using a resource type field somewhere in a hand-written method. The linker error at build time would help guard against an error when running the app in those cases.

*TeeChart.PCL.Android.dll* seems to be unusual because it has a generated `UpdateIdValues()` method. That method is only supposed to be generated for application projects. Curiously, it looks like *TeeChart.PCL.Android.dll* was was built with `$(AndroidApplication)`=`true`. It has the following assembly metadata:

```
[assembly: ResourceDesigner ("TeeChart.PCL.Droid.Resource", IsApplication = true)]
```

**Comment by Depechie** [comment] 2020-04-03 07:57
Hey @brendanzagaeski thanks for the detailed info! Indeed, going back to an older nuget fixes the issue of not being able to do an AOT build in our case ( with Android 9.0 ).
I'm going to send you findings over to Steema to see if they can help us out.

**Comment by jameswestgate** [comment] 2020-05-21 09:10
I have the same issue. Setting linker to Don't Link fixes the compiler error, but at the cost of a huge .aab / .apk. Link SDK libraries only option reproduces the issue.

Upgrading to Xamarin.Forms 4.6.0.800 and Xamarin.Essentials 1.5.3.2 resolved the issue for me with the correct linker settings.

**Comment by radekdoulik** [comment] 2020-05-21 11:05
@dellis1972 the TeeChart assembly might be built against older XForms and missing the reference? Or something might be wrong with the resources generation. The missing reference points to `Xamarin.Forms.Platform.Android.Resource`. There is similar bug open on AzDO IIRC, where TeeChart is involved as well.

**Comment by brendanzagaeski** [comment] 2020-06-03 23:47
*Release status update*

A fix that should help prevent similar issues from reappearing for the Steema.TeeChart.NET.Xamarin.Forms NuGet package in the future has now been published by the Steema team. To get the fix, update to the latest [Steema.TeeChart.NET.Xamarin.Forms](https://www.nuget.org/packages/Steema.TeeChart.NET.Xamarin.Forms/) NuGet package version 4.2020.5.28 (or higher).

A corresponding reply from the Steema team has been posted on a related Steema support ticket: https://www.steema.com/support/viewtopic.php?f=4&t=17342

The new _TeeChart.PCL.Android.dll_ library is now built with the `AndroidApplication` MSBuild property set to `false`, so it will no longer include the unneeded `UpdateIdValues()` method that was introducing some unexpected extraneous references to Android resource IDs.

Since the discussion on this issue ended up being about the Steema.TeeChart.NET.Xamarin.Forms NuGet package scenario, I will close this xamarin-android issue accordingly.

If any users see a similar error in the future for TeeChart or another library, please open a [new issue](https://github.com/xamarin/xamarin-android/issues/new/choose) to describe the error, and if possible, attach the diagnostic MSBuild output for the project so the team can take a look. Thanks!

**Closed by brendanzagaeski** 2020-06-03 23:47 UTC
Labels: Area: App+Library Build

**Comment by gustiaeppli** [comment] 2020-06-20 20:32
Is this also fixed in the STD library?
Steema.TeeChart.NET.STD.Xamarin.Forms -Version 4.2020.?.??
