### ISSUE TITLE
Azure DevOps build pipeline using macOS-latest unable to build Xamarin.Android project with v12.1 specified as the TargetFrameworkVersion

### ISSUE THREAD

**Issue by GreatBarrier86** [xamarin/xamarin-android#7245] opened 2022-08-09 19:04 UTC
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), Android for .NET (net6.0-android, etc.)

### Affected platform version

Azure DevOps macOS-latest

### Description

Hello,

When specifying the following line in the Xamarin Android csproj file, we get a build error with the Azure DevOps macOS-latest image. This was set through the Visual Studio project properties UI.

**Problem line in the csproj file**
`<TargetFrameworkVersion>v12.1</TargetFrameworkVersion>`
![image](https://user-images.githubusercontent.com/29482393/183739935-fa538570-0a93-4806-a9e8-bd18954e2afe.png)

**Error**
`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(278,5): error XA0000: Could not determine API level for $(TargetFrameworkVersion) of 'v12.1'. [/Users/runner/work/8/s/Mobile/CPSMobile/CPSMobile.Android/CPSMobile.Android.csproj]
Done Building Project "/Users/runner/work/8/s/Mobile/CPSMobile/CPSMobile.Android/CPSMobile.Android.csproj" (PackageForAndroid target(s)) -- FAILED.`

**Manifest line (which does not cause an error on its own)**
`<uses-sdk android:minSdkVersion="28" android:targetSdkVersion="32" />`

**Pipeline step YAML**
`steps:
task: XamarinAndroid@1
  displayName: 'Android: Build Project - Test'
  inputs:
    projectFile: '$(Parameters.AndroidProject)'
    outputDirectory: '$(Parameters.TestTargetFolder)'
    configuration: '$(BuildConfiguration)'
    msbuildVersionOption: latest`

### Steps to Reproduce

Create a project that references TargetFrameworkVersion v12.1 and try to compile it using a macOS-latest build pipeline.

### Did you find any workaround?

None that i found.

### Relevant log output

```shell
2022-08-09T19:00:22.4996360Z ##[debug]Evaluating condition for step: 'Android: Build Project - Test'
2022-08-09T19:00:22.4999500Z ##[debug]Evaluating: succeeded()
2022-08-09T19:00:22.5000170Z ##[debug]Evaluating succeeded:
2022-08-09T19:00:22.5001750Z ##[debug]=> True
2022-08-09T19:00:22.5002570Z ##[debug]Result: True
2022-08-09T19:00:22.5003530Z ##[section]Starting: Android: Build Project - Test
2022-08-09T19:00:22.5015530Z ==============================================================================
2022-08-09T19:00:22.5015960Z Task         : Xamarin.Android
2022-08-09T19:00:22.5016230Z Description  : Build an Android app with Xamarin
2022-08-09T19:00:22.5016460Z Version      : 1.200.0
2022-08-09T19:00:22.5016730Z Author       : Microsoft Corporation
2022-08-09T19:00:22.5017100Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/xamarin-android
2022-08-09T19:00:22.5017570Z ==============================================================================
2022-08-09T19:00:22.5057990Z ##[debug]tf resolvePath -workspace:ws_8_8 $/TFS/Main/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj "-collection:https://dev.azure.com/custardinsuranceadjusters/" -jwt:*** -noprompt
2022-08-09T19:00:23.9186840Z ##[debug]/Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj
2022-08-09T19:00:23.9677070Z ##[debug]Using node path: /Users/runner/runners/2.206.1/externals/node10/bin/node
2022-08-09T19:00:24.1268640Z ##[debug]agent.TempDirectory=/Users/runner/work/_temp
2022-08-09T19:00:24.1371360Z ##[debug]loading inputs and endpoints
2022-08-09T19:00:24.1480970Z ##[debug]loading INPUT_PROJECT
2022-08-09T19:00:24.1583080Z ##[debug]loading INPUT_OUTPUTDIR
2022-08-09T19:00:24.1642220Z ##[debug]loading INPUT_CONFIGURATION
2022-08-09T19:00:24.1643780Z ##[debug]loading INPUT_CREATEAPPPACKAGE
2022-08-09T19:00:24.1644740Z ##[debug]loading INPUT_CLEAN
2022-08-09T19:00:24.1645560Z ##[debug]loading INPUT_MSBUILDLOCATIONMETHOD
2022-08-09T19:00:24.1647070Z ##[debug]loading INPUT_MSBUILDVERSION
2022-08-09T19:00:24.1647960Z ##[debug]loading INPUT_MSBUILDARCHITECTURE
2022-08-09T19:00:24.1648780Z ##[debug]loading INPUT_JDKSELECTION
2022-08-09T19:00:24.1649580Z ##[debug]loading INPUT_JDKVERSION
2022-08-09T19:00:24.1650510Z ##[debug]loading INPUT_JDKARCHITECTURE
2022-08-09T19:00:24.1651370Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2022-08-09T19:00:24.1652250Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2022-08-09T19:00:24.1653180Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2022-08-09T19:00:24.1654070Z ##[debug]loading SECRET_PROCPARAM_KEYPASS
2022-08-09T19:00:24.1654890Z ##[debug]loading SECRET_KEYCHAINPASSWORD
2022-08-09T19:00:24.1655720Z ##[debug]loading SECRET_PROCPARAM_KEYSTOREALIAS
2022-08-09T19:00:24.1656570Z ##[debug]loading SECRET_PARAMETERS_KEYSTOREALIAS
2022-08-09T19:00:24.1657520Z ##[debug]loading SECRET_PARAMETERS_KEYPASS
2022-08-09T19:00:24.1658380Z ##[debug]loading SECRET_PARAMETERS_KEYSTOREPASS
2022-08-09T19:00:24.1659210Z ##[debug]loading SECRET_ADMINPASSWORD
2022-08-09T19:00:24.1660050Z ##[debug]loading SECRET_PROCPARAM_KEYSTOREPASS
2022-08-09T19:00:24.1660870Z ##[debug]loading SECRET_KEYSTOREALIAS
2022-08-09T19:00:24.1661690Z ##[debug]loading SECRET_CERTIFICATEPASSWORD
2022-08-09T19:00:24.1662460Z ##[debug]loaded 24
2022-08-09T19:00:24.1663220Z ##[debug]Agent.ProxyUrl=undefined
2022-08-09T19:00:24.1664110Z ##[debug]Agent.CAInfo=undefined
2022-08-09T19:00:24.1664920Z ##[debug]Agent.ClientCert=undefined
2022-08-09T19:00:24.1665730Z ##[debug]Agent.SkipCertValidation=undefined
2022-08-09T19:00:24.1667630Z ##[debug]check path : /Users/runner/work/_tasks/XamarinAndroid_27edd013-36fd-43aa-96a3-7d73e1e35285/1.200.0/node_modules/azure-pipelines-tasks-java-common/lib.json
2022-08-09T19:00:24.1669380Z ##[debug]adding resource file: /Users/runner/work/_tasks/XamarinAndroid_27edd013-36fd-43aa-96a3-7d73e1e35285/1.200.0/node_modules/azure-pipelines-tasks-java-common/lib.json
2022-08-09T19:00:24.1670790Z ##[debug]system.culture=en-US
2022-08-09T19:00:24.1672210Z ##[debug]check path : /Users/runner/work/_tasks/XamarinAndroid_27edd013-36fd-43aa-96a3-7d73e1e35285/1.200.0/task.json
2022-08-09T19:00:24.1674460Z ##[debug]adding resource file: /Users/runner/work/_tasks/XamarinAndroid_27edd013-36fd-43aa-96a3-7d73e1e35285/1.200.0/task.json
2022-08-09T19:00:24.1675920Z ##[debug]system.culture=en-US
2022-08-09T19:00:24.1676900Z ##[debug]project=/Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj
2022-08-09T19:00:24.1677860Z ##[debug]target=undefined
2022-08-09T19:00:24.1678680Z ##[debug]outputDir=/Users/runner/work/8/b/release/Test
2022-08-09T19:00:24.1679500Z ##[debug]configuration=release
2022-08-09T19:00:24.1680820Z ##[debug]createAppPackage=true
2022-08-09T19:00:24.1682770Z ##[debug]clean=false
2022-08-09T19:00:24.1683830Z ##[debug]msbuildArguments=undefined
2022-08-09T19:00:24.1685030Z ##[debug]jdkSelection=JDKVersion
2022-08-09T19:00:24.1685900Z ##[debug]Using JDK version to find JDK path
2022-08-09T19:00:24.1687110Z ##[debug]jdkVersion=default
2022-08-09T19:00:24.1688780Z ##[debug]jdkArchitecture=x86
2022-08-09T19:00:24.1690300Z ##[debug]Agent.Version=2.206.1
2022-08-09T19:00:24.2228130Z ##[debug]Processed: ##vso[telemetry.publish area=TaskHub;feature=XamarinAndroid]{"jdkVersion":"default"}
2022-08-09T19:00:24.2229730Z ##[debug]msbuildLocationMethod=version
2022-08-09T19:00:24.2230530Z ##[debug]msbuildLocation=undefined
2022-08-09T19:00:24.2231240Z ##[debug]msbuildVersion=latest
2022-08-09T19:00:24.2232640Z ##[debug]which 'msbuild'
2022-08-09T19:00:24.2233820Z ##[debug]found: '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild'
2022-08-09T19:00:24.2235800Z ##[debug]which '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild'
2022-08-09T19:00:24.2237100Z ##[debug]found: '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild'
2022-08-09T19:00:24.2238190Z ##[debug]/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild arg: ["/version","/nologo"]
2022-08-09T19:00:24.2239740Z ##[debug]exec tool: /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild
2022-08-09T19:00:24.2240550Z ##[debug]arguments:
2022-08-09T19:00:24.2241190Z ##[debug]   /version
2022-08-09T19:00:24.2241940Z ##[debug]   /nologo
2022-08-09T19:00:24.2242510Z [command]/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild /version /nologo
2022-08-09T19:00:24.3763570Z ##[debug]Exit code 0 received from tool '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild'
2022-08-09T19:00:24.3770360Z ##[debug]STDIO streams have closed for tool '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild'
2022-08-09T19:00:24.3784350Z ##[debug]Build tool path = /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild
2022-08-09T19:00:24.3789270Z ##[debug]system.defaultWorkingDirectory=/Users/runner/work/8/s
2022-08-09T19:00:24.3790450Z ##[debug]defaultRoot: '/Users/runner/work/8/s'
2022-08-09T19:00:24.3791550Z ##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
2022-08-09T19:00:24.3792760Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'false'
2022-08-09T19:00:24.3793870Z ##[debug]findOptions.followSymbolicLinks: 'false'
2022-08-09T19:00:24.3794920Z ##[debug]matchOptions.debug: 'false'
2022-08-09T19:00:24.3795950Z ##[debug]matchOptions.nobrace: 'true'
2022-08-09T19:00:24.3796980Z ##[debug]matchOptions.noglobstar: 'false'
2022-08-09T19:00:24.3798050Z ##[debug]matchOptions.dot: 'true'
2022-08-09T19:00:24.3799070Z ##[debug]matchOptions.noext: 'false'
2022-08-09T19:00:24.3800090Z ##[debug]matchOptions.nocase: 'false'
2022-08-09T19:00:24.3801120Z ##[debug]matchOptions.nonull: 'false'
2022-08-09T19:00:24.3802150Z ##[debug]matchOptions.matchBase: 'false'
2022-08-09T19:00:24.3803180Z ##[debug]matchOptions.nocomment: 'false'
2022-08-09T19:00:24.3804220Z ##[debug]matchOptions.nonegate: 'false'
2022-08-09T19:00:24.3805260Z ##[debug]matchOptions.flipNegate: 'false'
2022-08-09T19:00:24.3806430Z ##[debug]pattern: '/Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj'
2022-08-09T19:00:24.3823130Z ##[debug]findPath: '/Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj'
2022-08-09T19:00:24.3825830Z ##[debug]statOnly: 'true'
2022-08-09T19:00:24.3827020Z ##[debug]found 1 paths
2022-08-09T19:00:24.3828290Z ##[debug]applying include pattern
2022-08-09T19:00:24.3931540Z ##[debug]1 matches
2022-08-09T19:00:24.3933150Z ##[debug]1 final results
2022-08-09T19:00:24.4035310Z ##[debug]which '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild'
2022-08-09T19:00:24.4138250Z ##[debug]found: '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild'
2022-08-09T19:00:24.4240710Z ##[debug]/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild arg: /Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj
2022-08-09T19:00:24.4345380Z ##[debug]/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild arg: /t:PackageForAndroid
2022-08-09T19:00:24.4448870Z ##[debug]/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild arg: /p:OutputPath=/Users/runner/work/8/b/release/Test
2022-08-09T19:00:24.4552280Z ##[debug]/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild arg: /p:Configuration=release
2022-08-09T19:00:24.4652250Z ##[debug]exec tool: /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild
2022-08-09T19:00:24.4752970Z ##[debug]arguments:
2022-08-09T19:00:24.4855070Z ##[debug]   /Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj
2022-08-09T19:00:24.4957190Z ##[debug]   /t:PackageForAndroid
2022-08-09T19:00:24.5059260Z ##[debug]   /p:OutputPath=/Users/runner/work/8/b/release/Test
2022-08-09T19:00:24.5161730Z ##[debug]   /p:Configuration=release
2022-08-09T19:00:24.5253760Z [command]/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild /Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj /t:PackageForAndroid /p:OutputPath=/Users/runner/work/8/b/release/Test /p:Configuration=release
2022-08-09T19:00:24.6689170Z Microsoft (R) Build Engine version 16.10.1 for Mono
2022-08-09T19:00:24.6794270Z Copyright (C) Microsoft Corporation. All rights reserved.
2022-08-09T19:00:24.6892110Z 
2022-08-09T19:00:24.9650520Z Build started 8/9/2022 7:00:24 PM.
2022-08-09T19:00:25.8603920Z Project "/Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj" on node 1 (PackageForAndroid target(s)).
2022-08-09T19:00:25.8619330Z _CreateStampDirectory:
2022-08-09T19:00:25.8620130Z   Creating directory "obj/release/stamp/".
2022-08-09T19:00:26.9486520Z _ResolveAndroidTooling:
2022-08-09T19:00:26.9487330Z   Found Java SDK version 11.0.16.
2022-08-09T19:00:27.9259870Z   Found Java SDK version 11.0.16.
2022-08-09T19:00:28.3432200Z /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(278,5): error XA0000: Could not determine API level for $(TargetFrameworkVersion) of 'v12.1'. [/Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj]
2022-08-09T19:00:28.3496790Z Done Building Project "/Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj" (PackageForAndroid target(s)) -- FAILED.
2022-08-09T19:00:28.3760370Z 
2022-08-09T19:00:28.3761920Z Build FAILED.
2022-08-09T19:00:28.3782770Z 
2022-08-09T19:00:28.3791030Z "/Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj" (PackageForAndroid target) (1) ->
2022-08-09T19:00:28.3792220Z (_ResolveAndroidTooling target) -> 
2022-08-09T19:00:28.3793710Z   /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(278,5): error XA0000: Could not determine API level for $(TargetFrameworkVersion) of 'v12.1'. [/Users/runner/work/8/s/Mobile/MyApp/MyApp.Android/MyApp.Android.csproj]
2022-08-09T19:00:28.3794380Z 
2022-08-09T19:00:28.3794680Z     0 Warning(s)
2022-08-09T19:00:28.3794950Z     1 Error(s)
2022-08-09T19:00:28.3795490Z 
2022-08-09T19:00:28.3796300Z Time Elapsed 00:00:03.41
2022-08-09T19:00:28.4339820Z ##[debug]Exit code 1 received from tool '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild'
2022-08-09T19:00:28.4347400Z ##[debug]STDIO streams have closed for tool '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild'
2022-08-09T19:00:28.4380190Z ##[debug]task result: Failed
2022-08-09T19:00:28.4433500Z ##[error]Error: The process '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild' failed with exit code 1
See https://go.microsoft.com/fwlink/?LinkId=760847.
2022-08-09T19:00:28.4453720Z ##[debug]Processed: ##vso[task.issue type=error;]Error: The process '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild' failed with exit code 1%0ASee https://go.microsoft.com/fwlink/?LinkId=760847.
2022-08-09T19:00:28.4531090Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: The process '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild' failed with exit code 1%0ASee https://go.microsoft.com/fwlink/?LinkId=760847.
2022-08-09T19:00:28.4589770Z ##[section]Finishing: Android: Build Project - Test
```

**Comment by jonathanpeppers** [comment] 2022-08-09 19:16
@GreatBarrier86 I thought I saw you commenting on: https://github.com/xamarin/xamarin-android/issues/7233

I think this is duplicate of: https://github.com/actions/runner-images/issues/6038

The `macos-latest` image is broken, and I think you need to reinstall Xamarin.Android over top:
```
dotnet tool install --global boots 
boots --stable Xamarin.Android
```
I published a new stable version of `boots` today to try to help with this.

Let me know if that doesn't solve it? Thanks!

**Closed by jonathanpeppers** 2022-08-09 19:16 UTC
Labels: Area: App+Library Build, needs-triage

**Comment by GreatBarrier86** [comment] 2022-08-09 19:27
@jonathanpeppers, thanks. I did not realize this was the same issue. I did notice that it doesn't work for macOS 12 either so i wasn't sure if it was related. Thanks!

**Comment by GreatBarrier86** [comment] 2022-08-09 20:09
@jonathanpeppers, to confirm, your suggestion also resolved this issue as well. Just wanted to mention that in case someone else runs into the same issue. Thank you!
