### ISSUE TITLE
[Application] FullBackupContent is the wrong type

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#2386] opened 2018-11-05 16:46 UTC
I see that the `[Application]` attribute `FullBackupContent` member is `bool` but should be `string`:

https://developer.android.com/guide/topics/manifest/application-element#fullBackupContent

> VS bug [#723928](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/723928)

**Comment by mattleibow** [comment] 2018-11-05 16:56
I see this was processed quickly!

**Comment by JonDouglas** [comment] 2018-11-05 17:31
There seems to be a disconnect here. The API 28 docs state:

```
    <!-- Applications will set this in their manifest to opt-in to or out of full app data back-up
         and restore. Alternatively they can set it to an xml resource within their app that will
         be parsed by the BackupAgent to selectively backup files indicated within that xml. -->
    <attr name="fullBackupContent" format="reference|boolean" />
```

However the [documentation](https://developer.android.com/guide/topics/manifest/application-element#fullBackupContent) says it's a string

```
android:fullBackupContent="string"
```

Android Studio has the same behavior as us to which it accepts a boolean directly in autocompletion.

**Comment by jonathanpeppers** [comment] 2019-01-28 16:32
@mattleibow I think @JonDouglas's assessment is correct, and we don't need to do anything.

Let us know if there is a third value (in addition to true/false) you are trying to use and we should look into this further.

**Comment by brendanzagaeski** [comment] 2019-01-28 18:51
I might be misreading Jon Douglas's assessment, but I think we might still need to add a version of the property that takes a `string` so that users "can set it to an xml resource within their app."  I suspect we can't change the type of the existing property because that would introduce an API breakage, but maybe we can add a new `string` property that (when non-null) takes precedence over the `bool` property, and then we can add a build warning for when both properties are non-null.

**Comment by mattleibow** [comment] 2019-01-28 19:22
@brendanzagaeski is right - I actually hit this issue when porting a native sample and needed to set the value via a resource.

**Comment by tranb3r** [comment] 2022-04-14 10:44
This still needs to be fixed. Any update?

**Comment by jonathanpeppers** [comment] 2022-04-14 13:46
@tranb3r I'd recommend using `AndroidManifest.xml` directly for this one. Is there a reason that wouldn't work for you?

**Comment by tranb3r** [comment] 2022-04-14 14:40
Ok. 
But, if this is the official workaround, and if the issue is never going to be fixed, then maybe you should document it and close this issue.
Thanks

**Comment by jonathanpeppers** [comment] 2022-04-14 17:33
Yeah, we can close this, I didn't notice it was still open, thanks!

Anyone feel free to comment on this, if there is something we missed here.

**Closed by jonathanpeppers** 2022-04-14 17:33 UTC
Labels: bug
