### ISSUE TITLE
Missing android deploy log in output window of Visual Studio 2019 16.3.0 preview 2.0

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-android#3516] opened 2019-08-17 10:19 UTC
### Steps to Reproduce

1. New xamarin app for android (for example, blank xamarin forms for android)
2. Set build output verbosity to Normal in Visual Studio options
3. Deploy app to android emulator
4. Open build output window and look at the log

### Expected Behavior

The build output window should display the build log first, then the deploy log.

### Actual Behavior

The deploy log is missing.
Only these 3 lines are display for the deploy target:
2>Starting deployment to ....
2>Deploying to ...
2>Deployment was successful to ...

### Version Information

Issue is on Visual Studio 2019 16.3.0 preview 2.0.
No issue with Visual Studio 2019 16.2.2 (stable), the full deploy log is displayed.

**Comment by gmck** [comment] 2019-08-20 06:37
Even with diagnostic logging there is nothing re the deploy part

**Comment by dellis1972** [comment] 2019-08-20 12:02
@joj This looks like an IDE issue, where would be the best place to transfer this to?

**Comment by joj** [comment] 2019-08-20 14:58
We'll create an internal bug for this. We just confirmed it in testing.

**Comment by dellis1972** [comment] 2019-08-20 21:20
@joj what's the best thing to do with this issue? I'd rather not close it yet until we have a fix.

**Comment by joj** [comment] 2019-08-21 13:21
We have it linked from our issue.

**Comment by dellis1972** [comment] 2019-08-21 13:25
@gmck thanks for the bug report. As you will have seen our IDE team is looking into this issue. They will update this issue once they have a resolution/workaround.

**Comment by tranb3r** [comment] 2019-09-05 07:48
Is it fixed in Visual Studio 2019 16.3.0 preview 3.0 ? Looks like it is, but I'd like to have a confirmation... Thanks

**Comment by dellis1972** [comment] 2019-09-05 09:37
@joj can you confirm the fix went into 16.3.0 preview 3.0? (assuming we fixed it :P )

**Comment by gmck** [comment] 2019-09-09 02:16
@dellis1972 
Confirm that the diagnostic log in preview 3 looks really good.

**Comment by brendanzagaeski** [comment] 2019-09-25 07:12
Internal cross-referencing link for the Microsoft team:

> VS bug [<span>#</span>968839](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/968839)

**Comment by brendanzagaeski** [comment] 2019-09-25 07:17
*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included on Windows in Visual Studio 2019 version 16.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

**Closed by brendanzagaeski** 2019-09-25 07:17 UTC
