### ISSUE TITLE
System.IO.IOException: Sharing violation on path thrown when reading from an open stream

### ISSUE THREAD

**Issue by kyurkchyan** [xamarin/xamarin-android#3465] opened 2019-08-08 18:27 UTC
### Steps to Reproduce

1. Create Xamarin.iOS or Xamarin.Android project
2. Open a `Stream` and `StreamWriter` test.txt
3. Try to copy the file to another location without closing the stream

```
using(Stream outputStream = File.Open(testFile, FileMode.Append, FileAccess.Write, FileShare.Read))
using (StreamWriter outputFile = new StreamWriter(outputStream, encoding))
{
    for(int index = 0; index < 10; index++)
    {
        outputFile.WriteLine($"Log message {index}");
    }
    outputFile.Flush();
    File.Copy(testFile, archiveFile);
}
```

[SerilogSample.zip](https://github.com/xamarin/xamarin-android/files/3491786/SerilogSample.zip)

### Expected Behavior

`File.Copy` should be able to copy file to a new location

### Actual Behavior

The app will crash with `System.IO.IOException: Sharing violation on path` exception

### Details
Initially we found the issue while using Serilog file logging. In our solution we have a logic to copy the logs to a new location for zipping and uploading. Everything was working fine until we updated to the latest version of the Visual Studio and Xamarin. After doing some trials I pinpointed the issue using the above mentioned steps. In the sample project I have 3 targets - Xamarin.iOS, Xamarin.Android and .NET Core console. The app will crash on first 2, but work perfectly fine on Console target both Windows & Mac

### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.2.2 (build 21)
Installation UUID: 21f35cb0-ffca-4f2b-b96d-fc41cb3325af
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000319

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.319 (2019-02/52203786470) (64-bit)
	Package version: 600000319

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.5
	2.2.4
	2.2.1
	2.1.9
	2.1.2
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.2.204/Sdks
SDK Versions:
	2.2.204
	2.2.203
	2.2.103
	2.1.505
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/gagik/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 29.0.0 rc2

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/gagik/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-30 21:29:36 UTC

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802020021
Git revision: d2ffd09000c5d24a206b715b63d409e8e965689a
Build date: 2019-08-02 00:25:49+00
Build branch: release-8.2
Xamarin extensions: 4cc9cbbe68baaeb6bc654f36e057b1bd124f3f65

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by kyurkchyan** [comment] 2019-08-13 08:39
After more thorough investigation we've found a workaround and instead of using `File.Copy` we use the following code for copying files

```
public static async Task CopyFileAsync(string sourceFilePath, string destinationFilePath)
{
    using(FileStream sourceStream = File.Open(sourceFilePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
    using(FileStream destinationStream = File.Create(destinationFilePath))
    {
        await sourceStream.CopyToAsync(destinationStream);
    }
}
```

The crucial aspect in here is that you use `File.Open` method with parameter `FileShare.ReadWrite` to make this stream work nicely with open write stream. Though performance testing revealed this approach to be 5 times slower than `File.Copy` in our system the largest file is 30MB and it's still matter of milliseconds to do the copy on Android device, so the workaround was acceptable in our scenario. I'm sure If I spend several hours I'd be able to optimize the stream copy process a bit, but it's not going to be as optimal as `File.Copy` ever. 

But the issue and questions still remain
1. Why does the original sample work on Console but not on Xamarin?
2. Why did this work on older Xamarin version?

**Comment by brendanzagaeski** [comment] 2019-08-13 23:47
Thanks for the report and the test case! This behavior is under investigation in <https://github.com/mono/mono/issues/16032> and <https://github.com/xamarin/xamarin-android/issues/3426>. I'll close this issue as a duplicate of <https://github.com/xamarin/xamarin-android/issues/3426> for further tracking.

**Comment by brendanzagaeski** [comment] 2019-08-13 23:49
Duplicate of #3426

**Closed by brendanzagaeski** 2019-08-13 23:49 UTC

**Comment by kyurkchyan** [comment] 2019-08-14 07:52
@brendanzagaeski thanks for the info

**Comment by brendanzagaeski** [comment] 2019-10-01 18:20
*Correction of status:*

It tunehttps://github.com/xamarin/xamarin-android/issues/3426 

https://github.com/mono/mono/issues/16032

**Comment by brendanzagaeski** [comment] 2019-10-01 18:45
*Correction of status:*

Further investigation has shown that the `System.UnauthorizedAccessException` observed in <https://github.com/xamarin/xamarin-android/issues/3426> has a different underlying cause than the `System.IO.IOException: Sharing violation on path` exception on this issue <https://github.com/xamarin/xamarin-android/issues/3465>.

This issue matches <https://github.com/mono/mono/issues/16032>, but it does not match <https://github.com/xamarin/xamarin-android/issues/3426>.

The fix for <https://github.com/mono/mono/issues/16032> is now available in Xamarin.Android 10.0.0.43 (via <https://github.com/xamarin/xamarin-android/commit/359f2f815530e4b61fcd4c50eeaeb51bd232d099>), so I am updating this issue with that release information.

Thanks once again for this report!

* * *

A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.0.0.43

Fix included on Windows in Visual Studio 2019 version 16.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
