### ISSUE TITLE
Xamarin Android - New Created Tabbed App crashes after changing newly added ImageView's src attribute in VS2019.

### ISSUE THREAD

**Issue by GintasS** [xamarin/xamarin-android#3021] opened 2019-04-24 12:41 UTC
### Steps to Reproduce

1. Open VS 2019.
2. Create new Project - Xamarin.Android (Tabbed App)
3. Add ImageView control and change it's src attribute via Source editor.

### Expected Behavior
Loads custom image from drawable path.
![image](https://user-images.githubusercontent.com/20372363/56659765-9dd38480-66a6-11e9-87b1-57c77af0687a.png)

### Actual Behavior
Produces following errors:
![image](https://user-images.githubusercontent.com/20372363/56659532-10903000-66a6-11e9-987f-29a840733d8d.png)

(Designer error):
![image](https://user-images.githubusercontent.com/20372363/56659840-c78cab80-66a6-11e9-91bb-e98c0e74c2ae.png)

### Version Information
![image](https://user-images.githubusercontent.com/20372363/56659569-2867b400-66a6-11e9-9c72-2255de63e022.png)
![image](https://user-images.githubusercontent.com/20372363/56659593-34ec0c80-66a6-11e9-82ff-dff1f9df2daa.png)

### Log File
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin|Information|0|Xamarin - 16.0.0.515-d16-0+a3502d929
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin.VisualStudio.Android.XamarinAndroidPackage|Warning|0|Initializing Xamarin.VisualStudio.Android.XamarinAndroidPackage
Xamarin.VisualStudio.Android.AndroidVirtualDeviceProvider|Error|0|an error occurred loading avd `A`, the system image does not exists
Xamarin.VisualStudio.Android.AndroidVirtualDeviceProvider|Error|0|an error occurred loading avd `Android_Accelerated_x86_Oreo`, the system image does not exists
Xamarin.VisualStudio.Android.AndroidVirtualDeviceProvider|Error|0|an error occurred loading avd `Nexus_5X_API_25`, the system image does not exists
Xamarin.VisualStudio.Android.AndroidVirtualDeviceProvider|Error|0|an error occurred loading avd `Nexus_5X_API_25_2`, the system image does not exists
Xamarin.VisualStudio.Android.AndroidVirtualDeviceProvider|Error|0|an error occurred loading avd `Test`, the system image does not exists
Xamarin.VisualStudio.ProjectSystem.PackageServices|Warning|0|Failed to Restore Nuget packages for project <deleted path for security by me>\Visual Studio 2017\Projects\Test123\Test123\Test123.csproj.

.monodroid file:

MonoDroidLog: Information: 0: [I:]:                     Found Xamarin.Android 9.2.0.5
MonoDroidLog: Information: 0: [I:sdk]:                  Runtime path: <deleted path for security reasons>
MonoDroidLog: Information: 0: [I:sdk]:                  Framework path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0
MonoDroidLog: Information: 0: [I:]:                     Tracking android devices started
MonoDroidLog: Information: 0: [D:]:                     Tracking avd started
MonoDroidLog: Information: 0: [D:]:                     avd watcher *.ini path: '<deleted path for security reasons>'
MonoDroidLog: Information: 0: [D:]:                     TrackDeviceTask got: PMF4C17429003570	device
MonoDroidLog: Information: 0: [I:]:                     Got new device list from adb with 1 devices
MonoDroidLog: Information: 0: [D:]:                     avd watcher: got device list from avd with 5 devices
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 getprop
MonoDroidLog: Error: 0: [E:]:                     an error occurred loading avd `A`, the system image does not exists
MonoDroidLog: Error: 0: [E:]:                     an error occurred loading avd `Android_Accelerated_x86_Oreo`, the system image does not exists
MonoDroidLog: Error: 0: [E:]:                     an error occurred loading avd `Nexus_5X_API_25`, the system image does not exists
MonoDroidLog: Error: 0: [E:]:                     an error occurred loading avd `Nexus_5X_API_25_2`, the system image does not exists
MonoDroidLog: Error: 0: [E:]:                     an error occurred loading avd `Test`, the system image does not exists
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk\`, result=True
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidNdkLocation: `\`, result=False
MonoDroidLog: Information: 0: [I:]:                     Looking for Android NDK...
MonoDroidLog: Information: 0: [I:]:                     Looking for Android SDK...
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True
MonoDroidLog: Information: 0: [D:]:                     ValidateJavaSdkLocation: `C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\`, result=True
MonoDroidLog: Information: 0: [I:]:                     Found Xamarin.Android 9.2.0.5
MonoDroidLog: Information: 0: [I:]:                     Looking for Android SDK...
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 am broadcast -a "mono.android.intent.action.PACKAGE_VERSIONS" -e "packages" "Mono.Android.DebugRuntime,Mono.Android.Platform.ApiLevel_27,com.companyname.Test123" -n "Mono.Android.DebugRuntime/com.xamarin.mono.android.PackageVersions"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 cat /data/system/packages.xml
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 cat /dbdata/system/packages.xml
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 "pm" "list" "packages" "-f"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 getprop
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 am broadcast -a "mono.android.intent.action.PACKAGE_VERSIONS" -e "packages" "Mono.Android.DebugRuntime,Mono.Android.Platform.ApiLevel_27,com.companyname.Test123" -n "Mono.Android.DebugRuntime/com.xamarin.mono.android.PackageVersions"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 pm install -d "/data/local/tmp/com.companyname.Test123-Signed.apk"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 rm "/data/local/tmp/com.companyname.Test123-Signed.apk"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 "pm" "path" "com.companyname.Test123"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 "echo" "-n" "${EMULATED_STORAGE_SOURCE}"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 "echo" "-n" "${EMULATED_STORAGE_TARGET}"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 am broadcast -a "mono.android.intent.action.EXTERNAL_STORAGE_DIRECTORY" -n "Mono.Android.DebugRuntime/com.xamarin.mono.android.ExternalStorageDirectory"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 cd /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__ || exit 1; for f in *; do echo $f; done;
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Enumerating remote files
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Determining required operations
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Creating directories
MonoDroidLog: Information: 0: [D:NotifySync]:           CreateDirectory  /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__ 0
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Uploading files
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons> /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Test123.dll 88064
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Arch.Core.Common.dll 35440
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Arch.Lifecycle.Common.dll 55928
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Arch.Lifecycle.Runtime.dll 31872
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.Animated.Vector.Drawable.dll 77456
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.Annotations.dll 151672
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.Compat.dll 1699432
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.Core.UI.dll 545896
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.Core.Utils.dll 228976
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.CustomTabs.dll 162928
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.Design.dll 744552
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.Fragment.dll 409712
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.Media.Compat.dll 733304
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.Transition.dll 322680
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.v7.AppCompat.dll 1995896
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.v7.RecyclerView.dll 851576
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>/storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Android.Support.Vector.Drawable.dll 61056
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile C:\Users\Gintautas\Documents\Visual Studio 2017\Projects\Test123\Test123\obj\Debug\81\android\assets\Xamarin.Essentials.dll.mdb /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/Xamarin.Essentials.dll.mdb 50790
MonoDroidLog: Information: 0: [D:NotifySync]:           CopyFile <deleted path for security reasons>
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Upload completed
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Enumerating remote files
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Determining required operations
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Creating directories
MonoDroidLog: Information: 0: [D:NotifySync]:           SkipCreateDirectory  /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__ 0
MonoDroidLog: Information: 0: [D:NotifySync]:           CreateDirectory  /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/lib 0
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Uploading files
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Upload completed
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Enumerating remote files
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Determining required operations
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Creating directories
MonoDroidLog: Information: 0: [D:NotifySync]:           SkipCreateDirectory  /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__ 0
MonoDroidLog: Information: 0: [D:NotifySync]:           CreateDirectory  /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/dexes 0
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Uploading files
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Upload completed
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Enumerating remote files
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Determining required operations
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Creating directories
MonoDroidLog: Information: 0: [D:NotifySync]:           SkipCreateDirectory  /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__ 0
MonoDroidLog: Information: 0: [D:NotifySync]:           CreateDirectory  /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/packaged 0
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Uploading files
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Upload completed
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Enumerating remote files
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Determining required operations
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Creating directories
MonoDroidLog: Information: 0: [D:NotifySync]:           SkipCreateDirectory  /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__ 0
MonoDroidLog: Information: 0: [D:NotifySync]:           CreateDirectory  /storage/emulated/0/Android/data/com.companyname.Test123/files/.__override__/typemaps 0
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Uploading files
MonoDroidLog: Information: 0: [D:NotifyPhase]:          Upload completed
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 date +%s
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 setprop "debug.mono.extra" "debug=127.0.0.1:29212:29213,timeout=1556108815,loglevel=0,server=y"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 getprop
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 "echo" "-n" "${EMULATED_STORAGE_SOURCE}"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 "echo" "-n" "${EMULATED_STORAGE_TARGET}"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 am broadcast -a "mono.android.intent.action.EXTERNAL_STORAGE_DIRECTORY" -n "Mono.Android.DebugRuntime/com.xamarin.mono.android.ExternalStorageDirectory"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.Test123/md5fb9606f2c73fa0db52fc153b8c1b7d4d.MainActivity"
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 ps -A
MonoDroidLog: Information: 0: [D:GetLogCat]:            logcat -v time
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 logcat -v time
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 am force-stop com.companyname.Test123
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 setprop "debug.mono.connect" ""
MonoDroidLog: Information: 0: [I:]:                     Tracking android devices stopped

**Comment by GintasS** [comment] 2019-04-24 12:43
Also, if I change the path to this:(without the "android:")
![image](https://user-images.githubusercontent.com/20372363/56660125-7b8e3680-66a7-11e9-942b-f7df36fc228c.png)

It produces the following errors:
![image](https://user-images.githubusercontent.com/20372363/56660146-91036080-66a7-11e9-89c0-b33e37cb3e64.png)

Log:
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin|Information|0|Xamarin - 16.0.0.515-d16-0+a3502d929
Xamarin.VisualStudio.TastyPackage|Information|0|Hooked up SDB tracing adapter
Xamarin.VisualStudio.TastyPackage|Information|0|Initialization finished
Xamarin.VisualStudio.Android.XamarinAndroidPackage|Warning|0|Initializing Xamarin.VisualStudio.Android.XamarinAndroidPackage
Xamarin.VisualStudio.Android.AndroidVirtualDeviceProvider|Error|0|an error occurred loading avd `A`, the system image does not exists
Xamarin.VisualStudio.Android.AndroidVirtualDeviceProvider|Error|0|an error occurred loading avd `Android_Accelerated_x86_Oreo`, the system image does not exists
Xamarin.VisualStudio.Android.AndroidVirtualDeviceProvider|Error|0|an error occurred loading avd `Nexus_5X_API_25`, the system image does not exists
Xamarin.VisualStudio.Android.AndroidVirtualDeviceProvider|Error|0|an error occurred loading avd `Nexus_5X_API_25_2`, the system image does not exists
Xamarin.VisualStudio.Android.AndroidVirtualDeviceProvider|Error|0|an error occurred loading avd `Test`, the system image does not exists

.monodroid log file:

MonoDroidLog: Information: 0: [I:]:                     Found Xamarin.Android 9.2.0.5
MonoDroidLog: Information: 0: [I:sdk]:                  Runtime path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android
MonoDroidLog: Information: 0: [I:sdk]:                  Framework path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0
MonoDroidLog: Information: 0: [I:]:                     Tracking android devices started
MonoDroidLog: Information: 0: [D:]:                     Tracking avd started
MonoDroidLog: Information: 0: [D:]:                     TrackDeviceTask got: PMF4C17429003570	device
MonoDroidLog: Information: 0: [D:]:                     avd watcher *.ini path: 'C:\Users\Gintautas\.android\avd'
MonoDroidLog: Information: 0: [I:]:                     Got new device list from adb with 1 devices
MonoDroidLog: Information: 0: [D:RunShellCommand]:      PMF4C17429003570 getprop
MonoDroidLog: Information: 0: [D:]:                     avd watcher: got device list from avd with 5 devices
MonoDroidLog: Error: 0: [E:]:                     an error occurred loading avd `A`, the system image does not exists
MonoDroidLog: Error: 0: [E:]:                     an error occurred loading avd `Android_Accelerated_x86_Oreo`, the system image does not exists
MonoDroidLog: Error: 0: [E:]:                     an error occurred loading avd `Nexus_5X_API_25`, the system image does not exists
MonoDroidLog: Error: 0: [E:]:                     an error occurred loading avd `Nexus_5X_API_25_2`, the system image does not exists
MonoDroidLog: Error: 0: [E:]:                     an error occurred loading avd `Test`, the system image does not exists
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk\`, result=True
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidNdkLocation: `\`, result=False
MonoDroidLog: Information: 0: [I:]:                     Looking for Android NDK...
MonoDroidLog: Information: 0: [I:]:                     Looking for Android SDK...
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True
MonoDroidLog: Information: 0: [D:]:                     ValidateJavaSdkLocation: `C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\`, result=True
MonoDroidLog: Information: 0: [I:]:                     Found Xamarin.Android 9.2.0.5
MonoDroidLog: Information: 0: [I:]:                     Looking for Android SDK...
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True
MonoDroidLog: Information: 0: [D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True

**Comment by dellis1972** [comment] 2019-04-26 09:20
Thanks for the bug report. Some of the errors look like this of #3007 which is being worked on via PR #3025. I believe they are from the design time build and are not related to the runtime issue. 

That leave the drawable issues. You set the `src` to `@android:drawable/1`. What that will do is look for a drawable called `1` in the android system. No such such a drawable exists. Also `@drawable/1` will only exist if you add a drawable called `1` to your app. This is not mentioned in the steps to reproduce.

The list of available drawables in the `android` package are https://developer.android.com/reference/android/R.drawable.html 

When I follow the steps listed I get the following error

<img width="1193" alt="Error" src="https://user-images.githubusercontent.com/810617/56797182-02f4ba80-680c-11e9-8a34-dbcf220c2e08.png">

I still get the `LinkAssemblies` error which has already been fixed via PR #2795. This should be in the next release of VS 2019. 

Changing the `android:src` to `@android:drawable/star_on` the build error will go away. This is because star_on` is one of the drawables provided by the [android](https://developer.android.com/reference/android/R.drawable.html#star_on) package. 

So if you want o use `1` as a resource you will need to add a drawable of that name (eg. `1.png`) to the `drawable` folder in your `Resources` directory.

I don't think this is a bug we need to fix since its already been handled via #3025 and #2795 . So I will close this issue for now. If you are still having problems please reopen.

**Closed by dellis1972** 2019-04-26 09:20 UTC
