### ISSUE TITLE
No longer able to access `Android.Widget.ChoiceMode` when compiling against v2.3 in d15-6

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1170] opened 2018-01-09 18:20 UTC
It appears that the ChoiceMode property of `Android.Widget.AbsListView` https://developer.android.com/reference/android/widget/AbsListView.html#setChoiceMode(int) is no longer accessible when comping against v2.3. This appears to be a regression introduced in d15-6.

### Steps to Reproduce

1. Open the AccessoryViews monodroid sample - https://github.com/xamarin/monodroid-samples/tree/master/AccessoryViews
2. Ensure you have SDK Platform Version 10 (2.3) installed, and attempt to build the project. 

### Expected Behavior
The project builds without error when targeting v2.3. This succeeds using d15-5 builds:
https://gist.githubusercontent.com/pjcollins/22ca1e9064404355a0d88e72bb25d929/raw/3d07327d36390d523ac74e1b7d32af4fc63c73f5/15.5%2520Output

### Actual Behavior
The project fails to build against monodroid/d15-6:
http://xqa.blob.core.windows.net/gist/report-c995421b88984113bef0729590cdf1cf.txt
```
(CoreCompile target) -> 
  HomeScreen.cs(31,16): error CS1061: 'ListView' does not contain a definition for 'ChoiceMode' and no extension method 'ChoiceMode' accepting a first argument of type 'ListView' could be found (are you missing a using directive or an assembly reference?) [/Users/xamarinqa/myagent/_work/r1/a/monodroid-samples/AccessoryViews/AccessoryViews.csproj]
  HomeScreen.cs(31,29): error CS0234: The type or namespace name 'ChoiceMode' does not exist in the namespace 'Android.Widget' (are you missing an assembly reference?) [/Users/xamarinqa/myagent/_work/r1/a/monodroid-samples/AccessoryViews/AccessoryViews.csproj]
```
Interestingly enough, if I update the Target Framework version of my project to v4.0.3 or higher, the type can be resolved and the project builds successfully.

### Version Information

https://gist.github.com/pjcollins/03e44af172a79acd68ccf2d25dd129ae

**Comment by atsushieno** [comment] 2018-01-10 10:52
The Google documentation is a liar: there is NO setChoiceMode() in API Level 10.

![image](https://user-images.githubusercontent.com/53929/34768997-cf13310e-f63f-11e7-8938-6e06466d7221.png)

**Comment by atsushieno** [comment] 2018-01-10 10:55
Therefore this is a bugfix. monodroid-samples should be fixed to not invoke nonexistent method.

**Comment by pjcollins** [comment] 2018-01-10 16:43
@atsushieno I am not sure about this, perhaps your local documentation is the one that is lying...

Here is a java port that has a min, target, and compile version of 10, and successfully uses the following code:
```
    String[] items = new String[] { "Vegetables", "Fruits", "Flower Buds", "Legumes", "Bulbs", "Tubers" };
    setListAdapter(new ArrayAdapter<String>(this, android.R.layout.simple_list_item_checked, items));
    ListView lv = (ListView)findViewById(android.R.id.list);
    lv.setChoiceMode(1);
```
[LVChoiceModeTest.zip](https://github.com/xamarin/xamarin-android/files/1619665/LVChoiceModeTest.zip)

**Comment by atsushieno** [comment] 2018-01-10 16:55
Why don't just check sources? 

https://android.googlesource.com/platform/frameworks/base/+/android-2.3.7_r1/core/java/android/widget/AbsListView.java

**Comment by jonpryor** [comment] 2018-01-10 17:53
@atsushieno: It's not `AbsListView`, it's [`ListView`](https://android.googlesource.com/platform/frameworks/base/+/android-2.3.7_r1/core/java/android/widget/ListView.java), which *does* contain a [`ListView.getChoiceMode()` method](https://android.googlesource.com/platform/frameworks/base/+/android-2.3.7_r1/core/java/android/widget/ListView.java#3454).

Furthermore, [`src/Mono.Android/Profiles/api-10.xml.in`](https://github.com/xamarin/xamarin-android/blob/18afc2c3da217b2a0d7fd4c582a5a5bd51b256bb/src/Mono.Android/Profiles/api-10.xml.in) contains a `ListView.getChoiceMode()` method:

```xml
    <class abstract="false" deprecated="not deprecated" extends="android.widget.AbsListView" extends-generic-aware="android.widget.AbsListView" final="false" name="ListView" static="false" visibility="publi
      ...
      <method abstract="false" deprecated="not deprecated" final="false" name="getChoiceMode" native="false" return="int" static="false" synchronized="false" visibility="public">
```

The oddity here is that the d15-6 binding of API-10 in `Mono.Android.dll` doesn't contain *any* mention of `ChoiceMode`:

```bash
# From extracted output of xamarin.android-8.2.0-4.pkg
$ monodis --method .../lib/xbuild-frameworks/MonoAndroid/v2.3/Mono.Android.dll | grep ChoiceMode
# no matches
```

Compare to e.g. 8.1:

```bash
$ monodis --method /Library/Frameworks/Xamarin.Android.framework/Versions/8.1.2-0/lib/xbuild-frameworks/MonoAndroid/v2.3/Mono.Android.dll | grep ChoiceMode
28486: default class [mscorlib]System.Delegate GetGetChoiceModeHandler ()  (param: 32420 impl_flags: cil managed )
28487: default int32 n_GetChoiceMode (native int jnienv, native int native__this)  (param: 32420 impl_flags: cil managed )
28488: default class [mscorlib]System.Delegate GetSetChoiceMode_IHandler ()  (param: 32422 impl_flags: cil managed )
28489: default void n_SetChoiceMode_I (native int jnienv, native int native__this, int32 native_choiceMode)  (param: 32422 impl_flags: cil managed )
28490: instance default valuetype Android.Widget.ChoiceMode get_ChoiceMode ()  (param: 32425 impl_flags: cil managed )
28491: instance default void set_ChoiceMode (valuetype Android.Widget.ChoiceMode 'value')  (param: 32425 impl_flags: cil managed )
```

I do not currently understand where the `ListView.ChoiceMode` property went: `Profiles/api-10.xml.in` mentions it, [`methodmap.csv` mentions it](https://github.com/xamarin/xamarin-android/blob/master/src/Mono.Android/methodmap.csv#L453)...

...and I think I have the cause:

```
$ pwd
…/xamarin-android/src/Mono.Android

# Build API-10:
$ xbuild /v:diag /p:AndroidFrameworkVersion=v2.3 /p:AndroidApiLevel=10 > b.txt
```

The resulting `b.txt` contains:

```
                warning BG8700: Unknown return type Android.Widget.ChoiceMode in method GetChoiceMode in managed type Android.Widget.ListView.
                warning BG8800: Unknown parameter type Android.Widget.ChoiceMode in method SetChoiceMode in managed type Android.Widget.ListView.
```

The cause of this bug is a301764a, which changed `Android.Widget.ChoiceMode` from being declared in [API-1](https://github.com/xamarin/xamarin-android/commit/a301764a#diff-774451c2472ebdc3ed09635da6c542e5L2995) to being declared in [API-15](https://github.com/xamarin/xamarin-android/commit/a301764a#diff-774451c2472ebdc3ed09635da6c542e5R2980).

**Comment by atsushieno** [comment] 2018-01-11 07:05
ChoiceMode was removed because they were generated from AbsListView fields which DOES NOT EXIST in API Level 10. And getChoiceMode() and setChoiceMode are removed because they expect NONEXISTENT enums.

Fortunately they are in ListView in API Level 10, so they can be generated from there.

Although, while I can build Mono.Android.dll for the profiles including android-10, `make framework-assemblies` fails and I cannot verify the entire build locally.

	Build FAILED.
	Errors:

	src/Xamarin.Android.NUnitLite/Xamarin.Android.NUnitLite.csproj: error : /sources/xamarin-android/src/Xamarin.Android.NUnitLite/Xamarin.Android.NUnitLite.csproj: /sources/xamarin-android/src/Xamarin.Android.NUnitLite/Xamarin.Android.NUnitLite.csproj could not import "$(OutputPath)\..\..\..\xbuild\Xamarin\Android\Xamarin.Android.CSharp.targets"

		 0 Warning(s)
		 1 Error(s)

**Comment by atsushieno** [comment] 2018-01-11 07:07
To make sure: (1) ChoiceMode being removed in API Level 10 was correct. (2) Leaving ListView.SetChoiceMode() and .GetChoiceMode() to point to non-existent enum *and* not converting ListView. flelds to ChoiceMode is wrong (only when both conditions are met).

**Closed** 2018-01-17 23:53 UTC
Labels: Area: Bindings, regression
