### ISSUE TITLE
App Bundle is unable to load libmonosgen-2.0.so

### ISSUE THREAD

**Issue by mikepotvin** [xamarin/xamarin-android#3739] opened 2019-10-03 20:45 UTC
```
monodroid	Please either set android:minSdkVersion >= 10 or use a build without the shared runtime (like default Release configuration).


monodroid	Do you have a shared runtime build of your app with AndroidManifest.xml android:minSdkVersion < 10 while running on a 64-bit Android 5.0 target? This combination is not supported.

monodroid	Cannot find 'libmonosgen-2.0.so'. Looked in the following locations:
  /data/app/com.alc.qamdd-nY2sAX5UokJhVgTyoELvYg==/base.apk!/lib/arm64-v8a
  /data/app/com.alc.qamdd-nY2sAX5UokJhVgTyoELvYg==/split_config.arm64_v8a.apk!/lib/arm64-v8a
  /data/app/com.alc.qamdd-nY2sAX5UokJhVgTyoELvYg==/split_config.xxxhdpi.apk!/lib/arm64-v8a

```

### Steps to Reproduce

1. Use `msbuild -restore` build .aab file
2. Use `java -jar bundletool.jar build-apks` to build apk file
3. use `java -jar bundletool.jar install-apks` to install apk file

### Expected Behavior
Application should run
### Actual Behavior
Application hangs on startup
### Version Information
Xamarin.Forms 4.2

Possibly related to [Similar Issue](https://github.com/xamarin/java.interop/pull/421)

**Comment by mikepotvin** [comment] 2019-10-03 20:46
@jonathanpeppers pinging Jonathan since he may be familiar with this issue.

**Comment by jonathanpeppers** [comment] 2019-10-03 21:42
@mikepotvin you shouldn't need to run `bundletool.jar` directly.

Can you just use the `Install` target?
```
> msbuild foo.android.csproj /t:Install
```
Then launch the app by tapping the icon?

**Comment by grendello** [comment] 2019-10-04 07:24
@mikepotvin We will need more information in order to identify the issue. It would be best if you could provide a small application which reproduces the issue, but should it not be possible could you please provide the following:

  * Contents of your `Properties/AndroidManifest.xml` file
  * Listing of your `.aab` archive (the archive is just a ZIP file, you can use any zip utility to generate the listing e.g. `unzip -l` on Unix systems or `7z -l` on any operating system)
  * Full binlog of your build process (build with `msbuild /bl` which will generate `msbuild.binlog` in your solution directory)

@jonathanpeppers tentatively assigning this to you and @dellis1972 since it may be related to the build process, please bounce back if it turns out to be a different cause.

**Comment by jonathanpeppers** [comment] 2019-11-11 17:58
@mikepotvin let us know if you can send more info. Closing for now, thanks!

**Closed by jonathanpeppers** 2019-11-11 17:58 UTC
Labels: Area: App+Library Build, need-info
