### ISSUE TITLE
Atfter change building resources from aapt to aapt2 Resource.Designer.cs are wrongly generated

### ISSUE THREAD

**Issue by losmacko** [xamarin/xamarin-android#3225] opened 2019-06-14 13:20 UTC
### Steps to Reproduce
Xamarin.Android > 8.3
1. Change building resources from aapt to aapt2 
2. Build solution
### Expected Behavior
Resources.Designer.cs members of class should have quite similar values 
### Actual Behavior
Values are changes. For example every member what have value 0 now have much diffrent value ex:
button_min_width = 0 change to button_min_width = 23232323.

This cause that layout elements currently are wrong displayed, mvvmcross binding didn' t work and so one.
### Version Information
This was reproduced on both Visual Studion on Windows and Visual studio for Mac.
Current Version Xamarin.Android 9.2.3
I think this is connected with changed of generator of Resource.Designer.cs
in Xamarin.Android.Common.targets:

```
<_UseManagedResourceGenerator Condition=" '$(_AndroidUseAapt2)' == 'True' ">True</_UseManagedResourceGenerator>
<_UseManagedResourceGenerator Condition=" '$(_UseManagedResourceGenerator)' == '' ">False</_UseManagedResourceGenerator>
```
And in  GenerateResourceDesigner.cs:

```
        // Parse out the resources from the R.java file
        CodeTypeDeclaration resources;
        if (UseManagedResourceGenerator) {
            var parser = new ManagedResourceParser () { Log = Log, JavaPlatformDirectory = javaPlatformDirectory, };
            resources = parser.Parse (ResourceDirectory, AdditionalResourceDirectories?.Select (x => x.ItemSpec), IsApplication, resource_fixup);
        } else {
            var parser = new JavaResourceParser () { Log = Log };
            resources = parser.Parse (JavaResgenInputFile, IsApplication, resource_fixup);

```

fragment of /obj/Debug/R.txt : 

```
int[] styleable MultiSelectListPreference { 0x010100b2, 0x010101f8, 0x7f040151, 0x7f040152 }
int styleable MultiSelectListPreference_android_entries 0
int styleable MultiSelectListPreference_android_entryValues 1
int styleable MultiSelectListPreference_entries 2
int styleable MultiSelectListPreference_entryValues 3
int[] styleable MvxBinding { 0x7f040001, 0x7f04000b }
int styleable MvxBinding_MvxBind 0
int styleable MvxBinding_MvxLang 1
int[] styleable MvxControl { 0x7f04000d }
int styleable MvxControl_MvxTemplate 0
int[] styleable MvxExpandableListView { 0x7f040005 }
int styleable MvxExpandableListView_MvxGroupItemTemplate 0
int[] styleable MvxHorizontalGridView { 0x7f040000 }
int styleable MvxHorizontalGridView_FocusFirstChildOnLaidOut 0
int[] styleable MvxListView { 0x7f040002, 0x7f04000a }
int styleable MvxListView_MvxDropDownItemTemplate 0
```

and this is output of Resource.Designer.cs:
```
			// aapt resource value: 0x3
			public const int MultiSelectListPreference_entryValues = 3;
			
			public static int[] MvxBinding = new int[] {
					2130968577,
					2130968587};
			
			// aapt resource value: 0x7F010830
			public const int MvxBinding_MvxBind = 2130774064;
			
			// aapt resource value: 0x1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130968589};
			
			// aapt resource value: 0x7F010833
			public const int MvxControl_MvxTemplate = 2130774067;
			
			public static int[] MvxExpandableListView = new int[] {
					2130968581};
			
			// aapt resource value: 0x7F010835
			public const int MvxExpandableListView_MvxGroupItemTemplate = 2130774069;
			
			public static int[] MvxHorizontalGridView = new int[] {
					2130968576};
			
			// aapt resource value: 0x7F010837
			public const int MvxHorizontalGridView_FocusFirstChildOnLaidOut = 2130774071;
			
			public static int[] MvxListView = new int[] {
					2130968578,
					2130968586};
			
			// aapt resource value: 0x7F010839
			public const int MvxListView_MvxDropDownItemTemplate = 2130774073;


```

**Comment by losmacko** [comment] 2019-06-14 16:11
I think problem is touching stylable resources. In file _ManagedResourceParser.cs_  function _public CodeTypeDeclaration Parse(...)_ is forgotten that stylable resource could have 0 value and in that case new value is generated if my thoughts are good ;)

**Comment by brendanzagaeski** [comment] 2019-06-15 05:33
Thanks for the report! I believe this matches <https://github.com/xamarin/xamarin-android/issues/3049>. The candidate fix for that issue is included in the latest preview versions Xamarin.Android 9.4.0.17 and higher. If by chance you have an environment where you already have or don't mind installing the side-by-side Visual Studio 2019 version 16.2 Preview 2 on Windows, then you can double-check to make sure the fix resolves all the cases you are seeing too.

I'll tentatively close this as a duplicate of #3049, but feel free to comment back if you are seeing cases in Xamarin.Android 9.4.0.17 or higher that are still misbehaving, and I'll reopen this. Thanks!

**Closed by brendanzagaeski** 2019-06-15 05:33 UTC

**Comment by losmacko** [comment] 2019-06-15 08:06
How to install side by side version of preview release on Mac?

**Comment by brendanzagaeski** [comment] 2019-06-16 23:16
On Mac, the preview versions temporarily *replace* the previously installed versions instead of installing side-by-side. So you would temporarily switch to the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update), and then switch back to the **Stable** channel if you needed to to re-install the non-Preview versions.

(In theory you could also experiment with running just the *$HOME/Library/Caches/VisualStudio/8.\*/TempDownload/xamarin.android-9.4.0.34.pkg* preview installer package after the Visual Studio for Mac updater downloads it to that location (before you click the **Restart and Install Update** button in the updater). Then if you needed to switch back to the **Stable** channel, Visual Studio for Mac would only need to reinstall that one package. But using that individual package by itself is an untested scenario, so it's recommended to keep the Visual Studio for Mac and Mono Framework MDK versions aligned with the installed Xamarin.Android version when possible.)
