### ISSUE TITLE
[Designer] Designer crashed when setting the ttf files for TextView control.

### ISSUE THREAD

**Issue by SanthiyaArulsamy** [xamarin/xamarin-android#3254] opened 2019-06-19 16:41 UTC
### Steps to Reproduce

1. Add the custom library with TextView.
2. Add the custom font style for TextView(as like  SetTypeface(Typeface.CreateFromAsset(this.Context.Assets, "drilldown.ttf"), TypefaceStyle.Bold);)
3. Drag and drop the custom control in axml page.
4. Now the designer crashed with below issues
![image](https://user-images.githubusercontent.com/28334651/59783994-09b91e80-92df-11e9-8088-b9598800707b.png)

**Comment by pjcollins** [comment] 2019-06-20 21:17
This seems to be working fine for me using VS 16.1:

![image](https://user-images.githubusercontent.com/2000163/59880980-6e768680-937c-11e9-88ca-796443085d27.png)

I've attached a simple reproduction that I think matches your description Have you made sure to set the build action of your `.ttf` file to `AndroidAsset`? Does my reproduction otherwise differ from yours? If so, could you attach a solution file which demonstrates this problem?

[DesignerTestFontFile.zip](https://github.com/xamarin/xamarin-android/files/3312146/DesignerTestFontFile.zip)

**Comment by SanthiyaArulsamy** [comment] 2019-06-25 13:48
Please ensure this issue with VisualStudio 2017

**Comment by SanthiyaArulsamy** [comment] 2019-07-05 11:49
Can reproduce the issue in the attached sample?
[Designer_Android.zip](https://github.com/xamarin/xamarin-android/files/3362569/Designer_Android.zip)

**Comment by pjcollins** [comment] 2019-07-08 17:31
@SanthiyaArulsamy It looks like I am seeing a similar issue using the latest VS 2017 release. Would you be able to install VS 2019 to see if it resolves this problem for you?

**Comment by SanthiyaArulsamy** [comment] 2019-07-08 17:58
Yes it is resolved in VS 2019. May i know why it is throwing exception in VS 2017.

**Comment by pjcollins** [comment] 2019-07-08 18:29
I haven't attempted to dig into the root cause of the issue but we've spent some time in between these major releases improving our integration points and test coverage in this general area. Do you mind if I close this issue as it has been resolved in a more recent release?

**Comment by SanthiyaArulsamy** [comment] 2019-07-11 09:55
Yes..I need the fix for VS 2017.

**Comment by KarthikRaja26** [comment] 2020-10-01 08:16
Hi @pjcollins ,

We are also facing the same issue in VS17. So, could you please tell me the exact timeline for the fix ? 

Regards,
Karthik Raja

**Comment by KarthikRaja26** [comment] 2020-10-01 08:17
@samhouts please look on this

**Comment by jpobst** [comment] 2022-08-08 22:22
If this is still an issue:

This issue likely occurs in the Android Designer, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!

**Closed by jpobst** 2022-08-08 22:22 UTC
