### ISSUE TITLE
Android SDK Tools are empty VS 15.6.6

### ISSUE THREAD

**Issue by IoTFier** [xamarin/xamarin-android#1549] opened 2018-04-12 19:09 UTC
### Steps to Reproduce

1. Install or upgrade to VS 15.6.6 and install / upgrade VS preview to 15.7.3.
Accessing Android SDK tools shows empty platform / tools.
2. 
3. 

### Expected Behavior
I upgraded my VS stable to 15.6.6 and preview to 15.7.3 and now back to square one.
Click on Tools -> Android -> Android SDK Manager. 
It should show android platforms and tools.

### Actual Behavior
Android SDK tools are empty. See the screenshot.
It should shows empty android platforms and tools.

### Version Information
(stable)VS 15.6.6 ; (preview) VS 17.3
![vs 15 6 6 and vs 15 7 3 andorid sdk empty](https://user-images.githubusercontent.com/26844611/38698535-04fa43d0-3e5b-11e8-938b-a880caade164.JPG)

**Comment by ghuntley** [comment] 2018-04-13 06:56
I ran into something similar a couple days ago. This SDK location for this dialogue was empty even though SDK's were installed. It was a new computer so I thought maybe I did something wrong during install.

**Comment by IoTFier** [comment] 2018-04-13 09:09
HI @ghuntley , how did you address it ? 
This has nothing to do with your computer but to do with commitment of Xamarin team working on VS Windows to keep bringing / creating bugs that are eternal to the product releases.

This is a new developer community experience - _"Stay productive by quality testing of Visual Studio GA releases for Xamarin and not focus on business you are aiming for. Collaborate to invent / reinvent workarounds"_

**Comment by joj** [comment] 2018-04-13 12:36
This is fixed now. The fix will be available in the next preview of 15.7.

**Comment by IoTFier** [comment] 2018-04-13 15:40
Hi @joj, what about the fix in VS 15.6.6? How do we know this is not going to be broken as this issue has been around for a while (open and close)?

**Comment by joj** [comment] 2018-04-13 15:43
15.6 is in service release mode (meaning, only blocker bugs will be fixed there). This fix will be in 15.7. This fix is only for SDK Manager not showing the default path when opened from VS.

**Comment by IoTFier** [comment] 2018-04-13 15:45
well. in 15.6.6 when I set the path, it doesn't persist after I close the SDK Manager.
Also, which SDK Manager platform / tool path should be assigned if I already have Android SDK installed on my PC?

**Comment by vyedin** [comment] 2018-04-13 15:49
@IoTFier it's whichever instance of the SDK you want to use.

**Comment by joj** [comment] 2018-04-13 15:49
SDK Manager doesn't persist the SDK Path. It receives it from VS each time it's opened. Because of this bug, it's not getting it correctly. That's what was fixed.
The path you need to use is whatever you have in Tools -> Options -> Xamarin -> Android Settings. By default that will be `C:\Program Files (x86)\Android\android-sdk\` but it may change if you have your own SDK installed. Android Studio (the next most common choice) uses `C:\Users\[youruser]\AppData\Local\Android\sdk`

**Comment by joj** [comment] 2018-04-13 16:04
As I said, this fix is only for the SDK Manager not showing the path by default (which is what this bug is) and it will only land in 15.7, not 15.6.

**Comment by IoTFier** [comment] 2018-04-13 16:09
As much as your help is appreciated, it is disappointing when a servicing update breaks a functionality within the current GA release and then we get a directive to wait for next minor version release, which we don't even know when it is supposed to come out.

**_This problem wasn't in 15.6 until 15.6.6 came out - should that be addressed in 15.6 itself?_**

**Comment by joj** [comment] 2018-04-13 16:12
That's not accurate. It wasn't a service release that introduced this problem, but the stable. Our workflow puts previews in the hands of the users way before the stable lands. By the time it landed we already were on preview 2 of 15.7. This was fixed as soon as possible, but given that you can manually set the path in SDK Manager it doesn't qualify as a blocker, so it's going to be fixed in 15.7. The fix is already public in preview (or it will be in a few days).

**Comment by IoTFier** [comment] 2018-04-13 16:34
Setting path manually in 15.6.6 is not persisting the path.  I don't intend to go in circle here as I truly appreciate your responses. I can't switch to preview as the APIs supported for iOS in preview and stable are not same.

**Comment by joj** [comment] 2018-04-13 16:37
That's weird (the API thing). They may not be the same, but we never _remove_ API, so everything you're doing right now should work. 

On the persisting of the path, that's absolutely correct and by design. Our expectation is that a) VS will provide the path, so persisting is not necessary (and also may be wrong if you changed the path in Tools->Options at some point) and b) SDK Manager should be needed a few times a year at most, once everything is set up.

**Comment by IoTFier** [comment] 2018-04-13 16:54
This is the kind of dialogue box you get when you switch to preview 
![image](https://user-images.githubusercontent.com/26844611/38747690-489ae7a0-3f11-11e8-8535-4815da792978.png)
With stable the Xamarin.iOS is not the same version as '11.10'

**Comment by joj** [comment] 2018-04-13 16:55
The API is still the same. The SDK is different. If you git Install there, everything will be taken care of for you. If you want to go back, the same thing will appear and you can reinstall again.

**Comment by IoTFier** [comment] 2018-04-13 16:56
@joj  - so if I click on install will that affect my VS stable environment?

Will you please also tell me if someone is working on [1540](https://github.com/xamarin/xamarin-android/issues/1540)

**Comment by joj** [comment] 2018-04-13 17:03
If you install it will upgrade the Mac, and stable will pick that. On 1540, I don't know.

**Comment by jpobst** [comment] 2022-08-08 19:55
Assuming this issue is obsolete, as VS 2017 is no longer supported.

**Closed by jpobst** 2022-08-08 19:55 UTC
