### ISSUE TITLE
Xamarin.Android 8.3.0.19 freezes on startup in Release mode

### ISSUE THREAD

**Issue by kurtcz** [xamarin/xamarin-android#1686] opened 2018-05-16 05:40 UTC
### Steps to Reproduce

1. Checkout https://github.com/kurtcz/mariasek
2. Open Mariasek-Xamarin.sln, build and run project Mariasek.AndroidClient in RELEASE mode (you may need to download, build and reference Monogame 3.6 first)
3. App freezes immediately upon start (all is fine in DEBUG mode however)
4. After manually downgrading to previous Xamarin.Android 8.2.5.0 the problem goes away

**Comment by abdu292** [comment] 2018-05-16 08:56
Same issue. I spent many hours late night yesterday, was not realized the issue is with the new version.
Need to send the apk to the users by today. Any work around/suggestion without downgrading the version? Any help would be very much appreciated.

@kurtcz How did you downgrade the version? Did the downgrade bring any other issues over all?

**Comment by JonDouglas** [comment] 2018-05-16 17:26
@kurtcz @abdu292 Can one of you comment on what constitutes as a "freeze on startup in Release mode"? I was able to pull down this repository, install Monogame 3.6, and build the project in Release mode to which it deployed just fine on 8.3.0.19. Is the freezing refering to only showing the splash screen then, that's the only thing I noticed so far.

I was looking through the build output and it looks like you might be affected by a `mkbundle` regression which we opened a PR to fix yesterday. To work around this, you can uncheck the `Bundle assemblies into native code` option or use a previous version of Xamarin.Android(https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017). I have confirmed that this does in-fact let the game get to a title screen.

Given the PR is still open and we are working on getting a build ready, we will try to include this in the next available release.

https://github.com/xamarin/xamarin-android/pull/1683

I am however closing this issue as it's a duplicate of https://github.com/xamarin/xamarin-android/issues/1651

Thank you so much for the report and bringing this to our attention!

**Closed by JonDouglas** 2018-05-16 17:26 UTC
Labels: duplicate

**Comment by abdu292** [comment] 2018-05-16 18:16
Mine is a standard app (I didn't have mono game installed on my project). However unchecking the "Bundle assemblies into native code indeed fixes this, but almost doubling the apk size, raises another concern).

Any patch releases planned with this PR fix sooner (this week)?

Your effort is very much appreciated!

**Comment by kurtcz** [comment] 2018-05-16 20:53
@JonDouglas I can confirm that by "freeze" I meant that the splash screen never goes away.
Also I tried to downgrade to the previous version of Xamarin.Android which solved the problem.
Thanks for looking into this - looking forward to seeing the patch.

I really appreciate your timely response. However the issue raises some concerns: 
How come this was not caught before marking this release as "stable"?
How reliable really are these so called stable releases? Any plans in extending the tests to catch scenarios like this one in the future?

**Comment by JonDouglas** [comment] 2018-05-16 22:03
@kurtcz 

We value your feedback. This regression was surprising to us as we did not detect it with our Mono integration testing as 8.3 introduces a new version of Mono (5.10). We did receive a report on this 9 days ago which caught our attention and we issued a fix. We are hoping to get this into the next Visual Studio release as soon as possible.

**Comment by mlaban** [comment] 2018-05-17 01:41
@JonDouglas, do you have a time frame for this? We were set to release a version within the next few days, should we scrape those plans?

**Comment by JonDouglas** [comment] 2018-05-18 14:43
The fix has just been merged into our master branch(for those not following the other issue):

https://github.com/xamarin/xamarin-android/commit/1a45e1e2cdcbea84a024e86cdfabe9538763fafc

We are working on getting this in the next available release now that a build is green.

**Comment by abdu292** [comment] 2018-05-22 06:13
@JonDouglas do we know if this fix is available with VS 15.17.2 update that rolled it since hours back?

I don't see it in the release note.

**Comment by mclillill** [comment] 2018-05-22 06:15
No. It will be in 15.17.3.
See here:
[Comment on Issue 1651](https://github.com/xamarin/xamarin-android/issues/1651#issuecomment-390685550)
