### ISSUE TITLE
Error     <PreserveCompilationContext>true</PreserveCompilationContext>

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#7517] opened 2022-11-01 18:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-----PreserveCompilationContexttr/10179257)._

---
Error to activate     true

[Resultados-Compilación.zip](https://aka.ms/dc/file?name=B92ca8707faf9480f995adcd2131fe806638020724142081637_Resultados-Compilaci%C3%B3n.zip&tid=92ca8707faf9480f995adcd2131fe806638020724142081637)

---
#### Feedback Bot on 10/23/2022, 07:21 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jonpryor** [comment] 2022-11-01 18:54
`$(PreserveCompilationContext)` documentation: https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#preservecompilationcontext

> The `PreserveCompilationContext` property allows a built or published application to compile more code at run time using the same settings that were used at build time. The assemblies referenced at build time will be copied into the *ref* subdirectory of the output directory. The names of the reference assemblies are stored in the application's *.deps.json* file along with the options passed to the compiler. You can retrieve this information using the [DependencyContext.CompileLibraries](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencymodel.dependencycontext.compilelibraries#microsoft-extensions-dependencymodel-dependencycontext-compilelibraries) and [DependencyContext.CompilationOptions](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencymodel.dependencycontext.compilationoptions#microsoft-extensions-dependencymodel-dependencycontext-compilationoptions) properties.

Parts of this are *unsupportable* on Android; .NET Android has no `.deps.json` file, has no "output directory" of consequence -- the output is a `.apk` or `.aab` file, not a directory -- and thus has no `ref` directory.

That leaves the `DependencyContext.CompileLibraries` and `DependencyContext.CompilationOptions` properties, which are almost certainly not supported *now*, and I don't know if they *can be* supported.

This feels more like a qestion/issue for the `Microsoft.Extensions.DependencyModel` team.  I wonder how we can contact them…

**Comment by jonpryor** [comment] 2022-11-01 20:13
A quick github search finds:

 1. [`DependencyContext` source](https://github.com/dotnet/runtime/blob/ea04e238467bfd7f0e1800c10fb18bc2ff048922/src/libraries/Microsoft.Extensions.DependencyModel/src/DependencyContext.cs)
 2. [`DependencyContext.Default`](https://github.com/dotnet/runtime/blob/ea04e238467bfd7f0e1800c10fb18bc2ff048922/src/libraries/Microsoft.Extensions.DependencyModel/src/DependencyContext.cs#L38-L39) has a `[RequiresAssemblyFiles]` custom attribute:

    ```csharp
    partial class DependencyContext {
        [RequiresAssemblyFiles("DependencyContext for an assembly from a application published as single-file is not supported. The method will return null. Make sure the calling code can handle this case.")]
        public static DependencyContext? Default => _defaultContext.Value;
    }
    ```
 3. [`RequiresAssemblyFiles`](https://github.com/dotnet/runtime/blob/ea04e238467bfd7f0e1800c10fb18bc2ff048922/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/RequiresAssemblyFilesAttribute.cs?q=RequiresAssemblyFiles#L7) has this doc-comment:

    ```csharp
    /// <summary>
    /// Indicates that the specified member requires assembly files to be on disk.
    /// </summary>
    partial class RequiresAssemblyFilesAttribute {}
    ```

.NET Android apps can be considered as "single file" apps, quasi-architecturally.  Assemblies *are not* stored as distinct files on disk.

As such, `DependencyContext` cannot be supported until single file apps are supported.

See also: https://github.com/dotnet/runtime/issues/70438

In particular [this comment by vitek-karas](https://github.com/dotnet/runtime/issues/70438#issuecomment-1150073436):

> [DependencyContext is] tightly coupled with the `.deps.json` file format. There are .NET form factors which don't have `.deps.json`, for example Native AOT, and pretty much all of the mobile platforms.

We cannot support `$(PreserveCompilationContext)` at this time, and possibly ever.

Closing this issue as a duplicate of https://github.com/dotnet/runtime/issues/70438.

**Closed by jonpryor** 2022-11-01 20:13 UTC
Labels: Area: App+Library Build, needs-triage
