### ISSUE TITLE
make your android app 

### ISSUE THREAD

**Issue by artcyb** [xamarin/xamarin-android#3088] opened 2019-05-10 05:46 UTC
### Steps to Reproduce

1. 
2. 
3.

**Comment by JonDouglas** [comment] 2019-05-15 15:28
We are closing this issue for now as there is no information pertaining to what the issue is, nor how we can reproduce it.

Please feel free to file a new issue with the following information in mind:

https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests#bug-reports

**Closed by JonDouglas** 2019-05-15 15:28 UTC
