### ISSUE TITLE
ServicePointManager.ServerCertificateValidationCallback = ValidateServerCertficate; not working

### ISSUE THREAD

**Issue by PNDTCS** [xamarin/xamarin-android#3929] opened 2019-11-19 06:16 UTC
### Steps to Reproduce

ServicePointManager.ServerCertificateValidationCallback = ValidateServerCertficate;

private bool ValidateServerCertficate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            
        }
in visual studio 2019 (16.3.9) and xamarin.android 10.0.6.2 ValidateServerCertficate method never gets called. I am hitting "https://" request. 

Before updating visual studio and xamarin android to latest version ValidateServerCertficate is working properly.

### Expected Behavior

ValidateServerCertficate  should get called to validate server certificate.

### Actual Behavior

ValidateServerCertficate   not getting called in newer version of visual studio and xamarin android

### Version Information
Visual studio 2019 (v16.3.9)
Xamarin 16.3.0.278
Xamarin.Android 10.0.6.2

Please let me know if you need more information. 
Please provide solution for this as I have production release planned in coming week.

**Comment by radekdoulik** [comment] 2019-11-19 10:28
This is duplicate of https://github.com/xamarin/xamarin-android/issues/3682

Please use HttpClientHandler.ServerCertificateCustomValidationCallback instead.

**Closed by radekdoulik** 2019-11-19 10:28 UTC
Labels: duplicate

**Comment by PNDTCS** [comment] 2019-11-19 10:43
Can you please post here one example how to use it

**Comment by PNDTCS** [comment] 2019-11-19 12:51
I have added solution provided in #3682 and it works fine. Thanks
